### ISSUE TITLE
End of game stats not always displayed in console

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1001]
Author: @rmarquis (Spyhawk)
Date: 2017-02-16
Redmine Issue: 1001, https://dev.etlegacy.com/issues/1001

---

The end of game stats is not always displayed in client console.

Either the "ws" command is not sent for some reason (see Cmd_WeaponStat_f in g_cmds.c) or the cgs.dumpStatsTime variable (CG_ServerCommand in cg_servercmds.c) prevents it to be displayed.
Investigate and fix.

---

Related issue(s): #403

---

Related commit(s):
b6c3879c28e650701fb62aae142baa73415171de - game: fixed /statsdump not always displayed at end..

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2017-02-16T19:55:52Z

---

{TODO}
* move  the pretty print of G_printMatchInfo() on the client side.

**Comment by ETLegacyTeam** [comment]
From: @Aranud (Aranud)
Date: 2017-05-10T12:04:00Z

---

My current observation are as follow :

The "ws" command is sent properly.
And indeed, cgs.dumpStatsTime variable (CG_ServerCommand in cg_servercmds.c) prevents it to be displayed.

cgs.dumpStatsTime never change. It's all the times set to 0. 

The only way to update is in CG_dumpStats_f which is call from CG_DrawIntermission : 

			if (cg_autoAction.integer & AA_STATSDUMP)
			{
				CG_dumpStats_f();
			}

By defaut, cg_autoAction is set to 0. In the case the value is set to 4, it work properly (AA_STATSDUMP = 0x04).

EDIT : 
As IR4T4 said : 
cg_autoAction cvars controls several options for the user
one option is: print endgame - or not

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2017-05-10T15:30:16Z

---

I'll close this.

Spyhawk, adjust the default value if there is a real need for this. But I think most players are focussing the 2D stats in intermission so it's fine as it is.

**Comment by ETLegacyTeam** [comment]
From: Mateos (Mateos)
Date: 2017-05-10T15:57:47Z

---

IR4T4 wrote:
> But I think most players are focussing the 2D stats in intermission.

Seriously?

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2017-05-11T09:19:15Z

---

This is a real bug. This has nothing to do with cg_autoAction.

**Comment by ETLegacyTeam** [comment]
From: @realkemon (keMoN)
Date: 2018-02-24T18:04:27Z

---

Does this cover the empty stats in the intermission window as well, or only in the console?

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2018-02-24T21:03:44Z

---

Console. I don't remember having seen empty stats in the intermission window...

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2018-02-24T23:15:40Z

---

Ah, that. This was a bug that was quickly solved after the 2.75 release. From changelog:

> Fixed main debriefing stats not displayed when skill rating is disabled (also causing intermission chat issues)

**Comment by rmarquis** [comment]
This has been fixed in b6c3879c28e650701fb62aae142baa73415171de: `/statsdump` was always skipped for spectators not following any players at the end of map.
