### ISSUE TITLE
Zoomed sniper sensitivity

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1009]
Author: @mittermichal (kimi)
Date: 2017-02-22
Redmine Issue: 1009, https://dev.etlegacy.com/issues/1009

---

I think it would be nice to be able to change sensitivity of zoomed sniper. It would be greatly appreciated by low-sens players.
CS:GO has it.

**Comment by mittermichal** [comment]
implemented in https://github.com/etlegacy/etlegacy/pull/1919
I can't close this, because this was imported from redmine
