### ISSUE TITLE
Security files check

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1025]
Author: @rmarquis (Spyhawk)
Date: 2017-04-03
Redmine Issue: 1025, https://dev.etlegacy.com/issues/1025

---

Import ioq3/OpenJDK files check security fix from last month (thx Ensiform).

See also https://ioquake3.org/2017/03/13/important-security-update-please-update-ioquake3-immediately/

In OJDK:

* https://github.com/JACoders/OpenJK/commit/05928a57f9e4aae15a3bd0
* https://github.com/JACoders/OpenJK/commit/ef124fd0fc48af164581176

In ioq3:

* https://github.com/ioquake/ioq3/commit/376267d534476a875d8b9228149c4ee18b74a4fd
* https://github.com/ioquake/ioq3/commit/f61fe5f6a0419ef4a88d46a128052f2e8352e85d
* https://github.com/ioquake/ioq3/commit/b173ac05993f634a42be3d3535e1b158de0c3372

---

Related commit(s):
8e731a6029813c9eee2ef3d3d4ad449cccb77469 - misc: Merge some file writing extension checks fro..
 3500f7bccb9128125504a28277fb23d271f9b848 - sys: Don't load faulty DLLs - initial patch by ioq..
 f7aacf32b6cf892dfcc2f43006c02c347eb41ca7 - misc: merged latest ioq3 security files checks ref..
 4a982fe56fcaf4cb59035bae9bc0dbdbb158a158 - qcommon: fix donwload issue refs 1025
 07d509fadd61a408af06b167ea789ca6581fa158 - qcommon: fix clean command, fix updater removing o..
 642f3acd674b989d73e6821e13cedb01904d2d67 - misc: check for invalid game dirs - patch by ioq3 ..

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2017-04-03T13:02:58Z

---

We shouldn't merge it directly. COM_DefaultExtension is involved for checking file extensions. We should just make this function stronger and check the last chars directly.

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2017-10-20T15:22:00Z

---

Latest changes form ioq3 are merged. Please verify.

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2017-12-20T12:57:50Z

---

-Our clean command isn't working properly anymore.-

-Case 'clean all *.pk3' drops the game because we are using FS_Remove() instead of FS_HomeRemove in Cmd_CleanHomepath_f-

Code & clean command needs some rework:

{FIXME}
-1. We should use FS_HomeRemove in Cmd_CleanHomepath_f instead (requires changes to accept absolute paths or adjust Cmd_CleanHomepath_f)-
-2. 'force' param is using plain remove() which is  bypassing our  security fixes- Why there is a force param?
3. Inspect FS_DeleteDir & -FS_Delete-, both call remove()

**Comment by rmarquis** [comment]
Closing. The FIXME that are left aren't relevant anymore.
