### ISSUE TITLE
Inspect GTKRadiant to work with ETL

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1030]
Author: @thunderpwn (thunder)
Date: 2017-04-22
Redmine Issue: 1030, https://dev.etlegacy.com/issues/1030

---

would be great when it comes to having 2 installations on the machine, one for gaming and one for mapping.

**Comment by ETLegacyTeam** [comment]
From: @thunderpwn (thunder)
Date: 2017-04-22T19:10:46Z

---

I mean on installation so the path is set and will NOT turn to documents/etlegacy as default ...

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2017-04-24T13:43:10Z

---

You have to start ETL.exe  by CLI. There are 2 installs on your hd, in folder A and B:

Open the cli:

cd B
ETL.exe +set fs_basepath B +set fs_homepath B_homepath

or 

cd A
ETL.exe +set fs_basepath A +set fs_homepath A_homepath

**Comment by ETLegacyTeam** [comment]
From: @thunderpwn (thunder)
Date: 2017-04-28T05:11:44Z

---

Doesnt work , because when radiant starts you mapping etl it will choose etlegacy folder in documents...
Maybe store in a file?

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2017-04-29T04:43:06Z

---

I think your issue is caused by GTKRadiant  - https://github.com/TTimo/GtkRadiant/blob/master/radiant/preferences.cpp#L3737

The homepath is statically set  at line 3742. Are you sure your Radiant is using etl instead of et? See  ENGINE_ATTRIBUTE line 3738

At this point there is a need to extend  GTKRadiant to solve this.

**Comment by ETLegacyTeam** [comment]
From: @thunderpwn (thunder)
Date: 2017-04-29T08:48:19Z

---

yes it is using a renamed ETL to ET, works fine...
but the thing is that it sets the original hompath, and its a bit annoying... 

And I cant set up gtk radiant for compiling my own.. 
Tried a million times..

**Comment by ETLegacyTeam** [comment]
From: @thunderpwn (thunder)
Date: 2019-09-15T18:51:58Z

---

its possible to rename etl.exe to et.exe and it will work

**Comment by rmarquis** [comment]
This is an upstream issue.
See:
* https://github.com/TTimo/GtkRadiant/issues/358
* https://github.com/TTimo/GtkRadiant/issues/379
* https://github.com/TTimo/GtkRadiant/pull/384

Could be handled upstream by @Mateos81.

**Comment by rmarquis** [comment]
After some input from @realkemon and @Mateos81:

> It involves some manual preparation, but GTK and Net both work with ET/ETL.

Closing now.
