### ISSUE TITLE
When compiling error in libs\curl\libcurl.lib

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1035]
Author: Odal (Odal)
Date: 2017-05-15
Redmine Issue: 1035, https://dev.etlegacy.com/issues/1035

---

I installed from scratch VisualStudio 2017 (with options turned on for PC gaming/Unity/C++/etc), OS: WINDOWS10.

After getting the sources I created the etlegacy\build directory, then cd build and
*cmake -G "NMake Makefiles" -DBUNDLED_LIBS=YES .. && nmake*

After a while it stops with:
```<code class="bash">...
Scanning dependencies of target renderer_opengl2_x86
[ 41%] Building C object CMakeFiles/renderer_opengl2_x86.dir/glsl/tr_glslsources.c.obj
tr_glslsources.c
[ 42%] Linking C shared module renderer_opengl2_x86.dll
[ 50%] Built target renderer_opengl2_x86
[ 50%] Built target bundled_sdl
NMAKE : fatal error U1073: impossibile creare 'libs\curl\libcurl.lib'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX86\x86\nmake.exe"' : codice restituito '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX86\x86\nmake.exe"' : codice restituito '0x2'
Stop.

D:\etlegacy\build></code>
```

It seems that there is a misuderstanding _where_ the file libcurl.lib should be. 
* etlegacy\build\libs\curl\lib\libcurl.lib
* etlegacy\build\libs\curl\libcurl.lib   (this does not exist)

Infact I have a (stupid)
*WORKAROUND*:
to copy the first file to the second folder.

Then the compilation works

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2017-05-15T15:51:39Z

---

I'v had a similar error after checking out the latest changes from our lib submodule:
```
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
CMakeFiles/bundled_curl.dir/build.make:51: recipe for target '../libs/curl/lib/.libs/libcurl.a' failed
make[2]: [../libs/curl/lib/.libs/libcurl.a] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/bundled_curl.dir/all' failed

```

After cleaning the working directories, deleting the libs folder with new checkout the issue was gone.
Did you use an old repository path which was used before for your new VS17 install?

**Comment by ETLegacyTeam** [comment]
From: Odal (Odal)
Date: 2017-05-15T20:28:07Z

---

Before to post the bug, I get a completly new repository. I repeated this *2 times* to be sure.

But if microsoft decided to put "new features" in VS17,  more opened to other worlds (Linux, and its native languages and libraries(?)) there can be strange side effects.

**Comment by ETLegacyTeam** [comment]
From: @saukko28 (Saukko)
Date: 2019-06-11T16:41:56Z

---

This issue is still relevant in VS19. A possible fix or workaround (or whatever) is here:
https://github.com/etlegacy/etlegacy-libs/pull/10/commits/7a9e71aa1f6462856ebf3b4a6ab5510acd0768ef

I have used the piece of text (from the link) to fix the issue locally.

-*S

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-06-12T14:58:53Z

---

Yup, and I'm still waiting for you to confirm this works in both release and debug build - See the very same "PR":https://github.com/etlegacy/etlegacy-libs/pull/10 you linked to.
To expand on this, NMAKE tends to use a different`CMAKE_STATIC_LIBRARY_SUFFIX`  in debug mode, which means your change _might_ break here (not sure if that applies to curl though).

**Comment by rmarquis** [comment]
The fix has been committed as https://github.com/etlegacy/etlegacy-libs/commit/8f21ffdf011d0a202298d79b893248818cd3612f. Closing.
