### ISSUE TITLE
Servername search-bar in the server browser

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1044]
Author: @realkemon (keMoN)
Date: 2017-06-21
Redmine Issue: 1044, https://dev.etlegacy.com/issues/1044

---

From Discord/Irc
It is currently not possible to search for servernames in the search-bar, only mapnames.

---

Related issue(s): #1050

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2017-06-22T14:30:55Z

---

I think the color in the server strings is what has prevented us to implement this feature before.
Afair, the server list is a feeder, so we can't filter out colors of server string individually, but we'd need to remove color from all the feed altogether.

**Comment by ETLegacyTeam** [comment]
From: @realkemon (keMoN)
Date: 2017-06-22T15:14:08Z

---

That's a good point. I'd say we set this ticket to invalid then? Removing colours only to be able to search for servers is a bit drastic in my opinion. 
The feature would just be a nice-to-have.

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2017-06-22T15:33:02Z

---

Why we don't do a 2nd array for servernames w/o colors where we do the searches?

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2017-06-22T18:40:10Z

---

That could do the trick, I guess.

**Comment by rmarquis** [comment]
There is not much space available, but I'd argue the mapname search field is absolutely useless. Not a single time did I ever used it.
Replace it by the requested server search field.
