### ISSUE TITLE
Better favourites display

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1049]
Author: @alkhimey (artium)
Date: 2017-07-21
Redmine Issue: 1049, https://dev.etlegacy.com/issues/1049

---

Show a list of all favorites unconditionally.

Currently, one need to refresh whole server list just to be able to do a GUI equivalent of "/connect my.fav.server.com".

If the favorite server is down, or if the master server list is down, the favourite is shown.

**Comment by ETLegacyTeam** [comment]
From: @alkhimey (artium)
Date: 2017-07-21T13:09:53Z

---

*  the favourite is *not* shown.

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2017-07-22T17:37:41Z

---

The favourites did work for me when the master was down.

We may enable the filter automatically when there are no online servers found. Is that what you want?

**Comment by ETLegacyTeam** [comment]
From: @alkhimey (artium)
Date: 2017-07-22T20:25:41Z

---

IR4T4 wrote:
> The favourites did work for me when the master was down.
> 
> We may enable the filter automatically when there are no online servers found. Is that what you want?

Can you reproduce the following scenario?

Precondition: You have at least one favourite server.

1. Start etl and click "Play Online" in order to bring server selection screen.
2. In the filter area, set "Sources" to "Favorites". You will see at least one server in the list.
3. Exit the game.
4. Start game again and go to the "Play Online" menu. You will see that the filter is set to "Favorites" and there are no servers in the list.
5. Cycle the "Sources" filter until "Internet" is selected. The servers will start filling the list. Wait a moment until you favourite server appear in the list.
6. Cycle again the filter to "Favorites", you will see your favorite server there.

Based on this behaviour I guessed that behind the scenes the "Favorites" filter is actually filtering the list of servers received from the master. I might be wrong here.

**Comment by rmarquis** [comment]
Since this was reported, Favorites were moved to client-side database. It shouldn't happen anymore. Closing now.
