### ISSUE TITLE
Immediately grant skill-level buffs upon unlocking

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1059]
Author: @realkemon (keMoN)
Date: 2017-10-03
Redmine Issue: 1059, https://dev.etlegacy.com/issues/1059

---

From IRC/Discord:
Some skill unlocks are immediately granted like for example faster reload and chargebar, while others require a respawn.

Can this be confirmed and if it is actually like that, can those unlocks (e.g. Akimbo secondary) be granted on the fly without the need to die first?

**Comment by ETLegacyTeam** [comment]
From: @realkemon (keMoN)
Date: 2017-10-03T20:46:01Z

---

From Ensiform: 
idk if immediate is appropriate tbh
like the max health one could be given immediately (but dont actually give them health, just bump the cap up)


If level unlocks are about health, charge or ammo, then only the capacity should be adapted. For obvious reasons immediately receiving full health, ammo or charge would be a terrible thing.

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2017-10-04T13:23:50Z

---

Ensiform is right. Or just think about the case of getting a new weapon in between the game (with no respawn). bleh ... :///
If there is a skill which can be enabled on the fly w/o side effects we do that - but this should be specified in detail.

**Comment by ETLegacyTeam** [comment]
From: @realkemon (keMoN)
Date: 2017-10-04T23:13:52Z

---

I think stuff like this should behave consistently. Receiving one perk immediately and the other not might raise confusion.

Better close this ticket then.
Could you set it to invalid? Can't do that.

**Comment by rmarquis** [comment]
Closing as Invalid per request.
