### ISSUE TITLE
ETL wont start with multiple screen devices

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1061]
Author: @IR4T4 (IR4T4)
Date: 2017-10-21
Redmine Issue: 1061, https://dev.etlegacy.com/issues/1061

---

Forum post:
https://dev.etlegacy.com/boards/2/topics/3214

Currently r_mode 2 selects kind of  'native' screen resolution which might be the total reolution of all screen devices 
See console output of forum post: 3 monitors with 1920x1080 native resolution are creating a 5760x1080 resolution.

{FIXME}
In case of multiple screen devices use and set screen related cvar values for the device with poorest resolution
or get the primary device (if possible) and use this.

See also:
http://www.tomshardware.co.uk/forum/390122-33-monitors-1920x1080-native-resolution-5760x1080

**Comment by rmarquis** [comment]
This has been fixed as part of #1409 (primary or favorite display is used).
