### ISSUE TITLE
Ingame roq videos are not played correctly

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1068]
Author: @isRyven (ryven)
Date: 2018-01-04
Redmine Issue: 1068, https://dev.etlegacy.com/issues/1068

---

Ingame roq videos that are set to be played from shaders are displaying incorrect images, depending on angle of viewing.

Shader example:
```<code class="c">textures/t_text/fl_att
{
       qer_editorimage textures/t_text/suurusetest.jpg
       surfaceparm nonsolid
       surfaceparm nolightmap
       surfaceparm trans
       cull none
       {
                videoMap video/flame.roq
                blendfunc add
       }
}</code>
```

Attached examples of the bug from different maps, where roq files are used as a flame textures.

---

Related commit(s):
e01d6ffaac3bfcc598c1ec7c77ad79314ff666fe - fix videomaps not playing correctlyroq files are..

**Comment by ETLegacyTeam** [comment]
From: @isRyven (ryven)
Date: 2018-01-04T19:41:13Z

---

Map where you can easily reproduce it. Check the torchlights.

**Comment by ETLegacyTeam** [comment]
From: @thunderpwn (thunder)
Date: 2018-03-11T17:33:19Z

---

probably lays in RE_StretchRaw or RE_UploadCinematic since its the only stuff using tr.scratchImage wich is for cinematic stuff
also questions to ask:

- is generic shader right for this
- is projection right
- is it setup right

**Comment by Aciz** [comment]
This is still broken, if you have multiple .roq videos playing in your PVS, they break.

Test map: http://trickjump.net/downloads/etmain/verihard.pk3
