### ISSUE TITLE
Brightness changing multiple times while loading map

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1069]
Author: yks (yks)
Date: 2018-01-07
Redmine Issue: 1069, https://dev.etlegacy.com/issues/1069

---

When one connects to server and game starts to load a map, the brightness/gamma of the screen changes multiple times while loading. Brightness returns to normal when loading is complete and player is in game as spectator.

**Comment by ETLegacyTeam** [comment]
From: @thunderpwn (thunder)
Date: 2018-03-01T15:12:00Z

---

belive this just have todo with gamma init and building stuff as glsl and precompute lightning and stuff

**Comment by rmarquis** [comment]
It seems 43a6a111bfad54a29f887c9eac0c9763c01f43e7 has fixed this issue.

**Comment by Aciz** [comment]
Yep @jackeri mentioned that the implementation fixed this issue.

**Comment by rmarquis** [comment]
Nice! Closing ticket.
