### ISSUE TITLE
Games crashes if German Umlauts used in chat

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1072]
Author: tiffie (tiffie)
Date: 2018-02-16
Redmine Issue: 1072, https://dev.etlegacy.com/issues/1072

---

My game on 37.187.79.49:27964 crashed reproducible when sending ü, ö or ä in chat.

Client: ET Legacy v2.75-1537-gf8842e6d linux-i386 Feb 13 2018 DEBUG
Masked as: ET 2.60b linux-i386 May  8 2006
Built: 2018-02-13T20:25:15 UTC

ü -> "ERROR: invalid playerState field count"
ö -> "ERROR: CL_ParseServerMessage: Illegible server message 177"
ä -> "ERROR: CL_ParseServerMessage: Illegible server message 239"

Server problem or clients?

---

Related issue(s): #981

**Comment by ETLegacyTeam** [comment]
From: yks (yks)
Date: 2018-02-18T16:22:54Z

---

Tried on Windows, 2.75 client and on same server. Õ, Ä, Ö and Ü seems  to work and no crashes for me.

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2018-02-18T16:50:15Z

---

This bug is current master only, the 2.75 release isn't affected.

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2018-02-28T12:46:27Z

---

Status:
- the current implementation (combination of latest client and server) doesn't crash 
- german 'Umlaute' are displayed when the chat is initiated via the chat window, console is still failing (chars are replaced by spaces)  see #981

{FIXME}
- ensure the current client doesn't crash when connected to older server versions ( 2.75 & earlier)

**Comment by rmarquis** [comment]
Some more UTF8 work has been done in a6c09688c397057e4af24241f08d5fe4fd9f0933 as part of #1365. This should be entirely fixed now. Closing.
