### ISSUE TITLE
class/spawn binds in controls -> advanced menu

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1075]
Author: @realkemon (keMoN)
Date: 2018-02-24
Redmine Issue: 1075, https://dev.etlegacy.com/issues/1075

---

Use the empty space in the controls -> advanced menu to let players set spawn constellations.
[CLASS] + [WEAPON] -> KEY
or
[SPAWNPOINT] -> KEY

To have an effect they also need to be added to the default config

See attached screenshot for mock-up

**Comment by ETLegacyTeam** [comment]
From: @realkemon (keMoN)
Date: 2018-02-24T18:03:07Z

---

Thank you hatcher

**Comment by rmarquis** [comment]
This has been superseded by the in-game team/class and dynamic spawn points selectors. See #1265. Closing now.
