### ISSUE TITLE
Slicks are bugged on 32bit build

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1095]
Author: @isRyven (ryven)
Date: 2018-06-16
Redmine Issue: 1095, https://dev.etlegacy.com/issues/1095

---

Slick surface merged together with solid brush, ie. solid brush + slick brush on top of each other(slick brushes are also solid btw), breaks slick functionality on 45 degree angled plane, this isn't reproducible on 64bit build, it only happens on 32bit linux builds, windows builds don't get bugged. 

The bug in action, on real map, 45 degree slope just becomes non-slick:
https://streamable.com/jus8p

Now, this obviously doesn't happen with 2.60b, BUT the same bug appears  also in et300, which could mean, that any GPL based engine modification should inherit the very same problem!
Makes me wonder if compilation flags are sort of messed up? cmake shows that fast-math is enabled, so i don't know.
I didn't test master builds(2.77), since i don't have linux installed, capable to run 32bit builds atm, so i hope someone can test that for me, but the bug should be reproducible on 2.76.

!https://media.discordapp.net/attachments/353604235926962179/457545574724665355/unknown.png(45icetest)!
The attached map to test bug on:
* right slope - slick + brush on top of each other, 
* center - just slick, 
* left slope - brush + slick, that was moved 1 unit away, so they don't overlap together. 

The right one should bug, the rest are fine.

**Comment by Aciz** [comment]
This issue seems to have resolved itself at some point, I can no longer reproduce this on a server running 32-bit 2.76 release on Linux.
