### ISSUE TITLE
Fix opengles to work with Android devices

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1100]
Author: @rafal1137 (RaFaL)
Date: 2018-08-04
Redmine Issue: 1100, https://dev.etlegacy.com/issues/1100

---

Opengles needs a lot of changes to make it work with Android.

Note: I'm limited here since making this happen on Win is too much hassle.

---

Related commit(s):
 b7fb324d1d9885fb4ae7c5bd88b1c235a8d80e03 - rendererGLES: first attempt to fix opengles, refs ..
 54adc12e97159dea7ed014b6baeb369c7b9b2943 - rendererGLES: small optimization, use short instea..
 e33ee42de453693dc026274af36f0e8a5610b0a2 - rendererGLES: use float numbers in plane2[4] since..
 cbca20a06dd4e1d38b4afd25d08b59ae0f65e768 - rendererGLES: added some OpenGL ES implementation,..
 e877226c9cb8fb2e3898d3fefcb5984a8e7463e0 - rendererGLES: first attempt to fix opengles, refs ..
 5ee21d203da85916db3292cf977df5883b8c7a73 - rendererGLES: small optimization, use short instea..
 27f37224792b5c80c1d2129e1083811bf696cebf - rendererGLES: use float numbers in plane2[4] since..
 d04deb47bab14e16cb0fef7366cb3033dadeeac9 - rendererGLES: added some OpenGL ES implementation,..

**Comment by rafal1137** [comment]
This one hangs it over for years. can be closed now because it is working
