### ISSUE TITLE
Improve console language support

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1111]
Author: N3rwitZ (N3rwitZ)
Date: 2018-09-21
Redmine Issue: 1111, https://dev.etlegacy.com/issues/1111

---

Console can't print game messages in anything but English; whenever one is logged in there in different language, it looks like random gibberish, letters mixed with numbers and symbools ("D03/5!00:4N"). Thus as more languages are added to the game, players won't know what's the console saying after it prints some important events during the match (death messages, announcements) - these are translatable.

Tested: Legacy 2.76 compiled September 20, 2018 (thanks to ryven)

**Comment by ETLegacyTeam** [comment]
From: @jackeri (Jacker)
Date: 2018-09-21T11:44:55Z

---

I already added this a few years ago, but it was removed as it caused issues with vanilla clients which connected to legacy servers.

**Comment by ETLegacyTeam** [comment]
From: N3rwitZ (N3rwitZ)
Date: 2018-09-21T13:09:59Z

---

Jacker wrote:
> I already added this a few years ago, but it was removed as it caused issues with vanilla clients which connected to legacy servers.

Meaning chances for implementing it back are, at most... none? That would make console logging with selected different language a brutal mess, given console plays major role in game (also chat history besides server cvar control).

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2018-09-22T11:08:11Z

---

In the end it's more a thingy about how we deal with messages we can't send to vanilla clients. 

@Jacker What about a server mode which auto supports this improved console when there are no vanilla clients connected? Thinking about LAN games and reasons to install ETL it's a nice benefit :)

**Comment by ETLegacyTeam** [comment]
From: N3rwitZ (N3rwitZ)
Date: 2018-09-22T14:55:16Z

---

IR4T4 wrote:
> In the end it's more a thingy about how we deal with messages we can't send to vanilla clients. 

True so, given the situation. Jacker, what was with vanilla clients at first place? Have had errors of sorts? I can imagine they were crashing on console open for the differences in client game code.

**Comment by jackeri** [comment]
The console now supports all characters that are in the fontmap
