### ISSUE TITLE
Legacy UI: Able to scroll Credits

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1113]
Author: N3rwitZ (N3rwitZ)
Date: 2018-09-25
Redmine Issue: 1113, https://dev.etlegacy.com/issues/1113

---

I am full of ideas in the UI department these past days. How about we have a scrolling option enabled on Credits pages so instead of trying to fit two sentences into one, we can have text as long as we need; easily add names of everyone who contributed.

Use: low resolution players can see the Credits properly. Higher resolution players are fine because bigger screen space.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2018-09-26T12:17:48Z

---

Afair NQ mod implement something similar. It's not been added in Legacy mod since credits were quite short until now, and there is indeed an increasing space issue as time goes by.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-01-31T14:56:42Z

---

We're running out of space in the credits page. We should ideally handle this for 2.77.

**Comment by rmarquis** [comment]
Drop this feature, and replace in-game credits with a generic text instead. Keep track of credits on the wiki instead, along team members with their responsibilities.
