### ISSUE TITLE
Add a server command to prove external downloads 

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1118]
Author: @IR4T4 (IR4T4)
Date: 2018-10-16
Redmine Issue: 1118, https://dev.etlegacy.com/issues/1118

---

Server admins often don't synchronize external downloads (if set).

Create a command which proves integrity for admins.

**Comment by rmarquis** [comment]
This doesn't seem to solve any existing issue. Closing, but feel free to reopen in case it is deemed necessary.
