### ISSUE TITLE
Add option to disable loading riflenade by selecting weaponbank

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1159]
Author: @timosmit (Timothy)
Date: 2019-01-08
Redmine Issue: 1159, https://dev.etlegacy.com/issues/1159

---

Currently selecting weapon bank 3 will trigger the `weapalt` action, which can load a rifle grenade when you hold a K43 or Garand. This is not always desired, since some players bind weapon bank 3 to make sure they hold their main weapon. Moreover, since this action cannot be cancelled, it can be hard on you mid-fight.

---

Related issue(s): #1154

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-05-09T18:13:35Z

---

> what should be the ideal behaviour then? How would one switch to rifle/riflenade?
> just weapalt should do it
> So we wouldn't give a slot to rifle+nade?

This doesn't sound like an easy feature to implement (code wise). See if this is possible easily without the need to refactoring the whole weapon slot code. If the required work is too big, delay again - we should avoid to break everything now that we've stabilized the weapon code.

**Comment by Aciz** [comment]
Implemented in 4b79416513d56fa9b3e98954f8af5170eab7c094
