### ISSUE TITLE
Create the initial whitelist

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1164]
Author: @IR4T4 (IR4T4)
Date: 2019-01-15
Redmine Issue: 1164, https://dev.etlegacy.com/issues/1164

---

None

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2019-01-25T14:07:41Z

---

https://github.com/etlegacy/filehashes

**Comment by rmarquis** [comment]
Following the new approach discussed in #1161, I'm closing this ticket. Tracking the new implementation of a whitelist system in #1447.
