### ISSUE TITLE
 Extend the vfs for separating downloads

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1165]
Author: @IR4T4 (IR4T4)
Date: 2019-01-15
Redmine Issue: 1165, https://dev.etlegacy.com/issues/1165

---

None

---

Related issue(s): #1025

---

Related commit(s):
11c63f631258e6f03a5fabda2c7cf0faf86ca5f5 - client: added pak isolation supportrefs 1161 1..
 8d9b96d4af17b4d17884b4182801480aa09b7908 - Merge pull request 346 from isRyven/feature-pak-i..
 dc1e6eb1b43c8b98fd00ac2e202a3bbd3841c2bb - qcommon: don't hide server container paths refs 1..
 d4d0e5ea7e9f2f434d5488f2b9bfb3246e6a14c1 - client: fix FS_InvalidContainerName refs 1165

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-04-19T20:24:31Z

---

{FIXME}
* ~~check if the clean command is still useful, of if it can be removed - its purpose was to help cleaning files than will now be containerized.~~ (removed)
* ~~see com_cleanwhitelist cvar too~~ (removed, was related to /clean)
* ~~adjust current characters range limitation (one in download.c and other is in platform/sys_main).~~ (done)
* ~~remove redirect limitation (see ui_serverBrowserSettings as CVAR_INIT) if not needed anymore(?)~~ (it is still needed)

**Comment by rmarquis** [comment]
This subtask of pak isolation has been implemented. Closing.
