### ISSUE TITLE
Implement whitelist download and dialogs

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1166]
Author: @IR4T4 (IR4T4)
Date: 2019-01-15
Redmine Issue: 1166, https://dev.etlegacy.com/issues/1166

---

None

---

Related issue(s): #1199

---

Related commit(s):
c9b5888b270ed0dbd35bbe25cf00e2290e735cc8 - db: add whitelist table, fix start with non existi..
 b47cff6cc0a7f68069e1a25667940121824c4a83 - client: use whitelist from db - refs 1166
 2ad9ef057746bcc9626455a64c67c13a3e877c5e - qcommon: use whitelist from db - refs 1166

**Comment by ETLegacyTeam** [comment]
From: @isRyven (ryven)
Date: 2019-11-13T13:19:33Z

---

Check if we can reuse download system, so whilst connecting to the server we will perform the whitelist synchronization, and if necessary will first download whitelist reusing the download system and its ui, and then will perform the list checks.

**Comment by rmarquis** [comment]
Deprecated, due to the new approach discussed in #1161. Closing now.
