### ISSUE TITLE
Make effects display options consistent

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1173]
Author: @rmarquis (Spyhawk)
Date: 2019-01-18
Redmine Issue: 1173, https://dev.etlegacy.com/issues/1173

---

Depending on the effects display options selected, some players might have an advantage over others.

Indeed, some features can be disabled by default (cg_particules), while some can't (foliage, that is cheat protected).
Some are more game changing (explosion), while other are completely cosmetics (blood effects, atmospheric effects), and some cosmetics effects currently can't be disabled at all (debris effects of 2.76, airstrike plane model in soon-to-be-released 2.77, etc.).

Find a way to make this consistent accross the game options, while keeping performances and unfair advantages in mind.

A few arguments when this issue was discussed:

spyhawk

bq. maybe it would be good to add an "In-Game Effect" cvar to disable debris and plane effects. Save a few FPS.

hatcher

bq. Explosions should not be allowed to be turned off anymore. It's basically wallhack then. I played with potato graphics back in the day but now I refuse to do that because that's not the way forward and I often feel at a disadvantage behind explosions.

spyhawk

bq. I disagree: not a wallhack. Or we should disallow brass and blood (flash effect).

hatcher

bq. If you turn it off, you can but those peopel who don't turn it off, they can't. It's an unfair advantage that forces everyone to turn it off leading to the same thing that happened in the 2000's. Potato graphics. That's not the way forward in 2019.

hatcher

bq. bobbing and blood flash shouldn't be there to begin with

spyhawk

bq. Blood flash is exactly that, no?
those that disable it have an advantage

IR4

bq. it's a 1st p effect
explosions not
the blend stuff

spyhawk

bq. hmm okay. I'd accept that argument.
But still: 1st person effects are a drawback for those that enable them.

hatcher

bq. I don't know why a mathematical formula would be needed to decide what should be allowed and what shouldn't be, it's just what people decide but that also depends on where players are coming from. Old competetive players would want everything off, old casual players may want everything on. New players wouldn't even understand why it's even possible to turn off something like explosions but most would agree that flashing blood that covers the screen is stupid. On the other hand, something that happens in the world is not stupid just because you can't see through it and eats a few FPS.

**Comment by rmarquis** [comment]
`cg_visualEffects` has been added in 52219af45338681566120a427b9b3124f1e13946 and a14d8f065daf44ef69e0e2d9934ef025eaf29805.

`cg_wolfparticles` should be enabled by default and the cvar removed (see hatcher's comment above).
