### ISSUE TITLE
In-game VoIP support

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#119]
Author: @rafal1137 (RaFaL)
Date: 2012-11-15
Redmine Issue: 119, https://dev.etlegacy.com/issues/119

---

Should ET:L have this option?
Communicating between everyone on the server/team/party.

One should be able to disable/enable this anytime.

**Comment by ETLegacyTeam** [comment]
From: @JanSimek (Radegast)
Date: 2012-11-15T18:51:48Z

---

This should only be a matter of copy & paste from ioquake3 code. However, to make VOIP work two things would have to happen:

1. we would have to fix OpenAL support
1. we would have to either bump the protocol version or use dual-protocols like ioquake3 does = incompatibility with W:ET 2.60b

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2012-11-15T19:24:14Z

---

Don't get me wrong I like this feature but ... what system to add? mumble, teamspeak? ... just implementing one VOIP client system is a bad choice. Maybe better than none but in my eyes it's not the time to add such a feature. Beside Radegasts notes I can imagine keyboard issues (AZERTY problem - see #111) when there is a need for additional control keys of the VOIP client.

**Comment by ETLegacyTeam** [comment]
From: @JanSimek (Radegast)
Date: 2012-11-15T20:16:23Z

---

IR4T4 wrote:
> ... what system to add? mumble, teamspeak?

ioquake3 has a custom VOIP protocol which is part of the client and server. You only need to enable voip cvar and then press ’q’ to speak. Mumble positional audio support is a separate feature.

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2012-11-15T22:55:52Z

---

I see worth a try :)

**Comment by ETLegacyTeam** [comment]
From: @winrid (winrid)
Date: 2014-11-09T18:46:48Z

---

Radegast wrote:
> ioquake3 has a custom VOIP protocol which is part of the client and server. You only need to enable voip cvar and then press ’q’ to speak. Mumble positional audio support is a separate feature.

Is it proximity based? Proximity based VOIP is a very fun game dynamic. If you try out Resistance and Liberation you'll see what I mean. It could be a server setting.
EDIT: Didn't catch your last sentence.

**Comment by rmarquis** [comment]
Relevant about OpenAL/Mumble: https://github.com/kcat/openal-soft/issues/415

Since it isn't easy to get correct positional audio, and VoiP support is better provided by any more modern service, this feature isn't worth implementing.

Closing now.
