### ISSUE TITLE
Release 2.77 "Capture the city!"

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1192]
Author: @IR4T4 (IR4T4)
Date: 2019-01-24
Redmine Issue: 1192, https://dev.etlegacy.com/issues/1192

---

Main goals:

- Make new vfs container system work
- Make new db based favorites work 
- Adjust main menu to show quick join options
- Implement competition gameplay features based on received feedback
- ... fix as many other bugs as possible

Also:
- Update OB navpoints, WolfAdmin
- Update libs (minor update only)
- Ensure 2.60b client still works without crash (check new favorites system, use #LEGACY macro if needed)
- Tag Lua API doc
- Include CVE fixes

ETA: ASAP

For post-2.77
* prepare new style formatting (uncrustify, see morsik)

---

Related issue(s): #1191

**Comment by jackeri** [comment]
Released 1.3.2021 1:30AM GMT+0
