### ISSUE TITLE
Add b_banners CVAR from etpro

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1198]
Author: @BystryPL (Bystry)
Date: 2019-02-01
Redmine Issue: 1198, https://dev.etlegacy.com/issues/1198

---

Not much to say. Just a cool option for public legacy servers to put some additional info for players.

---

Related commit(s):
7096c0f96175cbeba81881b579d9085782f0b7df - cgame: add bp command, refs 233 1198This adds ..
 1b55e5946a20fbe37ef3a75e3cff79198f8bdbad - cgame: refactor banner print cvars, refs 233 119..
 42df645e186f7075caf99296b760aee02f8732d3 - ui: added banner time slider, refs 233 1198

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-02-01T17:27:16Z

---

This concerns server administration, so this is better implemented in WolfAdmin.

See https://dev.timosmit.com/bugtracker/view.php?id=98. This is planned for the next release already.
There is also an existing Lua banner script "here":https://github.com/etlegacy/etlegacy-lua_scripts/tree/master/banners.

Closing here.

**Comment by ETLegacyTeam** [comment]
From: @isRyven (ryven)
Date: 2019-02-02T21:44:06Z

---

Hello, if I may, my two cents, this isn't just concerns the server side. This, usually, also requires client side modification in order to implement feature correctly. You see, pretty much every implementation, apart from the lazy one used in provided lua script, requires a dedicated message space, which is usually a top part of the screen, and a dedicated server command "bp" sent to the client to display the message on that spot. You should of course be able to select the place banner is printed using the aforementioned cvar, but usually it would default to "bp", and be displayed on the top of the screen. This way messages printed using "bp", instead of "cp", are less distracting and could be disabled all along using client cvar. Hereby, I suggest to reopen the issue and actually implement it in the mod.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-02-03T13:16:38Z

---

A few things (personal pov and all):
* banners shouldn't be able to be disabled by cvars client side. That's the point of a admin banner: being (more or less) useful mandatory spam from admins.
* it's still server administration, and as such has not point in being implemented in the mod but better left to WA
* implementing a new bp print mod side when admin can use cp reasonably is bloat, especially as it would only been used for such server administration feature. I'd rather not have that in the code.

Lastly, I'm personally not a fan of banners in general (or watermark as implemented in some mods). To me, it's unecessary admin spam/ads that is better left outside the game. cp/cpm does also the job more than reasonably for in-game info.

**Comment by ETLegacyTeam** [comment]
From: @isRyven (ryven)
Date: 2019-02-03T14:43:36Z

---

Personally not being fan of banners either, and this is why I am proposing to add bp, since otherwise you can't run away from cp/cpm based madness running by lua.

cp, cpm and chat aren't good places for banners - it's annoying, distracting and useless. cpm prints are all about MODs and announcements, banners just won't be properly displayed simply due to the stream of MODs, more over banners are usually much longer, which could occupy more than a single line, leaving less space for something useful. As for cp banners, what can be worse? Having continuously repetitive messages printed on the center of the screen, definitely not for me. This is why I think banners should be controlled and have proper default behavior and place to be displayed, something you won't achieve with WA alone.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-02-03T15:28:57Z

---

> banners - it’s annoying, distracting and useless.

Yeah, pretty much my view: banners are a _shitty_ feature, and certainly not a "cool" feature imho.
In fact, I'd be personally fine in not adding banners support at all (not even in WA, but that's outside of my control ^^), because well, why should we encourage admins to use them in the first place?
Etpro might have it, but I really don't think we should add it because "etpro did".
And again, adding some cvar to disable them client side doesn't make sense - better not adding the feature at all then. At least, using them as cp/cpm print force admins not using too much, or they become really annoying for players.

However, I'm not strictly against adding a new print command - if (and only if) it does make sense somehow for the mod as a feature outside of abs/banners (but what?). Adding it just for the sake of displaying admin shit - no, I really don't want that. That's better left outside of Legacy mod.

**Comment by ETLegacyTeam** [comment]
From: @isRyven (ryven)
Date: 2019-02-03T16:21:05Z

---

Well whether we like it or not, banners gonna exist. I guess to address that issue, whoever thought about it first, decided to make it less distracting yet visible for any new player, and created bp to draw it on top. To be clear it's not just etpro feature, other mods also have it, to name few - etpub, jaymod, etrun and etjump (all can be checked in source code), and I have no doubts any other popular mod has it too. This just became some sort of standard among mods, and I guess people and scripts kinda expect bp to be there too. In etpro, bp is also used to draw match information in ettv mode (and maybe in shoutcaster mode), like times teams have set finishing specific goals in sw. Pretty sure I saw lua scripts are using bp to draw different kind of information too, like sprees. I mean it's not just for banners only really. To make it more generic I would suggest to give it different name, but I don't really want to break the standard naming convention over here. 
And I think not doing anything and allow polluting cp and cpm isn't a solution to the problem here, but we don't have to invent a solution really, since people already invented, it and this is bp!

P.s. Sorry I can't have this discussion with you in discord, since I am away, and it's much easier to write here :p

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-02-03T16:31:14Z

---

Well, if we do add banner print, I'd like to at least:
* use it for some mod features (maybe geoIP stuff printed on connect when enabled?), rather than being empty just for the sake of being hooked by Lua only;
* add a cvar to disable it client side. It's counter-intuitive to the very purpose of mandatory banners (see above), but serioulsy, admins can go eat d*icks. I don't want to see them in-game.
* please anyone, don't ask about adding watermark ever.

Other opinion welcome. Reopening in the meantime.

**Comment by ETLegacyTeam** [comment]
From: @isRyven (ryven)
Date: 2019-02-03T16:57:53Z

---

Sounds good to me.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-02-05T17:02:54Z

---

Kemon mentioned (jokingly?) that banners could be displayed to players when they are spectators only.
That might actually be a good solution, with minimal useless info displayed when people are playing, while still being visible at connection or other spec time.

**Comment by ETLegacyTeam** [comment]
From: @isRyven (ryven)
Date: 2019-02-06T09:08:29Z

---

I would just make bp command working, and let scripts to use it as needed. So we wouldn't concentrate as much on the banners as on some generic spot to print stuff? That implies that scripts would control when stuff is printed instead.

**Comment by ETLegacyTeam** [comment]
From: @timosmit (Timothy)
Date: 2019-02-06T09:44:46Z

---

Also, I'd like to quote this:

kemon wrote (Discord 05/02/2019 18:21):
> If there is currently banner spam in the chat then this is even worse than spam that is on the top of my screen, because I actually read the chat. So for me, moving the spam to the top would actually be better.

I second this. Personally I'd prefer server info and related stuff to be printed at the top. Then we have a clear distinction for all areas:

chat area: like the name implies, just chat messages (and command output from !commands)
cpm: game info (e.g. objective updates, obituaries)
center print: interactions that are relevant to the player
banner print: server information
console: everything

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2019-02-06T19:05:44Z

---

I like the idea of banner prints to spectators only.

**Comment by ETLegacyTeam** [comment]
From: mrmuppet (mrmuppet)
Date: 2019-02-09T00:52:43Z

---

IR4T4 wrote:
> I like the idea of banner prints to spectators only.

Agreed!

**Comment by isRyven** [comment]
changeset ecd531ed948c12e5bd393dca00049110cdbf42fe
