### ISSUE TITLE
Remove follow1 and follow2

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1204]
Author: @timosmit (Timothy)
Date: 2019-02-12
Redmine Issue: 1204, https://dev.etlegacy.com/issues/1204

---

According to spyhawk on Discord on 02/02/2019:
> follow1 and follow2 teams are leftover from a Q3 broken feature. Remove.

**Comment by rmarquis** [comment]
Done as part of #1392. Closing.
