### ISSUE TITLE
Link screenshot command to JPEG

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1205]
Author: @timosmit (Timothy)
Date: 2019-02-12
Redmine Issue: 1205, https://dev.etlegacy.com/issues/1205

---

According to Spyhawk on Discord on 25/01/2019:
> And I still need to make @/screenshot@ command use jpeg by default, or better, link it to the existing @cg_useScreenshotJPEG@ cvar.

**Comment by rmarquis** [comment]
This has been implemented in 0d1781f708adf5c3099055a81aa3511b53696923. See also #1300.
