### ISSUE TITLE
Not possible to crawl close to wall and objects

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1208]
Author: @rmarquis (Spyhawk)
Date: 2019-02-21
Redmine Issue: 1208, https://dev.etlegacy.com/issues/1208

---

It's not possible to crawl close to objects or walls, unlike vanilla. It is still possible to get close by crawling sideways, after which crawling forward directly towards the wall will push the player backward.
This *might* be related to fixed realHead box (very wild guess).

---

Related issue(s): #503, #1115

---

Related commit(s):
8c5b0c59036abde79acc41ab56771e48dbadfe2d - game: prevent rotation while proning if head go so..
 991c32d9c522d4e64c0d68455418f7cb10dad567 - game: add g_debugPlayerHitboxes 4 to display hitbo..
 683e7e735a0fa23f25c72b6ea48673f0abc57953 - cgame: forward view origin when prone to match hea..
 b2b08a5af1bc2aacd413ae6069d69f82a656bbab - cgame: don't play prone transition view when crouc..
 a4ab1a39612188e7e906144631e5bb9f28bb7ae5 - game: improve debug players hitboxes collision, re..
 8f306555761055b64f95c69224895f726d527282 - game: adjust collision detection on prone, refs 1..
 b22f27eb31d8f8c475da514df1c00d67b087eb6d - game: adjust Z hitbox collision on prone, refs 12..
 164b964c3682c0098363470e4c279d6dceff4d7b - game: removed unused variable
 3083f98b53cd8123e89df2cc486007ccfbf1b30c - mod: fix head/legs collision on steppable elements..

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-03-16T14:44:23Z

---

-I can reproduce as far as 2.72. This is much likely due to the readhead code, which was introduced in 2.71.- Can also reproduce on 2.71rc3, the issue might be even older.

And the current behaviour is correct, the player shouldn't be allowed to crawl too far... because the model then crawl inside the wall/objects.
It is however possible to crawl "from the side" (since the headbot doesn't interfere) and then rotate the body. See screenshot below.

Might be a good idea to prevent that rotation somehow.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-11-13T13:38:23Z

---

It feels like the head point of view is not at the correct place when crawling. You can see the headbox in front of you, basically. The coordinate of player pov might be adjusted vertically only, but not horizontally.

**Comment by ETLegacyTeam** [comment]
From: @Aranud (Aranud)
Date: 2020-02-04T23:40:22Z

---

{TODO} Could be related to theses changes. Investigate :

* https://github.com/etlegacy/etlegacy/blob/83141e0a3e28f5760964e94254641134f8b6489b/src/game/bg_slidemove.c#L400-L410 
* https://github.com/id-Software/Enemy-Territory/blob/40342a9e3690cb5b627a433d4d5cbf30e3c57698/src/game/bg_slidemove.c#L359 
* https://github.com/etlegacy/etlegacy/commit/8e9685f6851dd4c2db0abafda5f2c60edeb45246#diff-4941aec0b764cd0c85a6cd3e03ab42cb 
* https://dev.etlegacy.com/issues/164

**Comment by rmarquis** [comment]
Reopening: when facing a wall and proning, consider moving the collision box slightly backward, as to keep same behaviour as original ET.
