### ISSUE TITLE
Replace debug CVARs with Lua

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1240]
Author: @realkemon (keMoN)
Date: 2019-04-01
Redmine Issue: 1240, https://dev.etlegacy.com/issues/1240

---

There are various CVARs in the game which are clearly used only for debugging purposes and don't need to be in a public mod.
Can those be removed from the mod and moved to an optional Lua script as well (see #1238) so devs in need of them can quickly attach them to their game?

CVARs in question:
cg_debugAnim
cg_debugEvents
cg_debugPosition
cg_debugSkills
cg_gun_frame
cg_showMiss
cg_stats
cl_debugMove
cl_showmouserate
cl_shownet
cl_shownuments
cl_showSend
cl_showServerCommands
cl_showTimeDelta
com_showTrace
com_speeds

I'll populate this ticket with more if I find additional debug CVARs

//EDIT:
Maybe rename them all to debug_* and only make them accessible with enabled 'fs_debug' mode

---

Related issue(s): #1238 #1277

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-04-01T17:04:20Z

---

Ah... not convinced by that one. Debug cvars have the purpose of helping developers. While the're really useless for players, they're essential to us (especially when Lua scripts cannot replace them efficiently).
We shoudl probably hide them behind a debug mode though - I believe there is a macro we use for some of these.

**Comment by ETLegacyTeam** [comment]
From: @realkemon (keMoN)
Date: 2019-04-02T10:33:26Z

---

cg_showMiss
cg_stats
com_showTrace

**Comment by rmarquis** [comment]
This should be implemented through #1277. Closing this as duplicate.
