### ISSUE TITLE
Server crash related to filesystem access

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1243]
Author: @rmarquis (Spyhawk)
Date: 2019-04-02
Redmine Issue: 1243, https://dev.etlegacy.com/issues/1243

---

The test server tends to crash every few weeks or so. The logs have interesting content:

* it seems the game log file can't be opened (maybe some issue with log rotation)
* the mapvote.txt suddenly can't be opened
* the database eventually can't be accessed anymore (locked), resulting in a hard crash
* There are some WA error, but I believe this is unreletad (WA got some bugfix in its dev branch)

See attachment, last bit of the ~80mb server log file.

---

Related issue(s): #987

---

Related commit(s):
c6d650ea27fa902a81cbbc2e2ced4c021dc646ed - game: fixed mod logfile not always created, refs ..

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-04-02T16:27:53Z

---

For reference, there is a copy of the three previous crashed logs on the server (internal access, 80+ mb each):
* output_crashed_at_0820_on_270119.log
* output_crashed_at_1112_on_010419.log
* output_crashed_at_0554_on_060519.log

Additional info:
Restarted the test server.
-`WARNING: Couldn't open logfile: legacy_mod.log` is printed, but doesn't seem to be critical here.- (done)

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-04-12T16:24:56Z

---

About the mod log side-issue: it looks like the "append" mode fails to create a new file when it isn't already present. For some reason, the "create" fallback just fails.
* The issue doesn't happen on windows, but only Linux (confirmed on the test server running CentOS 7, locally on Arch, and on by a third party on his server).
* this isn't a permission issue, since it is possible to create a new file (tested locally)

I couldn't find much about that issue, apart from "this article":http://www.decompile.com/cpp/faq/fopen_write_append.htm ("The descriptions for both the "a" and "a+" append modes say that the file will be created if it doesn't exist. I've found, in practice, that this doesn't work. If the file doesn't exist when fopen is called with a "a" or "a+" open mode, the file will not be created.")

Suggestion for a dirty workaround: if the append mod fails, try creating the file with a normal "write" mode, close the file, and try to append it to it again. (done)

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-04-19T08:16:37Z

---

Server crashed again. Same symtoms. Log is 95 Mb this time (output_crashed_at_0453_on_190419.log).

A "recent commit":https://github.com/etlegacy/etlegacy/commit/e9e3364033a82360caa134389286b5e22c86962c fixed some issue in the Lua stack (" Lua vm stack was uncontrollably growing after each hook
  callback call"), see if that fix improves the situation on the next update.

* 06/05/19: Ignore the following log: output_stopped_at_1820_on_060519.log (server was restarted for maintenance).
* 05/06/19: new crash. Same symptoms. The Lua stack growth fix doesn't seem to have improved the situation here.
* 28/06/19: yada. Same symtoms.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-11-26T11:26:14Z

---

See Ododo's comment on seemingly unrelated(?) issue: https://dev.etlegacy.com/issues/987#note-8

> A file descriptor for etl.db seems to be created on each map load, without closing the previous. (see attachment)
> So maybe the system has reached a limit as the errno 24 on mapvoteinfo.txt suggest.

```
etlded  986 olivier    0u   CHR  136,0       0t0        3 /dev/pts/0
etlded  986 olivier    1u   CHR  136,0       0t0        3 /dev/pts/0
etlded  986 olivier    2u   CHR  136,0       0t0        3 /dev/pts/0
etlded  986 olivier    3r   REG    8,1 228138631  3541288 /home/olivier/Downloads/etlegacy-v2.76-i386/etmain/pak0.pk3
etlded  986 olivier    4r   REG    8,1     51616  3541289 /home/olivier/Downloads/etlegacy-v2.76-i386/etmain/pak1.pk3
etlded  986 olivier    5r   REG    8,1     89910  3541290 /home/olivier/Downloads/etlegacy-v2.76-i386/etmain/pak2.pk3
etlded  986 olivier    6r   REG    8,1   3214024  3543606 /home/olivier/Downloads/etlegacy-v2.76-i386/legacy/etl_bin_v2.76.pk3
etlded  986 olivier    7r   REG    8,1   7127049  3541052 /home/olivier/Downloads/etlegacy-v2.76-i386/legacy/pak3_v2.76.pk3
etlded  986 olivier    8u   REG    8,1     61440  4987129 /home/olivier/.etlegacy/etl.db
etlded  986 olivier    9u  IPv4  23271       0t0      UDP *:27960
etlded  986 olivier   10u   REG    8,1     61440  4987129 /home/olivier/.etlegacy/etl.db
etlded  986 olivier   11u   REG    8,1     61440  4987129 /home/olivier/.etlegacy/etl.db
etlded  986 olivier   12u   REG    8,1     61440  4987129 /home/olivier/.etlegacy/etl.db
etlded  986 olivier   13u   REG    8,1     61440  4987129 /home/olivier/.etlegacy/etl.db
etlded  986 olivier   14u   REG    8,1     61440  4987129 /home/olivier/.etlegacy/etl.db
etlded  986 olivier   15u   REG    8,1     61440  4987129 /home/olivier/.etlegacy/etl.db
etlded  986 olivier   16u   REG    8,1     61440  4987129 /home/olivier/.etlegacy/etl.db
etlded  986 olivier   17u   REG    8,1     61440  4987129 /home/olivier/.etlegacy/etl.db
etlded  986 olivier   18u   REG    8,1     61440  4987129 /home/olivier/.etlegacy/etl.db

```

**Comment by rmarquis** [comment]
Commit 0e80bda32d1bdbb54deea090088ba0f37f7606d0 might help here.

**Comment by rmarquis** [comment]
A quick check on test server seems to indicate the fd spam on `etl.db` is now gone:
```
$ ps aux | grep etlded (to get pid)
$ ls -l /proc/<pid>/fd
```
There are 2 fd on etl.db for some reasons, but it doesn't continuously grow.

**Comment by rmarquis** [comment]
Closing. This doesn't seem to occur anymore.
