### ISSUE TITLE
Bad command byte for client warning

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1245]
Author: @rmarquis (Spyhawk)
Date: 2019-04-07
Redmine Issue: 1245, https://dev.etlegacy.com/issues/1245

---

Report from TM:

```
WARNING: bad command byte for client 31
WARNING: bad command byte for client 31
WARNING: bad command byte for client 31
WARNING: bad command byte for client 31
...

```

This warning happens "on the host, and make people kinda lag out and not be able to move at all". "You have to disconnect your self or you kinda in limbo, can read the text on screen but can't move or anything else".
The issue is inconsistent: "will have to see if it keeps doing it again only happened twice today".

The warning is generated in `sv_client.c`:
```
if (c != clc_EOF)
	{
		Com_Printf("WARNING: bad command byte for client %i\n", (int) (cl - svs.clients));
	}

```
 It might be related to changes done to MSG_ReadByte(), or might simply due to an indexed array issue.
Closest commit that _might_ be related to that issue can be found "here":https://github.com/etlegacy/etlegacy/commit/40c4697cbdaea8abf8cca0304f8a0bc62a96e273

**Comment by rmarquis** [comment]
This has been fixed as part of #1365, specifically in a6c0968.
