### ISSUE TITLE
Blurred and pixelated hud icons with low picmip

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1251]
Author: @BystryPL (Bystry)
Date: 2019-04-18
Redmine Issue: 1251, https://dev.etlegacy.com/issues/1251

---

Same issue as previously with rank icons, this time with new objective icons. 

---

Related commit(s):
d9aeef01e6b361b6fcb806e5a5edc356f26dd62f - cgame: fixed objective indicator display with low ..
 b9d8a9c958d25dd876a3285e53ae77a89f2057bf - cgame: fixed blur on some obitiaries icon with low..
 871fa50fd87b645a60f76909d2ba0085c4667be7 - cgame: fix impact sound loading* impact sound lo..

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-04-18T15:27:22Z

---

{FIXME}
Let's use this ticket to track all icons that are problematic:
* -objective indicator icons (new icons only)- (fixed)
* some rank icons (scoreboard)
* -some obituaries icons (weapons, ..)- (fixed)
* rank icons on helmets
* ...

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-04-18T18:07:02Z

---

The new objective indicator icons should now be displayed correctly. I'm still unsure why the main objective icon is displayed correctly using the default `trap_R_RegisterShader()` function, or why all ranks aren't displayed correctly despite being registered with the `trap_R_RegisterShaderNoMip()` function. This doesn't make sense to me.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-06-23T11:00:02Z

---

Guess we fixed what we could. Delaying to 2.78 for the rest of the issue.

**Comment by Aciz** [comment]
About the rank icons - I think the issue is that they use the default shader found in `gfx_hud.shader` instead of the one in `legacy.shader`. I cannot get the ranks to display in locahost for whatever reason to confirm my suspicion.
