### ISSUE TITLE
Rain on Würzburg Radar too loud on OpenAL

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1262]
Author: @realkemon (keMoN)
Date: 2019-04-25
Redmine Issue: 1262, https://dev.etlegacy.com/issues/1262

---

Reported on-stream by "Lightningzor":https://www.twitch.tv/lightningzor .
Under s_initSound 2 (OpenAL) the Radar rain sound feels a little too loud.

**Comment by Rhino-Cracker** [comment]
Hi all, I can contribute to this issue, that a lot of sounds have a different distancial volume decay in OpenAL compared to the SDL audio backend:
- For example I'm not able to hear my own footsteps (in OpenAL). 
- Some environmental noise effects are as loud in OpenAL as if I'm directly at the source in SDL (I guess that rain keMoN reported counts to it). 
- And some other environmental sounds have a pretty strange decay behaviour (go from 100% to 50% when gaining distance and then suddenly drop to 0%). Concrete example: Theutonia, Allies Spawn, the helicopter sound. Go into the tunnel to the left and see how the volume drops from ~50% to 0 at some point in the tunnel.

Ah, I forgot: I'm using a 5.1 sound system, analog outputs, my onboard sound device (Gigabyte X570 Aorus Elite), Windows 10 Pro 1909 and mostly playing on bunker4fun (nq mod)

**Comment by Aranud** [comment]
Louds sounds are gone and the "Doubling the distance halves the source gain" behaviour has been replaced by a "Linear gain scaling between the reference and max distances".

There's still some difference with SDL like local sound barely audible when ambient sound like rain is played. That better than before but still too weak from what we are expecting.
Could be an issue with sound mixing and volume priority.
