### ISSUE TITLE
Lower resolutions are not centered on screen

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1267]
Author: @realkemon (keMoN)
Date: 2019-04-28
Redmine Issue: 1267, https://dev.etlegacy.com/issues/1267

---

It seems that lower resolutions are not centered on screen, but rather have their origin in the bottom left corner resulting in black bars on the top and the right of the screen.

//EDIT: Maybe useful information that I'm using and AMD Radeon

**Comment by ETLegacyTeam** [comment]
From: swecide (swecide)
Date: 2019-05-19T13:03:58Z

---

Just wanted to add that I think this happens when your OS/Desktop is running at a higher res compared to the game. For example I have my desktop set to 3840x2160 but the game is running at 1920x1080. Occasionally the game launches with the same phenomena keMoN described, the game still "thinks" its running in full screen. Intel Iris Pro Graphics 580 GPU here.

**Comment by rmarquis** [comment]
That one sounds like a driver or SDL issue, and I don't think we can actually fix that by ourselves. Kemon indicated the issue is now gone, it is possible that latest shipped SDL might have helped.
Closing.
