### ISSUE TITLE
ET Legacy crashes everytime its minimised

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1270]
Author: Patronza (Patronza)
Date: 2019-04-30
Redmine Issue: 1270, https://dev.etlegacy.com/issues/1270

---

Hi folks,

I've been enjoying ET Legacy heaps. Unfortunately every time I use ALT + TAB, or WIN + D, Legacy crashes completely once the desktop appears.

Running: Windows 10 Pro 64bit, ET Legacy 2.76.

Hope you guys can fix it sometime. Cheers!

---

Related issue(s): #986

**Comment by ETLegacyTeam** [comment]
From: @realkemon (keMoN)
Date: 2019-04-30T12:02:49Z

---

Do you have a crashlog for us so we can investigate what the issue might be?

To get one start your game with "/logfile 2" and then reproduce the steps leading to your crash.
You should now find a crashlog in your "homepath":https://dev.etlegacy.com/projects/etlegacy/wiki/Path_and_File_Structure#fs_homepath-content

**Comment by ETLegacyTeam** [comment]
From: Patronza (Patronza)
Date: 2019-04-30T12:33:51Z

---

keMoN wrote:
> Do you have a crashlog for us so we can investigate what the issue might be?
> 
> To get one start your game with "/logfile 2" and then reproduce the steps leading to your crash.
> You should now find a crashlog in your "homepath":https://dev.etlegacy.com/projects/etlegacy/wiki/Path_and_File_Structure#fs_homepath-content

Sorry, but I do not know what "/logfile 2" is? I tried using the console and entering that as a command, but nothing happened, and there is nothing that looks like a log in the main ET Legacy directory.
There is a file called logs.lua located in: C:\Program Files (x86)\Enemy Territory - Legacy\legacy\luascripts\wolfadmin\util

Cheers,
Patrick

**Comment by ETLegacyTeam** [comment]
From: @realkemon (keMoN)
Date: 2019-04-30T12:49:36Z

---

It is indeed a console cmd.

1. Open console [SHIFT]+[ESC]
2. Enter "/logifle 2"
3. Confirm it worked and initiate log with "/logfile" (it should return that it is currently 2 and that it started a logfile
4. Reproduce your steps
5. Find the crashlog.txt in fs_homepath

**Comment by ETLegacyTeam** [comment]
From: Patronza (Patronza)
Date: 2019-04-30T12:54:10Z

---

Ah rightio, legacy has a different console. I just used the "~" console. I'll do that tomorrow when I'm back on my computer. I looked in the wiki about logs, but there wasn't any wiki topic there that I could see.

Cheers,
Patrick

**Comment by ETLegacyTeam** [comment]
From: Patronza (Patronza)
Date: 2019-05-01T02:38:21Z

---

I tried your steps, but no longfile is produced anywhere I can find. I've even got windows to search all of C:/program files x86 for crashlog.txt.

So here I will upload a video of my steps... Just to show you I've generated a crashlog I use the filelog 2 command. Normally it confirms the command but then will say straight away that command not recognised (which it didn't this time).

**Comment by ETLegacyTeam** [comment]
From: Patronza (Patronza)
Date: 2019-05-01T02:40:43Z

---

The weird thing is that when I used OBS Studio to try and screen capture, Legacy did not crash and minimised normally.

**Comment by ETLegacyTeam** [comment]
From: @isRyven (ryven)
Date: 2019-05-01T08:20:27Z

---

Depending on which mod you are using, you will find the log file and/or crashlog in *Documents/ETLegacy/legacy* path (where *legacy* can be the name of the other mod that is crashing while you are playing ).

**Comment by ETLegacyTeam** [comment]
From: Patronza (Patronza)
Date: 2019-05-02T02:25:57Z

---

ryven wrote:
> Depending on which mod you are using, you will find the log file and/or crashlog in *Documents/ETLegacy/legacy* path (where *legacy* can be the name of the other mod that is crashing while you are playing ).

Ive looked EVERYWHERE for this log file, I even did a full search of C drive (I only have 1 HDD). I can only conclude that ET:L is not creating a log file. As I have previously mentioned some of the time the console will confirm a log was created, then follow immediately with a command not recognised error.

**Comment by ETLegacyTeam** [comment]
From: Patronza (Patronza)
Date: 2019-05-02T02:34:57Z

---

Patronza wrote:
> ryven wrote:
> > Depending on which mod you are using, you will find the log file and/or crashlog in *Documents/ETLegacy/legacy* path (where *legacy* can be the name of the other mod that is crashing while you are playing ).
> 
> Ive looked EVERYWHERE for this log file, I even did a full search of C drive (I only have 1 HDD). I can only conclude that ET:L is not creating a log file. As I have previously mentioned some of the time the console will confirm a log was created, then follow immediately with a command not recognised error.

I found a log within the file called "etconsole.txt". it states the following. (I alt + tab after getting the logfile is 2 confirmation):

logfile opened on Thu May  2 12:32:21 2019

]/logfile 2
]/logfile
"logfile" is: "2^7" default:"0^7"
----- CL_Shutdown -----
Closing SDL audio device...
SDL audio device shut down.
RE_Shutdown( 1 )
SDL input devices shut down.
-----------------------
PID file removed.
Network shutdown.

Also note that I am not using any mods. just base legacy. I start the game and do alt +tab or Win +D, and can replicate issue 100% of the time at any point, whether playing a hosted game or joined game, or just in the main menu

**Comment by rmarquis** [comment]
Can't be reproduced, and no useful information provided to debug it. Might actually be a driver issue. Closing now, but feel free to reopen if needed.
