### ISSUE TITLE
Add shoutcaster role

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1292]
Author: @rmarquis (Spyhawk)
Date: 2019-05-16
Redmine Issue: 1292, https://dev.etlegacy.com/issues/1292

---

Add shoutcaster role, which is basically the same as spec mode with a few useful addition:
* -can see player names floating above them (in spec and following mode), always!- (done)
* can see player health floating above them (in spec and following mode), always! (this require architectural changes, as health of all players is not sent to client - unless they are in the same fireteam)
* -can see revive icons- (done)
* -can see disguised covops- (done)
* -can see landmines (glowing red)- (done)
* -can see dynamite counter- (done)
* -can see tank and truck health- (done)
* -can see objective indicator, always!- (done)
* -can see compass/minimap even in free fly mode- (done)
* -can see all position on command map- (done)
* -can see respawn time of both team (see custom ETTV client screenshot)- (done)
* can see dynamite/landmine owner
* -can see scoring time of SW previous round (see custom ETTV client screenshot)- (not needed)
* can see throwed nade path (see CS-Go)
* can see through wall to some extend (see CS-Go)
* can see banner prints that print objective information showing what objective has been done in what time and for the next round it also prints if that was slower or faster. For example: in the next round allies team captures the forward flag, and it prints "allies has captured the flag in 1:56 (faster on 30s than in previous round)" or something like that. See games doing speedrun competition.

This is related to ETTV, which might never be implemented (due to prevalence of twitch nowadays), but this feature is still useful for stream.

In addition:
* -shoutcaster shoudn't be able to join the game (unlike spec)- (done)
* -can't be kicked (unlike spec). See  g_inactivity / g_spectatorinactivity too- (done)
* -add ref menu to designate someone as shoutcaster- (done)
* -add a rcon-like password system to let shoutcaster connect directly- (done)
* -more than a single shoutcaster could be added- (done)
* -add a label in scoreboard too- (done)
* -add label in spec view (instead of "spectator")- (done)
* -grey out team flags in limbo menu- (done, using existing code with ugly red colour)
* -add a new icon for shoutcaster (instead of the spectator's eye) in limbo menu and map- (done)

---

Related commit(s):
32f905f45b379d8b102cd22326dac38fb3f65c62 - mod: added shoutcaster management functions, refs ..
 cd1e8c72f01a9ec280d6c9c606575a1a6a84c39f - mod: added in-game shoutcaster management buttons,..
 47b8544116de960129db45236a53b21450b56c44 - ui: added shoutcast settings in hostgame, refs 12..
 38e73eed6b6840eeef8387c6f065e47289c9cfe4 - cgame: added shoutcaster label in freefly and scor..
 84c9afd154cb033a622a26aaae4c10185228d8e8 - game: added shoutcaster checks for join team, vote..
 16c249ff1dbc4156281dcb25970c1edf200ab143 - game: shoutcasters are immune to inactivity drop, ..
 d155e11372ee0a2f3423346e1401626c91139455 - game: shoutcasters can't be kicked by vote, refs ..
 711ff14e15411a51cec9ce6c1ca011763f688cb8 - game: added Lua shoutcaster player field, refs 12..
 79f79aaf460679b8204d7b49990b80e669535a9c - game: display shoutcaster status in /players comma..
 699fbf90ae94406d86f99773b94de6b088bb12cf - cgame: shoutcasters always see player name labels,..
 ec429297144a9d133188ce9eeb39952b1e13bdaf - cgame: don't draw crosshair health for shoucasters..
 19992fffb843ac6073168e3146ed79739ae4b045 - cgame: shoutcasters can see tank and truck health,..
 3b1193567857011dd767efd467328342d47deba5 - mod: shoutcasters can see landmines, refs 1292
 761b85f0a287461d501fcd918c38e42b9bed9b02 - cgame: shoutcasters can see revive and disguised i..
 0f970061ab65be23c87d79c0e8a42f053f59b246 - cgame: shoutcasters see compass per default, refs ..
 7dee0f5965fabb3e3cada61eee7c882b09ba9ae8 - cgame: adjusted labels height, refs 1292
 38f6d0d172177ea85deb86d825ba15cef171c0f6 - cgame: shoutcasters can see dynamite timer, refs ..
 f32e52c74010e31c6fcc9ef6a51cadc77f606e83 - mod: shoutcasters can see all players on command m..
 99feb48824fe9e5accc092329a8d31822b47014b - cgame: fixed compass icons display for shoutcaster..
 cdf660bc4add0d318065dbc0688343ff57b22e11 - cgame: adjusted objective indicator for shoutcaste..
 0716cf3ab7219225176b7bbbce7ce26994359776 - cgame: added shoutcaster spawn timers, refs 1292
 7ec81b67f33b1314741b36d79b0f9ef1537ae888 - game: fixed out-of-bound and args count mismatch e..
 558ca6e55a1266ff70766ee9e74ac089f4bd4930 - game: fixed shoutcaster login command, refs 1292
 0be8b52e71c5cf5d3a770d2877088d9b1f18b5fb - game: fixed missing parameters in read session dat..
 740e44a6d04cf10fca22dca06cae6f2d50c6c8bd - cgame: adjusted reinforcement timer alignment, ref..
 320a59e8293dda97dc24a0fdab0dc8fff4db40b0 - cgame: fixed command map update when sent to limbo..
 f9310bdd2411fe42a955f70632fc9e00e2ab57a3 - cgame: lock teams for shoutcaster and add debriefi..
 0987baa6ac1d630dbeffbd35faeef09ee63f5760 - cgame: adjusted vote string for shoutcaster, refs ..
 b5bb80700e96c59854872874aab5b0374abc6094 - cgame: fixed disguised icon on command map for sho..
 01e3b3ed8ca7e236f79078aecaf907979313923a - cgame: adjusted obj indicator color for following ..
 c40d3f6d16e6f9d2329d10d75b843aa683bb981c - cgame: adjusted limbo panel for shoutcaster, refs ..
 131fa12737dfcc3e2c1a2fe64601b4646664b85c - game: fixed logged out shoutcaster not unfollowing..
 4e156fede8e00040979ea5a74efc4e1ec33d067a - cgame: added client console feedback for shoutcast..
 a22ab65f4ced8767b7fbb72867b35ebf6a36c735 - cgame: minor cleanup, refs 1292
 d421b55fc6eb53f712727c81b73a861e64c21a9f - cgame: adjusted alt timer alignment in warmup, ref..
 a514c09832e08e9d334358a7a6fa15cc18e55580 - cgame: adjusted alt spawntimer alignment, refs 12..
 5c549860aabd4e92085f0c068293c9bc12bed7f2 - cgame: adjusted alt round timer alignment for low ..

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-05-17T10:20:46Z

---

Evaluate this for 2.77.

It shouldn't be too hard to implement (everything is in the code already), but we should be cautious on how we implement the SC role:
* -add a new team (blue, red, spec, shoutcaster): beware of how conditions across the game are handled (ie, not BLUE nor RED = spec team)-
* -use spec team but add some sort of "referee" flag: only check for the flag when code would diverge from the regular spec team (I'd favour this implementation).- (implemented this way)

{TODO}
* check SC assignment from referee menu. There seem to be an issue when players have the same nickname (check slot number rather than partial name match?)

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-05-17T13:03:35Z

---

Check etpub implemention - it's partial but quite some has been done. Also, it's implemented like referee is, so that would indeed by the preferred way to do it.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-06-23T11:02:02Z

---

Here are a few more improvement possible:
* ~~when following, display mine flag same team, translucent when other team~~ (done)
* ~~when following, display names~~ (done)
* ~~when following, display dyna counter~~ (done)
* ~~when following, display revive if medic of same team~~ (done)
* ~~when following, display disguised icon (noshoot if same team->OK, but other if other team)~~ (done)
* ~~when following, display both team reinforcement timer~~ (done)
* ~~fix ghost player icon when following on minimap/command map~~ (done)

The rest can be delayed to 2.78.

**Comment by rmarquis** [comment]
Tracking extra feature in a separate ticket, to be developed later. Closing now.
