### ISSUE TITLE
Add separate objective messages popup area

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1303]
Author: @rmarquis (Spyhawk)
Date: 2019-05-26
Redmine Issue: 1303, https://dev.etlegacy.com/issues/1303

---

Currently kills, join, objective messages are all displayed as side popup (cpm).
While a filter has been added (#805), it would be better to have a dedicated space for better readability.
This could also prove to be useful for the shoutcaster feature (#1292).

* Add a new separate, cpm-like space for obj and map scripts messages.
* Use longer fade time.

**Comment by u1ps** [comment]
There are extra popupmessageboxes now that can be customized to do exactly that

**Comment by Aranud** [comment]
This commit add 2 extra popupmessage comp, allowing 1 message feed to display only objective message. https://github.com/etlegacy/etlegacy/commit/458c4f7ae2c7cdd18e7bdbd7509d25bf8061dd75
