### ISSUE TITLE
Hunk_Alloc fails if RENDERER_DYNAMIC is set off

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1314]
Author: @saukko28 (Saukko)
Date: 2019-06-26
Redmine Issue: 1314, https://dev.etlegacy.com/issues/1314

---

So basically how to set this up:

1. Set RENDERER_DYNAMIC 'OFF' in CMakeLists.txt and leave FEATURE_RENDERER2 'ON'
1. Compile with MSVC with these parameters: cmake -G "NMake Makefiles" -DBUNDLED_LIBS=YES .. && nmake
1. Start ET: L
1. Open console and /devmap any of the maps

This will lead into Hunk alloc fails, see attached screenshots.

-*S

**Comment by ETLegacyTeam** [comment]
From: @thunderpwn (thunder)
Date: 2019-10-16T13:50:51Z

---

tried to raise com_hunkmegs?

**Comment by rmarquis** [comment]
This has been fixed in b20138ce394ca1da439c779e56fab58c5324e753.
