### ISSUE TITLE
Automatic redirect when server is full

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1336]
Author: @alkhimey (artium)
Date: 2019-08-19
Redmine Issue: 1336, https://dev.etlegacy.com/issues/1336

---

Currently there is only one really active ETL server which is the teammuppet server.

On a a good night it gets pretty crowded. Everyone wants to join it because the other servers are empty with only bots. 
But when the server gets completely full, all the players that want to join are either waiting or abandoning  and quitting the game.
It is a chicken and egg problem. No one want to join other servers because there are no players there and there are not players there because no one want to join them.
Additionally, some people do not like certain maps, so when it is chosen in the pool, they quit the game completely because there is no alternative.
Additionally, I personally think that 15 vs 15 on most maps is too much and degenerates the gaming experience.

So to solve this issue, what could be done is adding an option for the admins to set the address of an additional server. 
When a player tries to connect to a full server, it will redirect it to the additional server (with a clear message, so not to confuse the player). 
This will allow teammuppet admins to lower capacity of the main server a little bit and redirect the residue players to another server thus producing two active ETL servers.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-08-20T09:38:33Z

---

Redirection feature is disabled on purpose, wince it can be easily misused to force players to redirect to a specific server by shitty admins. However, we had a talk recently about a "quick join" feature that would select a populated server based on availability and popularity.

**Comment by rmarquis** [comment]
The discussed alternative is now tracked in #1420. Closing.
