### ISSUE TITLE
Add server flag on scoreboard

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1342]
Author: @rmarquis (Spyhawk)
Date: 2019-08-27
Redmine Issue: 1342, https://dev.etlegacy.com/issues/1342

---

With g_countryFlags option 2 removed (see 08fd5345d4861fde88b2ce392e672157166d5503), it would be great to have an option to display the server location (with maybe name, IP, ..) instead.
A flag could be drawn on the scoreboard, but this requires to find some space to display it. The scoreboard is quite crowded.

**Comment by rmarquis** [comment]
I feel this is completely unnecessary. This doesn't add any useful info (server ping is what's important), and unlike the nationality of players, nobody cares about the "nationality" of servers.

I'd suggest to drop the feature.

**Comment by rmarquis** [comment]
Dropping the feature. There is no space available, and no one is missing that feature anyway: it is just bloat. Closing.
