### ISSUE TITLE
Server crash on Netchan_Transmit

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1353]
Author: hellreturn (hellreturn)
Date: 2019-10-05
Redmine Issue: 1353, https://dev.etlegacy.com/issues/1353

---

Server crashed with below reasons. Forgot to report earlier, my apologies. 

Sending 32769 bytes in gamestate to client: 14
SV_Netchan_Transmit: unsent fragments, stacked
********************
ERROR: MSG_Copy: can't copy 32769 into a smaller 32768 msg_t buffer
********************
----- Server Shutdown -----

**Comment by ETLegacyTeam** [comment]
From: mrmuppet (mrmuppet)
Date: 2019-10-15T21:28:45Z

---

hellreturn wrote:
> Server crashed with below reasons. Forgot to report earlier, my apologies. 
> 
> Sending 32769 bytes in gamestate to client: 14
> SV_Netchan_Transmit: unsent fragments, stacked
> ********************
> ERROR: MSG_Copy: can't copy 32769 into a smaller 32768 msg_t buffer
> ********************
> ----- Server Shutdown -----

Same here from tonight.

******************** ERROR: Netchan_Transmit: length = 32769 ********************

**Comment by jackeri** [comment]
This should have been fixed in 7183aad44c4c6eaa4181fc8b70a9bdb88729a201 please confirm.

**Comment by rafal1137** [comment]
@jackeri This should require building snapshot and send it to our personal favorite server to test/confirm that one.

**Comment by jackeri** [comment]
Closing this, as there has not been any new reporting's of this.
