### ISSUE TITLE
Client download is not redirected (when minimized)

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1356]
Author: @lachmex (eagle_cz)
Date: 2019-10-24
Redmine Issue: 1356, https://dev.etlegacy.com/issues/1356

---

Reported by MrMuppet @ TeamMuppet:

Just noticed on the Legacy server, if you minimise your clinet and have not got a file, say the next map the server moves on to, it will not redirect download

Way to reproduce: 
Delete your maps out of your directory and connect to the server, minimise your et, when it moves to the next map it wont download, and you will be off for missing pk3 file ... 
Press reconnect and it will only download from the game and not the redirect server

**Comment by rmarquis** [comment]
Commit of interest: d7bbc268d7edaf4cd3dff87780b9c590abca9348.

**Comment by rmarquis** [comment]
This should be fixed by the above commit. Closing.
