### ISSUE TITLE
cg_thirdperson on MG

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1359]
Author: @realkemon (keMoN)
Date: 2019-11-12
Redmine Issue: 1359, https://dev.etlegacy.com/issues/1359

---

When cg_thirdperson is enabled and you mount an mg the view gets weirdly glitched. It feels like a mix between third- and firstperson view.
Also that way in 2.60b

**Comment by thunderpwn** [comment]
![mount 3rdperson](https://user-images.githubusercontent.com/3218273/77250114-f1977680-6c45-11ea-8b43-0f7d91264829.png)
can confirm this
