### ISSUE TITLE
Port of ET Legacy to Android compatible Devices

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1361]
Author: @rafal1137 (RaFaL)
Date: 2019-11-15
Redmine Issue: 1361, https://dev.etlegacy.com/issues/1361

---

Most of the work has been done  and Game is running at Android Phones.
Current Supported arch/API Devices:

bq. armeabi-v7a - 16 API and up
arm64-v8a - 21 to 26 API

At this moment will not write System Requirements.

There are few bugs remaining  which makes game crashable like cg_shadows 1, but game is mostly playabble and enjoyable as Touch Contoll game gets.

**Comment by rafal1137** [comment]
TODO:

> - When disconecting from a server Android UI stays on <- FIXME

**Comment by rafal1137** [comment]
Ref Note instead
* 7bb568d062a8e8d1200f08db49f89efe74a4388a
Use Defined Macro in menumacros.h

**Comment by rafal1137** [comment]
Since we are officialy on Master/ Release has been shiiped.
Closing it.
