### ISSUE TITLE
Fov different when spectating with set weapons

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1368]
Author: @rmarquis (Spyhawk)
Date: 2019-12-01
Redmine Issue: 1368, https://dev.etlegacy.com/issues/1368

---

FOV when using deployed weapon (MG42/Browning/mortar when set) is different from the view of the player when spectating that player. This results in weird
 shooting/aim when spectating these players. 

Gameplay is unaffected, this is cosmetic issue for spectators only.

---

Related commit(s):
2724e2b5dc48e844aa28edf046eada4beda94f16 - mod: fixed set weapons position not sent to follow..
 f3c5e20adbbc9df86153c86e415b2475da31929c - Revert "mod: fixed set weapons position not sent t..
 de3eb7568ea04f28deee2255d3838e3906505cd5 - cgame: fix set weapons position for spectating cli..

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-12-01T16:40:02Z

---

See attached screenshots. Same position, but one is player view and the other the same player view followed by spectators.

* It looks like the spectator view is shifted to the right, rather than shifted forward.
* Actually, the shift happens always in the same direction! On oasis, towards the East. 3D model seems shifted towards the South.
* Tank and fixed MG are unaffected.

This is an etmain bug! It has been fixed in etpro and nq. It is present in etpub and jaymod.

Edit: cg.pmext.mountedWeaponAngles in CG_OffsetFirstPersonView() is not set correctly for followers.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-12-03T15:55:35Z

---

Applied in changeset commit:2724e2b5dc48e844aa28edf046eada4beda94f16.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-12-03T19:45:45Z

---

Reopening. Client (master) is dropped with "Invalid entityState field count" when connecting to existing servers.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-12-03T22:55:10Z

---

Applied in changeset commit:f3c5e20adbbc9df86153c86e415b2475da31929c.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-12-03T22:56:17Z

---

Better fix by ryven. Note however that the z position isn't fixed, as it can't be easily derived (same as etpro, which doesn't fix the z axis either).

**Comment by isRyven** [comment]
At least while playing on tm i did notice that view is still sometimes wrongly offsetted, on both mortar and mg42.

**Comment by Aranud** [comment]
Could be fixed by this commit https://github.com/etlegacy/etlegacy/commit/75fed3ea34d65160ca9e0b61f3ef5670263bd3e1
