### ISSUE TITLE
Packaging request: Help compile glew for 32bit

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1374]
Author: Eonfge (Eonfge)
Date: 2019-12-22
Redmine Issue: 1374, https://dev.etlegacy.com/issues/1374

---

Hey everybody,

In an attempt to package ET:Legacy for Flathub, I've run into an issue. To provide the best experience for players, ET:Legacy is best run as a 32bit application, so users can use existing mods. One library required for this is glew, but I have been unable to compile it myself for 32bit. 

Thus, i want to ask if somebody here can provide me with more info concerning cross-compiling glew to 32bit.

Current Work In Progress packaging manuscript:
https://github.com/Eonfge/flathub/tree/com.etlegacy.ETL

Current Work In Progress submission thread:
https://github.com/flathub/flathub/pull/1182

Most other libraries already compile to 32bit (Minizip, glu, jansson) so with some assistance compiling glew to 32bit, it would be possible to publish an easy one click installer for Linux.

**Comment by ETLegacyTeam** [comment]
From: @isRyven (ryven)
Date: 2019-12-22T11:18:36Z

---

Hello, it is obvious to me it doesn't build 32 bit arch library, your main problem is that the glew pack it downloads comes only with Makefile in root, and i assume flatpack only uses that, completely ignoring CMakeList.txt build file. This means the cmake flags your are passing through config-opts (which specify binary arch) are completely ignored. 
Moreover, the glew we supply in etlegacy-libs contains custom CMakeLists.txt file, as at the time of adding the library, there was no vendor provided CMake support.
To solve the issue, you probably have to pass CFLAGS=-m32 through make-args or something like that, i have no clue how the whole thing is working on your end.

**Comment by rmarquis** [comment]
This isn't something under our control, nor is Flathub officially supported. Closing now.
