### ISSUE TITLE
Gibbed bodies stutter

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1385]
Author: @rmarquis (Spyhawk)
Date: 2020-01-05
Redmine Issue: 1385, https://dev.etlegacy.com/issues/1385

---

As part of a fix (see "37bdb10a169b68b35c66fb49c1f1ea1a07e5f986":https://github.com/etlegacy/etlegacy/commit/37bdb10a169b68b35c66fb49c1f1ea1a07e5f986), gibbed bodies are now applied gravity effect.
However, the gibbed bodies now stutter in many (but apparently not all) circumstances. It is very likely falling bodies were stuttering too, but since they were moving the issue couldn't be seen.

---

Related commit(s):
e6fc4fb62d55badf1371e211cb77a02290316540 - game: fixed gibbed bodies stutter and don't cut de..
 994463da7d1f26fe41d27e1e945c9fd2680485b6 - game: add gravity paused for item and physicsObjec..
 4fdef8a60006e5e5dca6d5b24c8fd8ebffc3b327 - game: better implementation to avoid corpse stutte..

**Comment by rmarquis** [comment]
This still happens on latest build. Reopening.

**Comment by keithmss** [comment]
Well done Aranud fun with rounding :)
