### ISSUE TITLE
Tallies votes results are confusing

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1386]
Author: @rmarquis (Spyhawk)
Date: 2020-01-07
Redmine Issue: 1386, https://dev.etlegacy.com/issues/1386

---

Tallies votes results are confusing, because the requirements for a vote to be accepted are not explicit: a minimum percentage of voters need to vote or a positive result will be dismissed.

Improve the UI with the required information, so people understand why a "successful" vote fails.

**Comment by Aranud** [comment]
Need feedback to know if the message look too long or not !
