### ISSUE TITLE
Windows 64bit Support for ETL

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1389]
Author: @rafal1137 (RaFaL)
Date: 2020-01-10
Redmine Issue: 1389, https://dev.etlegacy.com/issues/1389

---

Let add 64bit support for Windows and there is a reason and prove for make it happen.

Whenever i do devmap some maps with our HD textures installed like goldrush, dinkershing by kemon I am starting to get errors due too some limitations.
Not sure if everyone experienced that one.

PS: And of course R2 is used.

---

Related commit(s):
818318be697f2b395d6727bb1d327a9073e586f8 - client: dirty fix for buflen bufferoverflow, refs ..
 5cad58f1d0a8d867ed4ed1afd182950ab3d0f883 - renderer2: fix compiler warning, refs 1389

**Comment by u1ps** [comment]
Windows 64bit Support for ETL is here :D ?
