### ISSUE TITLE
Rename Legacy mod to League

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1396]
Author: @rmarquis (Spyhawk)
Date: 2020-02-08
Redmine Issue: 1396, https://dev.etlegacy.com/issues/1396

---

It's been a while ET:Legacy (engine) and Legacy (the mod) have been mixed up and confusing everyone, despite being two different things.
"Legacy" also has a [double meaning](https://dictionary.cambridge.org/dictionary/english/legacy), one being positive (cultural legacy) while the other is not (obsolete).
To clarify, rename the Legacy mod to "League". 

Advantages are:
* Clarify what the mod part is, and what the engine part is.
* Give a clear signal to the etpro community that the mod is a viable alternative
* Bypass the pakisolation transition issue from 2.76 to 2.77 (#1161) by "forcing" to download in a new mod directory

This is more than a simple string change.
Internal:
* ~~Combine both assets and binary paks into single one.~~ (done)
* ~~References to "Legacy" in the mod code need to be adjusted~~ (done)
* ~~Rename remaining LEGACY mod defines from the engine~~ (done, changed to ETLEGACY)
* ~~Rename `IS_LEGACY_MOD` to generic `IS_DEFAULT_MOD`~~ (done)
* ~~Rename `LEGACY_DEBUG` macro~~  (done, changed to ETLEGACY_DEBUG)
* ~~Rename `CS_LEGACYINFO` to generic `CS_MODINFO`~~ (done)
* ~~Check `MOD_CHECK_LEGACY` vs `IS_DEFAULT_MOD`~~ (done, changed to MOD_CHECK_ETLEGACY, IS_DEFAULT_MOD is something separate)

Logo:
* Adjust the string in the logo for UI (League)
* Adjust string in splashscreen (ET:Legacy? URL?). The "L" itself is fine to have in both.
* Adjust NSIS installer logo
* Adjust MacOS installer logo
* Adjust website logo

External:
* ~~Default subdirectory has to be changed~~ (ready)
* Server browser has to be adapted
* ~~Rename into `league_version.pk3` pak~~ (ready)
* ~~Adjust ETLmaster modpack variable~~ (ready)
* ~~Adjust config files (omnibot path,  filename, comp config  filename)~~ (ready)
* ~~Update description.txt file~~ (ready)
* Patch WA for mod name check
* ~~Rename Legacy Competition Config name to League one~~ (ready)
* ~~Update doc, README, INSTALL, ..~~ (ready)
* ~~Update installer paths~~ (ready)
* ~~Adjust Lua API doc (including URL in INSTALL.txt)~~ (ready)
* ~~Update easybuild scripts (`.bat` needs the variable name changed, unix doesn't)~~ (ready)
* ~~Fix translation support~~ (nothing to do, but new client required for translation support of League mod)

Infrastructure:
* adjust website
* adjust wiki
* adjust admin website/game server path
* adjust and check etlegacy test server
* adjust and check etlegacy-tools

Do this before providing public test snapshots.

**Comment by Exagone313** [comment]
Hi, is it intentional to keep setting `gamename` (or more broadly `GAMEVERSION`) to `legacy`?
PS: If changing `GAMEVERSION`, don't forget to read comment over `OMNIBOT_MODNAME` definition.

**Comment by rmarquis** [comment]
The change that occurred is partial only, touching the cmake files so far only, Eventually the mod code will be adjusted to allow anyone to fork easily. There are also more than mod name and mod url changes needed (like etbloat did) in mod code, such as config files that should at least become more generic, etc.

**Comment by zedar187** [comment]
From what i've gathered from a quick view:

The mod builds fine with just changing `MODNAME` in `cmake/ETLFunctions.cmake`.

There are some strings that need to be changed. Either dynamically, or in a way it's more generic. _Also I'm not sure what sticks to engine and what to the mod._ So here is a quick list:

- src/ui/ui_main.c, line 6189: Server Info shows "Version: ET Legacy $version-$commit"
 -- Same goes for the server info window in the server browser.
 -- As well as for the version line in the console
 -- The first echo on etlded
- src/game/g_script_actions.c: `G_LogPrintf("legacy announce: \"^7%s\"\n", token);`
- misc/etmain/etl_server.cfg: Hostname and MOTD_Line1 showing "ET: Legacy"
- misc/etmain/legacy.cfg: The config name itself, as well as hardcoded omnibot_path.
- competitive configs: Title showing "Config: Legacy Competition"
- Ingame Menu: ET Legacy + Logo
- Console + etlded: "Inizialising Legacy UI" and "Inizialising Legacy game $version-$commit"

Edit 1: + Changes in Wolfadmin need to be timed, as it contains hardcoded `if fs_game == legacy`

Edit 2: Main Menu button "Mods" showing the mod as "ET: Legacy - legacy mod", coming from `misc/description.txt`

**Comment by rmarquis** [comment]
Closing. It's apparently not needed anymore from a marketing standpoint, and there is quite some technical drawback both for transition and the required work needed on infrastructure.

On the bright side, it's much easier for any new third party mod to fork and base their work on Legacy.
