### ISSUE TITLE
Improve objective visibility on HUD

### ISSUE THREAD

**Issue by rmarquis** [etlegacy/etlegacy#1402]
On pub servers, people seems to not notice when you drop them an objective, due to lack of communication. It also happens they don't notice they picked the objective, as the HUD icon is in both case green (static when player is the carrier, but pulsing when a teammate carries the obj).

Improve the objective visibility, by:
* adding CP message when carrier get the obj
* changing side icon colour to blue when teammate has the obj (hopefully this won't cause any issue with team colours)
* adding icon on the compass even when not on fireteam.

**Comment by mittermichal** [comment]
I don't really like that spawn shield has higher priority than this.
I often find myself checking objective status with scoreboard when I respawn.
The information that you got the shield is not that important as you always know you got it after spawn or revive.
