### ISSUE TITLE
First map voting error in SilentMod?

### ISSUE THREAD

**Issue by ghost** [etlegacy/etlegacy#1406]
Hi

Congratulations to all etlegacy members for their fabulous effort for the Enemy Territory community

I would like to know if in version 2.76, can't you vote the first map in the SilentMod?

Maybe it's a bug or was it disabled in this version?

For now, my friends and I had to go back to version 2.75 that works well with the vote.

Thanks for your help

![2020-03-09-161237_1024x768_scrot](https://user-images.githubusercontent.com/61992365/76258256-34f2ed80-6221-11ea-813a-028938291f44.jpg)

**Comment by ghost** [comment]
We have no idea what you are talking about. Expand your problem:
- What is the observed behavior?
When it comes to voting the first map in SilentMod the voting option is disabled, in the second map the normal voting will appear again
- What is the problem or error?
Does not load the first map vote
- What is the expected behavior?
You can vote, in version 2.75 it works well, in 2.76 the voting of the first map does not work
- How to reproduce the problem?
Entered a server with active voting and Silent mod

**Comment by rmarquis** [comment]
Hi. Are you referring to your own server installation (etlded + silent mod), or is this about connecting to an online server (running the Silent mod) with the ET:L client?

Note: This is the follow-up of #1350. This is likely related to #1170.

**Comment by rmarquis** [comment]
After discussing the issue a bit, it appears this issue has been fixed already as part of #1170.

There was an issue with latched gametype in 2.76, making the server still considering running the default campaign mode in the first map. The cvar was correctly updated on the next map, allowing you to vote as expected.

The next 2.77 release will include the fix. Closing now.
