### ISSUE TITLE
Fullscreen mode always opens on primary screen

### ISSUE THREAD

**Issue by rmarquis** [etlegacy/etlegacy#1409]
When having a multiscreen setup, launching ETL in fullscreen mode always opens in the primary screen.
Even when having the windowed-game on secondary screen, entering fullscreen moves it to the primary screen.

We should be able to just get the current screen the window is on, and use it for fullscreen toggle.
Check OpenArena that works that way too (note: OA is still using SDL 1.2).

Possibly related: #1061

**Comment by jackeri** [comment]
This should be fixed now.
