### ISSUE TITLE
after alt + tab the game is on 7th position in alt+tab list on windows 7 

### ISSUE THREAD

**Issue by mittermichal** [etlegacy/etlegacy#1412]
If you switch between apps with alt+tab the last one would be on 2nd position,
so if u alt+tab 2 times in row you are back on the same app.

This doesn't work on Win 7, as the game appears on 7th position. This happens on Windows 7.

**Comment by rmarquis** [comment]
This works on Win 10. Since Win 7 is now unsupported, this is not worth fixing.
