### ISSUE TITLE
Rework HUD blood effects and add directional damage

### ISSUE THREAD

**Issue by rmarquis** [etlegacy/etlegacy#1413]
The blood effects displayed on HUD (`cg_bloodFlash`, `cg_bloodDamageBlend`) have always been too strong, resulting in the vast majority of players disabling these.

Reduce the effects to actually make then useful (but still optional), so players know they are getting damage, but can still see what is happening on the screen.

**Comment by realkemon** [comment]
Just for clarification, by making them useful, do you mean a plain rework of the blood effect so it isn't obstructing the view or are you thinking of implementing a directional damage indicator?

**Comment by rmarquis** [comment]
I haven't really thought about it, but directional damage might indeed make it more useful - atm, we rely on kickback to get an idea of which direction damage comes from.

**Comment by jackeri** [comment]
We should really take a look on how other "new" popular games handle damage feedback.

csgo, apex, overwatch come to mind.

**Comment by rmarquis** [comment]
Looking good!

**Comment by Aranud** [comment]
> 
> 
> Looking good!

Thanks you good sir !

**Comment by rmarquis** [comment]
Might be useful to add an UI slider for `cg_bloodFlashTime` too. Though I am not sure where to find the extra space to do that ;)

**Comment by Aranud** [comment]
> 
> 
> Might be useful to add an UI slider for `cg_bloodFlashTime` too. Though I am not sure where to find the extra space to do that ;)

Totaly agree. Perhaps we could add a "more" button and add all other missing cvar too
