### ISSUE TITLE
revive collision

### ISSUE THREAD

**Issue by mittermichal** [etlegacy/etlegacy#1417]
in etpro after reviving player while standing on him you get pushed back until you don't collide with him
https://streamable.com/o3ppo

doesn't happen in legacy:
https://streamable.com/4dimr

It gives reviving player possibility to shoot through revived player, but that's also possible in etpro, Though in etpro you have to keep moving forward through revived player to do it.

I think it also makes it easier for multiple players to chain revives.

The revived player is stuck if the reviving player is still inside of him. Maybe this is the only reason behind etpro behaviour.

**Comment by Aranud** [comment]
Investigation should start there : 
https://github.com/etlegacy/etlegacy/blob/e33eeb0985e53e8d0a9de59307d9d1422ab05319/src/game/g_active.c#L2252-L2261

**Comment by Aranud** [comment]
And more precisly : https://github.com/etlegacy/etlegacy/blob/e33eeb0985e53e8d0a9de59307d9d1422ab05319/src/game/g_active.c#L1960-L1991

**Comment by rmarquis** [comment]
Mentioned in discord already, but the push force when reviving seems too strong. The revived player might literally be "ejected" to a very long distance, depending on the geometry of the map. 

Maybe try to push the reviving player, rather than the revived one (seems to be that way in etpro).

**Comment by rmarquis** [comment]
ETPro has actually a similar implementation, with the very same issue. See screenshot below, the player was pushed quite far away from the revive location.

![2020-06-18-234922-oasis](https://user-images.githubusercontent.com/162442/85075597-d0034800-b1be-11ea-9c90-5b0dda742e5f.jpg)
