### ISSUE TITLE
enemy wounded can block team wounded for revive

### ISSUE THREAD

**Issue by mittermichal** [etlegacy/etlegacy#1418]
https://streamable.com/56kho
etpro got this fixed:
https://streamable.com/ew1b6
http://etpro.anime.net/etpro-3_2_0.html "enemy wounded could block team wounded for revive"

**Comment by isRyven** [comment]
Ah nice notes link.
`clientkick / kick would sometimes kick the wrong player` 
so it is the etmain bug after all
