### ISSUE TITLE
NSIS installer should look in $EXEDIR for downloadable files

### ISSUE THREAD

**Issue by kwade00** [etlegacy/etlegacy#1423]
Currently the NSIS installer checks $TEMP for WolfET.exe, omnibot-windows-latest.zip, GeoIP.dat.zip, and wolfadmin.tar.gz before proceeding to download them. When doing mass installs for a LAN session it isn't very convenient to copy these files into each temp folder before running the installer. If we add a section for each file that checks $EXEDIR as well then users can download those files once and put them in the same folder as the installer, eliminating multiple downloads. A very quick and simple fix.

**Comment by rmarquis** [comment]
If you need to do a mass installation, why not installing once and copying the whole directory to each machine?

**Comment by kwade00** [comment]
Then we have to manually create shortcuts, and we lose uninstall capability. (Computers may be brought by low-tech users who may want to uninstall someday.) More automation is better. This change wouldn't take more than a few minutes to implement in the NSIS script.

**Comment by rmarquis** [comment]
To uninstall, simply get rid of the directory? If you have all the files, it's faster to copy a directory than using the installer.

It seems to me that your trying to shoehorn the installer into a user case it was not designed for.

**Comment by kwade00** [comment]
The installer **already** checks the temp directory for these files, so I guess it was designed for it. It could also check the installer directory just as easily. It's nice to leave the computers in a state where Joe User can easily uninstall the software when he's ready.

As I said, just a few minutes of mostly copy and paste would do this.

**Comment by rmarquis** [comment]
**NO**. The installer was never designed for _mass_ install for a LAN.

> As I said, just a few minutes of mostly copy and paste would do this.

Then I'm glad you're volunteering.

**Comment by kwade00** [comment]
Gladly! My personal experience with this is due to poor Internet service where I live. As an aside it might be good to have a check for Omni-bot. I've personally had the download fail but the install didn't know and proceeded.

**Comment by kwade00** [comment]
Can I attach a patch here?
Just quick and dirty. Looks for the files in the installer dir, and copies them to temp if it finds them. Then checks temp again and continues.

[NSIS.template.in.patch.txt](https://github.com/etlegacy/etlegacy/files/4397718/NSIS.template.in.patch.txt)

**Comment by kwade00** [comment]
Missed the patch download.

[NSIS.template.in.patch.txt](https://github.com/etlegacy/etlegacy/files/4397995/NSIS.template.in.patch.txt)
