### ISSUE TITLE
LUA errors on VPS

### ISSUE THREAD

**Issue by urandom0** [etlegacy/etlegacy#1426]
Hi! There are some errors on my VPS:
```

Lua 5.3 API: file '/luascripts/wolfadmin/main.lua' loaded into Lua VM
Enable spawning!
********************
ERROR: G_Script_ScriptParse(), Error (line 186): '{' expected, but found 'spawn'.

********************
----- Server Shutdown -----
Lua 5.3 API: et_ShutdownGame error running lua script: '[string "/luascripts/wolfadmin/main.lua"]:140: attempt to index a nil value (upvalue 'events')'
==== ShutdownGame (0 - base47) ====
ShutdownOmniBot
---------------------------
Sys_Exit warning - PID file doesn't exist /home/server/.etlegacy/legacy/etlegacy_server.pid
Network shutdown.
```

VPS:
Linux vm3958 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux

On my computer (Elementary OS; Linux Lenovo-EOS 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux) there are no errors.
How I can fix these errors?

Edit: other info:
`Lua 5.3 API: file '/luascripts/wolfadmin/main.lua' loaded into Lua VM`

```
[WolfAdmin] Module 1.2.0 (4 January 2019) loaded successfully. Created by Timo 'Timothy' Smit.
[WolfAdmin] WolfAdmin running in standalone mode on unix.
[WolfAdmin] commands.load(): 61 entries loaded in 264 ms
[WolfAdmin] WolfAdmin running in standalone mode on unix.
Game Initialization completed in 1.57 seconds.
```

**Comment by isRyven** [comment]
I am pretty sure the problem is in the map script, lua has nothing to do with it (except that proper checks must be done to prevent the lua error if `et_ShutdownGame` hook was called before `et_InitGame`). So i'd suggest to look into map script instead, it probably contains bogus line, which prevents parser to proceed.

**Comment by urandom0** [comment]
Thanks! What map?
I have 74 maps... :D

**Comment by isRyven** [comment]
i guess `base47`

**Comment by urandom0** [comment]
@isRyven Very good, thanks!
I will remove base47 from the map rotation.

**Comment by rmarquis** [comment]
As discussed, not an ETL issue. Closing now.
