### ISSUE TITLE
FG42 texture issue on some maps

### ISSUE THREAD

**Issue by urandom0** [etlegacy/etlegacy#1427]
Please check out these pictures:
https://ibb.co/7pHZ7kT
https://ibb.co/rp5xPZQ
https://ibb.co/vk6jyy7
https://ibb.co/jVy0Nk0

On some maps (such as Würzburg Radar) the texture of the FG42 is incorrect.

ET:L v2.76
No LSB modules are available.
Distributor ID:	elementary
Description: elementary OS 5.1.3 Hera
Release: 5.1.3
Codename: hera
Linux Lenovo-EOS 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
(But I’ve experienced the same with other Linux distros /Debian/ and other version ET:L /v2.75./)

**Comment by rmarquis** [comment]
Are you sure you don't use any texture pack? Are you using official maps only?

**Comment by urandom0** [comment]
@rmarquis This is a freshly installed ET:L. with my old profile folder (~/.etlegacy). I delete ~/.etlagacy folder, created a new one and now the texture is okay.

**Comment by rmarquis** [comment]
Then it was a faulty downloaded skin pack. Closing.
