### ISSUE TITLE
ET Legacy macOS Catalina 10.15.4

### ISSUE THREAD

**Issue by dude10101** [etlegacy/etlegacy#1429]
Hey Guys,

I was wondering if its possible to play ET Legacy on Mac with the Catalina OS 10.15.4 ?
Thanks,

Simon

**Comment by zedar187** [comment]
Hi, there will be a Catalina version ready as soon as 2.77 gets released (no ETA). If you don't want to wait, you can still compile the latest master as it's already supporting Catalina.

Closing for now. Please start a new issue or come to our discord server, if you encounter any problems. :)

**Comment by rmarquis** [comment]
For the record: Please do **NOT** use the tracker to ask question.

See https://github.com/etlegacy/etlegacy/blob/master/CONTRIBUTING.md
