### ISSUE TITLE
Toggle small scoreboard for both teams

### ISSUE THREAD

**Issue by timosmit** [etlegacy/etlegacy#1435]
Currently the scoreboard is toggled to render smaller rows when the amount of player exceeds a certain limit. This, however, only applies to the team whose player count exceeds the limit. The other team is still rendered as usual. This makes for a hard visual comparison between player amounts (and see whether the teams are even).

Instead the scoreboard should render small rows when either team exceeds the limit.

![image](https://user-images.githubusercontent.com/4281972/79788962-c2118200-8349-11ea-86d3-4817b3e31251.png)

**Comment by rmarquis** [comment]
Fixed in 53aec41a880c0290f0a04276c598a073f6bcee0f, d8af06d262ecd2ebdbe531ca5e836314969d388d, 72e08be2a4f0eeddbd95a8ed5ff1e533f10643d1, 1e0dff0589638a80b417d82b591e77f9c901c0ee, 5bdb9c82d8aafcef455d20eca9cb50ba8788d655 and aecae895ace3893d081cb19429d3705073341bb1.
