### ISSUE TITLE
Problem with watching demos. ERROR cg_setlerpframeanimationrate bad animation number 233 and ERROR 'demoMSGlen > MAX_MSGLEN'

### ISSUE THREAD

**Issue by ryzyk-krzysiek** [etlegacy/etlegacy#1438]
When trying to watch a demo after a while (like a 1 minute max) I get an error that says 'cg_SetLerpFrameAnimationRate Bad animation number 233'.
 No matter which map is recorded error is always the same and at the same place/time everytime unless I skip it but it will occur sooner or later anyway at another place/time. 
 Few weeks ago I had no problem with watching but I believe there was an update recently. I also tried reinstalling the game (completely fresh install) but it still occurred.

The other error 'demoMSGlen > MAX_MSGLEN' is present when trying to watch demo with 'cl_AutoRecord 1', which I think is the same as with native ET client. It's not so bad but for a few days I was wondering why I couldn't watch untill I recalled from 10+ years ago that it might be that cvar, so maybe there is a chance to fix it.

I should probably make separate issues for both errors but I'm too lazy sorry :(

**Comment by ensiform** [comment]
Can you provide the legacy devs some of the demo files that are not working so they can test against and try to reproduce the issue.

**Comment by ryzyk-krzysiek** [comment]
Sure, 3 demos from 24.04.2020.

[demos.zip](https://github.com/etlegacy/etlegacy/files/4531977/demos.zip)

**Comment by rafal1137** [comment]
I cannot reproduce that lerp error. @ryzyk-krzysiek Can you clear your legacy dir and try watch demo again ? If not I will consider that ticket half-done and will close that one and will wait fot feedback

**Comment by ryzyk-krzysiek** [comment]
Alright, this is going to be long, so TLDR is I fixed it and found the culprit, which was some .pk3 file (pak3_v2.76.pk3).

I'm 95% sure this all started after an update to Team Muppets servers few weeks ago. My profile started looking like this:
![LegacyMainScreen](https://user-images.githubusercontent.com/4499367/81420037-936c1780-914f-11ea-82f5-763d376ce2df.png)

At first I thought my profile got corrupted or maybe it should look like this, especially after I reinstalled the game, downloaded update from the Muppet server and it started to look like that again(this was not long before I posted this issue here when I tried fresh install).

Before I reinstalled this time I tried using the buttons in options to delete files and I don't think anything got deleted and definitely didn't fix my problem (tried all options).

This time around when I did fresh install as requested I saved all files from documents and installation directory to try and compare and copy paste files to see if something changes even if all works.

I downloaded the newest update I believe from 2 days ago from muppets when I connected to their server so that I would be testing demos on the same version and my main screen was looking normal. I started looking at demo with default cfg that was crashing very fast with said error and it worked.

To not make it super long what I found after checking/copy&pasting old files is that I had 3 extra files before that were missing after todays installation and update in "C:\Users\me\Documents\ETLegacy\legacy" folder which were: 

- pak3_v2.75.pk3.tmp
- pak3_v2.76.pk3
- legacy_v2.76-1075-g765ea79.pk3

The "pak3_v2.76.pk3" was causing my profile to change as you can see on screenshot and for demos to crash when copied to legacy folder again. I briefly remember I was trying to delete some of those files few weeks ago but I guess I didn't try this one because it looks like it would be needed the most judging its name. I think if I did test more last time before posting I would came to conclusion faster that it was that update that was bricking my game, but I was too lazy to reinstall one more time and try without the update from server, so that is my bad.

Anyway, I will attach all 3 files in case you want to see them, and maybe check why/how the update could brick my game (If I'm not mistaken it was it, but I don't know what else could).

[LegacyUpdateFiles.zip](https://github.com/etlegacy/etlegacy/files/4600036/LegacyUpdateFiles.zip)

**Comment by rafal1137** [comment]
Ok tested with your files and I did get that lerp animation issue. It seems like issue with dll files.
Closing
