### ISSUE TITLE
Add server versioning check for Legacy mod

### ISSUE THREAD

**Issue by rmarquis** [etlegacy/etlegacy#1439]
Legacy mod is becoming increasingly popular, but some people get the bad idea to run it over 2.60b server side.

This is far from optimal, because:
* some features requires database access, which is not available in 2.60b. In such case, one would need to compile the mod with `FEATURE_DBMS=OFF` to avoid issues, but this is not done for releases.
* security features are directly implemented in the server component, rather than the mod (unlike other mods which had no other choice). This adds even more holes to the already security vulnerable 2.60b.

Add a check server-side to prevent Legacy mod to run on 2.60/2.60b, or at the very least a big fat warning.

**Comment by isRyven** [comment]
I think we would need to reopen this, as there were reports about NQ failing to run on `etlded`, and i suppose any other mod should fail as well if it does the version check on the qagame side, for instance hosting legacy mod on 2.76 will result in error (guess it's not that important, but just similar stuff might be or is done on the other mods it seems).

Commit causing issue:
https://github.com/etlegacy/etlegacy/commit/1546a5a7cd16f86e321dc34c2e99a5dca7086150#diff-0544ba2c2f531f3705e77b8bdc51a7430fabd91386d8415f6a3b45686cf74f66R3008

We should probably define `etVersion` cvar for the server side as well, and use that instead to perform qagame check, reverting `version` back to `FAKE_VERSION`.

**Comment by rmarquis** [comment]
See also #1225.

**Comment by rafal1137** [comment]
From available NQ code you can tell that it checks for version in qagame.

> trap_Cvar_VariableStringBuffer( "version", versionStr, sizeof(versionStr) );`

> if ( !strstr( versionStr, "2.60b") && !strstr( versionStr, "OpenWolf") ) {
> 		G_Printf( "^1Error: No Quarter doesn't support this ET version/engine %s..\n", versionStr);
> 		G_Printf( "^1Use ET 2.60b for Win/Linux or 2.60d for Mac or use ET:Xreal/OpenWolf");
> 		shutdown = qtrue;
> 		msgWhine = qtrue;
> 	}

So in this case FAKE_VERSION version is used thus when nq qagame checks for version it shutdown a server
