### ISSUE TITLE
Demo files are being overwritten with cl_AutoRecord enabled. (Lack of unique names)

### ISSUE THREAD

**Issue by ryzyk-krzysiek** [etlegacy/etlegacy#1445]
When using 'cl_AutoRecord' files for the same map on the same day are being overwritten because they get the same name, for example "adlernest_30_4.dm_84".

When using '\record' or 'cg_AutoAction' this problem does not occur. For example with 'cg_AutoAction' file names would look like this: "2020-04-30-225557-adlernest", "2020-04-30-225610-adlernest".

I don't know why there are inconsistencies between them, but somehow for me it was easier to find 'cl_AutoRecord' cvar because of its naming and with what I wanted to accomplish and I missed the setting in options ingame that uses 'cg_AutoAction' (and forgot about it, its like 2008 all over again).
I'm writing all this because I'm guessing you don't intend to get rid of that cvar since its still there and by looking at your description of it in the list of cvars in ETLegacy it is used after all by stupid me! :) (till today).

**Comment by rafal1137** [comment]
Related Commit:
* 2f04501d8a843f6aba614df8fe3863595098403a

**Comment by rafal1137** [comment]
#1438 
Fixed by forcing cvar to value 0 and closing

**Comment by ryzyk-krzysiek** [comment]
Sorry but I don't see how that could change anything. This problem is about that recording demos with cl_AutoRecord overwrites existing demos for a map that was played and recorded on the same day because it gets the same name. The "related" problem you quote was about being unable to watch demos while cl_AutoRecord cvar was enabled.

Without knowing the code of course I would suspect all that needs to change is how file names are generated when recording demo is done via cl_Autorecord cvar by for example using the method that is used when recording demos with cg_AutoAction cvar.

I'm sorry if there is something I'm wrong and it should work now and if my english is unclear.

**Comment by rmarquis** [comment]
@rafal1137 simply closed the wrong ticket by mistake. This issue is now fixed, using the same naming scheme as `/record` and screenshot with `F11`.

**Comment by rafal1137** [comment]
Yes it was me just another mistake :)
Also 2nd ticket has similiar issue thants why they are almost the same thou.
