### ISSUE TITLE
Skill rating 0 displays as negative

### ISSUE THREAD

**Issue by timosmit** [etlegacy/etlegacy#1449]
As the title suggests, skill rating 0.00 shows as -0.00 currently.

![negative_sr](https://user-images.githubusercontent.com/4281972/81216494-45ce9e00-8fdb-11ea-89a1-e462f0f18c55.png)

**Comment by Exagone313** [comment]
This is by design, when rating is between -0.005 and 0. If it is needed to hide that minus sign in that range, you could add a *round* function.

```c
#include <stdio.h>
#include <math.h>

int main()
{
	float rating = -0.0044444444f;
	printf("actual:\t%5.2f\n", (double) rating); // -0.00
	printf("round:\t%5.2f\n", (double) (round(rating * 100.f) / 100.f)); // -0.00
	rating = rating < 0.f && rating > -0.005f ? 0.f : rating;
	printf("manual:\t%5.2f\n", (double) rating); // 0.00
}
```

(Also floor could make more sense.)

**Comment by timosmit** [comment]
Exactly, but probably the printing function takes all decimals into account. In my opinion we should round the value before output if the player cannot see the last decimal.

**Comment by rmarquis** [comment]
There are other locations where rating is displayed and where that issue might be also present. Top of my mind: the in-game info window, and debriefing screen.

**Comment by Aranud** [comment]
I haven't found any other location for now. 
If you have any idea, still ready to do the change with the new function.

**Comment by rmarquis** [comment]
I've looked more carefully, here's two more:
* console stat dump in `G_printMatchInfo`
* award list in `G_BuildEndgameStats`

That should cover it.
