### ISSUE TITLE
Rework explosion and particles effects

### ISSUE THREAD

**Issue by rmarquis** [etlegacy/etlegacy#1450]
Particles effect has been turned on by default and the cvar removed (see #1173), in order to get rid of the unfair advantage provided.

The default explosions effect is however too strong, so take measure to diminish its intensity. Something like a semi-transparency would be great.

In addition, the cg_wolfparticles cvar hid many other smaller effects (smoke effects, debris, ..) at the same time. Since these are cosmetic only:
*  handled these by the `cg_visualEffects` cvar too, so only the tamed explosion effects would be mandatory.
* consider allowing shoutcaster to turn the main explosions effects off too
* cover ops smoke effect seems to end abruptly rather than fading away like other smoke effects. That specific effect is handled separately (as it was never allowed to turn it off), so improve it / merge it with the general particle effect.
  * particles: `CG_AddParticles()` + `CG_AddParticleToScene()` + `CG_ClearParticles()`
  * smoke grenade: `CG_AddSmokeSprites()` + `CG_SpawnSmokeSprite()` + `InitSmokeSprites()`

**Comment by isRyven** [comment]
I propose to allow hiding explosions under the `cg_visualEffects` cvar as well - as with the upcoming explosion effects diminishing, this shouldn't anymore give much of advantage as it does right now, hence could be toggleable.

**Comment by rmarquis** [comment]
There will still likely be diminished visibility, just not as much. As such, I'd rather test it first before allowing to be it togglable.

**Comment by rmarquis** [comment]
The explosion effects have been reworked, and the debris rescaled. I'd thus consider the feature done - even though tweaks are still welcome.

In addition, we should consider fixing and implementing #1453, as this really helps performance wise, especially on lower grade machines.
