### ISSUE TITLE
Port DirToByte and ByteToDir optimization

### ISSUE THREAD

**Issue by rmarquis** [etlegacy/etlegacy#1453]
This `DirToByte` and `ByteToDir` optimization replaces an expensive computation related to explosion, resulting in better/smoother FPS.

> It runs much faster because it does not..
 > * ..lookup a vector from an array, compare it with the input vector, the best matching vector's index in the array is returned.
 > * But instead, it stores the vector's xyz in 30 bits (10 bits per component).
 > * No need to lookup all vectors, compare vectors. Just split the components, and scale to float range values.

The current implementation is however buggy, and breaks explosion:

> he tried to store 4096 in 10 bits
>2^10 == 4096 is rather 2^10 != 4096 to my knowledge
> so possible overflows of each component that gets overwritten by next components producing absolutely wrong integer

Firstly introduced in 3cfe9bba92548a76a825e7c6aaf7c74cf4488b47 then reverted in 9ea416b8f3c3fabcb863f571209e6dbf989e351c.

**Comment by Aranud** [comment]
We could adjust the bits range to 1024 for each x y z values and then the code is correct ...

But the main problem is due to network restriction. We are trying to store an integer representation of a vector direction inside a byte :  

https://github.com/etlegacy/etlegacy/blob/214697e7b836695e3ce0bbfd71c918772d11c1cd/src/game/g_missile.c#L239

https://github.com/etlegacy/etlegacy/blob/214697e7b836695e3ce0bbfd71c918772d11c1cd/src/game/g_missile.c#L257

https://github.com/etlegacy/etlegacy/blob/214697e7b836695e3ce0bbfd71c918772d11c1cd/src/qcommon/msg.c#L1170

**Comment by Aranud** [comment]
A possible solution, reuse another field up to 32 bits and put the value inside.
Other possible solution, use raw value of direction (x, y ,z) and reuse 3 of these fields : 
https://github.com/etlegacy/etlegacy/blob/214697e7b836695e3ce0bbfd71c918772d11c1cd/src/qcommon/msg.c#L1129-L1143

The difficulty is to adjust the whole code where `DirToByte` is used

**Comment by rmarquis** [comment]
`eventParm` is 8bit only, so the above code will never work correctly without changing the way it is transmitted.

A possible solution could be reusing a different field from `netField` ... at this point we'd have better use a 32 bit field OR don't use DirToByte / ByteToDir and put the raw vector of x y z inside 3 fields each.

Changing it will not add a lot of to the bandwidth taking into account it's only necessary to transmit once. Actually, current code will transmit eventparm once, as these are set during spawn, so this is barely any net optimization as well.

We could get ride of both DirToByte and ByteToDir and send through network the raw value of direction in angle[0][1][2], then adjust the code to reuse these fields for both cgame/game.

However, that will break demo compatibility, and it seems to be unnecessary to ever do any changes, as it doesn't seems to be bringing any benefits whatsoever. We have to keep vanilla implementation for compatibility reason with 2.60b, so we'll not implement any (over engineered) optimization.

Closing now.
