### ISSUE TITLE
Ingame mouse click doesn't work

### ISSUE THREAD

**Issue by squintz585** [etlegacy/etlegacy#1455]
Fresh install of ET: Legacy 2.76 on Windows 10 (build 18363.778). After spawning ingame, the left and right mouse click doesn't work except sporadically and not as expected.

Mouse movement and cursor are unaffected. All other keys work ingame and mouse functions normally on the ET:L menu and within the OS, etc. Confirmed it's not a OS issue or a input driver issue. 

If this is related to issue #774 from 2015, were fixes were already incorporated into the latest version?

**Comment by rmarquis** [comment]
The fixes were incorporated. You are the first known person _in years_ to have this problem.
At the very least, ensure that you don't reuse old config.

**Comment by Aranud** [comment]
I close this issue for now. Feel free to reopen it if the issue still occur and by providing more informations.
