### ISSUE TITLE
Clicking on Mods on main menu triggers file name checks

### ISSUE THREAD

**Issue by Exagone313** [etlegacy/etlegacy#1460]
When clicking on `MODS` on main menu, it triggers file name checks for all mods (supposedly), which can freeze the client a bit. Also, the menu shown has an irrelevant `Reconnect` button.

Steps to reproduce:
* get some `~~~~~~~~~~.pkg3` files (?)
* click on `MODS`

![20-05-12-00-17-04-698545585](https://user-images.githubusercontent.com/11819703/81618068-e6abc780-93e6-11ea-98b7-69ffcfe97fc8.png)

Note: I didn't check what it does to click on the `Reconnect` button, and I no longer have invalid pk3 to try out right now.

**Comment by rmarquis** [comment]
The `~` limitation has been removed in latest code, so I guess this only happen on 2.76. The check is still done for other invalid (non-ascii) characters though.

I guess the reconnect button could be removed, but this might be a generic window.

(marking as bug, but I'm not sure if that's really a bug).

**Comment by Exagone313** [comment]
I guess these pk3 had non printable characters. I'm running a build from yesterday.

**Comment by rmarquis** [comment]
The way the filesystem works basically makes it mandatory to trigger the name file check from its parent call `FS_GetModList()`.

I don't think that is an issue though. The error sent is pretty generic, which means the button label is also generic. It's not worth "fixing" as this would simply add complexity for a single case. The "Reconnect" button simply doesn't do anything.

Closing now.
