### ISSUE TITLE
players with 0 ping don't get removed by inactivity

### ISSUE THREAD

**Issue by mittermichal** [etlegacy/etlegacy#1463]
![shot0009](https://user-images.githubusercontent.com/4035800/81684907-b2242400-9457-11ea-99e3-bbd1d3df8c10.jpg)

**Comment by rmarquis** [comment]
This player is using a private slot, which afaik are currently explicitly protected from being moved by inactivity check.

**Comment by timosmit** [comment]
The player with name `90909` is not using a private slot.

**Comment by mittermichal** [comment]
![shot0010](https://user-images.githubusercontent.com/4035800/81687135-2c08dd00-9459-11ea-8ab0-14fad8571f67.jpg)

**Comment by rmarquis** [comment]
My mistake, I wrongly remember that nick from some logs or something.

The player might be connecting from localhost then? That would explain the low ping, and why he's not moved.

**Comment by timosmit** [comment]
No. He does have a higher ping at the moment. Isn't he incorrectly 'protected' because of his 0 ping?

**Comment by timosmit** [comment]
According to MrMuppet: _Clients using ETL show a zero ping when they have their game minimised_. Is this correct?

**Comment by rmarquis** [comment]
This is the sole check done in `ClientInactivityTimer()` function:
```
	// no inactivity for localhost
	if (client->pers.localClient)
	{
		return qtrue;
	}
```
There is no ping check involved.
So I was wrong and even private slots should be taken into account.

However, TM uses their own Lua script for inactivity (because of #1366), so this might be a bug of their own.

**Comment by ensiform** [comment]
If he has 0 ping and not kicked it's because they are localclient. Not because the have 0 ping. It doesn't check ping. But ip localhost.  At least this is vanilla behavior.

**Comment by rmarquis** [comment]
TM script actually check for bots using ping with `ps.ping`, rather than local connection with `pers.localClient`:

```
-- do that for real players only (we dont wanna to move bots)
if tonumber(et.gentity_get(clientNum, "ps.ping")) > 0 and (tonumber(et.gentity_get(clientNum, "sess.sessionTeam")) == 1 or tonumber(et.gentity_get(clientNum, "sess.sessionTeam")) == 2) then
...
```

I'm not sure why player ping is zero here, but this issue in invalid. Closing now.
