### ISSUE TITLE
Grenade duping when revived.

### ISSUE THREAD

**Issue by ryzyk-krzysiek** [etlegacy/etlegacy#1467]
When player that primed a grenade gets killed, drops the grenade that will explode and gets revived he will have the same grenade count as if he never dropped it allowing him to use it again and go above the limit a specific class has.

Not sure if this is intended or left on purpose in Legacy due to balancing but it is present in ET since forever or atleast in ETpro 3.2.6. I also couldn't find any relevant information about it here.

It is pretty easy to stumble upon when one of the popular mechanics in ET is to teamkill to revive, which could be annoying to lose your grenade to. It can also be abused to some degree when defending objectives or in general, because the revived player can't die due to shield and can immediately prime another grenade which he should not have if not for this interaction.

I was hesitant to report it here for a long time because it has been in the game for so long, that I'm not sure if I would count it as a bug or a game mechanic at this point, but this could be said about many things that were left unfixed for many years and its not really for me to decide.

**Comment by rmarquis** [comment]
Certainly a bug to my eyes.
