### ISSUE TITLE
Enemy spawntimer breaks if map timelimit changes

### ISSUE THREAD

**Issue by isRyven** [etlegacy/etlegacy#1471]
Enemy spawntimer set by the `timerSet` command displays wrong counter values after the timelimit changes (eg. forced by the mapscript).

**Comment by rmarquis** [comment]
This can likely be fixed by implementing #1414.

**Comment by isRyven** [comment]
I think #1414 will only automate the process of inputting the period, the issues lies though in a way cgame code tries to adapt to the game timer itself to sync the seconds tick for the spawntimer, some offset issues arises because of that, as far as i remember.
