### ISSUE TITLE
Corpses can't be gibbed anymore

### ISSUE THREAD

**Issue by rmarquis** [etlegacy/etlegacy#1480]
Corpses can't be gibbed anymore. Usually, a player in limbo can still be gibbed by any explosion, but this seem to be broken.

This is especially annoying  for covops that can't cover his tracks anymore.

**Comment by rmarquis** [comment]
Bisected to 8fcacbcd35fc20432e5155dfff67ce004d4014c6.

**Comment by Aranud** [comment]
The issue is there https://github.com/etlegacy/etlegacy/commit/8fcacbcd35fc20432e5155dfff67ce004d4014c6#diff-0885708bc4122a5f57cc0ee20a920becR658
