### ISSUE TITLE
Improve sorting of server browser

### ISSUE THREAD

**Issue by timosmit** [etlegacy/etlegacy#1481]
Some servers have their names prepended with numerous spaces to be on top of the server browser. I suggest to trim the server names so this will not give anybody an advantage. Of course they can still use certain characters, but I doubt whether server owners will resort to this.

**example**
![image](https://user-images.githubusercontent.com/4281972/82559272-9c0d1680-9b6f-11ea-9ba7-2e99912da5cf.png)

**Comment by rmarquis** [comment]
Leading whitespace and other special characters should now be removed.

To be noted:
* sorting is done on the client, as such 2.60b and old ETL clients still won't sort correctly (same order, but without whitespace)
* two of the `| TWC |` servers still have *one* whitespace. I don't know what black magic happens here, but I seemingly can't remove these.

**Comment by rmarquis** [comment]
The space leftover issue happens because a color code (which isn't displayed) is present before extra spaces. The current fix simply moves the pointer at the "true" beginning of the string, but a much more elaborated fix is needed to filter these out.

**Comment by rmarquis** [comment]
Pushed a workaround, that actually breaks the first color code for a tiny number of existing servers (~2/370), but prevent any abuse by admins without the need to implement a much more complex solution.
