### ISSUE TITLE
Remove r_primitives

### ISSUE THREAD

**Issue by rmarquis** [etlegacy/etlegacy#1489]
The `r_primitives` cvar controls how elements are drawn onto the screen. Possible values are:

```
 "0" = based on compiled vertex array existance
 "1" = glDrawElemet tristrips
 "2" = glDrawElements triangles
 "-1" = no drawing
```

The default value `0` automatically choose between the optimal value, depending on the hardware. However, some gfx cards fail (mostly AMD/ATI) so one has to explicitly set it to `2`, which is equivalent of `0` when the hardware support the required `glLockArraysEXT` OpenGL function. This should be most if not all hardware from the past couple of years (I guess?).

Check `R_DrawElements`, and remove associated functions if necessary.
This has been done in ETe, and doint it should fix one very common issue for AMD/ATI users (see FAQ).

Implementing #1457 first might be a good idea.

Refs:
* [ETe commit](https://github.com/etfdevs/ETe/commit/e907be8fa1411c61554b64facfe1f67d17b6bece#diff-0e42ce7acea065751bd9175c72529697L168-L202)
* [glLockArraysEXT on freedesktop.org](https://dri.freedesktop.org/wiki/CompiledVertexArray/)
* [glLockArraysEXT on IBM Knowledge Center](https://www.ibm.com/support/knowledgecenter/ssw_aix_71/com.ibm.aix.opengl/doc/openglrf/glLockArraysEXT.htm)

**Comment by Aranud** [comment]
Current status as @rafal1137 said and for record : 

> There is still OpenGLES Renderer that needs to be look at.
