### ISSUE TITLE
Minimap icons flicker when near the edge of compass

### ISSUE THREAD

**Issue by rmarquis** [etlegacy/etlegacy#1492]
The objective icons on the minimap (map in compass) appear and disappear suddenly when they are in the edge of the minimap.

This is a regression, probably introduced a long time ago.

**Comment by rmarquis** [comment]
This is actually a vanilla issue. The calculation inside of `CG_ScissorEntIsCulled()` when `scissor->circular` isn't correct, and return `qtrue` when the icon is still visible in the compass. NB: check all icon entities, since behaviour of objectives and flags seem a bit different.

**Comment by zedar187** [comment]
Reopened. The player icon still flickers while moving. When standing still, the icon can disappear completely.

Tested on current master.

**Comment by rmarquis** [comment]
Note: the flickering is still there, but only when joining a dedicated server. When starting via "host game", it's fine.
I was not able to reproduce the player icon disappearing issue when standing still.

**Comment by zedar187** [comment]
It happens only while being in a team. When you're a spectator it works as expected.

**Comment by rmarquis** [comment]
I cannot reproduce while in a team. As spectator, the compass/minimap isn't displayed, and only the spectator icon ("green eye") is displayed by design.

I am also unsure if that player icon issue is related to that ticket, since the above changes should affect only objectives and capturable flags icons. I feel you're referring here to far away players, which aren't meant to be displayed in real time but in some "telegraphic" fashion instead (in Legacy we however lowered the update rate from 2 sec to 1 sec). See #681, and https://github.com/etlegacy/etlegacy/commit/cb541c323d5bc24e2924075c26a50cffddfbb74a as part of #661.

**Comment by rmarquis** [comment]
For the record:
* sometimes the flickering happens in warmup, but is then gone when the map is restarted. Maybe something related to icon caching?
* movers icons (tanks, ..) don't seem to be properly culled (tank was displayed outside the compass on Venice map)
* some icons (f.e. Adlernest objective icon) is displayed way outside the compass
* the issue reported by @zedar187 above seems to be something entire else (it is indeed icon of player himself). I still cannot reproduce, and it seems nobody else has observed that issue so far. No idea what's going on here.

**Comment by rmarquis** [comment]
> movers icons (tanks, ..) don't seem to be properly culled (tank was displayed outside the compass on Venice map)
> some icons (f.e. Adlernest objective icon) is displayed way outside the compass

This doesn't seem to be related to icon culling directly, but to the way the compass mask is handled (such icons were slightly visible outside the compass). If anything, the above commit made that underlying issue more visible.
This issue is also present on etpro/jaymod (flickering fixed), and etpub based mods (flickering unfixed, but icons slightly visible outside the compass).

**Comment by rmarquis** [comment]
* previous code has been adjusted to only slightly display icons outside the compass in case icon shader is missing
* shaders for some popular maps have been added in default shaders shipped by Legacy - more might be added if necessary.

As discussed with @zedar187, the mac issue will not be handled in this ticket (nobody can reproduce afaik).
