### ISSUE TITLE
Problem with weapon swapping.

### ISSUE THREAD

**Issue by ryzyk-krzysiek** [etlegacy/etlegacy#1494]
After some weeks I finally found and replicated an issue with weapon swapping. It occurs near door controls on adlernest and so I'm not sure if it's only map related or maybe objective as a whole.

https://streamable.com/k3tle1
After few seconds of trying I only managed to swap it after changing the angle.

[2020-06-18-104041-adlernest.zip](https://github.com/etlegacy/etlegacy/files/4797597/2020-06-18-104041-adlernest.zip)
Timestamp for demo is around minute 5 or just near the end, it should be easy to replicate though I think.

**Comment by Aranud** [comment]
Fixed by the change done from this issue : https://github.com/etlegacy/etlegacy/issues/1337
