### ISSUE TITLE
Missing indicators about allies taking objective.

### ISSUE THREAD

**Issue by ryzyk-krzysiek** [etlegacy/etlegacy#1499]
Today on Team Muppet server after axis returned objective on adlernest there was no sound alert, on screen indicator or information in chat log that allies took it again. It was only visible on scoreboard (+scores) and by the looks of it they took the objective immediately after axis returned it. I think it is not the first time there is no sound alert at least.

Demo(timestamp around 11:20 ingame time):
[2020-07-11-134927-adlernest.zip](https://github.com/etlegacy/etlegacy/files/4906770/2020-07-11-134927-adlernest.zip)

**Comment by rafal1137** [comment]
Let me throw few cents into this one.
1075 build version is required to play this demo.
From watching a demo Obj Indicators were working correctly. But there was 1 thing that got my attention, it was the sound.
"Obj has been taken" played twice when Ally and Axis took it and right after "Obj is Secure".

**Comment by ryzyk-krzysiek** [comment]
I rewatched that demo yesterday and today and I get different results than you and the one from a week ago.

1.  I deleted every pk3 file from mydocuments legacy folder (legacy_v2.76-1075-g765ea79.pk3 and newer 1150, 1226) and demo  replaying only stops working after I delete etl_bin_v2.76-1002-g588e294.pk3 and pak3_v2.76-1002-g588e294.pk3. So seems like I dont need 1075 build, no idea how it works.
2.  I'm getting sound alert and text log about axis securing and allies stealing objective at this time but they are reversed (allies steal alerts and then axis secure alerts, and only after about 2 seconds it shows on scoreboard that it was actually stolen again). The result would be pretty much the same as last week though, because axis would have thought that the objective is secure. There is no on-screen indicator still.
3.  The only thing that changed on my side is getting the 1226 version of the Legacy mod after reporting this issue. I have no clue if version even matters, but somehow I get different result then week ago (I watched the demo around 10 times since yesterday).
4.  Before I reported that issue I was checking the console while still being on server just on new map and there was no text and demo confirmed it later, so back then there was no difference between live game and demo.

This is what I get now(noscreen indicator even when the stolen objective shows up on scoreboard at 11:13):
![Stolen_objective_indicators](https://user-images.githubusercontent.com/4499367/87933891-5ba61800-ca8e-11ea-9a2c-5a9976b746be.png)

**Comment by rafal1137** [comment]
@ryzyk-krzysiek About those indicators on the left corner of screen nothing we can do it is in map script.

**Comment by rmarquis** [comment]
A few notes:
* version does matter. The subsystem is event based, so anything added/changed by have some naughty effect (it's not ideal, but this is a small price to pay for a snapshot version).
* the sound effect isn't real time, unlike the objective icon display. There is a queue to prevent sounds playing on each other, and sometimes sounds are dropped if they can't fit between similar events. As a rule of thumb, the icon display is more reliable than the sound effects.
* the scoreboard display isn't real time either, but updated every 2 secs if called. I don't know how that actually translates in demo recording (my guess would be the data is updated only when the player in the real time game called the scoreboard, but maybe not in demo which might use the latest version available). 
* events are limited in a specific time period. If too many events were called at the same time, I guess it is possible such events were simply dropped on the client side (or is that still the case? See #507). This _might_ explain different results in some case.

Also, while watching the demo, it wasn't clear to me if the obj had indeed been returned or if some allies player simply took back the dropped obj. You can't see what's actually happening in the demo, so some part of what happened is pure guess.

**Comment by ryzyk-krzysiek** [comment]
@rafal1137 
 Would sound alert and on screen indicator be dependant on that script too though? If last week there was no text wouldn't it make sense there would be no sound alert too because it depends on that part of script to relay information about objective being stolen? And now that there is text so is sound alert but since its in wrong order sound is too and there is no screen indicator because the information that went through last would be that axis returned the documents. Would that make the whole problem map related? Just pure speculation, because I don't know how any of this actually works.

@rmarquis 
 You can see the documents returned at 11:15 by field ops to my right. If you can't see it clear enough from my perspective you can change to freecam mode with 'KP_ENTER' (default setting) and focus on the documents as soon as they show up in the room. They are returned and taken immediately or very soon after 100%. Later on, at 10:53 you can see me go to the documents room and there are no documents on the table and there were no additional indicators between my time at both objective rooms in that span of 22 seconds time. 

I wanted to upload better clip that would show more but after 3hours of trying to upload 29mb video I gave up.
https://streamable.com/dk1722

e: Thanks for the replies with explanations.

**Comment by rmarquis** [comment]
This is potentially fixed by 31ee38561cafa4f77ea08cb3df98800c027ec1d9. Feedback needed in case the issue happens again.

**Comment by rmarquis** [comment]
It is hard to say what is causing the issue, or if it is still happening at all as it is not really prevalent.
Closing now, please reopen if it is observed again.
