### ISSUE TITLE
Display teammate icons with exact position on full command map (G)

### ISSUE THREAD

**Issue by realkemon** [etlegacy/etlegacy#1500]
We display the revive icon for teammates not on the minimap at the edge of the compass. There was a suggestion on Discord to extend that and draw exact position of the revive icon on the full command map that you can open with G. If the distinction can be done then I wouldn't draw them on the limbo menu command map since that one is exclusively for map features and objectives. The handheld command map however, could receive a stronger purpose by adding exact positions of teammates and their icons.
This does not necessarily have to be restricted to revive icons.

**Comment by rmarquis** [comment]
Already the case. Closing.
