### ISSUE TITLE
Deployed mobile MG movement not fixed to the scope on x axis

### ISSUE THREAD

**Issue by zedar187** [etlegacy/etlegacy#1501]
While deployed the movement of the MG is fixed to a certain x axis scope. If you scroll further "outside this scope" the camera movement stops, but the mouse movement gets recognized. You need to "scroll" the same amount back to get the camera moved again.

How to reproduce: spawn as a soldier with a mobile mg. Deploy it, move your mouse to the far right. At a certain degree, the camera is fixed, as it should. If you now scroll to the left, you have to move the same amount that you moved outside to the right side.

The mortar on the other hand is correct: after deployment you move to the far right. It snaps to the allowed scope. If you now move the mouse further to right, then back to left, the camera is moved instantly.

Tested on 0d93f1f.

**Comment by rmarquis** [comment]
Is this the same issue as #1479, or a different one?

**Comment by zedar187** [comment]
It's a different one. #1479 is about a wrong view/fov in relation to the model.

While playing around with this, I found an additional issue, which might make it a bit clearer. While deployed, just keep your mouse moving in one direction, e.g. to the right. After 360° the view snaps to the left. Same goes for the other direction.

In other words: the camera/view stops right at $x degree to the right, but the mouse movement still increases, instead of stopping (as the mortar correctly does).

https://streamable.com/d03v6g

**Comment by rmarquis** [comment]
I actually wonder if #1220 might be related.

**Comment by rmarquis** [comment]
This is a regression. Latest stable version 2.76 is not affected.

**Comment by rmarquis** [comment]
Bisected to abe4473cd932415c7bfecd46d90d389371ecd7b8.

The problematic part is at the very bottom of `PM_UpdateViewAngles()`:
```
		// all fine
		ps->delta_angles[YAW] = newDeltaAngle;
```
Commenting this single line prevents the issue. Adding a condition to check if using a settable weapon while prone might be enough here.

**Comment by Aranud** [comment]
Sorry, fixed.
