### ISSUE TITLE
libtoolize is not checked when verifying build deps

### ISSUE THREAD

**Issue by collivier** [etlegacy/etlegacy#1502]
autoreconf: running: libtoolize --copy --force
Can't exec "libtoolize": Aucun fichier ou dossier de ce type at /usr/share/autoconf/Autom4te/FileUtils.pm line 345, <GEN3> line 4.

**Comment by rmarquis** [comment]
Compiling issue might vastly vary depending on your system. We don't do any Linux packaging, but in this very case... ensure you have libtoolize installed.

Closing now.

**Comment by collivier** [comment]
Usually autoconf, cmake, et al. checks the compile dependencies are met before compiling (see the first step in easybuild.sh).
Nothing related to Linux packages, it's just about good programming practices.

**Comment by rmarquis** [comment]
Ah, easybuild.... reopening.
