### ISSUE TITLE
Invalid file name force reconnection

### ISSUE THREAD

**Issue by redtide** [etlegacy/etlegacy#1506]
In some servers people insists to use invalid pk3 filenames to inject custom configurations and menus.
Despite this if the map package is present the map is loaded correctly but when a game is ended the following message is displayed:
```
Server file name "<filename>" is containing an invalid character for the ET: Legacy file structure.
Downloading file denied.
```
This force a reconnection and it's not possible to play unless restarting and reconnecting, then the maps are loaded correctly anyway.

A valid alternative would be to log the issue and try to load the map requested by the game instead to fail and display the message, adding if necessary an option to enable this.

**Comment by isRyven** [comment]
We have removed pk3 character filter, so this should not be an issue anymore in upcoming version.

**Comment by redtide** [comment]
Thanks for the quick reply! Closing.
