### ISSUE TITLE
wiki pages not indexed by search engines

### ISSUE THREAD

**Issue by mittermichal** [etlegacy/etlegacy#1521]
https://github.community/t/my-github-wiki-is-not-crawl-data-by-google/947
githubs [robots.txt](https://github.com/robots.txt) explicitly forbids crawling wiki pages
if you google `site:github.com/etlegacy/etlegacy/wiki` it's empty 

One solution could be to move the wiki to readthedocs.io I guess

**Comment by rmarquis** [comment]
Is this really an issue? As discussed previously, the user docs (cvars) is already handled on read the docs, while the rest (dev doc, install, faq, anything susceptible of changing often) is on the wiki.

Rather, is there anything specific the wiki home page should be improved upon?

**Comment by mittermichal** [comment]
for example when some regular player wants to google search any FAQ question. It won't yield any results from wiki. Even myself when I try to look for something like file structure I try to google it 1st, then I realize I have to go to wiki.
Atleast the stuff relevant for regular players should be searchable IMO

**Comment by isRyven** [comment]
I agree at least FAQ section could be accessible from the search systems, as it lists pretty common issues people run into and asking about on discord.

**Comment by rmarquis** [comment]
Well, in that case feel free to send a PR to the https://github.com/etlegacy/etlegacy-docs repo.
A redirect can then be set from the wiki FAQ to rtd.

**Comment by mittermichal** [comment]
not an issue anymore since github enables indexing on wikis in repos with more than 500 stars
https://docs.github.com/en/communities/documenting-your-project-with-wikis/about-wikis
