### ISSUE TITLE
Failed compile etlegacy under clean installation of OS X Big Sur 11.0.1

### ISSUE THREAD

**Issue by raphaelthiel** [etlegacy/etlegacy#1523]
Comile failed under OS X 11.0.1

clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]:  [legacy/ui_mac] Error 1
make[1]:  [CMakeFiles/ui_mac.dir/all] Error 2
make: *** [all] Error 2
Exiting!

I tried following compile comands:
./easybuild.sh
./easybuild.sh -64
./easybuild.sh -64 --osx=10.15
./easybuild.sh -64 --osx=11.0.1

It would be great if there is a sharable osx 64 bit version. Thank you for your help

**Comment by zedar187** [comment]
Please provide a full compile log using `./easybuild.sh -64 --osx=10.15` either here in a code wrap or to a nopaste service.

**Comment by raphaelthiel** [comment]
Here is a copy of the log

https://www.icloud.com/iclouddrive/0jRg5oS5OLVB9s3aq9WSGldpg#etl

**Comment by zedar187** [comment]
Compilation works again with latest master code.
