### ISSUE TITLE
Un-hardcode domain name

### ISSUE THREAD

**Issue by rmarquis** [etlegacy/etlegacy#1529]
It has come to light that the domain name of the etlegacy.com infrastructure is pretty much hardcoded in the current code.
This is an issue in the very hypothetical case where the domain name couldn't be managed anymore for whatever reason, and as such it is a potentially critical issue that could flatline the whole project.

See 
`qcommon.h`:

```
#define MOTD_SERVER_NAME    "motd.etlegacy.com"    ///< location of the message of the day server
#define UPDATE_SERVER_NAME  "update.etlegacy.com"  ///< location of the update server

#define PORT_MASTER         27950
#define PORT_MOTD           27951
#define PORT_UPDATE         27951
#define PORT_SERVER         27960
```

Similarly to the existing `com_downloadURL`, add some `CVAR_INIT` cvars to allow a configurable domain name on the client side, ~~and do the same for the various port numbers,~~ for ex:

* `com_masterURL`
* `com_motdURL`
* `com_updateURL`

**Comment by isRyven** [comment]
i'd say no need for serverport as there is already `net_port` to set port anyways

**Comment by isRyven** [comment]
also if you define URL in the cvar this already implies port included

**Comment by rmarquis** [comment]
Ah, great!

**Comment by rmarquis** [comment]
Probably doesn't work with IPv6, but that might be outside of the intended use of this feature (being a last backup solution in case the worst happens on our end).
