### ISSUE TITLE
Client crashes during intermission time after completing round in stopwatch mode

### ISSUE THREAD

**Issue by BystryPL** [etlegacy/etlegacy#1537]
Happens randomly on legacy3 and legacy5 configs (haven't checked other configs). Game crashes to desktop.

**Comment by ryzyk-krzysiek** [comment]
The game crashes when doing reload on 0:00, but not always, there is a specific timing you need to hit I think. Still I reproduced it 3 times so I don't think it's coincidence. It can happen after first round too, the clip below is round 1. 

Tested on legacy3 config.

https://streamable.com/6c5bs2

**Comment by jackeri** [comment]
Reportedly this is fixed on the current master.
