### ISSUE TITLE
Capturing flag in wounded state.

### ISSUE THREAD

**Issue by ryzyk-krzysiek** [etlegacy/etlegacy#1538]
It's possible to capture the flag when in wounded state.
https://streamable.com/7zf941
[2020-12-29-200531-braundorf_b4 0740 Flag capture wounded.zip](https://github.com/etlegacy/etlegacy/files/5752116/2020-12-29-200531-braundorf_b4.0740.Flag.capture.wounded.zip) Time: around 7m40s

**Comment by mittermichal** [comment]
its an awesome feature :)
https://gfycat.com/waterloggedmedicalelephantbeetle-enemyterritory

**Comment by mittermichal** [comment]
https://vimeo.com/6819853 another funny case at 11:00

**Comment by rmarquis** [comment]
This has been fixed in etpub and nq codebases, see `checkpoint_spawntouch`:

```
// forty - dead guys don't capture spawns.
	if(other->health <= 0)
		return;
```

```
if ( other->client->ps.eFlags & EF_DEAD )
        return;
```

**Comment by mittermichal** [comment]
never heard anyone complain about this in competitive matches, everyone knows its possible and it happens sometimes on supply flag
