### ISSUE TITLE
Add option to display full map time along remaining time

### ISSUE THREAD

**Issue by Aciz** [etlegacy/etlegacy#1546]
Round timer should be configurable to display the round time in remaining time/full time format, eg. `7:53/12:00`

**Comment by rmarquis** [comment]
What's the point of the full map time, if I may ask?

**Comment by Aciz** [comment]
Sometimes you just want to know how long you've been playing the map? I surely don't remember the time limits of every single pub map there is.

As for maps that have various time limits: I'm not sure how those would work out, but I'd imagine the total time can be adjusted on the fly, just like remaining time.

**Comment by rmarquis** [comment]
I don't think that information is critical, at least not to the point of having it displayed on the player HUD. Maybe this can be merged with #1547 to add this information on the scoreboard instead?

**Comment by Aciz** [comment]
Sure, it could be there as well, it already displays the mission time on the right side, it could be added there. And the way I was initially thinking of the implementation would be to tie it to `cg_drawRoundTimer`, by setting a value of 2 it would also display the remaining time. So it would be fully optional, not something thats just added to everyones HUD.

**Comment by rmarquis** [comment]
I understood the optional aspect of it, but still, I don't see how that isn't extra unnecessary clutter on the HUD.
Scoreboard makes much more sense imho.

**Comment by jobhh** [comment]
Additionally, it might be confusing to see the full map time change in situations where extra time is awarded after an objective is completed (if that's a thing in ET Legacy).

**Comment by mittermichal** [comment]
Agree with @rmarquis I would definitelly not put it in HUD, because it's not important information, but should be fine in scoreboard:
![timelimit](https://user-images.githubusercontent.com/4035800/103480652-bd0c3a00-4dd5-11eb-980a-221226f87783.png)
Currently you can see timelimit in server info menu.
