### ISSUE TITLE
Add map name to scoreboard

### ISSUE THREAD

**Issue by Aciz** [etlegacy/etlegacy#1547]
Currently, the only way to see the currently running map is to go to server info menu and checking there, or by recording autodemo. Scoreboard could be made to display current map name in the middle, similar to how for example ETJump displays the map name.

![etjumpmap](https://i.imgur.com/uRtDHwP.png)

**Comment by rmarquis** [comment]
Note: the middle space is already used for various strings, depending on the game mode.
