### ISSUE TITLE
Set cl_doubletapdelay to "0" by default

### ISSUE THREAD

**Issue by BystryPL** [etlegacy/etlegacy#1549]
It's very common thing to see a lot of players getting the "prone bug", which consists in people randomly going prone in the middle of the fight. This is caused by the cl_doubletapdelay cvar which is set to "350" by default. This sets the maximum delay required between pressing the crouch key + forward key to be a double-tap. A lot of people don't set this cvar to "0" in their configs and this results in the "prone bug".

How to reproduce: set cl_doubletapdelay to "350", press your crouch key and while still pressing it then tap quickly two times your +forward key. This will result in proning. Setting cl_doubletapdelay to "0" prevents this kind of behaviour.

My suggestion is to simply set the value of this cvar to "0" by default. This will prevent the "prone bug" for new players or players that didn't set this cvar to "0" in their configs.

**Comment by jackeri** [comment]
There are lot of cvars that should have the default values changed. Like cg_drawcrosshair (this should be 5 by default, the 0 crosshair is horrible), and the cg_althud & cg_althudflags. New players or old returning players might have no idea you can change the hud so they play with the horrible etmain type huds (after which they think, wow what an awkward looking hud & game).

**Comment by rmarquis** [comment]
See also #1237.
