### ISSUE TITLE
Server browser not showing private slots

### ISSUE THREAD

**Issue by TeamMuppet** [etlegacy/etlegacy#1552]
Server browser does not show the total slots of a server including private slots, if players are on the server and connected with the private password they will not be added to the total clients on the server i.e 20 players on server 10 players joined with private password, browser only shows as 10 players on server.

**Comment by rmarquis** [comment]
As far as I remember, private slots are explicitly hidden as to not give the false impression public player can still join a "non-full" server.
This said, I do agree the player counter is counter-intuitive. Let's see if we can find a better solution.

**Comment by rmarquis** [comment]
Implemented, but do note this will only show up in newer servers build and with newer clients build too.

**Comment by surfzoid** [comment]
hi
seem broken in 78.1 client, from now, just after upgrade i see no player in browser but info server show me player (i m running linux)
