### ISSUE TITLE
Hide vehicle healthbar when setdamagable 0

### ISSUE THREAD

**Issue by realkemon** [etlegacy/etlegacy#1563]
In the new version of 'Supply Depot, by ginc' I added all necessary entities to allow server admins to toggle the truck between vulnerable and invulnerable. The only downside of that addition is that for the case where the truck remains invulnerable, there is now a healthbar displayed. In that case it can be considered as intrusive clutter, because the healthbar yields no benefit for the player.

Can the healthbar of script_movers be hidden when said script_mover is set to `setdamagable [script_mover] 0`? This is not a one time setting, but can change throughout the map if that is important for the implementation.

**Comment by rmarquis** [comment]
Note for later: Check `G_ScriptAction_SetDamagable` (`target->takedamage`) and `CG_ScanForCrosshairEntity`, in particular the `currentState.effect1Time` parameter that might be used here. 

Edit: Have a closer look at `SP_script_mover`, which control set `s.effect1Time` when health of a mover entity exists.

**Comment by rmarquis** [comment]
@realkemon Please test for any side effects, especially when the script is used back and forth. Newer automated build will be available on Friday.

**Comment by realkemon** [comment]
The healthbar is not brought back once the truck is damageable again. I toggled between the states multiple times and it didn't show again after the first time of being hidden.
//EDIT: tested with snapshot build: Commit hash: f75a738392e5e2d91446638f052eeb7a3ab5e4f4 from: 2021-02-09T23:00:25Z

**Comment by rmarquis** [comment]
Missed your comment, sorry.

Right, an `else` condition is indeed missing here. Following should do the trick. Pinging @ShadowRage or ETL workhorse @Aranud:

```
else
{
    target->s.effect1Time = 1;
}
```

**Comment by Aciz** [comment]
Not sure how exactly this issue appears, it seems to work as expected:

https://streamable.com/r1v6vk
