### ISSUE TITLE
Add option to set player position and pov

### ISSUE THREAD

**Issue by realkemon** [etlegacy/etlegacy#1564]
For comparing performance with `/r_speeds 1` it would help if we could save a certain player position including pov so we can be sure that the metrics should be identical. It would also help with taking before/after comparison shots for map overhauls. I think etjump saves the position, not sure about pov?
Saving the position is only one side though as it would need to be necessary to also set the position on a different map, possibly different game instance. 

Maybe sth like `/playerPosition` that prints the current position and pov in the console if it's called without arguments and sets the player to that position if it's called with arguments. Is that possible?

**Comment by Aciz** [comment]
Note: there is already `viewpos` for printing out X Y Z Yaw (lacking pitch and roll), and `freecamgetpos` & `freecamsetpos` which unfortunately are only available in demo playback in freecam mode.

**Comment by Aciz** [comment]
...and theres aleady also `setviewpos`... But this command along with `viewpos` should probably be extended to include pitch & roll.

**Comment by realkemon** [comment]
They could've gone for `viewPos` and `setPos`, but no....
But yes, those two sound perfect. Roll is probably unnecessary, but I guess it  wouldn't hurt either.
