### ISSUE TITLE
uncrustify version

### ISSUE THREAD

**Issue by mittermichal** [etlegacy/etlegacy#1574]
is uncrustify supposed to be updated?
it was mentioned in #1192
> For post-2.77
> 
>     * prepare new style formatting (uncrustify, see morsik )
@morsik 

@rmarquis did https://github.com/etlegacy/etlegacy/wiki/Coding-Conventions/_compare/d8436e7de2aafe15ea0d8f6135056f3a3a7ef19a so maybe he knows something about it :)

**Comment by rmarquis** [comment]
morsik wanted to prepare a new standard for uncrustifying the whole project, "fixing" some decision he made years ago.

Uncrustifiying the whole project will basically put an annoying giant commit in the middle of the history, which we'll come across again and again when backtracking regressions (there are a few commits like that, but most happened years ago). As such, I suggested to do it right post release, so we can more easily "work around" it.

From my POV: the current uncrustifiy standard isn't perfect, but it works okay. I don't think it is really necessary to update it.

Edit: to clarify, this isn't only about the uncrustify version, but also and primarily the ruleset we use in `uncrustify.cfg`.

**Comment by jackeri** [comment]
I think we should just set the currently suggested uncrustify version to the latest release version which is 0.72, and update in a year so again. The config as it as is okish.

**Comment by rmarquis** [comment]
Let's do this then, there is no point in using old versions from several years ago.
As of now, please ensure you all use the latest uncrustify version (0.73 at the moment).
The wiki has been updated accordingly.

Closing.
