### ISSUE TITLE
PAK and Map Downloads Capped at 100KB/sec

### ISSUE THREAD

**Issue by sadsfae** [etlegacy/etlegacy#1581]
Hi Folks, long-time server admin/player here.  It seems that clients aren't able to pull down PAK's and maps over HTTP beyond 100KB/sec.

I have tried various cvars like trying `0` or and other values but result is the same - always capped at 100KB/sec.

```
set sv_maxRate "900000"
set sv_dl_maxRate "900000"
```

On the client side I see:

```
Need paks: @legacy/pak3_v2.75.pk3@legacy/pak3_v2.75.pk3
Client downloading: legacy/pak3_v2.75.pk3
Server redirected download: http://funcamp.net/legacy/pak3_v2.75.pk3
Client download subsystem initialized
DL_DownloadLoop: Error - request terminated with failure status 'Unsupported protocol'
Download failure while getting 'http://example.net/legacy/pak3_v2.75.pk3'
Connected to a pure server.
Need paks: legacy/pak3_v2.75.pk
```

I can wget/curl these file fine from their HTTP locations at full speeds, I've tried both https and http for good measure.
I'm not sure what I am missing here, thanks for any guidance.

**Comment by mittermichal** [comment]
i think this is the case that ETL client doesnt support http, so it recejted http download and downloaded the file from game server.
also its sv_dlRate not sv_dl_maxRate and this controls game server download speed, you cant control https download speed with game server cvar, thats up to webserver

**Comment by mittermichal** [comment]
the cvar name was changed here: 108ca8503a141f996148b9c5b4dfed6e9ed78f51
before 2.75 release
https://github.com/etlegacy/etlegacy/releases

**Comment by sadsfae** [comment]
> i think this is the case that ETL client doesnt support http, so it recejted http download and downloaded the file from game server.
> also its sv_dlRate not sv_dl_maxRate and this controls game server download speed, you cant control https download speed with game server cvar, thats up to webserver

Thanks for the quick response, looking at HTTP logs I don't even see it attempting to pull it down so that makes sense.  Do you know what we'd need to use for these directives if we can't use HTTP/S?   


```
set sv_wwwDownload "1"
set sv_wwwBaseURL "https://example.net"
set sv_wwwDlDisconnected "0"
```

I recall it used to use libcurl but maybe that's changed or I'm misremembering.

**Comment by mittermichal** [comment]
I guess it depends what etlded version you are using. But I really don't know
the sv_wwwBaseURL should be `https://funcamp.net` in your case right?
notice that in your log it says:
Server redirected download: `http://funcamp.net`/legacy/pak3_v2.75.pk3
and then:
Download failure while getting '`http://example.net`/legacy/pak3_v2.75.pk3'

Also I dunno what should happen when 2.60b client tries to download https

**Comment by sadsfae** [comment]
> I guess it depends what etlded version you are using. But I really don't know
> the sv_wwwBaseURL should be `https://funcamp.net` in your case right?
> notice that in your log it says:
> Server redirected download: `http://funcamp.net`/legacy/pak3_v2.75.pk3
> and then:
> Download failure while getting '`http://example.net`/legacy/pak3_v2.75.pk3'
> 
> Also I dunno what should happen when 2.60b client tries to download https

I'm using an ETL 2.76 client and an ETL2.75 server but yeah, that's correct - I guess I did a poor job of faux sanitization.

I have the `pak3_v2.75.pk3` reachable and accessible in both `../legacy` and `../etmain` urls just wondering what I am missing that would keep the client from snatching it - it doesn't get it from me, just trying to understand why and what I'm doing wrong.

e.g. (Also available via HTTP)
https://funcamp.net/legacy/pak3_v2.75.pk3
https://funcamp.net/etmain/pak3_v2.75.pk3

**Comment by rafal1137** [comment]
@sadsfae  2.75 Server Does not support https at all so. Best way to get it working with https is to download from our snapshops

**Comment by sadsfae** [comment]
> @sadsfae 2.75 Server Does not support https at all so. Best way to get it working with https is to download from our snapshops

Ah ok, that makes sense - in this case I do redirect HTTP to HTTPS.

**Comment by rafal1137** [comment]
Yes you can but I suggest you to run server with 2.76. 2.75 kind of outdated and not supported

**Comment by sadsfae** [comment]
> Yes you can but I suggest you to run server with 2.76. 2.75 kind of outdated and not supported

I struggled with the omnibot setup on 2.76 (or it might have been noquarter mod - don't remember) so went back to 2.75 on the server side, thanks.  You can close this issue now, I'll use an HTTP-only mirror and later try upgrading again.
