### ISSUE TITLE
file permissions by etlded

### ISSUE THREAD

**Issue by Crytiqal** [etlegacy/etlegacy#1587]
Issue:

running etded instead of etlded creates the following files:
-rw-rw-r-- 1 steam steam 3.5K Feb 23 11:06 etconfig.cfg
-rw-rw-r-- 1 steam steam  11K Feb 23 11:06 etconsole.log
-rw-rw-r-- 1 steam steam  828 Feb 23 11:06 etserver.log

running etlded instead of etded creates:
-rwx------ 1 steam steam  11K Feb 23 11:06 etconsole.log
-rw-rw-r-- 1 steam steam  828 Feb 23 11:06 etl.db

Not only does etlded fail to create the etconfig.cfg and etserver.log, it also gives executable permissions to the randomly generated etconsole.log file. This is a security risk. If I would be running etlded under a sudo account, I could accidently execute ./etconsole.log and any malicious strings inserted by chat could be executed.
The default file permissions is 664 (rw/r/r)
Besides giving the file executable permissions, it also prevents any other user to read the logfile.
I am unable to open the logfile with my normal user account and use tail -f when starting the server with etlded.

Settings used:

// LOGGING
set logfile "2"		        // Console logging ( 1: enable 2: enable and sync )
set g_log "etserver.log" 	// Game logging
set g_logsync "1"

user:group is steam:steam for my gameservers.

**Comment by Aciz** [comment]
Same issue when running on 1612 build & ETJump, etconsole.log and any ETJump-specific logfiles are created with 700 permissions.
