### ISSUE TITLE
Patch movement inconsistencies with ETL/2.60b

### ISSUE THREAD

**Issue by Aciz** [etlegacy/etlegacy#1590]
Movement around patches due to abd2d4d is inconsistent between 2.60b and ETL. If we take 2.60b client + 2.60b server as a baseline for "how it should work", there are following issues:

* ETL client + ETL server = cannot "glide" patches
* ETL client + 2.60b server = can "glide" patches, but small prediction error occurs
* 2.60b client + ETL server = cannot "glide" patches
* 2.60b client + 2.60b server = normal behavior

Video demonstrating the issues:
https://youtu.be/efAVAvcYt-Y

The `ETL client + 2.60b server` prediction error might not be very visible in the video, but you can definitely feel it when playing.

The cvar `cm_optimizePatchPlanes` added in bbcb647 fixes the issue for `2.60b client + ETL server` case when it's set to __1__, but since this is not set on client, `ETL client + ETL or 2.60b server` both still suffer from prediction errors.

I am not sure what could be done to fix this, since obviously reverting abd2d4d is out of question I assume. If `cm_optimizePatchPlanes` could be somehow set to __1__ on client as well when the server has it set, it would fix the errors with prediction on `ETL client + 2.60b server / ETL server with cm_optimizePatchPlanes 1` cases. Even still, the behavior that ETL has in general is inconsistent with how it works in 2.60b

**Comment by ryzyk-krzysiek** [comment]
I think this visualizes the problem a little bit better: https://www.youtube.com/watch?v=_QYube6h7bo Anyone that played radar should be familiar with this line blocking players.

Prediction errors are a result of the difference in what the world is (client can predict he can move over without issue while server stops the player on that line).

I think there might be no solutions other than revert it or leave it as it is. (Cannot patch 2.6b client/server, cannot force the cvar on ETL clients with current ways cvars are, because it need to be done before map loads)

**Comment by rmarquis** [comment]
If I understand correctly, this ticket is now fixed and can be closed?

**Comment by Aciz** [comment]
Well no, ETL client + 2.60b server is still problematic, as 2.60b server doesn't have the cvar to transmit to clients. The recent change only fixed ETL server with `cm_optimizePatchPlanes 1` and ETL client, since the client would still have 0 as value.

**Comment by rmarquis** [comment]
I see. I guess it's another reason to push adoption for ETL server for third party mods, and the issue should resolve by itself with time.
Great job anyway!

**Comment by isRyven** [comment]
As far as i remember there should be some facilities to detect the server being used, based on that you could potentially force the cvar value.

**Comment by Aciz** [comment]
Yeah ETL clients on ETL servers without the patch fix no longer suffer from prediction errors thanks to that change, but even so, this doesn't change the fact that movement around patches is different, even when the prediction is working. But for the most part, the patch change is good, it's only really annoying that it breaks ETL client + 2.60b server compatibility, and for "niche" communities like trickjumping, the movement change is definitely noticeable, but at least we can revert that on ETL server side now.

**Comment by Aciz** [comment]
![image](https://user-images.githubusercontent.com/14221121/133001826-e85ed30b-8a80-4be5-ac7f-007760896082.png)

If we could query this `version` string in in `serverstatus` before cm is generated, we could straight up tell if the server is running 2.60b, and set the cvar to vanilla ET behavior, so ETLegacy clients would not suffer from prediction errors on 2.60b servers.

**Comment by ensiform** [comment]
Does ETL not fake the version string though?

https://github.com/etlegacy/etlegacy/blob/master/src/qcommon/common.c#L3024

**Comment by Aciz** [comment]
Doesn't seem so (I was under this assumption too though, maybe it was at some point?)

![image](https://user-images.githubusercontent.com/14221121/133002033-cba6000a-faaa-4d91-955b-a3d4009681e4.png)

**Comment by ensiform** [comment]
Looks like the status infostring key is overridden by ETL version https://github.com/etlegacy/etlegacy/blob/master/src/server/sv_main.c#L813

AFAIK by the time CM_LoadMap is called (from cgame) the serverinfo should already be accessible by client code because the gamestate is checked very early on and many configstrings are initalized in cgame, not to mention it should be included in the very first gamestate and subsequent packets received from server.

**Comment by isRyven** [comment]
As i mentioned already - client (and server) already has the facilities to check the full compatibility against server (or client). I have added this to improve command stripping for non-etl clients / servers. It's based on `version` string of the server (for clients) - pulled from `infoResponse`. Example usage on client:
 https://github.com/etlegacy/etlegacy/blob/e73c85eca7bf7fc0ce5b0b7bf3c2008270b7b9ce/src/client/cl_main.c#L1536
 
 This can be used right after client connects (passes the challenge and receives the baseline along with CS) or such - I am not entirely sure what would be the best place to force the cvar.

**Comment by Aciz** [comment]
I think everything that can be done is now done, only remaining issue is 2.60b client + etlded server, which is impossible to fix, but at least server operators have the option to revert to vanilla behavior now while still having ETL clients compatible too. Closing.

**Comment by Aciz** [comment]
Scrap that, my testing was bad as I only tested on devmap, and client resets cheat cvars after these checks, reopening....

**Comment by Aciz** [comment]
Alright, so I updated my server with the latest snapshot now, and downloaded a client for myself too to test things in a real world environment.

2.60b server + ETL client = client sets `cm_optimizePatchPlanes 1`
ETL server with `cm_optimizePatchPlanes 1` + ETL client = client sets `cm_optimizePatchPlanes 1`
ETL server with `cm_optimizePatchPlanes 0` + ETL client = client sets `cm_optimizePatchPlanes 0`

So it *should* be okay now, closing attempt v2 :D
