### ISSUE TITLE
Can't open ET Legacy 2.77 on Ubuntu 20.10

### ISSUE THREAD

**Issue by jcs224** [etlegacy/etlegacy#1592]
I'm using Pop OS 20.10 (a Ubuntu derivative) 64-bit, with Intel Xe integrated laptop graphics. I'm trying to run the 32-bit version of ET Legacy 2.77.

Here is the crashlog.

```
       0 ^2ET Legacy v2.77 linux-i386 Mar  1 2021
       0 Zone megs: 64
       0 INFO: fs_game now defaults to 'legacy' mod instead of 'etmain'
       0 ----- Initializing Filesystem --
       0 Current working directory:
       0     /home/joe/Games/etlegacy-v2.77-i386
       0 Current search path:
       0     /home/joe/.etlegacy/legacy
       0     /home/joe/.etlegacy/legacy/wolfadmin_1.2.0.pk3 (26 files)
       0     /home/joe/.etlegacy/legacy/pak3_v2.76.pk3 (1107 files)
       0     /home/joe/.etlegacy/legacy/legacy_v2.76-1589-gdb02861.pk3 (1326 files)
       0     /home/joe/.etlegacy/legacy/legacy_v2.76-1584-gf75a738.pk3 (1326 files)
       0     ./legacy
       0     ./legacy/legacy_v2.77.pk3 (1328 files)
       0     /home/joe/.etlegacy/etmain
       0     /home/joe/.etlegacy/etmain/z_zm_etmain_menu_24.pk3 (16 files)
       0     /home/joe/.etlegacy/etmain/venice_ne4.pk3 (325 files)
       0     /home/joe/.etlegacy/etmain/teuthonia_final.pk3 (144 files)
       0     /home/joe/.etlegacy/etmain/supplydepot2.pk3 (46 files)
       0     /home/joe/.etlegacy/etmain/supply.pk3 (44 files)
       0     /home/joe/.etlegacy/etmain/sp_delivery_te.pk3 (51 files)
       0     /home/joe/.etlegacy/etmain/jailbus_b2.pk3 (241 files)
       0     /home/joe/.etlegacy/etmain/isle.pk3 (59 files)
       0     /home/joe/.etlegacy/etmain/GA_El_Kef.pk3 (39 files)
       0     /home/joe/.etlegacy/etmain/fa_bremen_final.pk3 (109 files)
       0     /home/joe/.etlegacy/etmain/et_ufo_final.pk3 (45 files)
       0     /home/joe/.etlegacy/etmain/et_beach.pk3 (177 files)
       0     /home/joe/.etlegacy/etmain/eagles_2ways_b3.pk3 (264 files)
       0     /home/joe/.etlegacy/etmain/dubrovnik_final_1104.pk3 (186 files)
       0     /home/joe/.etlegacy/etmain/caen.pk3 (82 files)
       0     /home/joe/.etlegacy/etmain/braundorf_final.pk3 (76 files)
       0     /home/joe/.etlegacy/etmain/baserace.pk3 (129 files)
       0     /home/joe/.etlegacy/etmain/1944_beach.pk3 (60 files)
       0     ./etmain
       0     ./etmain/pak2.pk3 (22 files)
       0     ./etmain/pak1.pk3 (10 files)
       0     ./etmain/pak0.pk3 (3725 files)
       0     ./etmain/mp_bin.pk3 (6 files)
       0 
       0 10969 files in pk3 files
       0 --------------------------------
       0 Creating PID file 'profiles/monalichi/profile.pid'
       0 ----- Database Initialization --
       0 SQLite3 libversion 3.32.1 - database URI 'etl.db' - in file
       0 ... loading existing database '/home/joe/.etlegacy/etl.db'
       0 ... database file '/home/joe/.etlegacy/etl.db' loaded
       0 SQLite3 ETL: database init #2 /home/joe/.etlegacy/etl.db in [0] ms - autocommit 1
       0 SQLite3 ETL: DB schema version #2 is up to date
       0 --------------------------------
       0 execing default.cfg
       0 execing profiles/monalichi/etconfig.cfg
       0 couldn't exec autoexec.cfg
       0 Hunk_Clear: reset the hunk ok
       0 Not logging server attacks to disk
       0 ----- Client Initialization ----
       0 Trying to load "librenderer_opengl1_i386.so" from "."...
       0 Loading "librenderer_opengl1_i386.so" failed
       0 failed:
"libOpenGL.so.0: cannot open shared object file: No such file or directory"
       0 ----- Client Shutdown ----------
       0 --------------------------------
       0 PID file removed.
       0 SQLite3 database closed.
Failed to load renderer lib
```

**Comment by jcs224** [comment]
I also tried running `sudo apt-get install libopengl0`, which wasn't already installed, but it didn't fix the issue after installing it.

**Comment by tsolar** [comment]
@jcs224 in Debian I had the same issue. I installed `libopengl0`, the game starts but the screen turns black. I listen to sounds but screen is completely black. The only way to quit is to go to a TTY and kill/restart GDM3 (which is the display manager I use) :(

**Comment by jcs224** [comment]
@tsolar bummer. I should also note that 2.76 works fine so :man_shrugging:

**Comment by isRyven** [comment]
> @jcs224 in Debian I had the same issue. I installed `libopengl0`, the game starts but the screen turns black. I listen to sounds but screen is completely black. The only way to quit is to go to a TTY and kill/restart GDM3 (which is the display manager I use) :(

You can try running it in the windowed mode. This helps some times. `./etl +set r_fullscreen 0 +set r_mode -2`

**Comment by jackeri** [comment]
Is the black screen issue only with 32 bit client or also with 64 bit?

**Comment by jcs224** [comment]
For me, 32-bit won't open at all. Throws error as described.

64-bit shows a black screen when trying to open normally, but if I do the windowed mode it seems to work.

**Comment by yakoub** [comment]
i had similar problem, installing libopengl0 solves the libOpenGL problem but the game only runs in window mode while fullscreen is black .
the previous version v2.76 runs fine with or without libopengl0

**Comment by tsolar** [comment]
@yakoub Yep. 2.76 works fine.

@isRyven I ran what you mentioned (using 2.77 i386 binaries) and this is what I get (I am using two monitors/screens)
![photo_2021-03-02_01-19-38](https://user-images.githubusercontent.com/1470901/109596673-78f79600-7af5-11eb-886d-ee2d145773aa.jpg)

**Comment by jcs224** [comment]
Are you all using 32-bit or 64-bit linux? For me, 32-bit won't even open. I get the crash message and nothing happens at all. 64-bit leads to the black screen behavior you all are describing, which requires the windowed screen workaround. But at least it opens in 64-bit.

**Comment by mauricioduarte01** [comment]
> I also tried running `sudo apt-get install libopengl0`, which wasn't already installed, but it didn't fix the issue after installing it.

I have the same problem. Ubuntu 20.04 with installed libopengl0 game just crashes before even open it. So I don't know why some people managed to get it working. Maybe in my case it could be something related to using a Nvidia 1660ti GPU?

**Comment by rafal1137** [comment]
> 
> 
> > I also tried running `sudo apt-get install libopengl0`, which wasn't already installed, but it didn't fix the issue after installing it.
> 
> I have the same problem. Ubuntu 20.04 with installed libopengl0 game just crashes before even open it. So I don't know why some people managed to get it working. Maybe in my case it could be something related to using a Nvidia 1660ti GPU?

If you are using nvidia driver. You will have to install nvidia opengl equivalent lib.

**Comment by isRyven** [comment]
> @yakoub Yep. 2.76 works fine.
> 
> @isRyven I ran what you mentioned (using 2.77 i386 binaries) and this is what I get (I am using two monitors/screens)
> ![photo_2021-03-02_01-19-38](https://user-images.githubusercontent.com/1470901/109596673-78f79600-7af5-11eb-886d-ee2d145773aa.jpg)

You can change the window size in the options, if you haven't yet.

**Comment by jackeri** [comment]
Are you using dmw or what window manager is that?

**Comment by tsolar** [comment]
@jackeri it's the Awesome window manager

**Comment by tsolar** [comment]
@isRyven I could set the window size, but it wasn't needed before, so why is it needed now? :(

**Comment by jackeri** [comment]
It because SDL2 currently has a bug with dmw or tiled window managers I presume https://github.com/libsdl-org/SDL/issues/4136

**Comment by tsolar** [comment]
@jackeri in GNOME (on Xorg) it has the same behaviour
![photo_2021-03-02_11-15-03](https://user-images.githubusercontent.com/1470901/109661258-8ee27680-7b48-11eb-9e34-f08151667466.jpg)

**Comment by jackeri** [comment]
Right so it gets the window resolution wrong when windowed, how about when you run it in gnome with fullscreen. Where you had a black screen wit awm?

**Comment by tsolar** [comment]
@jackeri black screens on GNOME and Awesome. 2.76 works as expected (runs only on one screen) on both

**Comment by A6GibKm** [comment]
I get the blackscreen issue after switching to fullscreen, deleting local configs defaults to windowed where it works.

**Comment by sigzegv** [comment]
I have same issue, ubuntu 20.04 + gnome, tested either 32 and 64 builds, game on windowed fullscreen displays on both monitors and I'm not able to change the window size in game. Fullscreen displays black screen. I'm launching game with `./etl +set r_fullscreen 0 +set r_mode -2`

**Comment by rafal1137** [comment]
About the Multiple Setup Monitors: 
Enjoy your code read:

https://github.com/etlegacy/etlegacy/blob/0de5209e63d24465fdf50341e99da9eadcc6ac0a/src/sdl/sdl_glimp.c#L407-L507

**Comment by isRyven** [comment]
> I have same issue, ubuntu 20.04 + gnome, tested either 32 and 64 builds, game on windowed fullscreen displays on both monitors and I'm not able to change the window size in game. Fullscreen displays black screen. I'm launching game with `./etl +set r_fullscreen 0 +set r_mode -2`

`./etl +set r_fullscreen 0 +set r_mode -1 +set r_customwidth 1920 +set r_customheight 1080`

**Comment by sigzegv** [comment]
> > I have same issue, ubuntu 20.04 + gnome, tested either 32 and 64 builds, game on windowed fullscreen displays on both monitors and I'm not able to change the window size in game. Fullscreen displays black screen. I'm launching game with `./etl +set r_fullscreen 0 +set r_mode -2`
> 
> `./etl +set r_fullscreen 0 +set r_mode -1 +set r_customwidth 1920 +set r_customheight 1080`

This way it opens correctly on one monitor, but it doesn't seems to take primary monitor as default.
As example my monitor number 2 (as reported by gnome screen settings) is the primary at +0+0, the monitor number 1 is at +1920+0, and the game pops there (of course I can move the window manually, but correct popup should be expected, or maybe game needs a var for monitor selection).

**Comment by mittermichal** [comment]
@sigzegv maybe adding `+set vid_xpos <number>` would change the monitor?

**Comment by isRyven** [comment]
the vid_x/ypos cvars were removed as far as i remember, but checking out the code snippet posted by rafal, i can see that there is `r_windowLocation` to replace these, and it also should accept the display index

**Comment by yakoub** [comment]
no one has a clue why this happening ?
instead you talk about `GLimp_WindowLocation` which is not relevant to the problem of blank screen at all and should be discussed in separate issue .

**Comment by rafal1137** [comment]
> 
> 
> no one has a clue why this happening ?
> instead you talk about `GLimp_WindowLocation` which is not relevant to the problem of blank screen at all and should be discussed in separate issue .

Scroll Up or just read it here:
https://github.com/libsdl-org/SDL/issues/4136

**Comment by yakoub** [comment]
> > no one has a clue why this happening ?
> > instead you talk about `GLimp_WindowLocation` which is not relevant to the problem of blank screen at all and should be discussed in separate issue .
> 
> Scroll Up or just read it here:
> [libsdl-org/SDL#4136](https://github.com/libsdl-org/SDL/issues/4136)

sorry but i didn't find any comment above that mentions : libsdl-org/SDL#4136
this indeed seems to explain the problem, but i don't see where it was mentioned before your comment .

**Comment by jackeri** [comment]
@tsolar could you please test the latest snapshot from here: https://www.etlegacy.com/workflow-files I did some changes to the build and on my ubuntu vm at least if fixed the issues.

**Comment by tsolar** [comment]
@jackeri yay! It works as expected!

**Comment by jackeri** [comment]
Excellent, I will close this now. We will be releasing a patch version in the upcoming days. Stay tuned!
