### ISSUE TITLE
Pushing other players through solid objects.

### ISSUE THREAD

**Issue by ryzyk-krzysiek** [etlegacy/etlegacy#1595]
You can push players through a small destroyable doors on supply.

https://www.youtube.com/watch?v=nXqZgcL2kNA

**Comment by rmarquis** [comment]
I think this is a map issue rather than something that can be fixed in the code. Someone knowledgeable might chippin' here.

**Comment by ryzyk-krzysiek** [comment]
I tested it in on map `adlernest` now and it's the same, but I guess what you are saying could still be true.

https://www.youtube.com/watch?v=TmTHVtsxcU4

**Comment by isRyven** [comment]
It's not map related. The issue exists for some time now (i did report it several times through out the years), probably similar to the "door opens in the wrong direction" bug.

**Comment by rmarquis** [comment]
Ah, another reported issue for years that never got a ticket in the tracker.

**Comment by Aranud** [comment]
Fixed with love. Can't figure where the code was added, but not a vanilla issues https://github.com/id-Software/Enemy-Territory/blob/40342a9e3690cb5b627a433d4d5cbf30e3c57698/src/game/g_cmds.c#L2807-L2846
