### ISSUE TITLE
ALT + TAB is broken in fullscreen mode

### ISSUE THREAD

**Issue by Aciz** [etlegacy/etlegacy#1597]
Alt + tab no longer seem to work when running with `r_fullscreen 1`. The game window stays maximized, and I can't see anything else on the screen the game is running on. I can move the cursor to my 2nd monitor after hitting alt + tab, but it disappears after a few seconds. Setting `r_fullscreen 0` makes alt + tab work again.

Edit: Window 10 Pro 20H2, Nvidia GTX 1080 Ti, 461.72 driver.

**Comment by pxsxs** [comment]
same problem in GNU/Linux. Keybinds outside etlegacy no longer work

**Comment by jackeri** [comment]
This should have been fixed on 7f4cb515f379e2b3707959302b020f2ba48f2f08
