### ISSUE TITLE
Linux ppc64le client unable to join any hosted game

### ISSUE THREAD

**Issue by runlevel5** [etlegacy/etlegacy#1598]
OS: Fedora 33 ppc64le
Compilation option:

```
cmake 		-DCMAKE_BUILD_TYPE=Release \
		-DCROSS_COMPILE32=0 \
		-DZIP_ONLY=0 \
		-DARM=0 \
		-DBUILD_SERVER=1 \
		-DBUILD_CLIENT=1 \
		-DBUILD_MOD=1 \
		-DBUILD_MOD_PK3=1 \
		-DBUNDLED_LIBS=0 \
		-DBUNDLED_SDL=0 \
		-DBUNDLED_ZLIB=0 \
		-DBUNDLED_MINIZIP=0 \
		-DBUNDLED_JPEG=0 \
		-DBUNDLED_CURL=0 \
		-DBUNDLED_WOLFSSL=0 \
		-DBUNDLED_OPENSSL=0 \
		-DBUNDLED_LUA=0 \
		-DBUNDLED_OGG_VORBIS=0 \
		-DBUNDLED_THEORA=0 \
		-DBUNDLED_OPENAL=0 \
		-DBUNDLED_GLEW=0 \
		-DBUNDLED_FREETYPE=0 \
		-DBUNDLED_PNG=0 \
		-DBUNDLED_SQLITE3=0 \
		-DFEATURE_CURL=1 \
		-DFEATURE_SSL=1 \
		-DFEATURE_OGG_VORBIS=1 \
		-DFEATURE_THEORA=1 \
		-DFEATURE_OPENAL=1 \
		-DFEATURE_FREETYPE=1 \
		-DFEATURE_PNG=1 \
		-DFEATURE_LUA=1 \
		-DFEATURE_MULTIVIEW=1 \
		-DFEATURE_EDV=1 \
		-DFEATURE_ANTICHEAT=1 \
		-DFEATURE_GETTEXT=1 \
		-DFEATURE_DBMS=1 \
		-DFEATURE_RATING=1 \
		-DFEATURE_PRESTIGE=1 \
		-DFEATURE_AUTOUPDATE=1 \
		-DFEATURE_RENDERER2=0 \
		-DFEATURE_RENDERER_GLES=0 \
		-DRENDERER_DYNAMIC=1 \
		-DFEATURE_LUASQL=1 \
		-DFEATURE_OMNIBOT=1 \
		-DINSTALL_EXTRA=1 \
		-DINSTALL_OMNIBOT=1 \
		-DINSTALL_GEOIP=1 \
		-DINSTALL_WOLFADMIN=1 \
		-DCMAKE_INSTALL_PREFIX=/home/runlevel5/etlegacy \
		-DINSTALL_DEFAULT_MODDIR=. \
		-DINSTALL_DEFAULT_BINDIR=. \
		-DINSTALL_DEFAULT_BASEDIR=. \
                ..
```

when I try to join a game hosted by my other computer (runs x86_64 etlegacy), I run into following error:

![Screenshot from 2021-03-01 23-56-13](https://user-images.githubusercontent.com/135605/109505242-81010700-7af0-11eb-80dd-879c25cdf941.png)

**Comment by rafal1137** [comment]
We do not support ppc64le / ppc64 at all.

**Comment by runlevel5** [comment]
@rafal1137 yes I am fully aware. I can confirm that ppc64/ppc64le are not compatible with other platform and the other way around.

**Comment by ensiform** [comment]
The server would require cgame and ui in the binary pk3 of the ppc architectures as well. Which is only likely on your self hosted.

**Comment by runlevel5** [comment]
> The server would require cgame and ui in the binary pk3 of the ppc architectures as well. Which is only likely on your self hosted.

Indeed, you are absolutely right. I guess there is not possible to join cross-platform server then..

**Comment by ensiform** [comment]
This is already the case with x86 and x86_64.

**Comment by runlevel5** [comment]
Does that mean arm64 port (for RPi) is not compatbile x86_64 server?

**Comment by ensiform** [comment]
It means all the platforms you want to support need to be available on the server in the pk3. Or run a sv_pure 0 server. The way it's always been since the source release of ET and RTCW.
