### ISSUE TITLE
Integrity Error: Assets MD5 checksum failed

### ISSUE THREAD

**Issue by kekk** [etlegacy/etlegacy#1600]
I decided to try the installer and during the installation process I received notification of Integrity Error: Assets MD5 checksum failed and when I press Retry it starts downloading WolfET.exe and everything else installs correctly.

I'm not sure what it means.

**Comment by fredericve** [comment]
Can confirm here as well. Had the same issue. Just clicking retry and it continued fine.

I had 2.76 installed previously if that's at all important.

**Comment by kaixiong** [comment]
I encountered the error as well. But worse for me is that I cannot connect to the TeamMuppet ETLegacy server. Connections fail with an invalid PK3 error even with a clean install. I am not sure if the two issues are related.

**Comment by sebdanielsson** [comment]
I also got the .pk3 error when trying to join a server. Seems like the installer only download pak0.pk3, and not pak1.pk3 and pak2.pk3 which are also required.

**Fix:**
1. Download [Wolfenstein: Enemy Territory](https://www.splashdamage.com/games/wolfenstein-enemy-territory/) from Splash Damage
2. Extract the .pk3 files from the **_etmain_** folder inside the **_WolfET_2_60b_custom.exe_** installer and copy them to `C:\Program Files (x86)\ETLegacy\etmain`

**Comment by kaixiong** [comment]
The files can be downloaded from [here](https://mirror.etlegacy.com/etmain/). I can confirm that adding pak1.pk3 and pak2.pk3 fixes the issue.

**Comment by jackeri** [comment]
The next patch has a working installer. Closing this.
