### ISSUE TITLE
Option to reposition HUD elements for ultra widescreens

### ISSUE THREAD

**Issue by kaixiong** [etlegacy/etlegacy#1603]
I play ETL on an 35-inch ultra-wide screen at 3440x1440 (21:9) and find it difficult to quickly read off crucial HUD information such as health, reinforcement timer, etc. as they are too far off to the screen corners. It would be nice to be able to move them towards the center. One solution is to relocate them to the corners of an imaginary 4:3 (or 16:9) box centered on the display.

**Comment by mittermichal** [comment]
hi,
Its bit tedious work, but you can customize HUD by editing `fs_homepath`/legacy/ui/huds.hud
I'm not sure if its created there upon installation but you can get it [here](https://github.com/etlegacy/etlegacy/blob/master/etmain/ui/huds.hud) too.
example:
![image](https://user-images.githubusercontent.com/4035800/109556698-725a2600-7ad7-11eb-983b-a6a677d65081.png)

**Comment by mittermichal** [comment]
you can switch to it with `/cg_altHud <hudnumber>`
when you are on legacy server you can reload the HUDs with `/readhuds`

**Comment by kaixiong** [comment]
Very nice. I will try tweaking the numbers.

**Comment by rmarquis** [comment]
Adding an extra hud for widescreen by default might be a good idea.

**Comment by kaixiong** [comment]
I managed to improve it by adding a custom HUD config, but it wouldn't get loaded when I connect to a public server.

The other limitation with this approach is that I cannot reposition the clock and reinforcement timer.

**Comment by mittermichal** [comment]
Which server?
Can you share the hud file?

**Comment by kaixiong** [comment]
Here is my configuration based on HUD number 3. Essentially, I move elements on the left and right corners 100 units towards the centre of the screen.

The file is located in `fs_homepath`/legacy/ui/huds.hud. It gets properly loaded when starting a game on localhost - this was what I used for preview when I adjusted the values.

The servers I tried it on were:
- TeamMuppet ETLegacy
- TeamMuppet ETLegacy 2
- ET:Legacy 2.77 DEV (Official)

```
hudDef {
	hud {
		//inside the hud element following keywords apply
		// except for the hud number which tells the cg_althud variable value
		// all the others work like the following 1st number: x 2: y 3: width 4: height 5: component style 6: visibility (boolean type)
		// as expected a single file can contain multiple hud configurations
		// hudnumber value must be unique, if not then the hud will be discarded
		// PS. 'x' should be between 0 and 640 and 'y' between 0 and 480
		hudnumber 11
		compas 144 400 90 90 0 1
		staminabar 104 388 12 72 0 1
		breathbar 104 388 12 72 0 1
		healthbar 504 388 12 75 0 1
		weaponchangebar 524 388 12 75 0 1
		healthtext 480 415 0 0 0 1
		xptext 128 476 0 0 0 1
		statsdisplay 124 385 0 0 1 1
		weaponicon 438 424 60 32 0 1
		weaponammo 498 470 0 0 0 1
		fireteam 400 10 100 100 0 1
		popupmessages 4 100 72 72 0 1
		powerups 500 340 36 36 0 1
		hudhead 44 388 62 80 0 0
		cursorhints 296 260 48 48 0 1
		weaponstability 50 208 10 64 0 1
		livesleft 0 0 0 0 0 1
		votetext 8 224 0.22 0.22 1 1
		spectatortext 8 188 0.22 0.22 1 1
		limbotext 8 164 0.22 0.22 1 1
		followtext 8 164 0.22 0.22 1 1
	}
}
```

**Comment by mittermichal** [comment]
sorry I gave you incorrect advice.
The custom HUD file gotta be in `legacy/hud.dat` either in homepath or basepath.
https://github.com/etlegacy/etlegacy/blob/f6c75c3d8426ac93693557bd90e7dc6794c44e9a/src/cgame/cg_draw_hud.c#L674

**Comment by kaixiong** [comment]
Thanks, I have tested this and can confirm it works. I did need to set `cg_altHudFlags` for the setting to apply for the various clocks/timers.

**Comment by rmarquis** [comment]
> Adding an extra hud for widescreen by default might be a good idea.

Actually, having a third official "alt hud" with compass and other info in the bottom middle of the screen would be welcome, even for non extra wide screens. It's also apparently quite common in custom huds, so having a basic option "ready to use" would be great. Chat can be moved to the side.
