### ISSUE TITLE
etjump falldamage bug

### ISSUE THREAD

**Issue by pierdolen** [etlegacy/etlegacy#1605]
I'm not 100% sure if this is a ET:L issue or etjump, but since I was unable to reproduce this using the original ET 2.60b client (and also no 2.60b users complained about this afaik, while some ET:L users shared with me stories of having the same issue), I'm more inclined to believe it's some issue within the ET:L client.

**Description:**
This bug only occurs when playing on remote server, I was unable to reproduce it locally.  When falling from a greater height, the game acts for a split second that falldamage was taken and resets the speed to zero only to go back to the previous value moments later [(small demonstration)](https://www.youtube.com/watch?v=LpbxKLmFqSc). [This](https://www.youtube.com/watch?v=EsM8RYv2qYQ) is how it should look instead (no fall damage is taken anywhere). 

The bug can be fixed by quitting to desktop and launching ET:L again (reconnect, vid_restart don't fix it), but it's still fairly annoying.

**Steps to reproduce:**
- Start a server with any map
- Connect to the server
- Change map to **[13jumps_b1](https://et.clan-etc.de/etmain/13jumps_b1.pk3)** while still connected (this happens on other maps as well, but I picked this one for reproducing since this bug occurred to me a lot on this map)
- The bug will now be present until restarting the game completely
- It may also occur randomly upon connecting to the server, although it seems to happen more inconsistently

**Motivation to fix:**
My friends will laugh at me less for using legacy, also will improve lives of etjump players who use ET:L

**Versions used:**
Mod - etjump 2.4.0
Client - current 2.77 legacy (fresh install), it's been present in previous versions as well though
Server - tried with original 2.60b and with etlded 2.77 (all fresh install)

**Comment by Aciz** [comment]
It appears that ETLegacy has no idea we have a `nofalldamage` worldspawn key. Checking with `cg_debugEvents`, ETLegacy is getting `EV_FALL_DMG_25` event, which causes prediction error (side note: probably occurs on localhost if you add ping with `cl_packetdelay`).

![](https://i.imgur.com/nUJDoDT.png)

2.60b shows no such event:

![](https://i.imgur.com/XZ1BG3j.png)

You can also notice that ETLegacy is getting `EV_FALL_SHORT` event, which should never happen with `nofalldamage`.

**Comment by Aciz** [comment]
There is also problems handling `nojumpdelay`, possibly other worldspawn keys as well https://streamable.com/0ogp3c

**Comment by Aranud** [comment]
https://github.com/etlegacy/etlegacy/commit/b17d759f8899758f80e2caf0ce475d623bfe8b52#diff-736cc079734a1f224318d472acb62f05045120dd3fdc3e4372baf06791d5b789R660-R668

Above commit cause the following warning :        

```
0 CL packet 78.47.112.41:27965: connectResponse
0 ^3WARNING: server is not allowed to set shared=17
```

The client prediction is wrong due to the badly set cvar `shared` containing information about `nofalldamage` and `nojumpdelay` conf

**Comment by Aranud** [comment]
The workaround did the job but the way its handled right now should probably change in the future though.

Close for now and fix it on legacy side on new etjump release.
