### ISSUE TITLE
[v2.77] Lua 5.4 issues

### ISSUE THREAD

**Issue by hbokh** [etlegacy/etlegacy#1606]
With the new Lua 5.4 API, I encounter multiple issues.

For example for "WolfAdmin", the "spree announcements" seem to be broken.
From the `etconsole.log` I get this specific LUA error:

```
$ cat /srv/et/etpub1/legacy/etconsole.log | grep wolf
       0     /srv/et/etpub1/legacy/wolfadmin_1.2.0.pk3 (26 files)
       0 Lua 5.4 API: ^$file 'luascripts/wolfadmin/main.lua' loaded into Lua VM
       0 Lua 5.4 API: ^$et_InitGame error running lua script: '/srv/et/etbin/legacy/luascripts/wolfadmin/game/sprees.lua:123: bad argument #1 to 'find' (string expected, got nil)'
```

File `/srv/et/etbin/legacy/luascripts/wolfadmin/game/sprees.lua` is from WolfAdmin v1.2.1 (14 April 2020).

And another issue with the widely used script `announcehp.lua`:

```
346300 Lua 5.4 API: ^$et_Obituary error running lua script: '[string "lua/announcehp.lua"]:11: tried to get invalid gentity field "sess.sessionTeam"'
```

They used to work with Lua 5.3 API in v2.76.

**Comment by rafal1137** [comment]
> With the new Lua 5.4 API, I encounter multiple issues.
> 
> For example for "WolfAdmin", the "spree announcements" seem to be broken.
> From the `etconsole.log` I get this specific LUA error:
> 
> ```
> $ cat /srv/et/etpub1/legacy/etconsole.log | grep wolf
>        0     /srv/et/etpub1/legacy/wolfadmin_1.2.0.pk3 (26 files)
>        0 Lua 5.4 API: ^$file 'luascripts/wolfadmin/main.lua' loaded into Lua VM
>        0 Lua 5.4 API: ^$et_InitGame error running lua script: '/srv/et/etbin/legacy/luascripts/wolfadmin/game/sprees.lua:123: bad argument #1 to 'find' (string expected, got nil)'
> ```
> 
> File `/srv/et/etbin/legacy/luascripts/wolfadmin/game/sprees.lua` is from WolfAdmin v1.2.1 (14 April 2020).

With that one nothing can be done on our side. You should contact wolfadmin dev instead.

PS: We have fork of that repo but sprees were removed:
https://github.com/etlegacy/wolfadmin/commit/8eb29aca14f7e229775991379710050995af2967

**Comment by rmarquis** [comment]
Sprees has been buggy for a long time. The fork delivered with ETL installer (see [repo](https://github.com/etlegacy/wolfadmin)) indeed doesn't have that feature.

**Comment by hbokh** [comment]
¯\_(ツ)_/¯ 
Ping @timosmit

**Comment by hbokh** [comment]
I know this is closed, but for folks looking for a still working killing spree LUA script use the "official" one from here: https://github.com/etlegacy/etlegacy-lua-scripts/blob/master/killing-spree/killing-spree.lua

If you adapt the paths to use the WAV-files from `wolfadmin_1.2.0.pk3`, replace all the lines containing `misc` with `spree` - and `realpotter.wav` with `potter.wav`:

```diff
<         sound = "/sound/misc/realpotter.wav",
---
>         sound = "/sound/spree/potter.wav",
```
