### ISSUE TITLE
Can't change spawn time when hosting a server

### ISSUE THREAD

**Issue by terrachild** [etlegacy/etlegacy#1610]
2.77 isn't letting me change the spawn times when I host a server.
It defaults to the map setting.
I could do that on 2.76

**Comment by Aciz** [comment]
Do you have a config loaded? I am not sure how it was in 2.76, but in 2.77, all config files except `defaultcomp.config` set their own `g_userAxis/AlliedRespawnTime` values.

**Comment by terrachild** [comment]
When you 'Host Game' you can click on the "Advanced" button and set the spawn times to whatever you want, but in 2.77 they seem to be ignored there.  Why?

**Comment by PanzerMad** [comment]
Add this to your etl_server.cfg

```
set g_useraxisrespawntime "11"                  // Axis Respawn time
set g_useralliedrespawntime "11"                // Allied Respawn time
```

**Comment by terrachild** [comment]
I'll try that for now, but my group changes these settings all the time as a type of handicap for a well-playing team. So the 'Advanced' screen settings should work for ease of use.  Not sure why they worked in 2.76, but don't n 2.77.

**Comment by Aciz** [comment]
> When you 'Host Game' you can click on the "Advanced" button and set the spawn times to whatever you want, but in 2.77 they seem to be ignored there. Why?

I just tested this and it does work fine. I asked you already if you have a server config loaded when hosting but you never replied. When using `Host Game` menu, make sure this is set to `No` 

![image](https://user-images.githubusercontent.com/14221121/110904089-1a11f800-8311-11eb-82bf-d3c89672d7f1.png)

The `g_userAxis/AlliedRespawnTime` cvars are set by configs shipped with legacy mod, and they override any spawntimes you set yourself, if these configs are loaded.

**Comment by terrachild** [comment]
I never had to pay attention to "Auto-Configure Server" when changing these settings with previous versions.
Maybe that setting is new somehow with 2.77.
Whatever changed, you are correct, it does work if you set that to "No"

Thanks,

Chris
