### ISSUE TITLE
libOpenGL.so.0

### ISSUE THREAD

**Issue by 0xA1B2** [etlegacy/etlegacy#1614]
On Intel's Clear Linux ET:Legacy 2.77 (32-Bit) does not work, however 2.76 did work just fine. I use a Lenovo X250, with Intel Broadwell CPU, no dedicated GPU, just Intel GPU from the CPU.

There is no package to install for libOpenGL.so.0 in Clear Linux, as its not part of the distro.

admin@x250~/Downloads/etlegacy-v2.77-i386 $ ./etl
       0 ^2ET Legacy v2.77 linux-i386 Mar  1 2021
       0 Zone megs: 64
       0 INFO: fs_game now defaults to 'legacy' mod instead of 'etmain'
       0 ----- Initializing Filesystem --
       0 Current working directory:
       0     /home/admin/Downloads/etlegacy-v2.77-i386
       0 Current search path:
       0     /home/admin/.etlegacy/legacy
       0     ./legacy
       0     ./legacy/legacy_v2.77.pk3 (1328 files)
       0     /home/admin/.etlegacy/etmain
       0     ./etmain
       0     ./etmain/pak2.pk3 (22 files)
       0     ./etmain/pak1.pk3 (10 files)
       0     ./etmain/pak0.pk3 (3725 files)
       0 
       0 5085 files in pk3 files
       0 --------------------------------
       0 ----- Database Initialization --
       0 SQLite3 libversion 3.32.1 - database URI 'etl.db' - in file
       0 ... loading existing database '/home/admin/.etlegacy/etl.db'
       0 ... database file '/home/admin/.etlegacy/etl.db' loaded
       0 SQLite3 ETL: database init #2 /home/admin/.etlegacy/etl.db in [0] ms - autocommit 1
       0 SQLite3 ETL: DB schema version #2 is up to date
       0 --------------------------------
       0 execing default.cfg
       0 couldn't exec etconfig.cfg
       0 couldn't exec autoexec.cfg
       0 Hunk_Clear: reset the hunk ok
       0 Not logging server attacks to disk
       0 ----- Client Initialization ----
       0 Trying to load "librenderer_opengl1_i386.so" from "."...
       0 Loading "librenderer_opengl1_i386.so" failed
       0 failed:
"libOpenGL.so.0: cannot open shared object file: No such file or directory"
       0 ----- Client Shutdown ----------
       0 --------------------------------
       0 SQLite3 database closed.
Failed to load renderer lib
       0 Sys_Exit warning - PID file doesn't exist /home/admin/.etlegacy/legacy/profiles//profile.pid

**Comment by rafal1137** [comment]
This how things goes. You can either download missing lib or use latest snapshot that is using mesa GL instead of opengl.

**Comment by jackeri** [comment]
This was actually "reverted" back to the original, so now the future releases will link against libGL instead of libOpenGL. See: 076c370e0e1734f23ebf94059f3ad8ba082369cb
