### ISSUE TITLE
Airstrikes deals damage inside closed building

### ISSUE THREAD

**Issue by Helldembez** [etlegacy/etlegacy#1617]
**Description of the issue (current behavior, expected/desired behavior)**
While playing supply flag stage as axis, two of us got killed from an airstrike while being inside the bunker on the stairs. This should not happen. Could be a map design issue, but it doesn't happen on ET. Desired is to not get damage from outside while inside. Partial arty shells hitting inside through window or door openings is normal.

**Minimal steps to reproduce the problem**
Not sure how to reproduce this. But try to watch the demo and reconstruct the scenario from that. Throw airstrike near bunker in a way that it hits the inside part where people can stand. Watch the demo when 8:25 left on the clock.
[2021-03-09-225447-supply.zip](https://github.com/etlegacy/etlegacy/files/6126310/2021-03-09-225447-supply.zip)

**Motivation and use case for changing the behavior (if relevant)**
For a better gameplay experience of not dying through unintended game mechanics

**Version used, and behaviour on older versions (if relevant)**
v2.77, ET legacy mod. 

Let me know if more testing is required. I'll try to help where I can.

**Comment by rmarquis** [comment]
Possibly related or duplicate: #817, #1328
