### ISSUE TITLE
Omni-bot commands should not be in legacy.cfg

### ISSUE THREAD

**Issue by peninha** [etlegacy/etlegacy#1620]
The omni-bot commands inside legacy.cfg (bot difficulty "3"; bot moveskill "4"; bot minbots "-1"; bot maxbots "16"; bot balanceteams "1") don't get executed because the module omni-bot is not loaded yet.
Although it doesn't crash or cause any side-effects, it's misleading. Someone trying to modify these parameters wouldn't get any result.

**Comment by rafal1137** [comment]
Those commands have been removed. Closing
