### ISSUE TITLE
Installer issue: Assets MD5 checksum failed

### ISSUE THREAD

**Issue by HeDo88TH** [etlegacy/etlegacy#1621]
Installing on Windows 10 Pro 20H2 19042.867 x64 asking to download ET assets:

![setup-error](https://user-images.githubusercontent.com/7868983/111146458-c1995f80-8589-11eb-895e-0807b87da501.png)

**Comment by rafal1137** [comment]
Click Retry.
After installation download pak1-2 from https://mirror.etlegacy.com/etmain/ and put them beside pak0.pk3

You can also download latest snapshot from https://www.etlegacy.com/workflow-files that has this issue fixed or wait for next release soonish(TM).

Closing.
