### ISSUE TITLE
Adrenaline animation/usage is broken

### ISSUE THREAD

**Issue by Aciz** [etlegacy/etlegacy#1634]
Using adrenaline in legacy is broken in several ways.

* There is no usage animation, the syringe will just disappears. In etmain, you see yourself injecting the syringe.
* After using, weapon is autoswitched (though I think this is made intentionally looking at previous commits)
* Swapping back to adrenaline once it's been used seemingly tries to play the injection animation again

https://streamable.com/jq22tm

**Comment by rmarquis** [comment]
> After using, weapon is autoswitched (though I think this is made intentionally looking at previous commits)

Intentional yes. This is done for a couple of "weapon" such as smoke grenade.
The rest seems like a regression, it shouldn't be hard to backtrack to it.

**Comment by Aciz** [comment]
Probably a regression from 870d49756be67a5f6d4713e60375f79ccb89d242
