### ISSUE TITLE
French localization Display / Translation issue

### ISSUE THREAD

**Issue by DarkinMan** [etlegacy/etlegacy#1638]
There's a display and translation issue on the exit game context menu, as shown on the image.

![Display Issue](https://user-images.githubusercontent.com/82531098/114745971-82f4f180-9d4f-11eb-9c6e-fefe2864266e.png)

And because the translation isn't correct, I'd suggest to replace it with "Mouais, c'est ça, comme si tu avais mieux à faire !".

**Comment by rmarquis** [comment]
Translation are community provided. You can help fix translation issues at https://www.transifex.com/etlegacy/etlegacy
