### ISSUE TITLE
Extended setspawnpt implementation to allow selection of exact spawn slot per location

### ISSUE THREAD

**Issue by realkemon** [etlegacy/etlegacy#1641]
This ticket is based on a discussion we had on Discord.
Dersaidin gave the spawns in his maps *(at least Adlernest and Bremen)* unique `id` key-value pairs.
It seems like that is entirely useless, but would actually prove to be a very useful feature.

**Background:**
Apparently, changing `setspawnpnt` magically gives the ability to manipulate the exact spawnslot selection within a spawn location. For example, according to Kimi `setspawnpnt 2` on Adlernest spawns Axis players closer to the stairs and Allies a bit closer to the spawn exit. According to Aciz, `setspawnpnt 2` spawns the player on the East side of the train on Special Delivery rather than the default West side. There is seemingly no trace in the mapping process or any map files that would allow the intentional alteration by the mapper and it's, therefore, not possible to replicate spawn behaviour of the original maps in the overhauls.

**Proposal:**
For that reason we came up with this potential feature.
Add support for a new key-value pair `id` for `team_CTF_redspawn` and `team_CTF_bluespawn` entities. Through this pair, each spawn slot could be uniquely identified, which would allow the players to target individual spawn slots at a given spawn location through a cfg. This would be a much more transparent and logical implementation compared to the currently highly arbitrary `setspawnpnt` behaviour, at least for the official ET: Legacy overhauls (and any future map using it).

Aciz proposed extending the current `setspawnpnt` syntax to `setspawnpt <major spawnpoint> <minor spawnpoint>`. Major spawnpoint corresponds to the actual spawn location and minor spawnpoint represents an exact spawn slot within that location.
Currently, no solution has been discussed for when multiple players choose the same <minor spawnpoint>, but possibly use nearest unoccupied spawn slot by origin distance?

Supporting this in the official map overhauls is no hassle whatsoever!
![image](https://user-images.githubusercontent.com/8881420/116924804-a4634200-ac58-11eb-9953-5497888d3a69.png)

**Comment by hazz1nen** [comment]
Currently the way the spawn points are numbered is dependent on the order in which `team_WOLF_objective` entities appear in the .map file before compiling it. It's obscure and difficult to use for a mapper. It would be better to just give mappers a way to number those by giving them an `id` key too.

> Aciz proposed extending the current `setspawnpnt` syntax to `setspawnpt <major spawnpoint> <minor spawnpoint>.`

The way this would behave then would be `setspawnpt <id in team_WOLF_objective> <id in team_CTF_red/bluespawn>`.

Some concerns:
 - fall back to default behaviour if no `id` values are assigned
 - give out error when `id` values for some but not all `team_WOLF_objective` entities are assigned
 - `id` is a generic keyword and has already been used in at least Dersaidin's maps, might break
