### ISSUE TITLE
Do not write for a few seconds of the interruption.

### ISSUE THREAD

**Issue by Linuxy95** [etlegacy/etlegacy#1646]
You can't enter anything for the first few seconds of the interruption.

Can you please fix the problem?

**Comment by Linuxy95** [comment]
sv_floodProtect

**Comment by rmarquis** [comment]
I guess sv_floodProtect was the root of the issue, thus considering it fixed.

**Comment by Linuxy95** [comment]
Have you also fixed the problem?
