### ISSUE TITLE
System wide installation directories on Linux

### ISSUE THREAD

**Issue by pemensik** [etlegacy/etlegacy#1648]
I am trying to prepare native etlegacy package for Fedora (https://github.com/pemensik/etlegacy/blob/fedora/etlegacy.spec).

Now with 2.77.1, I am confused how default paths should be set. I tried using -DINSTALL_DEFAULT_BASEDIR=/usr, which kind of installed starters to correct location. But when I tried running etl outside game directory, it failed to start.

```
$ etlegacy 
       0 ^2ET Legacy 2.77-dirty linux-i386 Nov  2 2020
       0 Zone megs: 64
       0 INFO: fs_game now defaults to 'legacy' mod instead of 'etmain'
       0 ----- Initializing Filesystem --
       0 Current working directory:
       0     /home/pemensik/
       0 Current search path:
       0     /home/pemensik/.etlegacy/legacy
       0     /usr/legacy
       0     /usr/legacy/legacy_v2.77.1.pk3 (1329 files)
       0     /home/pemensik/.etlegacy/etmain
       0     /home/pemensik/.etlegacy/etmain/mp_bin.pk3 (6 files)
       0     /usr/etmain
       0     /usr/etmain/rhbptb.pk3 (16 files)
       0     /usr/etmain/pak2.pk3 (22 files)
       0     /usr/etmain/pak1.pk3 (10 files)
       0     /usr/etmain/pak0.pk3 (3725 files)
       0     /usr/etmain/mp_bin.pk3 (6 files)
       0 
       0 5114 files in pk3 files
       0 --------------------------------
       0 Creating PID file 'profiles/pemensik/profile.pid'
       0 ----- Database Initialization --
       0 SQLite3 libversion 3.34.0 - database URI 'etl.db' - in file
       0 ... loading existing database '/home/pemensik/.etlegacy/etl.db'
       0 ... database file '/home/pemensik/.etlegacy/etl.db' loaded
       0 SQLite3 ETL: database init #2 /home/pemensik/.etlegacy/etl.db in [1] ms - autocommit 1
       0 SQLite3 ETL: DB schema version #2 is up to date
       0 --------------------------------
       0 execing default.cfg
       0 execing profiles/pemensik/etconfig.cfg
       0 couldn't exec autoexec.cfg
       0 Hunk_Clear: reset the hunk ok
       0 Not logging server attacks to disk
       0 ----- Client Initialization ----
       0 Trying to load "librenderer_opengl1_i386.so" from "."...
       0 Trying to load "librenderer_opengl1_i386.so" from "/usr"...
       0 Loading "librenderer_opengl1_i386.so" failed
       0 failed:
"/usr/librenderer_opengl1_i386.so: cannot open shared object file: No such file or directory"
       0 ----- Client Shutdown ----------
       0 --------------------------------
       0 PID file removed.
       0 SQLite3 database closed.
Failed to load renderer lib
       0 Sys_Exit warning - PID file doesn't exist /home/pemensik/.etlegacy/legacy/profiles/pemensik/profile.pid
```

Because renderer is installed by make install into INSTALL_DEFAULT_MODDIR, I think fs_basedir should be initialized to it too. Or maybe better, any extension dlls should search some build-time set path. On tradditional linux distribution, it would be somewhere under */usr/lib*. On Fedora x86_64 builds should put libraries to */usr/lib64/etlegacy*. But pak3 files should belong to */usr/share* I think, as they are usually just game data archives, not executable code (with few exceptions?).

I haven't found a way to configure paths on current release. INSTALL_DEFAULT_BASEDIR is used to install also laucher into /usr/share/applications etc. To have working lauchner, it has to be pointing to /usr. But renderer detection does not work with this setting. I think INSTALL_DEFAULT_SHAREDIR should be made instead of BASEDIR to be able change location of startup icons. But -DDEFAULT_BASEDIR=\"${INSTALL_DEFAULT_MODDIR}\" would make more sense in cmake/ETLCommon.cmake.

**Comment by rmarquis** [comment]
Have you had a look at the [Packaging](https://github.com/etlegacy/etlegacy/wiki/Packaging) instructions?
I'd also recommend looking at the Arch Linux [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=etlegacy) so you'll get an idea how it's been done there.

Do note ETLegacy is difficult to package as you might want to provide the 32 bit version to ensure backward compatibility with existing mods (yes, that is a nightmare on modern Linux distribution). You'll see a 32 bit version on AUR [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=etlegacy32).

**Comment by rmarquis** [comment]
See also #1622 for a Flathub version.

**Comment by pemensik** [comment]
Thanks for a quick reply. Checked instructions, but it seems they do not work well on version 2.77.1.

```
%cmake -DBUNDLED_LIBS=OFF -DCROSS_COMPILE32=OFF -DBUILD_MOD=OFF \
       -DFEATURE_RENDERER2=ON -DINSTALL_DEFAULT_BASEDIR=%{_libdir}/%{name} \
       -DINSTALL_DEFAULT_MODDIR=%{_libdir}/%{name}

...
-- Install configuration: "Release"
-- Installing: /builddir/build/BUILDROOT/etlegacy-2.77.1-1.fc32.i386/usr/lib/etlegacy/librenderer_opengl1_i386.so
-- Installing: /builddir/build/BUILDROOT/etlegacy-2.77.1-1.fc32.i386/usr/lib/etlegacy/librenderer_opengl2_i386.so
-- Installing: /builddir/build/BUILDROOT/etlegacy-2.77.1-1.fc32.i386/usr/bin/etl
-- Installing: /builddir/build/BUILDROOT/etlegacy-2.77.1-1.fc32.i386/usr/bin/etlded
-- Installing: /builddir/build/BUILDROOT/etlegacy-2.77.1-1.fc32.i386/usr/lib/etlegacy/legacy/description.txt
-- Installing: /builddir/build/BUILDROOT/etlegacy-2.77.1-1.fc32.i386/usr/lib/etlegacy/etmain
-- Installing: /builddir/build/BUILDROOT/etlegacy-2.77.1-1.fc32.i386/usr/lib/etlegacy/etmain/legacy.cfg
-- Installing: /builddir/build/BUILDROOT/etlegacy-2.77.1-1.fc32.i386/usr/lib/etlegacy/etmain/mapvoteplayerscount.cfg
-- Installing: /builddir/build/BUILDROOT/etlegacy-2.77.1-1.fc32.i386/usr/lib/etlegacy/etmain/mapvotecycle.cfg
-- Installing: /builddir/build/BUILDROOT/etlegacy-2.77.1-1.fc32.i386/usr/lib/etlegacy/etmain/etl_server.cfg
-- Installing: /builddir/build/BUILDROOT/etlegacy-2.77.1-1.fc32.i386/usr/lib/etlegacy/etmain/lmscycle.cfg
-- Installing: /builddir/build/BUILDROOT/etlegacy-2.77.1-1.fc32.i386/usr/lib/etlegacy/etmain/objectivecycle.cfg
-- Installing: /builddir/build/BUILDROOT/etlegacy-2.77.1-1.fc32.i386/usr/lib/etlegacy/etmain/campaigncycle.cfg
-- Installing: /builddir/build/BUILDROOT/etlegacy-2.77.1-1.fc32.i386/usr/lib/etlegacy/etl_bot.sh
-- Installing: /builddir/build/BUILDROOT/etlegacy-2.77.1-1.fc32.i386/usr/lib/etlegacy/etlded_bot.sh
-- Installing: /builddir/build/BUILDROOT/etlegacy-2.77.1-1.fc32.i386/usr/lib/etlegacy/share/icons/hicolor/scalable/apps/etl.svg
-- Installing: /builddir/build/BUILDROOT/etlegacy-2.77.1-1.fc32.i386/usr/lib/etlegacy/share/applications/com.etlegacy.ETLegacy.desktop
-- Installing: /builddir/build/BUILDROOT/etlegacy-2.77.1-1.fc32.i386/usr/lib/etlegacy/share/mime/packages/etlegacy.xml
-- Installing: /builddir/build/BUILDROOT/etlegacy-2.77.1-1.fc32.i386/usr/lib/etlegacy/share/metainfo/com.etlegacy.ETLegacy.metainfo.xml
-- Installing: /builddir/build/BUILDROOT/etlegacy-2.77.1-1.fc32.i386/usr/lib/etlegacy/share/man/man6
-- Installing: /builddir/build/BUILDROOT/etlegacy-2.77.1-1.fc32.i386/usr/lib/etlegacy/share/man/man6/etl.6
-- Installing: /builddir/build/BUILDROOT/etlegacy-2.77.1-1.fc32.i386/usr/lib/etlegacy/share/man/man6/etlded.6
-- Installing: /builddir/build/BUILDROOT/etlegacy-2.77.1-1.fc32.i386/usr/lib/etlegacy/INSTALL.txt
-- Installing: /builddir/build/BUILDROOT/etlegacy-2.77.1-1.fc32.i386/usr/lib/etlegacy/COPYING.txt
```

Note startup icon and launcher is installed to path ``/usr/lib/etlegacy/share/applications/com.etlegacy.ETLegacy.desktop``, which does not seem correct. Arch Package is built on older version. But only with this setting it would search game files under ``/usr/lib/etlegacy`` as described by documents you pointed me to.

When I used 
 ``-DINSTALL_DEFAULT_BASEDIR=%{_prefix}  -DINSTALL_DEFAULT_MODDIR=%{_libdir}/%{name}``, files were installed to correct destination. But it then searches for both game data and renderer plugins in /usr. It seems any way some part of installation needs fixing.

I were able to get described behaviour by moving share directory to expected location manually:
``mv %{buildroot}%{_libdir}/%{name}/share %{buildroot}%{_datadir}`` with configuration like on the start.

**Comment by rmarquis** [comment]
Ah, interesting.

The 32 bit version of the Arch PKGBUILD above is built for the latest 2.77.1 version. In addition you can see the most recent git version [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=etlegacy-git).
There are [a few attempts](https://build.opensuse.org/search?search_text=etlegacy) for openSUSE in their build service, that might be worth a look (RPMBUILD syntax is quite similar to Fedora's).

**Comment by rmarquis** [comment]
A new path variable needs to be added in `cmake/ETLCommon.cmake` and code adjusted in `cmake/ETLInstall.cmake`.
PR welcome.

**Comment by rmarquis** [comment]
The variable `INSTALL_DEFAULT_SHAREDIR` has been introduced. It should ease Linux system-wide installation of extra files (mime, doc, icons, licenses, ...).

However, the original W:ET assets are still required to be in hardcoded (at compile time) `fs_basepath` where the game lib resides. I don't think it is worth the complexity to somehow split this variable to allow both `/usr/lib/etlegacy` and '/usr/share' for the game files, so I'd keep it as it is.

As an easy workaround, it is possible to use symlinks in the package, so you can still properly put data assets in `/usr/share`. This is what is done in the Arch Linux packaging:

> ln -s /usr/share/enemy-territory/etmain/{pak0,pak1,pak2}.pk3 /usr/lib/etlegacy/etmain/

Closing now.
