### ISSUE TITLE
Move Freenode IRC channel to Libera.chat

### ISSUE THREAD

**Issue by rmarquis** [etlegacy/etlegacy#1655]
This isn't any critical in any way, as the main live discussion has been happening on Discord for quite a while, but this might be a point to be discussed.

The past few days have been quite rough for the Freenode IRC network, and without entering into all the details, many of the Freenode volunteer staff has resigned following what seems to be a hostile takeover from a third party.

We can however still consider this is a major turning point in the history of the Freenode network that will never been the same, and an alternative built from the old staff is emerging.

Several networks involved in Free and Open Source Software have already migrated, including the closely related `ioquake3` (see [ioquake3 IRC moved to Libera](https://ioquake3.org/ioquake3/ioquake3-irc-moved-to-libera/)).

While we don't have all the detail yet, I'd suggest considering the possibility of doing the same.
* move the Freenode IRC channel to Libera, and adjusting the bridge bot
* alternatively, close down the Freenode channel without replacement. Most users - and most potential contributors - now are using discord, so Freenode has little value nowadays.

I'd prefer the first option, but I am very little involved in live discussion nowadays. Thoughts and suggestion?

**Comment by isRyven** [comment]
Well,
1. The Libera project is too new to consider stability-wise.
2. Everyone switching the networks smells like a yet another hype train.
3. Freenode will keep functioning providing service, so why bother?
4. I am not an IRC user, my opinion doesn't really matter.

**Comment by Aranud** [comment]
Snowflake matter

**Comment by rmarquis** [comment]
A few points:
* major channels from FOSS communities migrated (to name a few: Arch Linux, Ubuntu, MediaWiki...). These are not coming back.
* Freenode used to be synonymous with FOSS communities. This is now questionable.
* The advantage of using the network of FOSS communities (especially of sister projects like ioquake or unvanquished) is to make it easier to contact members of various team. Yes, that is not really relevant anymore in the Discord era but used to be the case.
* I am not using IRC actively anymore, at least for etlegacy. My opinion doesn't really matter either, but if I have to connect to IRC, I see little reason to connect to Freenode considering the above.
* Actually, my opinion really doesn't matter. Consider this ticket as a heads up, but no urgent decision or decision at all is necessary.

**Comment by rmarquis** [comment]
Well apparently a new channel has been already registered on Libera by morsik. Just need to close down the one on Freenode then.

**Comment by isRyven** [comment]
Ah yes good old democracy :D

**Comment by rmarquis** [comment]
Reference to freenode have now been adjusted to Libera, in code and on the website.
I'll let @belst and @morsik handle the bridge bot and the old channel, if necessary.

**Comment by morsik** [comment]
@isRyven I totally agree this is not democratic at all (although, I asked question about this on our Discord and no one had any objections about this; also - I didn't merged this intentionally, just approved for "non-democratic argument" reason, but whatever…)

Looking for what happened with FreeNode and how FreeNode staff behaved last week, It's pretty dangerous using FreeNode still. Taking over channels just because someone wrote in topic "Libera.Chat" is not normal and not good for community.

And I agree, Libera.Chat may be not the best place. Personally I think, FOSS shouldn't move to Libera, as it was created by people in conflict with FreeNode, but well… it'll be just easier for everyone to meet us there like any other FOSS project. And that's also reason why I just registered channel on Libera, and didn't forced anyone to move in the first place - to do some discussion first.

**Comment by isRyven** [comment]
Thanks for the input!

**Comment by morsik** [comment]
@isRyven well… apparently now you have no arguments anymore :) https://www.devever.net/~hl/freenode_suicide

**Comment by isRyven** [comment]
Well, my 3rd argument still holds, the service is still available. Nothing prevents you from registering a new etlegacy channel, until someone else does that, to keep the control.

**Comment by morsik** [comment]
> Nothing prevents you from registering a new etlegacy channel, until someone else does that, to keep the control.

completly not true, as many people has autoreconnect enabled and it's impossible to register channel when someone already joined ;)

And when new IRCd server it's even less possible, as there is cache for channel - and even leaving channel doesn't make it free anymore.
