### ISSUE TITLE
Add a setting for permanent map toggle

### ISSUE THREAD

**Issue by dpierangeli** [etlegacy/etlegacy#1656]
On default keybind one 'g' toggles the map during play.

On new maps i found myself to keep g pressed a lot of time to watch the map.

I'd like an option to use the map button as a toggle without the need of the pression.

Press - show map
Press - hide map

**Comment by Aciz** [comment]
You can do this with a script.

```
set mapOpen "+mapexpand; set mapToggle vstr mapClose"
set mapClose "-mapexpand; set mapToggle vstr mapOpen"
set mapToggle "vstr mapOpen"
bind G "vstr mapToggle"
```

**Comment by rmarquis** [comment]
Sounds like a very user specific need that is easily met with a script. I don't think the feature is needed as a standard feature, so closing now.
