### ISSUE TITLE
Snapshot Build testing positive for Malware

### ISSUE THREAD

**Issue by SharpestTool** [etlegacy/etlegacy#1670]
Windows Defender getting hits on the most recent snapshot build for the Wacatac.B!ML trojan...

Snapshot Download URL: 
https://www.etlegacy.com/workflow-files/dl/26242aae34ffcbc2e2ea499aae644b7f44667a3a/win32/etlegacy-v2.77.1-375-g26242aa-x86.zip

![image](https://user-images.githubusercontent.com/11582695/124797319-c064b780-df17-11eb-89ff-47c6a8ffbbe8.png)

**Comment by rmarquis** [comment]
It's obviously a false positive due to heuristic detection, and nothing we can do but [report it](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-false-positives-negatives) to MS.

Closing.
