### ISSUE TITLE
Apple M1 native arm64 binaries

### ISSUE THREAD

**Issue by 0xA1B2** [etlegacy/etlegacy#1690]
Please support the Apple M1 natively :)

**Comment by ensiform** [comment]
That would be ideal, but there are no builders available on GitHub Actions to freely use which are running on Apple Silicon hardware. I believe cross compiling is somewhat possible, but a nightmare with varying libs needing to be supported and may not be able to fully compile and link against those under x86_64 host.

**Comment by jackeri** [comment]
I was finally able to compile universal binaries of ETL today, trying to get it tested before the next release.
![image](https://user-images.githubusercontent.com/2070060/145306492-34920491-165c-4f35-8ed0-6bbc424686b7.png)

**Comment by jackeri** [comment]
The latest snapshots now have universal bin mac packages (x86_64 & arm64).
https://www.etlegacy.com/workflow-files
I'm closing this as done, if you have issues then reopen.

**Comment by sebdanielsson** [comment]
> The latest snapshots now have universal bin mac packages (x86_64 & arm64).
> https://www.etlegacy.com/workflow-files
> I'm closing this as done, if you have issues then reopen.

Just tried to open ETL 2.81.1 without Rosetta but it crashes. Is there an issue to track which dependencies that are still not fixed?

**Comment by jackeri** [comment]
I am running the 2.81.1 on my m1 without any issues. Could you provide some sort of terminal output of the crash and otool -L output on the binary you are trying to run.

**Comment by sebdanielsson** [comment]
Interesting. I deleted the whole directory from /Applications and ran the installer again and now it works without issues. Sorry for bothering!😃
