### ISSUE TITLE
etlegacy 2.77.1: Build error: 'clientInfo_t' {aka 'struct clientInfo_s'} has no member named 'weaponState'

### ISSUE THREAD

**Issue by Kieltux** [etlegacy/etlegacy#1697]
Hello,
 I try to update the openSUSE etlegacy package in the games repository, but I can't compile the etlegacy release 2.77.1:

```
[   49s] /home/abuild/rpmbuild/BUILD/etlegacy-2.77.1/src/cgame/cg_players.c: In function 'CG_Player':
[   49s] /home/abuild/rpmbuild/BUILD/etlegacy-2.77.1/src/cgame/cg_players.c:3100:69: error: 'clientInfo_t' {aka 'struct clientInfo_s'} has no member named 'weaponState'
[   49s]  3100 |                     && (cgs.clientinfo[cent->currentState.clientNum].weaponState == WSTATE_IDLE)
[   49s]       |                                                                     ^
[   49s] make[2]: *** [CMakeFiles/cgame.mp.i386.dir/build.make:440: CMakeFiles/cgame.mp.i386.dir/src/cgame/cg_players.c.o] Error 1
[   49s] make[1]: *** [CMakeFiles/Makefile2:284: CMakeFiles/cgame.mp.i386.dir/all] Error 2
[   49s] make[1]: *** Waiting for unfinished jobs....
```
[Full build log for openSUSE Tumbleweed](https://build.opensuse.org/package/live_build_log/home:Kieltux:branches:games/etlegacy/openSUSE_Tumbleweed/i586)

I get the same error message, when I try to build etlegacy for openSUSE 15.2 and 15.3.

How can I fix this? Thank you.

**Comment by rmarquis** [comment]
As per `clientInfo_t` definition in `in cg_local.c`, `weaponState` is dependent on `FEATURE_MULTIVIEW` being enabled (which it is by default).

```
#ifdef FEATURE_MULTIVIEW
	// per client MV ps info
	int ammo;
	int ammoclip;
	int chargeTime;
	qboolean fCrewgun;
	int cursorHint;
	int grenadeTimeLeft;                ///< Actual time remaining
	int grenadeTimeStart;               ///< Time trigger base to compute TimeLeft
	int hintTime;
	int sprintTime;
	int weapHeat;
	int weaponState;
	int weaponState_last;
#endif
```

I'd suggest to check your RPMBUILD as it seems this CMAKE option is turned off. Ideally, use our default options. That variable should however be made independent from that CMAKE option, as it seems it isn't completely related to Multiview anymore (see 0bcd0c8b300025536181f11c61b66b4e49f9a2cb).

**Comment by Kieltux** [comment]
Thank you so much. Changing MULTIVIEW to ON (default) was the solution.

**Comment by ensiform** [comment]
This sounds more like a bug indeed, it should not be trying to access multiview variables which are only used when viewing multiple clients. Other clients in the world won't necessarily have their weapon state setup or any part of the block of variables which are for feature multiview. And the ps weaponstate is not transmitted into entitystate unfortunately.

If truely intended to be checking the multiview states is intended, then the variable accessor should be encapsulated in the feature ifdef too.

**Comment by rmarquis** [comment]
Good point Ensi. I've fixed the compilation issue, but I am not sure that line actually brings something useful - or at least it seems indeed quite hacky as per the original commit message.
