### ISSUE TITLE
Make creating/joining a fireteam automatic in stopwatch mode

### ISSUE THREAD

**Issue by BystryPL** [etlegacy/etlegacy#1701]
A suggestion for competitive gameplay: make creating/joining a fireteam automatic in stopwatch mode. Fireteam is a must in competitive games. It's always a bit of pain in the ass to gather all players in 1 fireteam, also sometimes people forget about it and have to do it just before the game starts or even during the game. Forcing it/making it automatic would be an interesting feature and would prevent those situations. I'm not quite sure how it should work though (forcing a fireteam without leader in each team which players would join automatically upon joining a team?), so I leave it for further discussion.

**Comment by isRyven** [comment]
I would perhaps rather make a cvar for this, like `g_autoFireteam`, which would automatically add a player into a free fireteam on game join. Then you could just enable the cvar in comp config. Making game type specific behavior, is just additional hassle in this case.

**Comment by Aciz** [comment]
> I would perhaps rather make a cvar for this, like `g_autoFireteam`, which would automatically add a player into a free fireteam on game join. Then you could just enable the cvar in comp config. Making game type specific behavior, is just additional hassle in this case.

`g_autoFireteams` is already a cvar, when enabled, it will prompt about joining/creating a fireteam when you first join a team. This could be extended with value __2__ to make the joining automatic too.

**Comment by isRyven** [comment]
Ah yeah, thought so. Sounds good.
