### ISSUE TITLE
Bugged enemy spawntimer

### ISSUE THREAD

**Issue by mittermichal** [etlegacy/etlegacy#1713]
It's bugged, sometimes the spawntimes are incorrect when using resetTimer command.

_Originally posted by @BystryPL in https://github.com/etlegacy/etlegacy/issues/1573#issuecomment-917706868_

**Comment by mittermichal** [comment]
@BystryPL can you check `g_redlimbotime` and `g_bluelimbotime` in console when this happens?

**Comment by mittermichal** [comment]
I also wonder if this happens to the whole team or just one player

**Comment by oheikk** [comment]
`resettimer` automation breaks after using `timerset`. For example if you do `timerset 30`, after that `resettimer` will always set timer to 30.

I think need to restart game to resume automatic behaviour, or haven't found any other way at least.
