### ISSUE TITLE
`ENABLE_ASAN` option in CMake doesn't enable address sanitizer on Windows

### ISSUE THREAD

**Issue by Aciz** [etlegacy/etlegacy#1729]
Not sure if this a Windows only issue, but enabling the `ENABLE_ASAN` option in `CMakeLists.txt` does not enable address sanitizer on Windows., and needs to be forced with `cmake . -DENABLE_ASAN=ON`

Output of `cmake .` after enabling from `CMakeLists.txt`

![image](https://user-images.githubusercontent.com/14221121/134224149-e2aeb79a-c4f5-4b17-8539-3624e39619cd.png)

With `-DENABLE_ASAN=ON`

![image](https://user-images.githubusercontent.com/14221121/134224209-518ae066-157f-48bc-bdf3-e8e6e4d113f8.png)

**Comment by rmarquis** [comment]
That's a weird one. I don't want to be that guy, but are you sure you changed the variable in the CMakeFile and reloaded generated files prior to running it? Not using VStudio/MSVC, but afaik you need to generate intermediate files with `cmake -G "NMake Makefiles"` with msvc (see README or easybuild.bat).

**Comment by Aciz** [comment]
Yes this can very well be just me doing something wrong, cmake isn't my strong suite :P I'll mess around with it more today and see if I can get it working

**Comment by rmarquis** [comment]
Yeah, you can use cmake directly if you use another compiler (gcc/clang through mingw), but it's a bit more convoluted when using MSVC.

Using `easybuild.bat` should help greatly though.

**Comment by Aciz** [comment]
Alright I can confirm this was my mistake indeed, address sanitizer enables fine when generating build files. Closing.
