### ISSUE TITLE
High resolution crosshairs

### ISSUE THREAD

**Issue by Aciz** [etlegacy/etlegacy#1736]
The current crosshairs that the game offers are 64px images. They were probably fine back in the day, but nowadays, with bigger screens and higher resolutions, most of them are extremely blurry even when set to "Small" size. We should look into providing higher resolution crosshair images, maybe even implement some new ones if there is desire (T shaped crosshair anyone?)

The current crosshairs are simple enough that a good upscaler will work okay on most of them, I already played around with this idea and found that the results with ESRGAN 4x using `4x_scalenx_90k` model provides "okay" results, but not really up to a quality that I would be comfortable shipping with the game. Even still, the stock crosshair are also pretty simple to just re-create by a semi-skilled artist in photoshop.

Edit: this would also be an excellent use case for the SVG support that the engine has.

**Comment by mittermichal** [comment]
also would be nice to have client custom crosshair like custom HUDs

**Comment by Aciz** [comment]
> also would be nice to have client custom crosshair like custom HUDs

`sv_pure 1` is obviously an issue here, but some sort of custom crosshair generator could be implemented using cgame draw tools (lines, dots, circles etc.)

**Comment by mittermichal** [comment]
Is it not possible to do same way as with custom HUDs, because you can only register shader from files that are loaded from pk3s?

**Comment by Aciz** [comment]
Yes, any custom crosshair would have to be in a pk3 on the server you're playing at. So just letting clients use whatever custom crosshair they want is not possible.

**Comment by jackeri** [comment]
The svg support was initially meant for the high quality crosshairs, and the first tests were done with tga -> svg conversions to test out the results (ofc the converted graphics could not be added to the sources because of the license). The crosshairs would need to be remade (which should not be a big deal to anyone with knowledge of illustrator or something similar.
