### ISSUE TITLE
Cancel votes & ref voting behaviour

### ISSUE THREAD

**Issue by Helldembez** [etlegacy/etlegacy#1750]
I have received feedback that players want the ability to cancel votes. If I recall correctly, in ETPro you could cancel by pressing ESC or F2 when being the votecaller. Being a ref also had the effect of automatically passing or cancelling the vote.

This implementation of ref voting might not be ideal as it leads to accidental vote passes / fails. Mostly in a comp setting where the ref is also playing as a normal player.

For now I suggest just being able to cancel votes as votecaller and start the discussion regarding the rest.

**Comment by Aranud** [comment]
refs #2085
