### ISSUE TITLE
Merge r_fastsky and cg_skybox cvars

### ISSUE THREAD

**Issue by realkemon** [etlegacy/etlegacy#1758]
Got the [report on Discord](https://discord.com/channels/772823517434740766/893465147820093471/893605383980064820) that  `r_fastSky` should also remove everything in the `props_skyPortal` (e.g. background hills). This is currently done by `cg_skyBox 0`. The thing is that `cg_skyBox` does everything that `r_fastSky` does and more. Can these two cvars be merged to make things a bit clearer? Possibly with bitflags to allow the different combinations?

`r_fastSky 0` and `cg_skyBox 1`:
![shot0004](https://user-images.githubusercontent.com/8881420/135721162-fe9bc0f6-401d-46c7-b3cf-0f5821a24c1b.png)

`r_fastSky 1` and `cg_skyBox 1`:
![shot0005](https://user-images.githubusercontent.com/8881420/135721183-e21bb35e-dfcc-4068-a924-4f408d947e17.png)

`r_fastSky 0` and `cg_skyBox 0`:
![shot0006](https://user-images.githubusercontent.com/8881420/135721198-f8b09492-ef3e-4a8c-9900-a294c6c470bd.png)

**Comment by rmarquis** [comment]
`r_fastSky` is engine side, while `cg_skyBox` is on the mod side.
`r_fastSky` might also be needed for dev of other mods, and as first thought I'd say it would be a bad idea to (somehow) merge their functionality. But we can have a deeper look.

**Comment by realkemon** [comment]
The the end user it just seems redundant imo. I know it's the strong side of ET that everything can be adjusted with cvars, but I think fewer, but more concise ones might be clearer and easier to document/maintain. But I don't know how it's handled behind the scenes.

**Comment by rmarquis** [comment]
Yes, I totally agree on the principle of the idea, but I do expect some technical barrier here.

**Comment by hazz1nen** [comment]
`cg_skybox` is cheat protected. I guess there's no reason to remove the protection though?

**Comment by Aciz** [comment]
I honestly don't see it being a good thing to merge these, they serve very different purposes. Removing cheat protection from `cg_skybox` does make sense though.
