### ISSUE TITLE
Hide demo recording message

### ISSUE THREAD

**Issue by zenixje** [etlegacy/etlegacy#1761]
Competitive players always record demos, it would be nice if we can hide the message (or make it shorter/smaller)

https://postimg.cc/nMwhqTFY

**Comment by Aciz** [comment]
You can already achieve this with `cg_recording_statusline` cvar, which controls the Y position of the message, by just moving it off screen. But yeah a dedicated cvar would probably be more convenient.

**Comment by rmarquis** [comment]
Yeah, I kinda hated that long line even for casual play. I am not sure displaying the current time and size on screen is useful at all to be honest. A simpler `⦿ REC` as default would be enough imho.

And by extension, we might simply print `<triangle> PLAY` when playing demo, if that's enough (edit: nvm, the date is still useful here).
Note: unicode chars are simply printed as `.` in the 2.60b client.

**Comment by rmarquis** [comment]
I quickly had a look the other day: I first wanted to move the extra details in console instead, but that would mean cleaning up cgame code to move them to the client. It's more work than it seems worth the hassle, and I am not sure how reliant other mods are on that specific code so it might be better to keep it as is it.

However, what we can do is finding a better cgame cvar to replace `cg_recording_statusline` (using a y-pixel value which seems unnecessary), with the following options:

* 0: hidden
* 1: default, more discreet message only
* 2: longer message, equivalent of what we have currently

Something like `cg_demo_status`.

**Comment by mittermichal** [comment]
I would rather put it as hud element to have these settings nicely at one place
your mentioned values 1&2 could be represented in hud element style attribute

**Comment by rmarquis** [comment]
That sounds indeed better!

**Comment by zenixje** [comment]
The current recording message, red recording is fine.
