### ISSUE TITLE
Game window loses focus while moving mouse on some Windows systems

### ISSUE THREAD

**Issue by Aciz** [etlegacy/etlegacy#1762]
Several user have reported that after upgrading to 2.78, the game window keeps losing focus when they move their mouse around, and they can see their mouse cursor appearing, and input to game stops working. I tested this with @realkemon who is also suffering from this, and it seems like the culprit is SDL2.0.16. On an older build that I made, just before upgrading from 2.0.14 to 2.0.16, the issue doesn't appear.

There's obviously something else related to this other than purely the SDL upgrade, since it doesn't happen to all users, but it quite literally makes the game unplayable for some people.

**Comment by rmarquis** [comment]
SDL changelog (short version) is available [here](https://www.libsdl.org/tmp/SDL/WhatsNew.txt).

Potentially responsible:
> * Added SDL_SetWindowAlwaysOnTop() to dynamically change the SDL_WINDOW_ALWAYS_ON_TOP flag for a window
> * Added SDL_SetWindowKeyboardGrab() to support grabbing the keyboard independently of the mouse

Does the issue appears in windowed mode only? Windowed fullscreen?

By any chance, do we have any hint of a similar characteristic of impacted players? F.e., the German keyboard layout has always been a bit awkward due to its `^` placement, maybe there is something related to layout.

**Comment by realkemon** [comment]
Happens unrelated to windowed/fullscreen mode as far as I can tell, because I always have that issue.

**Comment by Aciz** [comment]
For kemon, it happened on windowed, borderless windowed and fullscreen. I've been trying to get specifics from the people who reported this, and the only common thing I've gotten so far is that both kemon and some other guy have an integrated mouse input method on their keyboard (kemon has a trackpoint, the other guy has a touchpad).

Edit: I have a bluetooth keyboard with an integrated touchpad too, and I did test that and had no issues.

**Comment by rmarquis** [comment]
I've skimmed through the SDL tracker, and I see a few tickets that potentially match the above issue: 
* https://github.com/libsdl-org/SDL/issues/4450
* https://github.com/libsdl-org/SDL/pull/4293
* https://github.com/libsdl-org/SDL/issues/3076

This is also a long shot, the date of some of the tickets might matches the 2.0.16 release window, but the issue might be older and I can't explain why it wouldn't have been present before. Maybe some other change they did for last SDL makes that issue triggers more easily.

Basically, the ETL window might somehow lose focus prior to be completely created, or somehow might open in the background rather than the foreground, and things go bersek. Focus can be lost by quickly clicking on another window, or *I guess* might be stolen by some other program. Do you happen to have any overlay program automatically running, maybe some recording software that captures the screen, Idk?

This might have also been solved recently in SDL master by this commit: https://github.com/libsdl-org/SDL/commit/632aca29453cf09a44bd45497363607a106634f8

**Comment by realkemon** [comment]
> Do you happen to have any overlay program automatically running, maybe some recording software that capture the screen, Idk?

Not consciously at least. It's possible that the NVIDIA settings or some launcher like Steam or whatever is stealing focus, but that would be quit concerning.

**Comment by ryzyk-krzysiek** [comment]
I have the same issue when debugging on 2 windowed clients, one works fine and another one has no focus on mouse making it impossible to move around.

**Comment by rmarquis** [comment]
> I have the same issue when debugging on 2 windowed clients, one works fine and another one has no focus on mouse making it impossible to move around.

I assume this happens on 2 different machines? Do you have any special keyboard with integrated mouse, or anything out of the ordinary?

I can't reproduce anything locally :/

**Comment by Aciz** [comment]
Overlays seem to have no effect at least for me, I always have GeForce experience running, so it's ingame overlay is active. Also tried turning on RTSS, nothing.

**Comment by rmarquis** [comment]
Some news from upstream: https://github.com/libsdl-org/SDL/commit/632aca29453cf09a44bd45497363607a106634f8 doesn't seem to help much, but https://github.com/libsdl-org/SDL/commit/c542de92135a79f25648e75b1c2ab0fd581e29c0 seems to do so!

Let's try to backport the fix.

**Comment by rmarquis** [comment]
Long story short: it took me way too much time to backport that fix. The patch would basically stop applying once I fixed the rejected hunks. I eventually resorted to do it in a dirty manual way, as to get something compiled.

Please find attached a new .exe with the SDL2 fix for testing. Note this is a mingw build, so you'll also need to put the attached libs in your ETL directory. I'll try to fix that cmake patching madness in the meantime.

[etl-sdl2.0.16-focusinput-fix.zip](https://github.com/etlegacy/etlegacy/files/7297403/etl-sdl2.0.16-focusinput-fix.zip)

**Comment by Aciz** [comment]
I've linked this to the people on discord who reported having this issue, waiting for results.

**Comment by Aciz** [comment]
This fix doesn't seem to actually work at all, first of all, it's complaining about missing renderer lib `renderer_opengl1_x86.dll`, which we don't seem to use anymore, and grabbing that from the latest release that shipped with it (2.76) just makes the game not launch at all.

**Comment by rmarquis** [comment]
Oh damn. I compiled the renderer in an external lib. Here it is attached, to be put next to the exe.

[renderer_opengl1_x86.zip](https://github.com/etlegacy/etlegacy/files/7317232/renderer_opengl1_x86.zip)

**Comment by realkemon** [comment]
Game still loses focus using the provided files :/
(Tested in windowed mode)

**Comment by Aciz** [comment]
Could we perhaps ship windows version with SDL 2.0.14, and use .16 for Linux/MacOS? Should be definable in cmake I think?

**Comment by rmarquis** [comment]
Yes, we can ship the older SDL for windows.

I'll however also try to provide an exe compiled with the last SDL dev version (current 2.0.17) for testing. This might help upstream to fix the issue if that's not done properly yet.

I'll prepare both exes asap.

**Comment by rmarquis** [comment]
Here they are:

[etl-sdl-2.0.14.zip](https://github.com/etlegacy/etlegacy/files/7317267/etl-sdl-2.0.14.zip)
[etl-sdl-2.0.17dev.zip](https://github.com/etlegacy/etlegacy/files/7317268/etl-sdl-2.0.17dev.zip)

Feedback on both set very welcome.

**Comment by realkemon** [comment]
etl-sdl-2.0.14.zip - works
etl-sdl-2.0.17dev.zip - loses focus

**Comment by rmarquis** [comment]
All right. Looks like upstream isn't aware of that particular bug, or at least what they've done hasn't properly fixed all user cases.

Might I ask if you'd be able to record the buggy behaviour, as to show them exactly what is happening? We'll need to prepare a bug report to help them fix that issue. I compiled SDL master (2.0.17 commit at 1b49f092431379d43649d85c5b35b604d977be11).

For 2.78.1, we'll ship 2.0.14 for windows.

**Comment by realkemon** [comment]
@rmarquis @Aciz is this okay?
https://streamable.com/zx36y7

Had to reduce resolution to fit the keyboard input thingy. Couldn't get it to always stay on top :/

**Comment by Aciz** [comment]
Looks okay to me, you can clearly see that you cursor leaves the game window, which should not happen.

**Comment by rmarquis** [comment]
Perfect, thanks! Ticket is now filled on SDL tracker.

**Comment by rmarquis** [comment]
@realkemon Here's two new exes for feedback, as per upstream request.

[etl-sdl2.0.16-minus89b62093.zip](https://github.com/etlegacy/etlegacy/files/7321511/etl-sdl2.0.16-minus89b62093.zip)
[etl-sdl2.0.16-minus4359a47b.zip](https://github.com/etlegacy/etlegacy/files/7321514/etl-sdl2.0.16-minus4359a47b.zip)

**Comment by realkemon** [comment]
@rmarquis 
Both exes work. 
Window doesn't lose focus and I can play regularly.

**Comment by rmarquis** [comment]
Thanks! Not the result I expected, but hey, programming is weird sometimes.

**Comment by rmarquis** [comment]
@realkemon And here's the proposed [upstream fix](https://github.com/libsdl-org/SDL/issues/4823)! It most likely works, but direct feedback would be greatly appreciated.

[etl-sdl2.0.17dev_plusPR4831.zip](https://github.com/etlegacy/etlegacy/files/7336375/etl-sdl2.0.17dev_plusPR4831.zip)

**Comment by dpierangeli** [comment]
I had the same problem, tested the upstream fix and is now gone. Thanks!

**Comment by realkemon** [comment]
Can confirm that the fix works. Yay!

**Comment by rmarquis** [comment]
Thanks! 

From the info I could gather around by looking at SDL tracker, DPI scaling might be the reason some people encountered that issue and not others.

There is little else we can do here, so closing the ticket now. We'll update to SDL 2.0.18 in a couple of months.

**Comment by rmarquis** [comment]
@realkemon @dpierangeli @lstolcman 

Since the proposed PR was only partially merged, upstream is asking feedback on what's actually been merged in SDL master. Here's (hopefully) the final exe for testing:

[etl-sdl-2.0.17-c583055.zip](https://github.com/etlegacy/etlegacy/files/7357330/etl-sdl-2.0.17-c583055.zip)

**Comment by realkemon** [comment]
@rmarquis those files work as well. :)

**Comment by rmarquis** [comment]
Thanks!

**Comment by lstolcman** [comment]
works great for me as well
