### ISSUE TITLE
Moving/rotating ingame issues on v2.78.0 on 4k monitor/150% scaling

### ISSUE THREAD

**Issue by lstolcman** [etlegacy/etlegacy#1778]
Hi.

I have 4k (3840x2160) monitor, and scaling in windows set to 150%

I was previously using 2.77.1 and it was perfectly fine.

After upgrading to 2.78.0, I cannot play - after joining the game, it stucks after few seconds of moving (keyboard - wsad) or rotating around (by mouse). I have to either turn on again the keyboard key, or force moving around by mouse.
It looks like the game window is loosing focus? (sometimes I can see a mouse pointer for a fraction of second - the same behavior you ahve when you try to minimize old game, but it does not support it).

Short video - I try to move around as much as I can, but sometimes the player is stuck, and you may observe this "mouse pointer" sometimes (between 0s-5s it is visible twice): https://vimeo.com/631378485

The problem exists only when the scaling is set. When it is 100% (no scaling/zooming), the issue is gone.

I did not have this problem on 2.77.1, despite scaling set to 150%

**Comment by rafal1137** [comment]
You are propably experiencing the same issue posted here:
#1762 
You can download zip file from this comment and test if issue still persist,
Waiting for your response.

**Comment by lstolcman** [comment]
Okay, I tested it and seems that the SDL patch https://github.com/libsdl-org/SDL/issues/4823 fixes the problem: https://github.com/etlegacy/etlegacy/issues/1762#issuecomment-942073891
So sad that we will have to wait couple of months for a new sdl release and a fix. Wouldn't creating etlagacy patch version and lowering sdl version be a good solution?

**Comment by rafal1137** [comment]
@lstolcman There was planned Hotfix Release in few weeks.
Yeah already done on our side with downgrading the SDL.

https://github.com/etlegacy/etlegacy-libs/commit/ce9ea73ef3bd5a93368cb35123c1671fb5e5cdbe

Since issue has been resolved (partially) by an patch file. Closing
