### ISSUE TITLE
Game crashing to desktop when loading HUD

### ISSUE THREAD

**Issue by BystryPL** [etlegacy/etlegacy#1779]
ETL crashing to desktop on macOS when connecting to a dedicated server (when the map is loading). The game just crashes, there is no information, nothing in crashlog as well. Crash on macOS 10.14.6. This crash has been confirmed with 2 players, occurring in the same cirumstances.

The crash started to happen after updating the server from 2.78 to 2.78.0-25-gbe7d965.

EDIT: crashing both on 2.77.1 and 2.78 client.

**Comment by rmarquis** [comment]
I don't see anything in recent changes that would be macOS specific. Even libs changes shouldn't have any impact.
By any chance, were these clients using some custom HUD scripts? That's along shot, but might be related to the `demotext` addition in 9cecd204ea6a59df72c2ec6a6535dc72246a0312.

Edit: ah, crashing on old 2.77.1 too. Definitely something else.

**Comment by BystryPL** [comment]
We were just discussing that it might be indeed the custom HUD, as Aranud did some changes in the part of the code that is related to HUD. But the crash occurs both for a player with a custom HUD and without one. So I don't think it is custom HUD related. I managed to get some logs from when my client crashes though and it seems that it could be related to HUD in general:

```
0 -- Trying zipped .bundle... failed (not a valid zip)
       0 -- Trying extension-less dylib... succeeded
       0 Sys_LoadDll(legacy/cgame) found vmMain function at 0x13d3883f0
       0 ^9Initializing legacy cgame ^2v2.78.0-25-gbe7d965
       0 198 client cvars in use
       0 LOADING...  - collision map -
       0 LOADING...  - sounds -
       0 Initializing Sound Scripts
       0 ...loading 'sound/scripts/vo_allies.sounds'
       0 ...'sound/scripts/vo_allies.sounds' parsed - total script sounds: 48
       0 ...loading 'sound/scripts/vo_axis.sounds'
       0 ...'sound/scripts/vo_axis.sounds' parsed - total script sounds: 96
       0 ...loading 'sound/scripts/sw_goldrush_te.sounds'
       0 ...'sound/scripts/sw_goldrush_te.sounds' parsed - total script sounds: 148
       0 ...3 of 3 sound scripts files loaded. Total sounds: 148
       0 done.
       0 ^1ERROR: sound file 'sound\movers\doors\door4closeq.wav' does not exist or can't be read
       0 LOADING...  - graphics -
       0 LOADING...  - maps/sw_goldrush_te.bsp -
       0 stitched 16 LoD cracks
       0 ...loaded 25975 faces, 578 meshes, 272 trisurfs, 0 flares, 0 foliages
       0 ^3WARNING: light grid mismatch
       0 LOADING...  - entities -
       0 LOADING...  - game media -
       0 LOADING...  - textures -
       0 LOADING...  - models -
       0 LOADING...  - heads-up display -
       0 ----- Client Shutdown ----------
```

**Comment by rmarquis** [comment]
Yes, looks like it crashes on `CG_Hud_Setup()`.

The refactoring by Ara looks good to me at first sight, but here's 2 things to check in the HUD scripts:
* `cursorhint` has been properly renamed to `cursorhints` in 15911c68cebb5c7881ffd3ce2366f1120310b6dc (there's a weird mix of both syntax in prior code)
* `demotext` has been added in 9cecd204ea6a59df72c2ec6a6535dc72246a0312

**Comment by mittermichal** [comment]
![shot0000](https://user-images.githubusercontent.com/4035800/137679621-390a0622-5094-47d4-a64f-73a9efd9c5ea.jpg)
latest snapshot works for me on macOS

**Comment by BystryPL** [comment]
Working for me as well on snapshot 2.78.0-44-g1380848. Client version 2.78.

![shot0052](https://user-images.githubusercontent.com/45846431/137972423-0d11b09c-67be-4feb-b8d4-db6fb54d0b4b.jpg)

**Comment by rmarquis** [comment]
Great, closing ticket.
Good job here @mittermichal :)
