### ISSUE TITLE
Show name next to obj stolen/secured/returned/dropped

### ISSUE THREAD

**Issue by x0rnn** [etlegacy/etlegacy#1832]
This is a feature request. Currently, when a player for example steals an objective the game will output "Allies have stolen the X".

How about appending the ​player's name, so it would for example say: "Allies ([!!!]x0rnn) have stolen the X")?

I do something like that with a lua script: https://github.com/x0rnn/etpro/blob/master/lua/objtrack.lua

**Comment by BystryPL** [comment]
But why? You can check it in the scoreboard already.

**Comment by x0rnn** [comment]
Because it's easier and faster if I can immediately read who stole it/returned it, not opening the scoreboard and blurring my vision and lowering my focus by looking at all the names instead of the game. It instantly gives me useful intel on which player is where by not having to look at the scoreboard.

**Comment by Aciz** [comment]
This info should probably be only visible for teammates? So for example if Allies steal objective:

Axis print:
`Allies have stolen the objective!` 

Allies print:
`[!!!]x0rnn has stolen the objective!`

**Comment by x0rnn** [comment]
No, it should be visible to all, since you already get the same info on the scoreboard (except returning objectives, I haven't thought about that).

**Comment by Aciz** [comment]
I don't think you see who's carrying the objective on the enemy team from the scoreboard? I think it only shows teammates who are carrying, but I might be wrong here.

**Comment by x0rnn** [comment]
You're making me confused right now, now even I'm not sure anymore heh.

**Comment by Aciz** [comment]
Okay seems I was wrong, you do see it. So per-team prints don't make sense then.

![image](https://user-images.githubusercontent.com/14221121/142266087-af590a50-7a3e-4750-ad65-593d785f2c6d.png)

**Comment by x0rnn** [comment]
Well I guess it makes sense for the "X returned the objective" message, otherwise you get intel of a player's whereabouts you wouldn't otherwise know.

**Comment by rmarquis** [comment]
I'd say per-team print only make sense as that information  doesn't bring any useful information to the opposite team, and is essentially extra unnecessary bloat. Might be useful for teammates maybe (FT already provide the info too).

**Comment by Aciz** [comment]
There's also a consideration about the actual implementation: these prints come from mapscript, so we can't simply modify them in code (or we can, but they are made with `wm_announce` which can be used for other things).

**Comment by x0rnn** [comment]
> I'd say per-team print only make sense as that information doesn't bring any useful information to the opposite team, and is essentially extra unnecessary bloat. Might be useful for teammates maybe (FT already provide the info too).

I'd say seeing an opponent's name who stole an objective isn't unnecessary bloat and is more useful to the opposite team than teammates, i.e., I get to know whether it's someone with a SMG, rifle, etc., someone bad or someone good... But I guess this is all subjective...

> these prints come from mapscript

The drop and secure messages do indeed, so that's a bit tricky, but the steal/return messages come from either (if not present in the mapscript maybe?) (or both?). In logs it's the team_CTF_redflag/team_CTF_blueflag lines.

**Comment by jackeri** [comment]
I fail to see the value in this, even less so for the enemy team. Just bloat imho.

**Comment by x0rnn** [comment]
Well I guess I'm the only one checking the scoreboard to see who stole an objective.

It could at least be an optional "bloat" with a cvar maybe. And an easier way without modifying and appending names to the existing messages would be to just print a new line with e.g. "x0rnn stole the objective!"

**Comment by x0rnn** [comment]
Can be done in Lua so closing this.
