### ISSUE TITLE
MSI AfterBurner RivaTuner doesn't work with this new version of ET Legacy

### ISSUE THREAD

**Issue by bnikkhah** [etlegacy/etlegacy#1841]
I use RivaTuner to track my my FPS, GPU, and CPU usage and it works great on all my games except for this new ET Legacy patch. Every time a map loads, my RivaTuner gets all grayed out and glitchy and I can't even view the stats. The old version of ET Legacy worked fine for RivaTuner.

Would anyone know what's going on?

**Comment by Helldembez** [comment]
Do you have the exact version numbers by any chance? Mod version may also depends on the server you are playing.

**Comment by u1ps** [comment]
![image](https://github.com/user-attachments/assets/61495668-328b-4cb5-b9bb-894d79d15f96)

Windows 10

ETLegacy 2.81.1 

MSI AfterBurner 4.6.5

Seems like it is working
