### ISSUE TITLE
Throwing has excessive force

### ISSUE THREAD

**Issue by BystryPL** [etlegacy/etlegacy#1852]
After last update throwing has excessive force (canisters, landmines, other items perhas). Apparently it's been a known bug but after last update to build 84 it's happening a lot more ofte (several times per 1 map). See videos below. 

https://streamable.com/m89f0b
https://clips.twitch.tv/AdventurousScaryCougarCopyThis-GKTEpkqspf8ux3sG

**Comment by BystryPL** [comment]
Demo, 12:45 timestamp:
https://easyupload.io/o2uyyl

**Comment by Aranud** [comment]
As @ryzyk-krzysiek already proposed it, we should anti-lagged the firing missile and see pro / con.

@ryzyk-krzysiek Do you agree with if I do it for you ?

**Comment by ryzyk-krzysiek** [comment]
> As @ryzyk-krzysiek already proposed it, we should anti-lagged the firing missile and see pro / con.

Anti-lagging fire missile will not do anything I think? The missile will not explode instantly so the changes to other players positions will not matter. Anti-lagging explosions might feel weird with high pingers (afaik people will see nades far away and die to them) but could be worth trying out I guess.

I don't think it would change anything when it comes to this issue though. I don't know what is causing it, but judging how it happens to every throwable weapon including rifle that uses different function in `g_weapon`, my guesses are:

1. Somehow `ps->viewangle` is wrong making players throw in the wrong directions.
2. Somehow `muzzleEffect` is wrong making players throw in the wrong directions.
3. It seems to happen to everyone on the server at the same time so it is some general server issue.
4. I don't believe build 84 has anything that would make it happen more often, rather it is just a coincidence.
