### ISSUE TITLE
Inconsistency between file read order between ETL and 2.60b

### ISSUE THREAD

**Issue by Aciz** [etlegacy/etlegacy#1855]
Now that ETLegacy is in a state where it can be used to properly host ETJump servers, I have noticed there's some inconsistency between how pak files are referenced between 2.60b and ETL. The issue seems to be that ETL handles `_` and `.` chars in a different order than 2.60b. Current ETJump version 2.4.0 has a pk3 name `etjump.-2.4.0.pk3`, while the previous version has `etjump-2_3_0.pk3`. This causes the following incompatibility with a client running 2.60b:

2.60b client connecting to an ETJump server running 2.4.0 with ETL server will get kicked for unpure client error on Windows (Linux segfaults), if the client has both 2.4.0 and 2.3.0 pk3 files present in etjump folder. Upon connecting, the loading screen displays the client is loading ETJump 2.3.0 instead of 2.4.0. Afterwards, 2.3.0 cgame/ui modules can be found extracted in etjump folder, instead of 2.4.0 ones. This issue doesn't happen if the server is also running 2.60b, it's exclusive to servers running ETL.

I am honestly not sure what's going on here and how the server can mess up client's file loading order like this, but clearly something weird is going on between server and client communicating which pak file should be used.

**Comment by Aciz** [comment]
So after some investigation, this is actually caused by, once again, too many PK3s on server. Server exceeds `BIG_INFO_STRING` and doesn't send `sv_paks` to client, causing the client to load non-pure paks on a pure server. Talked with @jackeri and we should really not send this whole list anyway, at least for etmain content as it makes no sense.

**Comment by jackeri** [comment]
Possible fixes done in dfb95bdb15b60e1110188867a5cdfb205c1d07d8 and in a7065b540a34a7cb9d89ff9dbf2e755a5a5c5850 possible workaround the issue (or break everything).

**Comment by jackeri** [comment]
This seems to be fixed, so closing it.
