### ISSUE TITLE
Server-side demo recording

### ISSUE THREAD

**Issue by x0rnn** [etlegacy/etlegacy#1860]
Could this be implemented into Legacy? See: https://github.com/x0rnn/amk-etwolf-server-demo

It's a library for etded 2.60b (not compatible with ETL I think) to allow recording players server-side, identical to a client-side /record. Useful for admins to get demos of players from their POV without them knowing, without lag, etc., you even see who they were spectating while dead waiting for respawn, so you can also explain how they "knew" someone was behind a corner, etc.

In etpro you have to use an external Lua for admins to record/stoprecord, for example: https://gist.github.com/x0rnn/302dcdf4070ecad3738b2598dbb7ee57

The same could be used in ETL, or maybe a better built-in method could be made.

If not, maybe I can ask the author to make it ETL compatible, although not sure if it would have to be updated every time ETL gets updated?

**Comment by Aciz** [comment]
We've had server side demo recording for a while already, though I am not sure how complete it is functionality wise. `demo_record` is the command to start recording on server side, and `sv_autoDemo` can be used to automatically start recording.

**Comment by x0rnn** [comment]
Oh, didn't know. Closing this then. Thanks!
