### ISSUE TITLE
Add ET:Legacy Flathub Badge on main website

### ISSUE THREAD

**Issue by Eonfge** [etlegacy/etlegacy#1869]
With the release of 2.79, I had the Flathub version updated in just an hour or two, making the whole process incredibly smooth. Your pre-compiled packages work well and they contain all the meta data. Thanks for that!

## Stats 

After updating the Flathub package, I kept an eye on the download statistics and they're really good:

- 30 people updated the game the same day and 
- 20 people installed the game for the first time.
- about 150 people use ET:Legacy with Flathub (using the November-update numbers)

https://klausenbusk.github.io/flathub-stats/#ref=com.etlegacy.ETLegacy&interval=infinity&downloadType=installs%2Bupdates

## Promotion

So, where am I going with this? Well, I think that the Flathub version would definitely be the easiest way for people to install ET:Legacy on Linux and it would be cool if you could add a Badge to the ET:Legacy downloads page!

```
<a href='https://flathub.org/apps/details/com.etlegacy.ETLegacy'><img width='240' alt='Download on Flathub' src='https://flathub.org/assets/badges/flathub-badge-en.png'/></a>
```
https://flathub.org/badges

This would make it easier to casual users to install and run the game with one click. Now, flathub is no replacement for your binaries, because servers will still want to use those, but it would be very cool if Flathub could be promoted side-by-side. 

## Why Flathub
The flathub package is great for a few reasons:
- Easy install for all users on every Linux distribution
- Secure install for all users, since Flatpak enforces sandboxing
- Identical dependency-stack for all Linux users (no more issues with different SDL versions)
- 32bit ET:Legacy wrapped in a container so users don't need to install 32bit libraries on their machine

If you have any further questions, feel free  to ask.

## Related issues

- Discussing Flathub maintainer-access for ET:Legacy developers: https://github.com/etlegacy/etlegacy/issues/1622

**Comment by jackeri** [comment]
Hi, thanks for the Flathub package maintenance, I added the flathub link to the downloads page https://www.etlegacy.com/download
