### ISSUE TITLE
Changing sound placing of a landmine

### ISSUE THREAD

**Issue by zenixje** [etlegacy/etlegacy#1870]
Would it be possible to change the sound of a placing a landmine? It is same as throwing a dynamite and sometimes really confusing. We received this report from serveral players on the ETLC Discord.

**Comment by kuromiii** [comment]
As a quick note, NoQuarter has a custom bouncing sound for landmines, so maybe we can get permission to use it.
Otherwise, I don't see any sound that we could use as an alternative in the base game, so we would have to create our own or find a free-to-use alternative...

**Comment by Aciz** [comment]
As a note, ETPro has a custom sound for both landmine and satchel bounce, these are the same sounds as @kuromiii mentioned. I have no idea about the origin of these sounds.

![image](https://user-images.githubusercontent.com/14221121/147507779-f50d1a7a-be6d-4ab3-804b-55c0a97cc11a.png)
