### ISSUE TITLE
Reevaluate and further discuss how hitsounds mechanic should work regarding explosives

### ISSUE THREAD

**Issue by BystryPL** [etlegacy/etlegacy#1877]
There has been an important change made by Jacker in this commit: https://github.com/etlegacy/etlegacy/commit/604e5cda049dd5a22737f4c90fe949012071a4d1. This makes the hitsound not activate by explosives anymore. 

As this decision will cause potientially an important change in the gameplay, I suggest to reevaluate and further discuss after some testing phase in gather matches on the ET: Legacy Competitive Discord server how the hitsound mechanic should work regarding the explosive weapons. Specifically, we should evaluate if:
- hitsounds should be activated by explosives;
- players should get XP by dealing damage to enemies with explosives;

**Comment by Helldembez** [comment]
Important to note is this was introduced to prevent sound bugs like this https://streamable.com/0onw2v . That should be fixed by this commit.
