### ISSUE TITLE
omni-bots not packed with v 2.79.0

### ISSUE THREAD

**Issue by standa4** [etlegacy/etlegacy#1885]
Release version 2.79.0 does not include omni-bots.
Only directory et/incomplete_navs in present in the archive inside legacy directory (and its content also seems incomplete - only with_script dir). Same applies for docker image for this version (no omni-bots).
Not sure if it was intended or it is a bug in packaging process.
Could you make a new release with omni-bots included?
Thank you.

**Comment by Aciz** [comment]
It was a bug, not intended. Omni-bots can be still manually installed (and they are installed with the installer, just not included in the binary release).

**Comment by standa4** [comment]
Thanks for the answer.
Any plan for minor release with fix? I use official docker image on my server. Manual installation is not strait-forward in prepared image if I don't want to edit it or manually install within each created container.
I will think about easiest workaroud for docker container before new release is available.
Thanks
