### ISSUE TITLE
stuck midair

### ISSUE THREAD

**Issue by zenixje** [etlegacy/etlegacy#1886]
https://clips.twitch.tv/ObliqueSpookyPandaBigBrother-W13atm2B0rXgFCWS

This was on snapshot v2.79.0-7-gb5ad814. I have seen the same thing happen when we had the server on sv_fps 100.  But that was not the case here.

**Comment by ryzyk-krzysiek** [comment]
Likely caused by antiwarp, when increasing `sv_fps`, `g_maxWarp` should be increased accordingly as explained here:
https://github.com/etlegacy/etlegacy/pull/1880

**Comment by Aranud** [comment]
Old issue. To be reopen in case it is reproducible.

**Comment by x0rnn** [comment]
This is definitely still happening. I thought it was something wrong with func_fakebrushes, but no.

[2023-11-26-022407-fueldump.zip](https://github.com/user-attachments/files/16347523/2023-11-26-022407-fueldump.zip)

Btw, we have sv_fps 20 and g_maxWarp 6

**Comment by x0rnn** [comment]
Also regarding the demo above, you always get stuck at the same location, it's not random...

**Comment by Aciz** [comment]
Any custom mapscripts? LUAs? This doesn't happen with default mapscripts and no LUAs loaded.

**Comment by x0rnn** [comment]
Yes, but I checked and there are no func_fakebrushes there to begin with. Lua I don't know why or how it could cause that. Also the twitch video has no mapscript with func_fakebrushes I would assume.

**Comment by mittermichal** [comment]
same thing happened to me on TM server few days ago on venice, will post demo and video later

**Comment by x0rnn** [comment]
Stairs in venice, right?

**Comment by mittermichal** [comment]
yes, those that tank goes through right after it passes AT gun

**Comment by Aciz** [comment]
All of the stuck spots in these clips correspond to the spectator spawn point in each map, so very likely something to do with that.
