### ISSUE TITLE
ETLegacy on Wayland, GLW_StartOpenGL() - could not load OpenGL subsystem: Unknown error

### ISSUE THREAD

**Issue by Eonfge** [etlegacy/etlegacy#1905]
### Overview

Okey, bit of background. Linux has two display systems. X11 which is older then I am, and Wayland, X11 is slowly being deprecated in favour of Wayland since X11 has a lot of problems, but such a fundamental change takes time and not all applications are directly compatible.

The same applies for ET Legacy 2.79

### Details
```
System:
  Host: kevin-at-fedora Kernel: 5.16.5-200.fc35.x86_64 x86_64 bits: 64
    compiler: gcc v: 2.37-10.fc35 Desktop: GNOME 41.3
    Distro: Fedora release 35 (Thirty Five)
Machine:
  Type: Desktop Mobo: Micro-Star model: B450 GAMING PRO CARBON AC (MS-7B85)
    v: 1.0 serial: <superuser required> UEFI: American Megatrends LLC. v: 1.F4
    date: 04/22/2021
CPU:
  Info: 8-core model: AMD Ryzen 7 2700 bits: 64 type: MT MCP arch: Zen+
    rev: 2 cache: L1: 768 KiB L2: 4 MiB L3: 16 MiB
Graphics:
  Device-1: NVIDIA GM204 [GeForce GTX 970] vendor: Micro-Star MSI
    driver: nvidia v: 510.47.03 bus-ID: 26:00.0
  Display: wayland server: X.Org 1.21.1.4 compositor: gnome-shell driver:
    loaded: nvidia resolution: 1: 2560x1440~60Hz 2: 1280x1024~60Hz
  OpenGL: renderer: NVIDIA GeForce GTX 970/PCIe/SSE2
    v: 4.6.0 NVIDIA 510.47.03 direct render: Yes
```

### How to reproduce
- Get the flatpak https://flathub.org/apps/details/com.etlegacy.ETLegacy
- Switch to Wayland on the system
- Force ETLegacy to use wayland using an override:

`/.local/share/flatpak/overrides/com.etlegacy.ETLegacy`
```
[Context]
sockets=wayland;!x11
```

-  `flatpak run --command=sh --devel com.etlegacy.ETLegacy`
  - You will be prompted to download all the SDK packages that bundle `gdb` and `ftrace`
-  `/app/bin/etl.sh`

### Debug
```
[kevin@kevin-at-fedora ~]$ flatpak run --command=sh --devel com.etlegacy.ETLegacy 
[kevin@kevin-at-fedora ~]$ /app/bin/etl.sh 
       0 ^2ET Legacy v2.79.0 linux-i386 Dec 23 2021
       0 Zone megs: 64
       0 INFO: fs_game now defaults to 'legacy' mod instead of 'etmain'
       0 ----- Initializing Filesystem --
       0 Current working directory:
       0     /home/kevin
       0 Current search path:
       0     D /home/kevin/.etlegacy/legacy
       0     D /app/bin/legacy
       0     D /home/kevin/.etlegacy/etmain
       0     D /app/bin/etmain
       0     P /home/kevin/.etlegacy/legacy/legacy_v2.77.pk3 (1328 files)
       0     P /app/bin/legacy/legacy_v2.79.0.pk3 (1381 files)
       0     P /app/bin/etmain/pak2.pk3 (22 files)
       0     P /app/bin/etmain/pak1.pk3 (10 files)
       0     P /app/bin/etmain/pak0.pk3 (3725 files)
       0 
       0 6466 files in pk3 files
       0 --------------------------------
       0 Creating PID file 'profiles/Eonfge/profile.pid'
       0 ----- Database Initialization --
       0 SQLite3 libversion 3.36.0 - database URI 'etl.db' - in file
       0 ... loading existing database '/home/kevin/.etlegacy/etl.db'
       0 ... database file '/home/kevin/.etlegacy/etl.db' loaded
       0 SQLite3 ETL: database init #2 /home/kevin/.etlegacy/etl.db in [1] ms - autocommit 1
       0 SQLite3 ETL: DB schema version #2 is up to date
       0 --------------------------------
       0 execing default.cfg
       0 execing profiles/Eonfge/etconfig.cfg
       0 couldn't exec autoexec.cfg
       0 Hunk_Clear: reset the hunk ok
       0 Not logging server attacks to disk
       0 ----- Client Initialization ----
       0 Trying to load "librenderer_opengl1_i386.so" from "/app/bin"...
       0 ETKEY found
       0 Available client translations: Afrikaans Bulgarian Catalan Czech Danish German Greek English Esperanto Spanish Finnish French Irish Hebrew Hungarian Italian Korean Dutch Norwegian Polish Portuguese Romanian Russian Slovak Slovenian Albanian Serbian Swedish Turkish
       0 Available mod translations: Afrikaans Bulgarian Catalan Czech Danish German Greek English Esperanto Spanish Finnish French Irish Hebrew Hungarian Italian Korean Dutch Norwegian Polish Portuguese Romanian Russian Slovak Slovenian Albanian Serbian Swedish Turkish
       0 Language set to English
       0 --------------------------------
       0 IP: 127.0.0.1
       0 IP: 192.168.178.23
       0 IP6: ::1
       0 IP6: 2001:985:13a3:1:2aeb:555b:a4e2:f8f5
       0 IP6: fe80::7830:495c:6948:2784%enp34s0
       0 Opening IP6 socket: [::]:27960
       0 Opening IP socket: 0.0.0.0:27960
       0 Network initialized
       0 ----- Initializing Renderer ----
       0 SDL build version 2.0.18 - link version 2.0.18
       0 SDL initialized driver "wayland"
       0 Initializing OpenGL display
       0 Estimated display aspect: 1.778
       0 ...setting mode -2: 2560x1440
tty]libEGL warning: DRI2: failed to create dri screen
       0 Using 24 color bits, 24 depth, 0 stencil display
       0 Available modes [1]: '2560x1440'
       0 ----- Initializing Filesystem --
       0 Current working directory:
       0     /home/kevin
       0 Current search path:
       0     D /home/kevin/.etlegacy/legacy
       0     D /app/bin/legacy
       0     D /home/kevin/.etlegacy/etmain
       0     D /app/bin/etmain
       0     P /home/kevin/.etlegacy/legacy/legacy_v2.77.pk3 (1328 files)
       0     P /app/bin/legacy/legacy_v2.79.0.pk3 (1381 files)
       0     P /app/bin/etmain/pak2.pk3 (22 files)
       0     P /app/bin/etmain/pak1.pk3 (10 files)
       0     P /app/bin/etmain/pak0.pk3 (3725 files)
       0 
       0 6466 files in pk3 files
       0 --------------------------------
       0 ----- Client Shutdown ----------
       0 ----- Initializing Filesystem --
       0 Current working directory:
       0     /home/kevin
       0 Current search path:
       0     D /home/kevin/.etlegacy/legacy
       0     D /app/bin/legacy
       0     D /home/kevin/.etlegacy/etmain
       0     D /app/bin/etmain
       0     P /home/kevin/.etlegacy/legacy/legacy_v2.77.pk3 (1328 files)
       0     P /app/bin/legacy/legacy_v2.79.0.pk3 (1381 files)
       0     P /app/bin/etmain/pak2.pk3 (22 files)
       0     P /app/bin/etmain/pak1.pk3 (10 files)
       0     P /app/bin/etmain/pak0.pk3 (3725 files)
       0 
       0 6466 files in pk3 files
       0 --------------------------------
       0 RE_Shutdown( 1 )
       0 SDL input devices shut down.
       0 --------------------------------
       0 PID file removed.
       0 SQLite3 database closed.
GLW_StartOpenGL() - could not load OpenGL subsystem: Unknown error
       0 Sys_Exit warning - PID file doesn't exist /home/kevin/.etlegacy/legacy/profiles/Eonfge/profile.pid
       0 Network shutdown
```

**Comment by Aciz** [comment]
We did add wayland support at some point and it was working, but checking out myself now I can confirm I have the same issue. Not really sure what could be wrong here, maybe it's due to newer SDL version than we had at the time (we were on `2.0.14` back when it was added), or maybe it's just nvidia being nvidia.

**Comment by Aciz** [comment]
From a quick test, this seems to be still broken on 2.80.0. Can you verify that this is the case for you as well?

**Comment by Eonfge** [comment]
Can confirm. Did a quick test but the situation appears to be unchanged.

**Comment by Aciz** [comment]
So this is likely an SDL2 issue, and as Wayland support is constantly evolving with SDL2 and in general, it's unlikely we can ensure that Wayland is always in a working condition. Once 2.0.22 rolls out, I can check if that would resolve the issue, and ship it with a next version. For now, you can try to compile the project yourself by disabling use of bundled libs in `CMakeList.txt` and installing `sdl2-git` package, maybe that will get Wayland running.

I don't currently have a Wayland-capable debugging setup, but I'll try to set one up at some point and see more precisely what''s broken.

**Comment by Aciz** [comment]
Well that didn't take long to setup...

Seems it's not actually SDL2 issue per se, but a GLEW upstream issue
https://github.com/nigels-com/glew/issues/172

This can be probably worked around though.

**Comment by Eonfge** [comment]
> Well that didn't take long to setup...

@Aciz Forgive me for asking? Was it actually easy to set up or was it a bit idiosyncratic? I Also write guides for Fedora Magazine and I'm always on the look-out for technology that needs better explaining?

**Comment by Aciz** [comment]
> > Well that didn't take long to setup...
> 
> @Aciz Forgive me for asking? Was it actually easy to set up or was it a bit idiosyncratic? I Also write guides for Fedora Magazine and I'm always on the look-out for technology that needs better explaining?

Wasn't hard, just had to install gnome shell (running on Arch with i3 + picom with nvidia).

**Comment by Eonfge** [comment]
Interesting problem. I know that Desktop Environments like GNOME, KDE and XFCE app support Flatpaks but I never gave mush thought about basic window managers. Might be worth looking into a bit.

As for the issue; The game still runs on Wayland with XWayland, so nothing critical.

**Comment by Aciz** [comment]
@Eonfge a build including this fix is now available over at https://www.etlegacy.com/workflow-files, could you verify that it runs for you now?

**Comment by Eonfge** [comment]
It seems to work for me. I made a draft here so you can test it as well:
https://github.com/flathub/com.etlegacy.ETLegacy/pull/18

I did run into some weird behaviour. I have a dual monitor setup but the game start on the second screen, so that might require some tweaking.
