### ISSUE TITLE
Map gamepad on android

### ISSUE THREAD

**Issue by Martijnsx** [etlegacy/etlegacy#1914]
Since a long time player of ET Legacy i was looking for ways to play the game on an hand held. 

To my surprise there is an android version of the game. I installed it and wanted to play with a bleutooth gamepad. However, mapping the keys to the gamepad is not working. I tried on 2 gamepads (saitake 7007F and Ipega PG-9167) and 2 different phones. Not all keys can be registered. Also the touch operation of the game is not suited for key by key mapping. What goes wrong i do not know exactly but try mapping yourself with a bluetooth gamepad and see it does not work well.
 

Will you be adding proper bluetooth controllers settings or will you add a description on how to play with a bluetooth controller on android?

Maybe give this a high priority because why have an android version while we can not play it with a controller?

Thnx

**Comment by rafal1137** [comment]
Changes are in master. And it can be closed

**Comment by Martijnsx** [comment]
Hi Rafal,
Does this mean that bluetooth controllers can now be mapped and work on android ET?

Best regards,
Martijn

**Comment by rafal1137** [comment]
@Martijnsx 
Yes it is working for Android and also for Linux and Windows
