### ISSUE TITLE
Too much "LoadMenu" lines in file "ui/menus.txt" causes client to crash on Ubuntu

### ISSUE THREAD

**Issue by u1ps** [etlegacy/etlegacy#1924]
Adding custom menus causes crash on Ubuntu. Works without problems on Windows OS. Below is just a quick file that creates duplicate of in game main menu. You can load it on windows without problem, loading it in Ubuntu will cause crash. Is there some kind of limitation in Ubuntu and is there a way to fix it, allow more lines? or perhaps the issue is somewhere else
[loadmenu.zip](https://github.com/etlegacy/etlegacy/files/8193035/loadmenu.zip)

**Comment by ensiform** [comment]
What's the error message?

**Comment by Aciz** [comment]
Probably x64 issue rather than OS specific, does it happen with x86 client on Ubuntu?

**Comment by mittermichal** [comment]
It didn't crash for me on ubuntu 64bit nor 32bit

**Comment by mittermichal** [comment]
ok it crashed now:
0 UI_Alloc: Failure. UI out of memory!

**Comment by mittermichal** [comment]
increasing MEM_POOL_SIZE in ui_shared.c fixes this.
ui_report after increase:
```
]\ui_report
Memory/String Pool Info
----------------
String Pool is 67.9% full, 267012 bytes out of 393216 used.
Memory Pool is 53.8% full, 2256480 bytes out of 4194304 used.
```

@u1ps what does `ui_report` say on windows?

**Comment by u1ps** [comment]
ui report no mods loaded *windows
![uidef](https://user-images.githubusercontent.com/99591943/156939153-dcf0cc0f-af2e-496b-b5a9-c383a1428928.png)
ui report with mod active *windows
![uinew](https://user-images.githubusercontent.com/99591943/156939189-71003f65-09f1-4f2c-a2c9-67b66af47a9e.png)

**Comment by ensiform** [comment]
For reference I just increased the memory pools double on ETe's etmain portion so similar could be done here.

https://github.com/etfdevs/ETe/commit/76d6c516427a8f33a98313d4c870ffce5aff9758

**Comment by u1ps** [comment]
Just giving some more info on the case. Menu mod was run on legacy server and Ubuntu and Mac users started experiencing crashes when connecting to server, no problems on windows users. Is it possible to increase memory pool size in future updates of Legacy, if it does not cause any harm or issues? That should fix the issue and will prevent similar cases in future.

**Comment by Aciz** [comment]
Yeah should not be an issue to increase it afaik, it's just an arbitrary limit. But again, this is x86/64 issue, x64 takes up more memory and thus fills up the allocated memory, resulting in crash.

**Comment by Aciz** [comment]
This should be resolved by https://github.com/etlegacy/etlegacy/commit/3868bf31650cd791b37135a3231765ca26deda29
