### ISSUE TITLE
slow mouse speed and zoomed skybox when dying while sniping

### ISSUE THREAD

**Issue by mittermichal** [etlegacy/etlegacy#1925]
how to reproduce:
- `devmap etl_supply`
- spawn as allied sniper
- zoom with sniper
- `give health -100`

I tried to debug it. Issue seems with `cg.zoomval` - it's not reset to 0 when player dies.
![2022-03-06-192523-etl_supply](https://user-images.githubusercontent.com/4035800/156936712-a071af4b-8eb3-43bf-bd9e-909d2bbed01e.jpg)

**Comment by mittermichal** [comment]
https://clips.twitch.tv/IgnorantWimpyAdminTTours-sEpf9bLobH4KCHny

**Comment by isRyven** [comment]
it's rather a skyboxportal issue, same thing happens when you die being mounted to the tank (eg. dingenskirchen)

**Comment by ryzyk-krzysiek** [comment]
I've never seen the issue with skybox, but I saw that sensitivity and zoom issue more than a month ago when I played a lot on TM servers with FG42.

From what I checked it was introduced here https://github.com/etlegacy/etlegacy/issues/1359
I think this is ok way to fix this https://github.com/ryzyk-krzysiek/etlegacy/commit/b57f1d5efd083c7a4fab93b740f58e14318816c3
or maybe move the third person check inside here https://github.com/etlegacy/etlegacy/blob/06757b9021e4adc5e85f3c41caeb9dcb97f2e0a3/src/cgame/cg_view.c#L901-L911
