### ISSUE TITLE
"validate_openURL" does not open "ui_finalURL"

### ISSUE THREAD

**Issue by DanTheMann15** [etlegacy/etlegacy#1934]
ETL Version: 2.79.0 RELEASE

when i edit a custom menu to add my clan's website URL, the **_exec "set ui_finalURL [URL]"_** function doesn't work. and it keeps opening https://www.etlegacy.com instead of https://ets-clan.com. it worked fine in previous versions of etlegacy (such as 2.77.0)

here's the ets_slinks.menu and ets_site.menu from the latest release build of menu version 5.1.1 for etlegacy. [menu-snippets.zip](https://github.com/etlegacy/etlegacy/files/8385290/menu-snippets.zip)

this exact same code works just fine in every other mod, but not in the latest version of etlegacy.

If anyone can look into this issue, please let me know. - Ets|PsycoPappy 4

**Comment by u1ps** [comment]
This is how github link works under credits, if it helps:

`BUTTON( SUBWINDOW_X+6, SUBWINDOW_Y+SUBWINDOW_HEIGHT-24, .5*(SUBWINDOW_WIDTH-18), 18, _("YES"), .3, 14, close etlegacy_github ; uiScript validate_openURL "https://github.com/etlegacy/etlegacy/" )`

**Comment by DanTheMann15** [comment]
i wonder if they removed the set ui_finalURL function in ETL. because this appears to be direct.

i'll do tests and maybe see if i can use a clever trick to make it work under 1 menu.

**Comment by Aciz** [comment]
It was removed as part of 92140a1641f9fc9d0d7092df7aef1d99a9576bdc, `validate_openURL` is the command you want to use.

**Comment by DanTheMann15** [comment]
@Aciz - that sucks... 

i found that `exec "set ui_finalURL "URL""` indeed still sets your UI Final URL, but `uiScript validate_openURL` is not opening the value set in `ui_finalURL`, since it was changed to just open https://www.etlegacy.com

the only way i can get the game to open a site is to add the URL directly to uiScript validate_openURL.
(thanks for pointing it out @u1ps)

example: `uiScript validate_openURL "https://ets-clan.com"`

but i like to give users the "are you sure" choice when opening a website URL or connecting to a server before interrupting your game to take you to the website.

`ets_site.menu` is the shared confirmation window that allows the user to say yes or no to opening a website they click on in the menu, it relies on the `ui_finalURL` value set when the user clicks on a button in the ETS Site Links menu `ets_slinks.menu`.

but now the confirmation window can't work because of the inability to open the URL set in ui_finalURL. i need an alternative.
so i am trying to figure out how to get around this without cloning the confirmation window several times just to point it to a different URL.

**Comment by DanTheMann15** [comment]
*Bump

As this issue still remains unresolved, i am dropping ET Legacy support in my server menus unless there is an alternative to temporarily persist selected URL's or re-enabling ui_finalURL, as i am unwilling to clog up menus.txt and fattening-up the menu's pk3 with redundant custom menus just to have a subwindow for each individual URL.

it's super efficient to use the same popup window as a confirmation window as i stated above. which keeps the server menu tidy, efficient and tiny. who doesn't like a server menu that packs several features in a small ~19KB package?

**Comment by x0rnn** [comment]
Maybe related? https://github.com/etlegacy/etlegacy/issues/2335

**Comment by rafal1137** [comment]
@DanTheMann15 As default `validate_openURL` is using etlegacy.com page unless you specify it yourself
https://github.com/etlegacy/etlegacy/blob/fed9528388ac16ea68fb3c9e35a6cd6745f3405e/src/ui/ui_main.c#L5901-L5911

And it should work but things happen it will not work from time to time start. Currently taking a look at specific issue with in_game upgrade issue.

And as reference you should play with those finding:
https://github.com/search?q=repo%3Aetlegacy%2Fetlegacy%20validate_openURL&type=code

And see if any of those works or wait for my fix that would be the fix for this and mentioned issue.

**Comment by rafal1137** [comment]
@DanTheMann15 So yeah there is final note from me. It is working but there is a catch in in_game menu for some reason it does not accept MOUSE input but only Keyboard ENTER key.

So yeah you should  specify  the link for it.
```
BUTTON( SUBWINDOW_X+7, SUBWINDOW_Y+SUBWINDOW_HEIGHT-26, .5*(SUBWINDOW_WIDTH-18), 20, "^7Yes", .25, 14, close ets_site ; uiScript validate_openURL "https://ets-clan.com" )
```

Waiting for your response.

**Comment by DanTheMann15** [comment]
I've written this statement before above, but i have to write it again. :\

How the menu's website links worked is that it uses `exec "set ui_finalURL https://example.com"` to when a user clicks a website link button.

in `ets_slinks.menu` when the ets website button for example is pressed, this gets executed:
`BUTTONEXT( 40, 120, 160, 22, _("^1Ets^0|^7Website"), .25, 14, exec "set ui_finalURL https://ets-clan.com"; open ets_site, tooltip _("https://ets-clan.com") )`

it then opens `ets_site.menu` which is the confirmation window.

if a user clicks "No", it closes the subwindow and goes back to the "Site Links" menu.
if a user clicks "Yes", it then executes `uiScript validate_openURL` and opens the website set in `ui_finalURL`.

but since `92140a1`, ui_finalURL is no longer able to persist custom URL's and is permanently set to `https://www.etlegacy.com` so when users click "Yes", they are taken to etlegacy.com instead of the intended website.

`ets_site.menu` is meant to be the confirmation window for ALL websites, but now if i want to get around this new limitation, i'd have to make a copy of `ets_site.menu` for each website and that's really inefficient and no other mod has this problem.

the other option is to remove `ets_site.menu` but then the game would close and the website will open instantly if the user clicks a website button. and sometimes that just sucks.

**Comment by rafal1137** [comment]
@DanTheMann15 As stated  above validate_opneURL if not explicit set, it falls to default website which is `etlegacy.com`
For a reason why `ui_finalURL` was removed take a look at commit message.
There is no need to make a new copies of `ets_stite.menu` for every website you just edit existing one to make use of 

```
BUTTONEXT( 40, 120, 160, 22, _("^1Ets^0|^7Website 1"), .25, 14, clearFocus ; uiScript validate_openURL "https://ets1-clan.com", tooltip _("https://ets1-clan.com") )
BUTTONEXT( 40, 120, 180, 22, _("^1Ets^0|^7Website 2"), .25, 14, clearFocus ; uiScript validate_openURL "https://ets2-clan.com", tooltip _("https://ets2-clan.com") )
```

Also if you do not specify to the param to quit a game when button is clicked there is no way game will quit

**Comment by DanTheMann15** [comment]
> @DanTheMann15 As stated above validate_opneURL if not explicit set, it falls to default website which is `etlegacy.com` For a reason why `ui_finalURL` was removed take a look at commit message. There is no need to make a new copies of `ets_stite.menu` for every website you just edit existing one to make use of
> 
> ```
> BUTTONEXT( 40, 120, 160, 22, _("^1Ets^0|^7Website 1"), .25, 14, clearFocus ; uiScript validate_openURL "https://ets1-clan.com", tooltip _("https://ets1-clan.com") )
> BUTTONEXT( 40, 120, 180, 22, _("^1Ets^0|^7Website 2"), .25, 14, clearFocus ; uiScript validate_openURL "https://ets2-clan.com", tooltip _("https://ets2-clan.com") )
> ```
> 
> Also if you do not specify to the param to quit a game when button is clicked there is no way game will quit

this doesn't get me the desired behavior, it just instantly opens your browser to the site without a confirmation window and makes the game flash as it tries to minimize.

What i want is that if you click a button in `ets_slinks.menu`, it opens a confirmation subwindow "`ets_site.menu`" and asks the user a Yes or No question.

if yes -> open the website you selected and minimize or close game.
if no -> close subwindow and return to ets_slinks.menu

btw, slinks is short for "Site LINKS".

here's the current version of the server menu for et legacy, looking at it's code should give you the full understanding how it works.
[ets_etlegacy-menu_5.1.2_10D95_release.zip](https://github.com/etlegacy/etlegacy/files/12330566/ets_etlegacy-menu_5.1.2_10D95_release.zip)

Just note the pk3 and the files inside are read only, you'll need to change the attributes if you are going to edit it to suggest what i could do different that gets me the behavior i want without ui_finalURL.

i'll do testing of my own as well.

everything works perfectly on ET Legacy versions 2.77 through 2.78.1, but got broken in 2.79.0 and later.

it's easy to fix the link for the rules as it uses it's own confirmation subwindow.

**Comment by rafal1137** [comment]
@DanTheMann15 So yeah I had to make seperate file for every link:
[ets.zip](https://github.com/etlegacy/etlegacy/files/12359421/ets.zip)

All things work exept etkey but well it just need to be fixed

**Comment by DanTheMann15** [comment]
> @DanTheMann15 So yeah I had to make seperate file for every link: [ets.zip](https://github.com/etlegacy/etlegacy/files/12359421/ets.zip)
> 
> All things work exept etkey but well it just need to be fixed

I think you see what i mean now. ;)

also note the filesize (in bytes) as well: 18,340 → 62,649
in that amount of space (despite being tiny) i can fit 3 and ⅜ pk3's of the original menu.

it really goes to show how ui_finalURL really did help a lot on making menus super efficient.

**Comment by rafal1137** [comment]
@DanTheMann15 Yeah meaby efficent but as author of those changes pointed at abusability of it.
We need to decide here do we get old behaviour back with abusability of it or we keep current changes with preventing those.

**Comment by DanTheMann15** [comment]
@rafal1137 I'm not sure how vulnerable ui_finalURL really is, but as far as i know there is no record of anyone abusing it, especially nowadays with fewer and fewer people playing enemy territory as time goes on.

you and the rest of the dev team can ultimately decide on whether or not to restore ui_finalURL's functionality, i have no power over that. but it's a real pity that i would have to make separate confirmation subwindows for each site.

i plan on making an update v5.2 that does that just to fix the website linking issues, but v6.0 (and any version later) will be completely incompatible with etlegacy. (i'll explain why later).

also, can you show or tell me an example of how ui_finalURL can be abused, it'd give me better insight.

**Comment by rafal1137** [comment]
Meaby it was about .cfg files being culplit here.
But I have solution here:
https://github.com/etlegacy/etlegacy/commit/43910ea4732d29013e409b0beb27573113003932

I can see your point here. 
Are you abble to build from this branch ?

**Comment by DanTheMann15** [comment]
@rafal1137 re-enabling ui_finalURL will restore broken functionality in the server menus and allow 6.0 support.

as for building on that branch, i can clone it but i'd need to figure out how to get the opengl dev libs set up in msys2 as i'd build it using cmake via mingw64, but that would take me some time.

**Comment by rafal1137** [comment]
@DanTheMann15 I compiled it myself here take it and test it is `tar.gz` package its builded like in every release/snapshot just copy required files or run from here it is your choise:
https://www.dropbox.com/scl/fi/dubwrib1sz2zeev6za12h/etlegacy-v2.81.1-275-gf727a23-x86_64.tar.gz?rlkey=4a0wfs879lo557y1gs16hlb33&dl=0


PS: It is only 64bit and as for testing purpose

**Comment by DanTheMann15** [comment]
thanks, i'll test-drive it on ubuntu!

**Comment by DanTheMann15** [comment]
@rafal1137 I have ran it on my ubuntu installation, easy as pie.

I have tested the release 5.1.2 of the server menu attached here (and above): [ets_etlegacy-menu_5.1.2_10D95_release.zip](https://github.com/etlegacy/etlegacy/files/12330566/ets_etlegacy-menu_5.1.2_10D95_release.zip)
here's the results:

the menu itself works as intended, but when i try opening websites i notice that there is a semicolon after the URL.
example: `https://ets-clan.com/index.php?/forums/ ;` which also has a side issue of opening the website incorrectly.

the other links `https://ets-clan.com` and `http://etkey.net` the game opens your browser but it doesn't open the target websites, only your browser's homepage opens, it probably has to do with that semicolon.

**Comment by rafal1137** [comment]
@DanTheMann15 Ok found the issue here I do terminate all ui_finalURL with `\n`
But this should be taken https://github.com/etlegacy/etlegacy/blob/fa79ee0b2c76dd2db75c0874dbe6c86a87f3e5e8/src/ui/ui_atoms.c#L113
```
set ui_finalURL https://ets-clan.com\n
```
[ui.zip](https://github.com/etlegacy/etlegacy/files/12841010/ui.zip)

So there are 2 solutions here we either terminate it on our side or in yours pk3
Looking forward for you answer

PS: Sorry for long delay

**Comment by DanTheMann15** [comment]
Sorry for taking so long, but i have been thinking about this based off my tests and from porting what will become the 3rd beta of ETS Menu 6.0 to ET Legacy.

I believe it's better to terminate it from the game's side so nobody gets confused when making their menus, so it'll behave just like on any other mod.

**Comment by rafal1137** [comment]
@DanTheMann15 Ok done. Now all links included in your pk3 works fine without weird extra chars in it.
Marking it as fixed/closed. Will merge changes to master.

**Comment by rafal1137** [comment]
@DanTheMann15 Done
https://github.com/etlegacy/etlegacy/pull/2402

**Comment by DanTheMann15** [comment]
👍🏻
