### ISSUE TITLE
Server cvar to show who spectators are spectating

### ISSUE THREAD

**Issue by x0rnn** [etlegacy/etlegacy#1935]
How about being able to see who spectators are spectating, like in Quake 3 or etjump, but with a server cvar that enables or disables the feature?

**Comment by Aciz** [comment]
I like the idea, but does it need a server side toggle? Why not a client side toggle?

**Comment by x0rnn** [comment]
Well I was thinking a server admin should maybe have the choice of what kind of information would be visible to the players, such as country flags, who spectators are spectating, and can't think of anything else at the moment xD

**Comment by mittermichal** [comment]
I think some spectators would not want to share who they are spectating

**Comment by Aciz** [comment]
So it could be done like `cg_countryFlags` - you decide if you share the information.

**Comment by x0rnn** [comment]
Possibly yes, but I'd leave that for the server admins to decide. Or yea, maybe also add a client cvar if someone wants that info hidden.

I don't remember exactly if in Quake 3 you could see the name of the player you spectated, or you could simply tell who someone was spectating because the pings shown were identical, but there wasn't an option to disable that. In Quake Live they removed that feature.

**Comment by Aciz** [comment]
Any client cvar can be forced by server admins if they so choose via sv_cvars, so having a client only option would be the most flexible - admin has control if the feature is available, but if it is, individual client still can hide it if he/she wants to.

**Comment by x0rnn** [comment]
> So it could be done like `cg_countryFlags` - you decide if you share the information.

Actually, this just shows/doesn't show the country flags of players for you, it doesn't enable you to explicitly not share that information if you don't want to.

**Comment by Aciz** [comment]
> Actually, this just shows/doesn't show the country flags of players for you, it doesn't enable you to explicitly not share that information if you don't want to.

Yeah, I mixed up the cvars there, the correct cvar is `cg_allowGeoIP`.
