### ISSUE TITLE
objective dissapears if its carrier gets revived while he is alive

### ISSUE THREAD

**Issue by mittermichal** [etlegacy/etlegacy#1936]
If player carries objective and gets revived with `revive` command while he is alive, then he doesn't carry objective anymore, but the objective is not returned.
not sure if this is worth fixing :D

**Comment by Aciz** [comment]
So is this about the revive at low hp LUA? I'm a bit confused with "revived while he is alive" part :D

**Comment by mittermichal** [comment]
its something else because when you use this command you get invul. shield and can't move for a while just like with regular revive

**Comment by mittermichal** [comment]
I guess `revive` is cheat command meant for development mode, so probably not worth bothering with.
Perhaps there might be some other cases where same thing can happen.

**Comment by Aciz** [comment]
Yes, it's a cheat command, and moreover it's a server command, not a client command.
