### ISSUE TITLE
Some new big icons render through walls.

### ISSUE THREAD

**Issue by randomek** [etlegacy/etlegacy#1943]
From ryzyk-krzysiek bellow:

Those are new voice chat icons, similiar to icons when you call for ammo or call for medic, so there is no issue with that per se. But they render through walls.

It started from 2.80 version.

Client config:
etlegacy-v2.80.0-i386
Ubuntu 20.04.4 LTS
![et1](https://user-images.githubusercontent.com/9695467/163055122-8d6399eb-5f14-4cf4-aabb-2acc70253057.png)
![et2](https://user-images.githubusercontent.com/9695467/163055131-a0c6a339-ccdb-477b-856c-158956e6c3f8.png)

Server: System:	(os.linux)ET Legacy v2.80.0 linux-x86_64 Apr 9 2022
TeamMuppet ETLegacy
Mod:	legacy v2.80.0

**Comment by ryzyk-krzysiek** [comment]
Those are new voice chat icons, similiar to icons when you call for ammo or call for medic, so there is no issue with that per se. But they render through walls.

![obraz](https://user-images.githubusercontent.com/4499367/163059100-d48e64dd-a6ce-4d1f-97f7-c5a549c66fc6.png)

**Comment by u1ps** [comment]
What about making additional icons customizable in options? Switch between default blue ! vs more detailed chat icons. If it is possible to make it so

**Comment by Aranud** [comment]
Fixed in d76bcf9b3f6b94f9ebd03eb5590e2c0a745227b6
