### ISSUE TITLE
Gibbing is sometimes not working properly

### ISSUE THREAD

**Issue by BystryPL** [etlegacy/etlegacy#1956]
https://clips.twitch.tv/ConcernedSpunkyAubergineBuddhaBar-08-5TpS6ubeyTp9u

In certain positions, it's impossible to 1-hit gib a corpse with a knife. In the situation above, I think that should've been a 1-hit gib. Could someone that have outdated software (2.60b) test this on ETPro as well if it behaves the same?

This happens too in other spots. Please close this ticket if this behavior is intended.

**Comment by HeDo88TH** [comment]
The clip shows gibbing on the body. The head was somehow behind the player and the knife could not reach it. If I recall correctly, the on-hit-gib happens if you gib the head of the corpse, not the body.
