### ISSUE TITLE
Gun sounds / step sounds gets doubled 

### ISSUE THREAD

**Issue by BystryPL** [etlegacy/etlegacy#1957]
https://clips.twitch.tv/NurturingZealousMonitorJebaited-GGdFzdx2SRpuoiQb

The gun sounds and step sounds gets doubled on a regular basis. This intensifies when the load on the network increases (streaming or playing on overpopulated server such as TM public).

**Comment by Aciz** [comment]
The fix in #1968 seems to be working well and there are no side effects reported, closing.
