### ISSUE TITLE
All new hitbox and bounding box system

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#198]
Author: @jackeri (Jacker)
Date: 2013-02-10
Redmine Issue: 198, https://dev.etlegacy.com/issues/198

---

The current system of hit detection is flawed and outdated in many ways, and as computers have gotten a lot quicker after the cold war the more complex calculation needed for detection is no longer a problem.

I think we should go with the common idea of bounding box which has the hit boxes inside of it.
We can use the animation skeleton to bind hit boxes more accurately to the model.

https://developer.valvesoftware.com/wiki/Hitbox

---

Related issue(s): #98, #109, #503

---

Related commit(s):
4d5f6793c5ed41ae58037765bbcadeceb9a58f72 - mod: use fixed height hitboxes from etpub, refs 1..
 f24596c5b8a4574b636e86b33b079ecaef4f5adb - game: added g_debugHitboxes CVAR_CHEAT, refs 198
 20cc5ff581390bb22e2a64503e65b9324cd0f06a - mod: use fixed height hitboxes from etpub, refs 1..
 2dea3c0fc9a8f29f3eb63dae51661e1ecffe372d - game: added g_debugHitboxes CVAR_CHEAT, refs 198
 c142cba01857c7be53f758b037f63f8cdd8b827b - game: g_debughitboxes fixed
 e1b640918e540180ed55185ce6f5d9154db84416 - game: fixed antilag trace functions to use our pro..
 2ef0fb06d052909dc013b63d2cae65cf158b8d6b - included the mdx files for the realhead code on qa..
 b501d55ded9e5e503090b66714001405e103aa30 - woops the macros were incorrect
 cc81256c7218e8f31c42b20b92f5408f38b106ca - only allow the sv_gettag to use client code on rel..
 5408aba40342eeb33d91e81150887cb9ba373689 - game: g_realhead added
 fa56a80da9cdeb42dec9435b6f112a62e3a7421b - mdx fixes
 2969011f6b032db29a48e76e6d0f7106214765c9 - game: clean up
 b31702535951fc049d1a7ff3d79f16bb4c628263 - fixed the build on non mdx configuration
 2b9d4cdcee65bdf983481694d3fd51053b10f95b - realhead code now works, but needs testing
 eac71cfb179335c44a15684d2eaacf8a3e81bcf0 - added missing code and uncrustified
 41effd953dc930040ce463faf15a95c1961cb680 - enable mdx support by default
 39d296a3c62e26d3b2576efec63c4db679a6260a - game: server side realistic hitboxes fixed
 23ca303a7dc0481992f312fb77d45cc6108b701c - fixed the infinite helmet bug, refs 198
 48e592773599ebb5ee5c24995c588c703bfe71ce - changed the frametime value to be calculated based..
 eb6b0b62c3635eb1fec5ca0d3bcddcfc6ffb0da3 - game: added Neil  Toronto's skip correction code
 3ec570f3cb23829ea8916bc0224217f863fe8b42 - game: fix warnings refs 735
 299c89d0f64ae93bdba63f056a76d0d151699de7 - enabled realhead also for proning players
 d6da69e18867c8c8d037491d88c130ee48fbfc66 - cgame: added comment about CG_RailTrail time value..
 1fccfc3943398c270c9ef10ae2a80ec0e49b50ff - mod: fixed prone hitbox height and debug hitbox re..
 6ff60b749d4cd0919020bd81b60e244c71ea33e6 - cgame: adjusted client side predicted hiboxes heig..
 b208525b48e1204afb06196706b2c46e8cc6e054 - game: fixed legs debug hitbox not displayed, refs ..
 d447aabebac6a95e6217a10ae3eba1cfc2f11ee6 - cgame: added client side head and legs debug hitbo..
 fabe421f0d407d9adfd969fade5f8ad7bd7096f5 - cgame: display debug hitbox for current alive clie..
 1a42738b476e2b044e3fd35d529dfc82eaccade6 - mod: small hitbox height optimization, refs 198 ..
 9952397d3be9e1e6210f9a0c9258b54cfb767014 - game: fixed debug hitbox head ent reference, refs ..

**Comment by ETLegacyTeam** [comment]
From: @adanski (Dragonji)
Date: 2013-05-11T10:15:38Z

---

I think it is not a good idea to add such accurate hitboxes to W:ET. People who play the game for years are used to the big boxes they played with for the whole time.

Jaymod and N!tmod for example have options to use such hitboxes:

!http://obrazki.elektroda.pl/9445010600_1368266722.jpg!

And they are a complete fail in my opinion, almost none server use them because as I said previously people are used to the ones they played with for years, the accurate ones completely change gameplay as players become unhittable. The other thing is that mid server can become a lag fest with such hitboxes even if running on Core i7 machine...

I'd only like to suggest to just slightly adjust original/ETPro hitboxes, what I' thinking about is something like this:

!http://obrazki.elektroda.pl/9863735000_1368266180.png!

Bodybox ending at the shoulders level instead of the top of the head, it is a big change already but worth implementing in my opinion so:
1. Players won't become unhittable
2. Players won't be "granted" with bodyshots while shooting at the head level anymore.

**Comment by ETLegacyTeam** [comment]
From: Mateos (Mateos)
Date: 2013-05-11T10:46:14Z

---

It is supposed to be an option isn't it?

N!tmod is quite popular, even if the hitboxes are tinier. As well, there's people who likes it, people doesn't.

Not sure about setting the majority on a side or the other one :) Personally I see it as a extra challenge, be more accurate. At least you know that you hit what you shoot with such new hitboxes, while laggers can hit anything with the etmain one, even if they shoot totally left of right :/

**Comment by ETLegacyTeam** [comment]
From: @adanski (Dragonji)
Date: 2013-05-11T10:59:03Z

---

Mateos wrote:
> N!tmod is quite popular, even if the hitboxes are tinier. As well, there's people who likes it, people doesn't.
N!tmod by default uses the same big boxes as other mods and ETPro, the picture I posted is just an option which can be enabled but doesn't have to. I know only 1 server which uses realistic N!tmod hitboxes and it is the server of N!tmod devs.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2013-05-11T11:24:44Z

---

Dragonji wrote:
> Mateos wrote:
> > N!tmod is quite popular, even if the hitboxes are tinier. As well, there's people who likes it, people doesn't.
> N!tmod by default uses the same big boxes as other mods and ETPro, the picture I posted is just an option which can be enabled but doesn't have to. I know only 1 server which uses realistic N!tmod hitboxes and it is the server of N!tmod devs.

You can't make everybody happy, so make this a cvar. A more modern, accurate hitbox system is definitely welcome, especially if the mod wants to become active on the pro-scene. Lag compensation will do the rest.

**Comment by ETLegacyTeam** [comment]
From: @adanski (Dragonji)
Date: 2013-05-11T12:54:49Z

---

Spyhawk wrote:
> Lag compensation will do the rest.
Well I don't think so, as some mods use Neil Toronto's Unlagged code and it still feels like players were unhittable with smaller hitboxes. The problem with this is spread, if you decide to make hitboxes much smaller, you should also decrease spread of weapons.

EDIT:
Damn, I mean spread of course, not recoil.

**Comment by ETLegacyTeam** [comment]
From: @saukko28 (Saukko)
Date: 2013-05-11T15:39:14Z

---

I have always been against the ETPro hitboxes and I still won't change my mind. Those hitboxes are the worst hitboxes with Jaymod. I think Jaymod might have new hitboxes but still has that awful hit detection as usually. When there is a standing player on ETPro and you shoot almost a meter to left or right you will still hit the enemy. So yeah I would rather be with the idea to make a CVAR out of this. Make one for accurate hitboxes and for the hitboxes like ETPro's (bähhh).

-*S

**Comment by ETLegacyTeam** [comment]
From: @adanski (Dragonji)
Date: 2013-05-11T16:20:31Z

---

All of the mods has got same hitboxes as ETPro by default (at least if talking about size), an only exception is NQ where bodybox doesn't cover head :)

But yeah, why not to make tiny boxes as a cvar, I just think it is a waste of time, I doubt anyone will ever use such realistic CS-like ones.

**Comment by ETLegacyTeam** [comment]
From: @jackeri (Jacker)
Date: 2013-05-11T20:33:06Z

---

Just to point out that a big part of the hitbox system update is that the hitboxes would actually use the bone data, now the hitboxes are pretty much hard coded. Any one with a brain can see that its never a good idea to have hard coded vertex data when it should be read in and calculated properly per model and animation. When we move into a new model format that will be one thing i will be looking at.

**Comment by ETLegacyTeam** [comment]
From: @adanski (Dragonji)
Date: 2013-05-12T16:45:06Z

---

Jacker wrote:
> Just to point out that a big part of the hitbox system update is that the hitboxes would actually use the bone data, now the hitboxes are pretty much hard coded. Any one with a brain can see that its never a good idea to have hard coded vertex data when it should be read in and calculated properly per model and animation. When we move into a new model format that will be one thing i will be looking at.
That's what N!tmod does AFAIK.

Anyway, I hope it will be cvar-controlled.

**Comment by ETLegacyTeam** [comment]
From: @adanski (Dragonji)
Date: 2013-05-12T21:19:52Z

---

Jacker wrote:
> The current system of hit detection is flawed and outdated in many ways, and as computers have gotten a lot quicker after the cold war the more complex calculation needed for detection is no longer a problem.
> 
> I think we should go with the common idea of bounding box which has the hit boxes inside of it.
> We can use the animation skeleton to bind hit boxes more accurately to the model.
> 
> https://developer.valvesoftware.com/wiki/Hitbox

If you want such tiny hitboxes, that's absolutely fine. But you need to redefine the spread in the guns otherwise the game will be totally different from the one we used to play for 10 years.

The thing with CS is it's a slow game, strategic, and the game can be mastered with the aiming. In ET type game I don't think there is any place for extremely small hitboxes combined with vanilla spread. CS spread and hitboxes work, because it's so slow.

**Comment by ETLegacyTeam** [comment]
From: @jackeri (Jacker)
Date: 2013-05-13T07:33:07Z

---

The spread of the guns is already rather small for an fps game. Tbh the hitboxes aren't so small as you make them to be. You do understand that while the hitboxes are fine for the most part while the model is standing but they are bugged in many other postures? Fixin them by hardcoding is just pointles when we could just use bone data. This is rather an issue like people wanting to play 2.55 because it has bugs.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2013-11-20T19:35:28Z

---

Since ET:L still uses the terrible default etmain hitboxes, here is what I suggest for 2.71: implement the hardcoded "fixed" hitboxes from etpub, and do so by default (no cvar required) since these are more bugfix than a different hitboxes system. This would be only an intermediary step while the new hitboxes system is implemented later.

See the attached screenshots:

* lower the standing player's body hitbox to the shoulders.
* lower the crouching player's body hitbox to the shoulders.
* lower the wounded player's body hitbox to a reasonable height.
* lower the prone player's body hitbox to a reasonable height.
  
I'll try to find a way to fix the swimming hitbox too (not fixed in etpub). Also, the headboxes seem curiously accurate, although the code from g_realHead has not been implemented yet. Did I miss something here?

**Comment by ETLegacyTeam** [comment]
From: Mateos (Mateos)
Date: 2013-11-20T19:42:46Z

---

According to the screenshots, the entire bottom of the legs is still "safe", isn't it?

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2013-11-20T19:50:36Z

---

Yes. The etpub hitboxes aren't great, but they are still an improvement over the current situation.

**Comment by ETLegacyTeam** [comment]
From: Mateos (Mateos)
Date: 2013-11-20T19:58:12Z

---

It is possible to implement a more accurate system atm, or would the extra required work be not worth it?

Just to know, I'm not against it as this: is the system far different from the ETPro one?

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2013-11-20T20:15:01Z

---

As I understand it, ETPro hitboxes are similar to the etpub hitboxes above but with some work done on the antilag side (most of which has been incorporated in et:l already). See http://enemyterritorytips.wordpress.com/2008/11/22/hitboxes-in-enemy-territory-et-pro-reyaip-report/.

NQ hitboxes are much more complex, as shown here: http://www.crossfire.nu/journals/view/id/125816
This might be a too big change for 2.71 already, and the work involved might be not worth it if we want to implement a better skeleton hitbox system later.

Edit: NQ g_debugHitboxes shows default squared hitboxes like etpub/etpro, so the change above would bring legacy mod more or less on par with etpub/etpro/nq.

**Comment by ETLegacyTeam** [comment]
From: @adanski (Dragonji)
Date: 2013-11-21T21:05:58Z

---

Spyhawk wrote:
> NQ hitboxes are much more complex, as shown here: http://www.crossfire.nu/journals/view/id/125816
This is all Jaymod, Indloon posted pics from Jaymod docs.

This is NQ: http://imageshack.us/a/img69/2272/20110804220214goldrus##jpg

**Comment by ETLegacyTeam** [comment]
From: @realkemon (keMoN)
Date: 2013-11-22T09:49:20Z

---

I have to say, I'm not a fan of changing the wounded player hitbox. 
When I'm medic and want to revive someone (frequently with enemies around) I want to make that quick.
With that tiny hitbox you are most likely to miss the wounded player and since the animation of the syringe is horribly slow it takes nearly up to 2 seconds to give it another chance.

The reviving process is using the hitboxes as-well, isn't it? :P

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2013-11-22T19:20:22Z

---

Dragonji> Thx, so as I suspected it the NQ hitboxes aren't as complicated (see my edit above).

KeMon> Unless you're not even aiming at the wounded teammate, this change probably wouldn't make any difference for a medic. But it would certainly make it simpler to gib wounded players for the enemy. Double edge sword, you know.

Edit: harder->simpler

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2014-02-04T18:19:08Z

---

Spyhawk, can you tell us which hitbox issues are exactly fixed by your commits?

I've realized our debug vars g_debughitboxes and g_debugbullets show different hitboxes.
I think g_debugbullets still shows http://dev.etlegacy.com/attachments/download/215/standing_bug.jpg and g_debughitboxes shows http://dev.etlegacy.com/attachments/download/216/standing_fixed.jpg which is finally correct.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2014-02-04T19:58:54Z

---

IR4T4> Previous commits should have changed the hitbox height of the standing, prone and dead positions (see screenshots above). The swimming box is unchanged and still buggy (similar to standing hbox), since I've not been able to have a consistent height in all situation in water. Overall, the current hitboxes should be similar to ETPub default.

I'm not sure why you get different debughitbox, might be related to antilag that I overlooked.

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2014-02-04T21:11:20Z

---

Well ... we have no g_hitboxes cvar like etpub and we should use the ClientHitboxMaxZ adjustment for bullet/weapon related traces only (no need to do for all). Adjustments have to be done before the trapTrace call and in case you set the r.maxs[2] value on real game ents it should be undone after.

Edit: if you enable both cvars g_debugbullets 3 and g_debughitboxes 1 you'll notice the difference in both debug views.

**Comment by ETLegacyTeam** [comment]
From: @saukko28 (Saukko)
Date: 2014-12-16T23:56:27Z

---

Head hitbox seems very random to me. I can take a demo footage of it. I just doubt it would be spread causing such unreliability. I actually can finally finish my enemy with headshots when he is on the ground. Significant improvement to the better. Going to try a bit more later on to see some more.

-*S

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2014-12-16T23:59:07Z

---

Players now have unlimited helmets (helmet pops up, but another reappears on the model). The responsible commit seems to be "39d296a3c62e26d3b2576efec63c4db679a6260a":https://github.com/etlegacy/etlegacy/commit/39d296a3c62e26d3b2576efec63c4db679a6260a

**Comment by ETLegacyTeam** [comment]
From: @jackeri (Jacker)
Date: 2014-12-17T12:06:27Z

---

Spyhawk wrote:
> Players now have unlimited helmets (helmet pops up, but another reappears on the model). The responsible commit seems to be "39d296a3c62e26d3b2576efec63c4db679a6260a":https://github.com/etlegacy/etlegacy/commit/39d296a3c62e26d3b2576efec63c4db679a6260a

Fixed!

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2016-09-05T13:17:32Z

---

We should have another look at this, as Jaymod (now open sourced) implements hitboxes based on skeleton animation.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-01-27T19:19:48Z

---

{FIXME} Tracked in #1120.

* fix debug hitbox code
* add missing debug hitbox
* adjust hitbox height to improve prediction (ZMax)
..

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-01-28T20:01:37Z

---

Moving to 2.77 for the hitbox debug code.

**Comment by rmarquis** [comment]
Since the current hitboxes are pretty standard across most ET mods (ETPro excluded), let's close this ticket and focus on the better hitboxes model described in #1404 for further improvement.

Note: the current underwater/swimming hitbox isn't quite right, but nobody else could fix it due to code limitation. Maybe we'll achieve something better with that new model.
