### ISSUE TITLE
Discord Overlay

### ISSUE THREAD

**Issue by bnikkhah** [etlegacy/etlegacy#1981]
I'm a regular user of Discord and it would be great to have the Discord overlay work for ET Legacy. Does it work for anyone else?

Thanks for the help!

**Comment by Aciz** [comment]
Works fine for me (at least on Windows, no idea if it's even supported on other platforms). Is Discord detecting ET: Legacy for you already? It doesn't detect it by default, you need to manually add it.

**Comment by bnikkhah** [comment]
I tried to manually add it, but unfortunately it doesn't appear for me. And I have Windows 11.

**Comment by Aciz** [comment]
The game needs to be running while you add it, it won't appear otherwise. If it doesn't appear even then, maybe it has something to do with Win 11.

**Comment by bnikkhah** [comment]
> The game needs to be running while you add it, it won't appear otherwise. If it doesn't appear even then, maybe it has something to do with Win 11.

That worked! Thank you so much! :)
