### ISSUE TITLE
SDL renderer causes a SEGFAULT

### ISSUE THREAD

**Issue by Janno58** [etlegacy/etlegacy#1996]
My game crashed with same stacktrace as in #1190. So i have been trying to isolate what is causing it. And i believe i have a cure and a probable cause. 

The game only seems to crash when you use a SDL that is compiled with `-DSDL_RENDER=ON`.
Game works fine with bundled SDL because etlegacy turns the SDL_RENDER off explicitly.

If your distro SDL causes a crash you can disable the renderer with: `SDL_FRAMEBUFFER_ACCELERATION=false`

This fixes the symptoms but i think the real problem lies in `sdl_glimp.c`
Specifically the splash drawing functions in` GLimp_Splash`

This function seems to use `SDL_GetWindowSurface` that in documentation states:

> You may not combine this with 3D or the rendering API on this window.

If you comment out `SDL_UpdateWindowSurface` the game again works fine.

From what i have been able to figure out is that if you have `SDL_RENDER=on` then `SDL_GetWindowSurface` will create a OpenGL renderer that will conflict with etlegacy renderer. 

If you disable SDL render then SDL will use basic X11 functions to draw the splash screen and the game works.

**Comment by Aciz** [comment]
Great find! I've been scratching my head a bit with this one already in #1978. Interestingly, even without using the bundled SDL, the 2.0.20 version works fine, so something must have changed in SDL side for .22 regarding this.

**Comment by biopsin** [comment]
@Janno58 are you able to test against SDL2 2.24.0?

**Comment by Aciz** [comment]
Fixed as part of 5935e4e52d8c7c69201ca3ce448170d7dece2fe5, the splash screen itself is not functional but it no longer segfaults.
