### ISSUE TITLE
Server crash - etlegacy-v2.80.2-61-g4f8f910 - cgame.mp.x86_64.so

### ISSUE THREAD

**Issue by csmaxpower** [etlegacy/etlegacy#2061]
Attempting to run the latest snapshot (`etlegacy-v2.80.2-61-g4f8f910`) and cannot get the server to start due to the following.

# Error found in etconsole.log
```
700 ********************
ERROR: Failed to locate cgame.mp.x86_64.so for pure server mode. You'll probably need cgame for other platforms too.
********************
     700 Server attack log closed
     700 ----- Server Shutdown (Server crashed: Failed to locate cgame.mp.x86_64.so for pure server mode. You'll probably need cgame for other platforms too.
) -----
```
[etconsole.log](https://github.com/etlegacy/etlegacy/files/9122104/etconsole.log)

**Comment by ryzyk-krzysiek** [comment]
Possibly related to https://github.com/etlegacy/etlegacy/pull/2042?

**Comment by ensiform** [comment]
The server does in fact have the matching cgame file listed in a pk3, right?

**Comment by ryzyk-krzysiek** [comment]
Latest snapshot `etlegacy-v2.80.2-62-g5d7bc7d` looks to be fine, can you checkout if it works for you too? Seems like something went wrong with pk3 building on previous.

**Comment by csmaxpower** [comment]
This did indeed fix the issue.  Can confirm it works on latest snapshot of `etlegacy-v2.80.2-65-gb91f30a` as well.  Thank you for the quick fix!

**Comment by ensiform** [comment]
Yeah the snapshot that was having a problem was literally missing the mod files for that platform.
