### ISSUE TITLE
vehicle shadow disappears

### ISSUE THREAD

**Issue by mittermichal** [etlegacy/etlegacy#2072]
Vehicle shadow disappears, but reappears when looking downwards. It works fine on 2.60b.
![2022-07-24-131052-etl_supply](https://user-images.githubusercontent.com/4035800/180644700-56e41974-0f8f-469a-a310-38a377d03262.jpg)
![2022-07-24-131050-etl_supply](https://user-images.githubusercontent.com/4035800/180644703-62f472f6-2f04-4ecd-8243-29f3bc5b429c.jpg)

**Comment by rafal1137** [comment]
It does also flicker when you aim at specified angle and move around.

**Comment by suburbski** [comment]
ETe has a wip branch for this, see [here](https://github.com/etfdevs/ETe/issues/74)

**Comment by mittermichal** [comment]
nice, thanks!
