### ISSUE TITLE
Server error after a few maps with "ERROR: info_limbo_camera cannot find target"

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#208]
Author: @JanSimek (Radegast)
Date: 2013-02-12
Redmine Issue: 208, https://dev.etlegacy.com/issues/208

---

Dedicated server crashes after several hours of uptime with this error:
```
********************
ERROR: info_limbo_camera cannot find target

********************

```

ETPub code of @info_limbo_camera@ and @G_FindByTargetname@ functions is the same as in ET:L.

```
------------------------------------------------------------
InitGame: \g_heavyWeaponRestriction\100\mod_url\www.etlegacy.com\omnibot_playing\0\P\-121212121212\g_maxlivesRespawnPenalty\0\voteFlags\63979\g_balancedteams\1\g_maxGameClients\0\g_covertopsChargeTime\30000\g_soldierChargeTime\20000\g_LTChargeTime\40000\g_engineerChargeTime\30000\g_medicChargeTime\45000\g_bluelimbotime\20000\g_redlimbotime\30000\gamename\legacy\g_axismaxlives\0\g_alliedmaxlives\0\g_gametype\6\g_antilag\1\g_voteFlags\0\g_minGameClients\2\g_needpass\0\g_maxlives\0\g_friendlyFire\1\sv_allowAnonymous\0\sv_floodProtect\0\sv_maxPing\0\sv_minPing\0\sv_maxRate\25000\sv_maxclients\32\sv_hostname\ET: Legacy Test Server\sv_privateClients\2\mapname\golddays_v4\protocol\84\timelimit\20\version\ET 2.60b linux-i386 May  8 2006
Map changed, clearing player stats.
Cvar_Set2: g_scriptName
Enable spawning!
Cvar_Set2: g_gravity 800
G_PickTarget: target allied_spawn not found
G_PickTarget: target axis_spawn not found
Cvar_Set2: g_redlimbotime 15000 
Cvar_Set2: g_bluelimbotime 30000
Cvar_Set2: timelimit 20
G_PickTarget: target axis_spawn not found
ERROR: Can't find models/mapobjects/goldbox_sd/goldbox.tag
ERROR: Can't find models/mapobjects/goldbox_sd/goldbox_trans_red.tag
G_SetEntState: entity 112 already in desired state [0]
ERROR: Can't find models/mapobjects/goldbox_sd/goldbox_trans_red.tag
G_SetEntState: entity 113 already in desired state [0]
ERROR: Can't find models/mapobjects/goldbox_sd/goldbox.tag
ERROR: Can't find models/mapobjects/goldbox_sd/goldbox_trans_red.tag
G_SetEntState: entity 115 already in desired state [0]
ERROR: Can't find models/mapobjects/goldbox_sd/goldbox.tag
ERROR: Can't find models/mapobjects/cmarker/cmarker_crates.tag
ERROR: Can't find models/mapobjects/cmarker/cmarker_flag.tag
ERROR: Can't find models/mapobjects/miltary_trim/sandbag1_45.tag
ERROR: Can't find models/mapobjects/cmarker/cmarker_flag.tag
ERROR: Can't find models/mapobjects/cmarker/cmarker_crates.tag
ERROR: Can't find models/mapobjects/radios_sd/compostalliedopened.tag
ERROR: Can't find models/mapobjects/radios_sd/compostaxisopened.tag
ERROR: Can't find models/mapobjects/radios_sd/compostneutralclosed.tag
ERROR: Can't find models/mapobjects/pump_sd/pump_base.tag
ERROR: Can't find models/mapobjects/pump_sd/pump_animated.tag
ERROR: Can't find models/mapobjects/cmarker/cmarker_flag.tag
ERROR: Can't find models/mapobjects/cmarker/cmarker_crates.tag
ERROR: Can't find models/mapobjects/cmarker/cmarker_flag.tag
ERROR: Can't find models/mapobjects/cmarker/cmarker_crates.tag
ERROR: Can't find models/mapobjects/cmarker/cmarker_flag.tag
ERROR: Can't find models/mapobjects/cmarker/cmarker_crates.tag
Disable spawning!
ERROR: Can't find sound/maps/golddays_v4.sps
0 teams with 0 entities
-----------------------------------
Setting MOTD...
Game Initialization completed in 0.03 seconds.
Omni-bot: Looking for /home/etlegacy/etlserver/mods/legacy/omni-bot/omnibot_et.so, 
Omni-bot: Found Omni-bot: /home/etlegacy/etlserver/mods/legacy/omni-bot/omnibot_et.so, Attempting to Initialize
Omni-bot: Omni-bot Loaded Successfully
ET autoexec script executed. 
ERROR Loading Waypoints.
Bot Initialized in 0.09 seconds.
Omni-Bot Initialization completed in 0.10 seconds.
Cvar_Set2: gamestate 1
G_SetEntState: entity 199 already in desired state [0]
G_SetEntState: entity 200 already in desired state [0]
G_SetEntState: entity 197 already in desired state [0]
G_SetEntState: entity 195 already in desired state [0]
G_SetEntState: entity 203 already in desired state [0]
Cvar_Set2: com_errorMessage info_limbo_camera cannot find target

********************
ERROR: info_limbo_camera cannot find target

********************
----- Server Shutdown -----
Sending heartbeat to etmaster.idsoftware.com
==== ShutdownGame (0)====
-- Script System Info --
Current Memory Usage 1.85209 MB
Soft Memory Usage 1.8 MB
Hard Memory Limit 2 MB
System Memory Usage 1.82929 MB
Full Collects 0
Inc Collects 0
GC Warnings 0
Threads: 0, 0 Running, 0 Blocked, 0 Sleeping
ShutdownOmniBot
ShutdownGame:
------------------------------------------------------------
Cvar_Set2: session 6 0 golddays_v4
Cvar_Set2: fireteam0 \id\-1
Cvar_Set2: fireteam1 \id\-1
Cvar_Set2: fireteam2 \id\-1
Cvar_Set2: fireteam3 \id\-1
Cvar_Set2: fireteam4 \id\-1
Cvar_Set2: fireteam5 \id\-1
Cvar_Set2: fireteam6 \id\-1
Cvar_Set2: fireteam7 \id\-1
Cvar_Set2: fireteam8 \id\-1
Cvar_Set2: fireteam9 \id\-1
Cvar_Set2: fireteam10 \id\-1
Cvar_Set2: fireteam11 \id\-1
Cvar_Set2: sv_running 0
---------------------------
Cvar_Set2: nextmap map_restart 0
WARNING: watchdog will trigger in 4 seconds
Idle Server with no map - triggering watchdog

```

{UPDATE} After starting server under gdb with @+set developer 1@ there is a new error:

```
Cvar_Set2: com_errorMessage G_FindConfigstringIndex: overflow

********************
ERROR: G_FindConfigstringIndex: overflow

********************
----- Server Shutdown -----
Sending heartbeat to etmaster.idsoftware.com
==== ShutdownGame (0)====
ShutdownOmniBot
ShutdownGame:
------------------------------------------------------------
Cvar_Set2: session 6 0 v2_factory
Cvar_Set2: fireteam0 \id\-1
Cvar_Set2: fireteam1 \id\-1
Cvar_Set2: fireteam2 \id\-1
Cvar_Set2: fireteam3 \id\-1
Cvar_Set2: fireteam4 \id\-1
Cvar_Set2: fireteam5 \id\-1
Cvar_Set2: fireteam6 \id\-1
Cvar_Set2: fireteam7 \id\-1
Cvar_Set2: fireteam8 \id\-1
Cvar_Set2: fireteam9 \id\-1
Cvar_Set2: fireteam10 \id\-1
Cvar_Set2: fireteam11 \id\-1
Cvar_Set2: sv_running 0
---------------------------
Cvar_Set2: nextmap map_restart 0
WARNING: watchdog will trigger in 4 seconds
Idle Server with no map - triggering watchdog
[Inferior 1 (process 19367) exited normally]

```

-----

Following bug was fixed thanks to crapshoot and ETPub: 

```ERROR: SP_team_WOLF_objective: exceeded MAX_MULTI_SPAWNTARGETS (16)
```

MAX_MULTI_SPAWNTARGETS was not changed in ET:L

---

Related commit(s):
70d52bc3951566110be9d64b97a05575b6e6c994 - game: fixed 'exceeded MAX_MULTI_SPAWNTARGETS' erro..
 fa691316ed00809a5bd3917d979000d057d3f4c4 - game: reset the remappedShaders data structure on ..
 ad9db31af78394f5c0ef048b512bd7f29e0a9d0c - game: reset the remappedShaders data structure on ..
 630f70b3da42cee1ce076ede39a8c85d86a8e7a7 - game: better debug info for info_limbo_camera_setu..
 c40fce1f807c390814abf616fb4798fa280c1704 - game: debug info refs 208 refs 405
 2968b38afabc1caefb003cd1fd43028874c5710a - game: don't drop invalid weapons refs 208
 1595920f80138ce954b58feeda1baaaa5bb2ffe9 - mod: exclude WP_NONE from weapon stats refs 208
 ca1b57792ac2322dcfa1a537666f086b0dab4c1d - mod: don't start to reload invalid weapons (there ..
 7a62c835564251dca6411b5b766d312ef3920954 - game: better debug info for info_limbo_camera_setu..
 f7f5cfd2fefd3782a3dac515a09116e154b9170d - game: debug info refs 208 refs 405
 a82c65614a85e0f7f439c9f560b44fa998cef6b2 - game: don't drop invalid weapons refs 208
 d18da5863e760e1f2724f975c179acf2c5b20f1d - mod: exclude WP_NONE from weapon stats refs 208
 80ca51d84639538e30c910bbbe8994c6c61fe2ce - mod: don't start to reload invalid weapons (there ..

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2013-02-12T05:26:39Z

---

That's odd ... the test server we have had some games on is up for more than 48h ... did you run stock maps ?

**Comment by ETLegacyTeam** [comment]
From: @JanSimek (Radegast)
Date: 2013-02-12T10:56:34Z

---

It happened several times on Goldrush, but I suspect it is related to omnibot (10 bots running), because crash follows immediately after "Omnibot inicialization is complete" log message. I cannot upload server log, because it gets misformatted after some time of running - another new issue. Now I am trying to run empty server and see if it crashes or not.

_EDIT:_ no, happens even with @omnibot_enable = 0@

**Comment by ETLegacyTeam** [comment]
From: crapshoot (crapshoot)
Date: 2013-02-12T20:18:35Z

---

ETPub has a fix for this. see https://www.assembla.com/code/etpub/subversion/commit/404

**Comment by ETLegacyTeam** [comment]
From: @JanSimek (Radegast)
Date: 2013-02-12T20:27:53Z

---

crapshoot wrote:
> ETPub has a fix for this. see https://www.assembla.com/code/etpub/subversion/commit/404

Thank you, user:crapshoot! This bug was driving me crazy.

**Comment by ETLegacyTeam** [comment]
From: @JanSimek (Radegast)
Date: 2013-02-12T22:24:40Z

---

Applied in changeset commit:70d52bc3951566110be9d64b97a05575b6e6c994.

**Comment by ETLegacyTeam** [comment]
From: @JanSimek (Radegast)
Date: 2013-02-13T11:24:49Z

---

Here we go again, I suspect this error is similar to the first one:
(I don't have complete log, but I will update this post when this crash happens again)

```
-----------------------------------
Setting MOTD...
Game Initialization completed in 0.14 seconds.
Omni-bot: Looking for /home/etlegacy/etlserver/mods/legacy/omni-bot/omnibot_et.so, 
Omni-bot: Found Omni-bot: /home/etlegacy/etlserver/mods/legacy/omni-bot/omnibot_et.so, Attempting to Initialize
Omni-bot: Omni-bot Loaded Successfully
ET autoexec script executed. 
Loaded Waypoints.
Bot Initialized in 0.10 seconds.
Omni-Bot Initialization completed in 0.10 seconds.
********************
ERROR: info_limbo_camera cannot find target

********************
----- Server Shutdown -----
Sending heartbeat to etmaster.idsoftware.com
==== ShutdownGame (0)====
-- Script System Info --
Current Memory Usage 1.85218 MB
Soft Memory Usage 1.8 MB
Hard Memory Limit 2 MB
System Memory Usage 1.82929 MB
Full Collects 0
Inc Collects 0
GC Warnings 0
Threads: 0, 0 Running, 0 Blocked, 0 Sleeping
ShutdownOmniBot
---------------------------
WARNING: watchdog will trigger in 4 seconds
Idle Server with no map - triggering watchdog

```

**Comment by ETLegacyTeam** [comment]
From: @JanSimek (Radegast)
Date: 2013-02-17T13:36:28Z

---

Bug report updated with further details provided by @+set developer 1@. These errors look interesting:

```
G_PickTarget: target allied_spawn not found
G_PickTarget: target axis_spawn not found

```

_EDIT:_ no, these errors happen even when golddays map loads fine

**Comment by ETLegacyTeam** [comment]
From: @rafal1137 (RaFaL)
Date: 2013-02-17T20:03:33Z

---

I did few map <mapname>
I think 1 of maps may be corrupted somehow

**Comment by ETLegacyTeam** [comment]
From: @JanSimek (Radegast)
Date: 2013-02-17T21:12:48Z

---

It doesn't seem to be map related - it happened so far on goldrush, golddays_v4 and fueldump.

**Comment by ETLegacyTeam** [comment]
From: @JanSimek (Radegast)
Date: 2013-02-18T13:50:19Z

---

user:IR4T4 added more verbosity to the error message:

```ERROR: G_FindConfigstringIndex: overflow 'textures/cptnt_baseracebeta3/flag_Allied_spawn1' (576 608) max: 32
```

Server was running fine all night, but when I joined it the next day and voted for baserace desert map this error was thrown upon map change.

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2013-02-18T20:21:59Z

---

It seems the configstring is not populated properly from time to time OR the holding buffer/getter function has issues. 
When you enter the 'configstrings' cmd several times it also occures it's not fully printed:

```
 347: axis_hq_compost_construct
 348: oasis_allies_city_capture
 349: oasis_allies_pumps_repair
 350: allies_hq_compost_construct
Userinfo: \name\[BOT]Kaolin\rate\25000\snaps\20\ip\localhost\cl_guid\OMNIBOT1200000000000000000000000
Userinfo: \name\[BOT]Kaolin\rate\25000\snaps\20\ip\localhost\cl_guid\OMNIBOT1200000000000000000000000
Userinfo: \name\[BOT]Kaolin\rate\25000\snaps\20\ip\localhost\cl_guid\OMNIBOT1200000000000000000000000

```

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2013-02-18T23:45:09Z

---

Baserace: configstrings command executed .. (full output is attached)

1st call
```
...
 577: textures/baserace_desert/cm_red_box.tga
 578: textures/baserace_desert/cm_nobox.tga
 579: textures/cptnt_baseracebeta3/flag_axis_spawn1
 580: textures/cptnt_baseracebeta3/flag_allied_spawn1
 581: gfx/2d/compass
 582: gfx/2d/compass_al0ax0
 583: gfx/2d/compass_al0ax6
 584: gfx/2d/compass_al0ax5
 585: gfx/2d/compass_al0ax4
 586: gfx/2d/compass_al0ax3
 587: gfx/2d/compass_al0ax2
 588: gfx/2d/compass_al0ax1
 589: gfx/2d/compass_al6ax0
 590: gfx/2d/compass_al5ax0
 591: gfx/2d/compass_al4ax0
 592: gfx/2d/compass_al3ax0
 593: gfx/2d/compass_al2ax0
 594: gfx/2d/compass_al1ax0
...

```

2nd call:
```
...
577: textures/baserace_desert/cm_red_box.tga
 578: textures/baserace_desert/cm_nobox.tga
 579: textures/cptnt_baseracebeta3/flag_axis_spawn1
 580: textures/cptnt_baseracebeta3/flag_allied_spaw 782: Allied Construction Materials
 787: \e\72\o\8\cix\1\cia\2\s\3\n\axis Materials\x\-864\y\3472\z\68
 788: \e\119\o\0\s\1\n\Tower Rocketgun\x\1112\y\-2464\z\360
...

```

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2013-02-21T22:44:46Z

---

I was able to 'reproduce' the crash on the testserver: 

- start a map and wait until warmup is over
- timelimit 0.1
- vote map 

Just do that several times ...


--------------

The configstring command has similar behaviour as our 'crash' cause: The area we are interested in is dropped a lot!
```
363: sound/movers/doors/door2_endcq 704: n\[BOT]Nohope\t\1\c\4\r\0\m\0000000\s\0000000\dn\\dr\0\w\10\lw\10\sw\14\mu\0\ref\1

```

**Comment by ETLegacyTeam** [comment]
From: acqu (acqu)
Date: 2013-02-26T13:17:07Z

---

EDIT: hm weird, i first thought that by downgrading my gcc i would be able to circumvent all these fixes, but it seems this is not the case. Basically i have the same problem with an independent source, it messes up the configstring at numspawntargets and reaches MAX_MULTISPAWN_TARGETS after a certain amount of maps.

Anybody has an explanation what is happening here ? I have no problems with the same source on windows. Also it is worth noting that the downgrading of my gcc from v4.6 to 4.4 was working at first. But now it seems something has changed on my system. I only ran a makefile of another build in between :< Did test thouroughly yesterday and today morning and there all worked with v.4.4. So yea, anybody a deeper explanation ? Also: this only happens if i conditionally compile Omnibot into my build. If i exclude it all is fine. Maybe something gets messed up in the linking ? Some functions may not work ? Are there problems when compiling with a really low gcc version, e.g. 3.3 ?

**Comment by ETLegacyTeam** [comment]
From: @JanSimek (Radegast)
Date: 2013-11-24T14:03:01Z

---

Here we go again. Server running stock maps and 8 omnibots errors out with this @info_limbo_camera@ error after a day or two of uptime.

Server log: http://pastebin.com/QMh27zrM

**Comment by ETLegacyTeam** [comment]
From: @JanSimek (Radegast)
Date: 2013-11-24T14:13:39Z

---

Our version:2.71rc3 server with custom maps seems to be running without any problems, so I removed the custom maps and restarted the server, because that is the only thing, besides @xpsave.lua@ script and highres flags, that is different between these servers.

*Server 1* (version:2.71rc3, Omni-bot, dynamite.lua, original maps):

    * @etlegacy.com:27960@     

*Server 2* (git version, Omni-bot, dynamite.lua, xpsave.lua, original maps):

    * @etlegacy.com:27961@

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2013-11-24T14:35:34Z

---

I did notice same issue with rc3 but I don't know how to reproduce :/ It happens after days ...

**Comment by ETLegacyTeam** [comment]
From: @JanSimek (Radegast)
Date: 2013-11-27T19:28:08Z

---

Server number 2 was down again and I had to restart it.

```
Kill: 5 7 26: [BOT]Fullthrottle killed [BOT]Brad by MOD_ARTY
Kill: 4 5 9: [BOT]Kaolin killed [BOT]Fullthrottle by MOD_THOMPSON
Kill: 1 4 41: [BOT]Sean killed [BOT]Kaolin by MOD_LANDMINE
Kill: 1 2 41: [BOT]Sean killed [BOT]Gali by MOD_LANDMINE
Item: 6 item_health
Medic_Revive: 3 7
********************
ERROR: Couldn't find item for weapon 0
********************

```

I will recompile it tomorrow, so it includes the recent commits with more debug info and I will add a debug lua script to @lua_modules@ as well.

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2013-11-28T07:00:23Z

---

This ticket is about 3 errors now :-O

In fact WP_NONE has no item - this should be fixed with latest commits.

Radegast, let the Lua script also call svcmd 'game_memory' - I would like to know if there are game memory issues

{FIXME}ERROR: info_limbo_camera cannot find target

**Comment by ETLegacyTeam** [comment]
From: acqu (acqu)
Date: 2014-02-15T18:10:06Z

---

I think i have the same problem as you guys with my codebase. Are there any news on this?

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2014-04-03T16:00:28Z

---

Can't reproduce 'info_limbo_camera cannot find target' for sh*t :/

**Comment by cakeET** [comment]
I experienced these error recently. The cause in my case was the game library (.so / .dll) was not always being unloaded and reloaded between map changes. There are a variety of variables initialized by the unload/load process that when not reset cause these and other similar crashes. 

The fix for me was to compile in gcc with the flag -fno-gnu-unique. The cause is likely the same or similar but this fix was for a C++ code base and may not apply to C. Another option is to compile with clang, which, at least for me, didn't have the same unloading issue.

Apparently: _"If the reference count drops to zero and no other loaded libraries use symbols in it, then the dynamic library is unloaded."_ So, if either references remain > 0 or symbols from the library are still in use dlclose() can fail to unload the library.

From the gcc man about -fno-gnu-unique:
On systems with recent GNU assembler and C library, the C++ compiler uses the "STB_GNU_UNIQUE" binding to make sure that definitions of template static data members and static local variables in inline functions are unique even in the presence of "RTLD_LOCAL"; this is necessary to avoid problems with a library used by two different "RTLD_LOCAL" plugins depending on a definition in one of them and therefore disagreeing with the other one about the binding of the symbol. But this causes "dlclose" to be ignored for affected DSOs; if your program relies on reinitialization of a DSO via "dlclose" and "dlopen", you can use -fno-gnu-unique.

source and relevant info is here:
https://stackoverflow.com/questions/24467404/dlclose-doesnt-really-unload-shared-object-no-matter-how-many-times-it-is-call
