### ISSUE TITLE
Map Voting : each vote equal 1pts

### ISSUE THREAD

**Issue by Aranud** [etlegacy/etlegacy#2100]
Right now the map voting works like this if i am correct?

You get list of maps to choose from and you can pick up to 3 maps and give 3 votes with different points (1, 2 and 3). If you consider 3 - 100% , 2 - 66%, 3 - 33%. Lets say there are 3 maps on the list you would like to play. Your option is to choose only one and give it 100% and 2nd vote will be 66%, 3th 33% impact. Or you give this 1 pt to map "i might want to play?".

Would it not be better to give 1 equal point up to 3 maps from list. This way you can choose up to 3 maps you want to play and each vote has equal impact. It feels much easier for player to vote maps like that. Might be just my opinion.

My idea would be having check boxes in front of each map on the  voting list. Each player can have up to 3 boxes checked and after sending votes each checked box will count as 1pt.

I think up to 3 votes, each vote equal 1pts might work better.
![312123rey6t](https://user-images.githubusercontent.com/99591943/162626145-56b6eb89-fd59-4adf-afb7-c2f10e0dd97d.png)

_Originally posted by @u1ps in https://github.com/etlegacy/etlegacy/discussions/1939_

**Comment by u1ps** [comment]
Is it possible for server admin to choose map list size and amount of votes per client? If not i think it would be a nice addition to have some control over the system from server side. If it is not too complicated to make.

**Comment by Aciz** [comment]
Map list size can be controlled with `g_maxMapsVotedFor` cvar. Don't really see much of point in being able to control the number of votes.

**Comment by hellreturn** [comment]
Bug where you can re-connect and vote multiple times -> Is that resolved?

**Comment by rafal1137** [comment]
@hellreturn The only thing that was changed with voting was this one.
https://github.com/etlegacy/etlegacy/commit/0162ce044637c5ea0dccc76b6c874445b7219303

**Comment by rafal1137** [comment]
PS: Also this one might be an insterest for you https://github.com/etlegacy/etlegacy/issues/1424

**Comment by Aranud** [comment]
> Bug where you can re-connect and vote multiple times -> Is that resolved?

@hellreturn Yep, it is handle on client disconnect / reconnect. The casted votes are simply decremented from total amont of vote : https://github.com/etlegacy/etlegacy/blob/38942c91db37076ee3a584dff484da4586acab75/src/game/g_client.c#L3370-L3392

**Comment by Aranud** [comment]
The purpose of this ticket was to make each vote points equal to 1. As more changes have been involoved, I prefer close it for now and create a new one depending of futur feedback.
