### ISSUE TITLE
Some Installer issues

### ISSUE THREAD

**Issue by sharky009** [etlegacy/etlegacy#2178]
First Thanks for the nice work of keeping ET alive!

Now to the main part. While installing ETL i found some little things that are a bit confusing.
First: The installer installs the shortcuts (Startmenu and Desktop) only for the curent user and not for all users. This should be easy to fix i think. 
Second: If you install in silent mode (which nsis can normally do well), the installer still pops out some information boxes which will hinder the process on going on. It would be nice of they can be hidden when running in silent mode (or a switch would be added to hide them?)

**Comment by jackeri** [comment]
Had totally forgotten about the silent mode with nsis. The messageboxes are now hidden. I will figure out some parameters for the different installer components.

**Comment by jackeri** [comment]
The installer now has /noassets /noomnibot /nogeoip /nowolfadmin /noshortcuts flags that disable the installers output per parameter.
