### ISSUE TITLE
Fix OpenBSD issues

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#223]
Author: @IR4T4 (IR4T4)
Date: 2013-03-01
Redmine Issue: 223, https://dev.etlegacy.com/issues/223

---

It seems macro '__linux__' is not active on OpenBSD - see http://www.dev.etlegacy.com/projects/etlegacy/repository/revisions/1b7d0d9ce3aa4d496679b296974fdcf719e7d09d/diff/src/game/g_lua.h

1. There are some locations in the code where the '__linux__' macro is used only! (simple text search in /src '__linux__')

2. There is '__FreeBSD_kernel__' (q_plattform.c 185) and '__BSD__' (net_ip.c 1562) defined. Isn't this the same?

**Comment by ETLegacyTeam** [comment]
From: @jackeri (Jacker)
Date: 2013-08-28T11:41:13Z

---

Why wont we just add: 
#if defined('__BSD__') || defined('__FreeBSD_kernel__')
ifndef '__linux__'
#define '__linux__'
#endif
#endif

? Without the ' signs ofc..
I know its an ugly solution but, still prettyer than quadtrillion new macros..

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2013-08-29T08:32:08Z

---

Jacker wrote:
> Why wont we just add: 
> #if defined('__BSD__') || defined('__FreeBSD_kernel__')
> ifndef '__linux__'
> #define '__linux__'
> #endif
> #endif
> 
> ? Without the ' signs ofc..
> I know its an ugly solution but, still prettyer than quadtrillion new macros..

I'm not sure if we can do that w/o modifing more in q_platform.h. '__BSD__' macro (which is kind of opposite case of  macro '__linux__’ is not active on OpenBSD) doesn't seem available on all BSD platforms -  we set it explicitly in current line 258 of q_plattform.h.

**Comment by rmarquis** [comment]
According to #1341, OpenBSD compiles fine - there is just a last issue with clang w/o debugging symbols.
Let's close this ticket now.
