### ISSUE TITLE
Timing issue (?) with Frostbite mapscript

### ISSUE THREAD

**Issue by Aciz** [etlegacy/etlegacy#2235]
Not quite sure if this is a timing issue or some logic issue in code, but on Frostbite (both original and ETL version), Axis lower garage spawn is supposed to be disabled on map start. The spawn starts in disabled state, and is enabled in mapscript after setting autospawns. On legacy it's still possible to spawn on the lower spawn though, whereas you'll always spawn in upper spawn in other mods.

**Comment by Aciz** [comment]
Can be fixed in mapscript by adding `wait` between autospawns and `altertentity` call, so could be order-of-execution issue, where alertentity call will get processed first if issued on same frame.

```
        setautospawn "Axis Barracks" 0
        setautospawn "Command Post" 1
        wait 200
        alertentity axis_garage_spawns
```

**Comment by ryzyk-krzysiek** [comment]
It's this https://github.com/etlegacy/etlegacy/commit/8f480d33a25987ba22ef5f0b02d1ce03263a2445 I was thinking from the beginning it's bad idea fixing it, who knows what else it broke... just revert it I guess..
