### ISSUE TITLE
func_fakebrush prediction broken

### ISSUE THREAD

**Issue by oheikk** [etlegacy/etlegacy#2242]
`func_fakebrush` collision prediction doesn't work properly, because client never gets the mins and maxs from server. The `solid` encoding doesn't work here (I don't know what it's used for, but from the looks of it it's not meant to be used with arbitrarily sized boxes)

Example that spawns a `func_fakebrush` close to flag on supply for easy testing.
```
create
{
	scriptname "collisiontestonsupplynonsymmetric"
	classname "func_fakebrush"
	origin "-250 2300 250"
	contents 1
	mins "-100 -100 0"
	maxs "25 25 100"
}
```
Edit: pasted wrong example

Adding another example to show it won't work even if mins and maxs are symmetric, if they are above 255:
```
create
{
	scriptname "collisiontestonsupplybig"
	classname "func_fakebrush"
	origin "-250 2000 250"
	contents 1
	mins "-300 -300 0"
	maxs "300 300 100"
}
```

**Comment by ryzyk-krzysiek** [comment]
What exactly is the issue with collision prediction here? I was only able to reproduce miss prediction when proning, but mentioned commit doesn't fix it.

**Comment by oheikk** [comment]
My bad, pasted the wrong example (it does currently work, if using abs(mins[0]) == abs(mins[1]) == maxs[0] == maxs[1] and the values are small enough.) I've edited it, this one should show it.

**Comment by oheikk** [comment]
```c
// sv_world.c l258
// assume that x/y are equal and symetric
i = gEnt->r.maxs[0];
if (i < 1)
{
	i = 1;
}
if (i > 255)
{
	i = 255;
}
```
From the looks of it, just maxs[0] is used and expanded outwards to every direction from origin for prediction.

**Comment by ryzyk-krzysiek** [comment]
Right, so looks like every map entity that is not a `bmodel` is potentially broken as client might not use the correct mins/maxs but server will.

Just to note why proning prediction is broken (Legacy/VET/ETJump/ETPro) regardless of incorrect mins/maxs (with ANY non-bmodel):

This removes collision on head/legs with `CONTENTS_BODY` (players).
https://github.com/etlegacy/etlegacy/blob/0ce90b2535cdab3e871a73cdb9bc293186f2786e/src/game/bg_pmove.c#L278-L279
https://github.com/etlegacy/etlegacy/blob/0ce90b2535cdab3e871a73cdb9bc293186f2786e/src/game/bg_pmove.c#L370-L371

Every non-bmodel has default contents set to `CONTENTS_BODY`
https://github.com/etlegacy/etlegacy/blob/0ce90b2535cdab3e871a73cdb9bc293186f2786e/src/qcommon/cm_load.c#L849

Server side: proper contents are set when checking for collision with entities:
https://github.com/etlegacy/etlegacy/blob/0ce90b2535cdab3e871a73cdb9bc293186f2786e/src/server/sv_world.c#L662-L666
https://github.com/etlegacy/etlegacy/blob/0ce90b2535cdab3e871a73cdb9bc293186f2786e/src/server/sv_world.c#L702-L706

Client side: contents are not networked and thus client always uses default contents (`CONTENTS_BODY`), even if networked there is no trap call to set them. This means head/legs is never clipping against non-bmodels, on supply for example you can try flag post (other than `func_fakebrush`).

**Comment by oheikk** [comment]
Are there (currently) any non-`bmodel` entities that allow arbitrary mins/maxs except for `func_fakebrush`?

**Comment by ryzyk-krzysiek** [comment]
I don't know actually, I've never done any maps and I'm not familliar with map entities.

**Comment by Aciz** [comment]
No, the only non-bmodel entities that even have mins/maxs are weapon_ entities, which get their mins/maxs from the item definitions.
