### ISSUE TITLE
Flamethrower spawns too many flames with cg_drawGun 0

### ISSUE THREAD

**Issue by suburbski** [etlegacy/etlegacy#2282]
The best 64 bit mod has a [fix](https://github.com/etjump/etjump/pull/919) for this

**Comment by Aranud** [comment]
I can't see any difference in graphic visual ... does it impact the number of local entity created ?

**Comment by Aciz** [comment]
It appears if you keep tapping `+attack`, holding it down won't cause issue iirc.

**Comment by Aranud** [comment]
haha nice catch ... I will not ask why you are firing flamethrower like this ... gonna use the best 64 bit mod to fix this
