### ISSUE TITLE
64-bit Windows release is missing omnibot_et_x64.dll

### ISSUE THREAD

**Issue by j-mattsson** [etlegacy/etlegacy#2284]
64-bit Windows release is missing "omnibot_et_x64.dll".

Console:
```
Omni-bot: ^2Looking for legacy/omni-bot\omnibot_et_x64.dll, not found
Omni-bot: ^2Looking for .\omni-bot\omnibot_et_x64.dll, not found
Omni-bot: ^2Looking for omnibot_et_x64.dll, not found
```

I'm using "Windows 64-bit binaries" (Archive version), I have not tested the installer.

**Comment by rafal1137** [comment]
This one has been fixed you can test it in one of the spanshots 
https://www.etlegacy.com/workflow-files/
