### ISSUE TITLE
`remapshader` doesn't work

### ISSUE THREAD

**Issue by oheikk** [etlegacy/etlegacy#2299]
On some maps that use a lot of remapshader console is filled with quite a bit of spam.

Also, crucially, the wheels of the tank don't go round and round no more. :(

https://user-images.githubusercontent.com/107760898/226106124-074cc3c1-c0ad-4c6e-bcff-8427366d86b2.mp4

**Comment by jackeri** [comment]
This was just fixed on commit: dc6acd18743574cf3542768b899100a9935356fe
