### ISSUE TITLE
% in chat sends as .

### ISSUE THREAD

**Issue by ETLIssues** [etlegacy/etlegacy#2301]
% in chat sends as . in console and main chat. classic bug, still present. not a big deal but if it's an easy fix 🤷‍♂️

**Comment by ensiform** [comment]
It's intentional, not a bug and has been the case in all quake 3 based games

**Comment by ETLIssues** [comment]
> It's intentional, not a bug and has been the case in all quake 3 based games

Sure, I can believe that. So other than tradition, what is the purpose of changing a % to a . in chat?

**Comment by ensiform** [comment]
> > It's intentional, not a bug and has been the case in all quake 3 based games
> 
> Sure, I can believe that. So other than tradition, what is the purpose of changing a % to a . in chat?

It's done to prevent formatting string abuse ( %i %s %f etc) over the network such as in chat or other string read/writes.

In changing this, it breaks network protocol compatibility including old demos.

There's a way to do a workaround for chat but I'll leave that to legacy devs to implement. Basically involves replacing the % with an unused ASCII code that's not graphical and replaces it back to % when parsing the chat message. Not the easiest or cleanest but only way to not break protocol versions.

**Comment by ETLIssues** [comment]
I'll go ahead and close this even though it's technically fixable, then. Appreciate the information.

**Comment by jackeri** [comment]
<img width="560" alt="image" src="https://user-images.githubusercontent.com/2070060/226841173-b0b7d2fa-f7c1-4454-95f0-366cb24bfb44.png">
Fixed
