### ISSUE TITLE
Scoreboard obscured when scoped in with sniper

### ISSUE THREAD

**Issue by rorgoroth** [etlegacy/etlegacy#2304]
Version 2.81.1, TM ETL1 Server.

See attached image, when playing or as spec when the weapon is in scoped mode the scoreboard/player-table brought up  by holding tab is obscured.

![2023-03-23-140045-et_beach](https://user-images.githubusercontent.com/77244135/227230330-c918e0b4-004e-44af-9be4-7bf60799be46.jpg)

**Comment by Aranud** [comment]
Thank you for the report!
