### ISSUE TITLE
Make surrender vote be a majority vote instead of one F2 cancelling it

### ISSUE THREAD

**Issue by x0rnn** [etlegacy/etlegacy#2308]
As per the title, make callvote surrender a majority vote like the other votes instead of 1 player voting F2 cancelling it. If the majority want to surrender, pass it.

**Comment by winrid** [comment]
It looks like it is *supposed* to only fail the vote if > `100 - vote_percent` vote no:

```
else if (level.voteInfo.voteNo && (level.voteInfo.voteNo >= (100 - pcnt) * total / 100)) {
AP(va("cpm \"^1Vote FAILED! ^7(^2Y:%d^7-^1N:%d^7) ^7(%s)\n\"", level.voteInfo.voteYes, level.voteInfo.voteNo, level.voteInfo.voteString));
```

Maybe you were testing with bots? they don't count (not a "voting client"):

```
total = level.voteInfo.numVotingTeamClients[other->client->sess.sessionTeam == TEAM_AXIS ? 0 : 1];
```

**Comment by winrid** [comment]
Confirmed it does function this way... I think I see the issue, will open a PR.

**Comment by winrid** [comment]
Fixed via https://github.com/etlegacy/etlegacy/pull/2315

**Comment by x0rnn** [comment]
Thanks for fixing.

**Comment by x0rnn** [comment]
I think this caused a new bug.

If there are 2 players and 1 callvotes something, the vote will automatically pass if he disconnects.

**Comment by winrid** [comment]
@x0rnn My original solution to this did not have this problem :) but the issue was then a single user couldn't pass a vote by themselves, so I made a change which results in the bug you mention.

What we can do is keep track of the voter and only pass when one user if that user created the vote?

**Comment by x0rnn** [comment]
Sounds good

**Comment by winrid** [comment]
> @x0rnn My original solution to this did not have this problem :) but the issue was then a single user couldn't pass a vote by themselves, so I made a change which results in the bug you mention.
> 
> What we can do is keep track of the voter and only pass when one user if that user created the vote?

fixed in https://github.com/etlegacy/etlegacy/pull/2338

**Comment by winrid** [comment]
@x0rnn Realized that I didn't read your comment completely. I created a new issue for that: https://github.com/etlegacy/etlegacy/issues/2454
