### ISSUE TITLE
Handle Large XP Values Gracefully

### ISSUE THREAD

**Issue by winrid** [etlegacy/etlegacy#2313]
People have been playing Enemy Territory forever, so they have large XP values that start to make the scoreboard look funny. New people might look at it and think it's broken. We can make the scoreboard look nicer and maybe better show off the high XP :)

Proposal:

- Abbreviate large values in the scoreboard: 4.52M instead of 4521024
- Also abbreviate in Server Info list.
- Retain raw XP value in HUD, most likely. Maybe format it: 4,521,024 - Maybe show as smaller font is value is really large?

**Comment by winrid** [comment]
First bullet being addressed here: https://github.com/etlegacy/etlegacy/pull/2312

**Comment by rmarquis** [comment]
Or just fix the issue at the root: never display the total XPs, just the differential XPs earned across a map/campaign, which should be already the default.

**Comment by winrid** [comment]
Nah, I don't think that should be the default. People will be very upset if we change that I think :D They like to show off their XP.

**Comment by rmarquis** [comment]
Isn't it already the case? Differential XPs has been implemented like ~5 years ago.

**Comment by winrid** [comment]
Not on any servers I play on. It shows their total XP.

What is the push back against this change? It makes the game feel a lot nicer, differential XP showing, or not.

**Comment by rmarquis** [comment]
XP save historically introduced many side effects (on gameplay and such), which led to many mods introduced hard-coded features to counter them. The total XP is also utterly meaningless, and some replacement has been introduced gradually in Legacy mod, such as differential XPs.

If you aim to make an irrelevant number look nicer, then it is just a band-aid on a wooden leg. Just get rid of the reason these values are irrelevant in the first place. Jmho, but what do I know really :]

**Comment by winrid** [comment]
Yeah, what do you know? :) I do not think they are meaningless. It is a nice indicator of how long the person has been playing on that server etc.

**Comment by winrid** [comment]
Okay, I guess I see now. I had not played on any ETLegacy mod servers before :)
I suppose I was hoping to fix things for the other mods, assuming they didn't override the scoreboard draw calls. I'm still learning how the game and mods work, sorry. :)

**Comment by rmarquis** [comment]
Yes, I assume it's not possible to do that for other mods without having their source code, as the XP system is implemented at the mod code level.
