### ISSUE TITLE
Bug: holding binoculars while having a weapon with weapalt equipped

### ISSUE THREAD

**Issue by x0rnn** [etlegacy/etlegacy#2326]
Holding the binoculars and trying to walk/run with a weapon such as a sniper, engi rifle, silenced pistol will continuously switch/spam weapalt.

**Comment by x0rnn** [comment]
It says in the Changelog for 2.8X.X - next release: https://github.com/etlegacy/etlegacy/wiki/Changelog/b0d6c0dad053e1869f7457be179a3842e1bf19f1#weapons

"Fixed binocular switching multiple time while moving", but it's not, unless that was something else?

**Comment by Aranud** [comment]
I can't reproduce the binoc issue with last snapshot version. On 2.18.1, it is indeed present.
Possible fix https://github.com/etlegacy/etlegacy/commit/a8aac33229a8d4aaabb899572b58f23ca817b6a4

**Comment by x0rnn** [comment]
I removed old mod pk3s and issue seems to be gone. ¯\_(ツ)_/¯
