### ISSUE TITLE
Spawnflags 2 (no tripod) on misc_mg42 makes them bulletproof

### ISSUE THREAD

**Issue by x0rnn** [etlegacy/etlegacy#2332]
Setting spawnflags 2 on misc_mg42 makes them spawn without a tripod, unlike spawnflags 1, but it also makes them indestructible with bullets, only with explosives. MG42s on maps such as battery and et_beach cannot be destroyed with bullets, for example. Might be a nice idea to remove this undocumented feature of them being bulletproof with spawnflags 2...

**Comment by u1ps** [comment]
i agree both spawnflags should be either indestructible or destructible with bullets for consistency and less confusion

**Comment by x0rnn** [comment]
I guess we can just call it an undocumented feature.
