### ISSUE TITLE
Log engineer repairs

### ISSUE THREAD

**Issue by x0rnn** [etlegacy/etlegacy#2333]
Log engineer repairs with G_LogPrintf into the server log.

`G_LogPrintf("Repair: %d %s\n", ent->client->ps.clientNum, repaired_objective_name);`

Could maybe even add objective destructions, "Objective_Destroyed: %d %s" for engineer dynamites and covert satchels. Edit: to simplify and highlight only important destructions, log only engineer dynamites of objectives in TOIs.

It would be nice to have this information in the log to be able to parse it and calculate statistics and such and as far as I know these stats aren't being saved right now at all?

**Comment by x0rnn** [comment]
It seems there already is a "Repair:" line being logged, but only for MG repairs for some reason. Could it be changed to log all repair events instead?

**Comment by Vorschreibung** [comment]
Abusing ETL log lines as an API for the LUA side is a terrible and irresponsible idea, when adding a LUA Hook for this particular case is a matter of adding a function and creating a LUA bind for it, which can all be done within 5min to 1hr depending on your experience with the code and has been done dozens of times by one-time contributors in the past.
