### ISSUE TITLE
ui/ingame_menu.menu UPGRADE link does not work on 2.60b

### ISSUE THREAD

**Issue by x0rnn** [etlegacy/etlegacy#2335]
The "Old Software" UPGRADE NOW button/link does not work on 2.60b from the ingame_menu.menu, nothing happens by clicking it. The one in main menu works fine.

This custom menu item from TM's server works normally ingame, though, so I don't know what the problem is with ingame_menu.menu: `BUTTON( SUBWINDOW_X+6, SUBWINDOW_Y+SUBWINDOW_HEIGHT-24, .5*(SUBWINDOW_WIDTH-18), 18, _("YES"), .3, 14, close website ; close main ; uiScript validate_openURL "https://teammuppet.com/home"; open teammuppet )`

**Comment by rafal1137** [comment]
@x0rnn You should take a look at my answer here:
https://github.com/etlegacy/etlegacy/issues/1934#issuecomment-1675873967
