### ISSUE TITLE
Small characters in console with r_scale 2

### ISSUE THREAD

**Issue by ghost** [etlegacy/etlegacy#2351]
When using `r_scale 2` (at 1080p), console is barely readable as the letters don't get scaled up correctly.

![shot0001](https://github.com/etlegacy/etlegacy/assets/141928628/83f3b186-81c0-48f7-b6fb-a0f16c73fe5a)

**Comment by Aciz** [comment]
Temporary workaround is to set `con_fontName` to empty to use vanilla ET console font, that is scaled correctly.
