### ISSUE TITLE
Spectator freecam is not speclocked correctly

### ISSUE THREAD

**Issue by kajto3** [etlegacy/etlegacy#2354]
When one of the teams is speclocked, you cannot spectate any of its players and you're locked into spectating the other team / can't use the "spectator flying/freecam" feature. This is vanilla behavior and it works correctly right after the command is executed.

But you're able to "fly" again after the game restarts/map changes. You can also simply do `/team s` and you are unlocked again. If you start spectating someone from the other team, you're locked again (can't press space).

Another issue with speclock, but probably can be related: when both of the teams do the `/speclock`, you're able to "fly" wherever you want and still be able to potentially spy or do whatever speclock was designed to prevent. In ETPro, when both teams were speclocked, you just see the black screen, unable to see anything.

**Comment by ryzyk-krzysiek** [comment]
`CG_DrawFlashBlendBehindHUD` is where the blackout happens for client but after hud rework it is unreachable for spectators.

Before:
https://github.com/etlegacy/etlegacy/blob/0f4f2bbf8d718e5c99ac69ba98b32b1436e4dd16/src/cgame/cg_draw.c#L4278-L4283

After:
https://github.com/etlegacy/etlegacy/blob/338deafaf66384530c2bb1f7bebae1fe68565b5e/src/cgame/cg_draw.c#L4235-L4241
