### ISSUE TITLE
Make /ignore and /unignore work with part of name

### ISSUE THREAD

**Issue by x0rnn** [etlegacy/etlegacy#2372]
Currently it works with exact name or client id thanks to https://github.com/etlegacy/etlegacy/commit/02c6c368564285f2901cd31b95a426335f38965e, but would be nice if it worked with part of name as well.

**Comment by Aciz** [comment]
https://github.com/etjump/etjump/blob/f48d4719a99a4f2f6b31a4529d51942570c7f428/src/game/g_cmds.cpp#L253-L318
