### ISSUE TITLE
Incorrect cgame used on Android

### ISSUE THREAD

**Issue by ghost** [etlegacy/etlegacy#2375]
Android app seems to always be using cgame from APK, rather than the one from server the client is connecting to. The correct cgame (that is, the one from pak provided by server) is extracted to the app data folder, but the bundled one actually loads.

I tried with latest snapshot (`363-g8c26358`) and connected TM server, which currently has `66-g337f962` deployed. The APK snapshot version appeared on the loading screen and shortly after entering the game, I was disconnected with *Unknown event: 56*, which makes sense, given that I have an incompatible cgame loaded.

![](https://github.com/etlegacy/etlegacy/assets/141928628/2dad183f-82d6-4720-bf84-b87d62bcaac7)

**Comment by rafal1137** [comment]
It is issue with overwriting/no properly unpacking cgame ui files.

By Default Android Apk comes with current pk3 file in which is located from AssetManager and copied to the Internal Storage
https://github.com/etlegacy/etlegacy/blob/524f1ccce774594db16f226917441abbba077e2d/app/src/main/java/org/etlegacy/app/ETLMain.java#L104-L115

https://github.com/etlegacy/etlegacy/blob/524f1ccce774594db16f226917441abbba077e2d/app/src/main/java/org/etlegacy/app/ETLMain.java#L130-L141


Connecting to any Legacy Server that comes with non current version downloads pk3 files into dlcache dir in which those files should be extracted. but they do not.

![obraz](https://github.com/etlegacy/etlegacy/assets/2415096/fe5fcaf9-c05e-4fe4-8f48-a22e0c12175b)

PS: This one may have something to dowith current Android Restrictions.
We either allow some more access to the internal of etlegacy app or we move into another dir outside of `Android/data`

**Comment by x0rnn** [comment]
Yes, move it. I/we can only access Android/data for reading, can't copy any configs or demos there due to unrooted Android protection.

**Comment by rafal1137** [comment]
So yeah it looks like this Android Restricts everything to the `Android/data/etlegacy` instead of `sdcard/legacy`
Need to take a deeper look at it.

**Comment by rafal1137** [comment]
Just connected to the Hirntot with their more up to date snapshot build and it did worked flaweslly.
It is like older snapshots/releases are not compatible anymore :O

**Comment by ghost** [comment]
Hirntot runs on a snapshot built yesterday. The problem occurs once qagame and bundled cgame from APK become incompatible enough. It wouldn't work with a snapshot APK against v2.81.1 cgame and vice-versa.

**Comment by rafal1137** [comment]
> Hirntot runs on a snapshot built yesterday. The problem occurs once qagame and bundled cgame from APK become incompatible enough. It wouldn't work with a snapshot APK against v2.81.1 cgame and vice-versa.

Yes they did updated to the latest one. but they in fact had previous one before that in which latest apk snapshot worked fine.

**Comment by ghost** [comment]
The previous one was fairly recent as well. Anyway, is loading the actual server-provided cgame doable? Using whatever APK is close enough to what the server is running is *an option*, but only as far as the server runs Legacy mod. If other mods decided to compile for Android, current Legacy client would still try to load the Legacy cgame that came up with it, or at least that's what it does now.

**Comment by x0rnn** [comment]
This will be a problem for our custom freezetag gamemode we will have as an Xmas event on Hirntot. Requires a custom built mod. Not that we expect any/many Android players but it won't be compatible.

**Comment by rafal1137** [comment]
With removing the culprit:
https://github.com/etlegacy/etlegacy/commit/043fa19510e570a15dfbe905f58f2ff55c79adc2
Results in failing to load lib.

### Here is explanation:

Android is restricting access to the shared libraries specified by android namespaces (basically lib outside of `/data/com.etlegacy.app/lib` directory and sytem ones) .
Every attemps will result in:
```
2024-11-15 17:58:16.471 32718-323   linker                  com.etlegacy.app                     E  library "/storage/emulated/0/Documents/etlegacy/legacy/libui.mp.android.arm64-v8a.so" ("/storage/emulated/0/Documents/etlegacy/legacy/libui.mp.android.arm64-v8a.so") needed or dlopened by "/data/app/~~T5VbOWvoijo2kWqdmUfqqw==/com.etlegacy.app-c5T5Fai9JnMRWL8a0D-T4g==/base.apk!/lib/arm64-v8a/libetl.so" is not accessible for the namespace: [name="clns-4", ld_library_paths="", default_library_paths="/data/app/~~T5VbOWvoijo2kWqdmUfqqw==/com.etlegacy.app-c5T5Fai9JnMRWL8a0D-T4g==/lib/arm64:/data/app/~~T5VbOWvoijo2kWqdmUfqqw==/com.etlegacy.app-c5T5Fai9JnMRWL8a0D-T4g==/base.apk!/lib/arm64-v8a", permitted_paths="/data:/mnt/expand:/data/data/com.etlegacy.app"]
2024-11-15 17:58:16.471 32718-323   SDL/APP                 com.etlegacy.app                     I  Error loading library: dlopen failed: library "/storage/emulated/0/Documents/etlegacy/legacy/libui.mp.android.arm64-v8a.so" needed or dlopened by "/data/app/~~T5VbOWvoijo2kWqdmUfqqw==/com.etlegacy.app-c5T5Fai9JnMRWL8a0D-T4g==/base.apk!/lib/arm64-v8a/libetl.so" is not accessible for the namespace "clns-4"
```

Thats why it was loading wrong versions because it was using provided libs withing apk (server and app needs to have same versions to work fine without any issues)

Currently looking for solutions.
1. Best scenario everyone having rooted devices so I can make symlink programatically it will not work on non-rooted. 
2. Create custom namespace/Add them to namespace in order to load them properly
3. There are existing solutions that I found but not sure if they will even work.
4. Throw banana at the smarphone (meaby it magically work)

**Comment by rafal1137** [comment]
From internal testing:
You can now watch demos and connect to the servers with older versions of mod
