### ISSUE TITLE
Screen shakes for everyone when mortar is used

### ISSUE THREAD

**Issue by x0rnn** [etlegacy/etlegacy#2385]
[demo0000.dm_84.zip](https://github.com/etlegacy/etlegacy/files/13248531/demo0000.dm_84.zip)

**Comment by Aranud** [comment]
That has been added intentionally for weapon set, which include MG and Mortar once set : https://github.com/etlegacy/etlegacy/commit/e426a87317012bf4c1ce8c57c6adbe166d22c49c#diff-d4a02cdd5fc4794bec220b8a793ce86d3345213933af5a50890b987f3db489e8R3980-R3984
