### ISSUE TITLE
Blank map in intermission in campaign mode

### ISSUE THREAD

**Issue by x0rnn** [etlegacy/etlegacy#2386]
![nomap](https://github.com/etlegacy/etlegacy/assets/16674038/5f5d48f1-d7af-47f8-9b8d-bd5fe052d3e7)

When not all pk3s of the campaign are on the client's side, the intermission looks empty. See image.

**Comment by Aranud** [comment]
Related part returning error on parsing arena file failure : https://github.com/etlegacy/etlegacy/blob/b64ee04574bd589fc06ba2ddd3ae164c08af4d98/src/cgame/cg_missionbriefing.c#L457

**Comment by Aranud** [comment]
This issue should be fixed by skipping map which aren't present locally yet
