### ISSUE TITLE
Allow players to change the hud

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#240]
Author: @jackeri (Jacker)
Date: 2013-03-07
Redmine Issue: 240, https://dev.etlegacy.com/issues/240

---

Allow players to change betweed hud styles, i will implement basic etpro like huds but the settings will be as generic as possible.

Currently works:
cg_althud to change the hud
.hud scripts to add 3rd party huds to the game

---

Related commit(s):
7b1a24e8045229275e2aa6e21393e84569d9ac14 - cgame: added entry function for future alt hud mod..
 3f201b26d9dfd4799742cf44fc1e550856f9780b - cgame: hud refactoring, refs 240
 241b0ae672175e8941808a2aa6d1a4aefbdf1d42 - cgame: hud refactoring almost done, refs 240
 9bd897acf7075431b50965bf5a03ff889af57a73 - cgame: althuds now work on some level, refs 240
 d3a4a88990de0485e602d840cc68e652ebc96fe8 - cgame: widescreen fix on althuds, refs 240
 17c3f5640c537876578f4721d5812198c4513018 - cgame: althud code now works with .hud scripts, re..
 e021091668cec4d4e0da285f5d711e2b6ed4288f - cgame: added icon shadowing to the custom hud, ref..
 e85da3298ba321e609b30d81a4601e92ce586f78 - cgame: althuds compas artifax fixed and the animat..
 eb007a116f8111e8499514fc9afc27b8d19df5e0 - cgame: fixed default compas location, refs 240
 4f9412c8d6fc01315e49189f1234d5fab0a76910 - cgame: fixed sample .hud script and added debug co..
 5d6c417bbc7dc0a575428e00c129d1c0845cd9d3 - cgame: disable compas grid because of the widescre..
 cd88c4f73daced0329de92bb184207ee209b39dc - cgame: draw the grid for non ws refs 240 , code s..
 0de771d2ea97f22d0f4a82bbd724fd773136b952 - cgame: added althudflags partially, hud code almos..
 a36a1a082829b5f8cd8ffe03f091611982a65da0 - cgame: finalized the hud code, refs 240
 35d02bcabe036149bd671e3286b46eada1301ca4 - cgame: warning fixes refs 240

**Comment by ETLegacyTeam** [comment]
From: @jackeri (Jacker)
Date: 2013-03-23T19:46:20Z

---

The locations of the hud components are now easily moddable, just need to write handler code.

**Comment by ETLegacyTeam** [comment]
From: @jackeri (Jacker)
Date: 2013-03-24T15:13:18Z

---

Hud structure is done, small fixes left and then i can move on to making the config reading stuff.

**Comment by ETLegacyTeam** [comment]
From: @jackeri (Jacker)
Date: 2013-03-25T21:57:59Z

---

The hud system now works with .hud scripts. Sample is located in the ui/huds.hud path (i will fix the content later).

**Comment by ETLegacyTeam** [comment]
From: Mateos (Mateos)
Date: 2013-03-26T18:47:28Z

---

Nice work!

**Comment by ETLegacyTeam** [comment]
From: @jackeri (Jacker)
Date: 2013-08-27T21:02:04Z

---

This functionality has now been implemented.

**Comment by mittermichal** [comment]
players cant use their own hud on online pure servers because the game reads ui/huds.txt from pk3

**Comment by rmarquis** [comment]
@mittermichal This latter issue is tracked in #1268.
