### ISSUE TITLE
Headshot puff/smoke is too intense

### ISSUE THREAD

**Issue by kajto3** [etlegacy/etlegacy#2405]
It has something to do with recent changes (cg_impactEffects, then changed to cg_bloodPuff).

When the hit is a headshot, there's much more smoke generated. I remember there was an issue with the HS smoke being red color, compared to gray body shots. Right now it looks like the previous issue was "fixed" just by changing the color to gray.

Presentation:
https://cdn.discordapp.com/attachments/346956915814957067/1172289614602575902/2023-11-09_22-36-01_Trim.mp4
https://discord.com/channels/260750790203932672/346956915814957067/1172289564493234258

**Comment by Aranud** [comment]
Found the difference: https://github.com/etlegacy/etlegacy/commit/0c2678db683e9e49817b275b7b5d6737b5c8287f#diff-9bdea2878da0624c83132687d6046dd7455a2bed5cd7eeff4d89eb0b3b8563abL6918

Previously, if the blood was disable, the headshot "puff" effect was the same as the other hit region puff effect. In case of blood, the puff effect is bigger, that what is currently observable
