### ISSUE TITLE
Support for controllers on Android

### ISSUE THREAD

**Issue by lesleyxyz** [etlegacy/etlegacy#2419]
I thought it would be quite cool. It would make Android have a less disadvantage.

My use case is being able to play ET on a nintendo switch. Mine runs already android, but having controller support would be such a good gaming experience.

I think if you can port that to PC as well, it would be a big win for ET.

**Comment by rafal1137** [comment]
This already has been  done for snapshots builds/upcoming release
`Reworked/Better Support for Gamepads`
https://github.com/etlegacy/etlegacy/wiki/Changelog#general-1
