### ISSUE TITLE
Don't loop construction sound

### ISSUE THREAD

**Issue by x0rnn** [etlegacy/etlegacy#2429]
Play it only once, or restart if you stop using the pliers and then start again. Related to #862.

**Comment by Vorschreibung** [comment]
The looping behavior might be wanted, see https://github.com/etlegacy/etlegacy/issues/862 - needs clarification first to confirm if the current behavior is a bug or not.

Note that this has balance implications, as looping sounds are advantageous to defenders.

If the issue reported here is that the sound effect does not loop well to the ears, then an alternative fix could be to find a different construction sound that loops better, but it's unclear as of now in this ticket why construction sound ought not to be looped.
