### ISSUE TITLE
mapname_loc_override.dat do not work if they are inside a pk3

### ISSUE THREAD

**Issue by x0rnn** [etlegacy/etlegacy#2445]
Some maps do not have any locations at all, and on etpro you could fix this server-side by having them inside a pk3 that is required to download, however on legacy this does not work. The location files are not read when they are inside the pk3.

**Comment by jackeri** [comment]
Could you provide an example of this? Example map & locations, pk3.

**Comment by jackeri** [comment]
I just checked that the location’s data is normally loaded fine from a pk3, so would really like to see a case where this fails.

**Comment by x0rnn** [comment]
http://download.hirntot.org/etmain/ht_campaign05_2023.pk3

Downloads to etmain/dlcache, e.g. we named the water tower in Fueldump another name, doesn't show it on server to players though.

**Comment by jackeri** [comment]
The reason for that is simple. legacy.pk3 has priority due to the alphabet so the locations are loaded from there. User another letter at the beginning of the file to get priority.

**Comment by x0rnn** [comment]
Wait, we have e.g. "ht_campaign05_2023.pk3" and "ht240114_legacy_2.81.1.pk3" (not legacy_*.pk3), so ht_campaign05_2023.pk3 should get priority anyway, yet it doesn't load the overrides to players.

**Comment by jackeri** [comment]
The order is “reversed” I guess if you think about it that way, meaning that anything after legacy_*.pk3 alphabetically gets to override stuff from legacy_*.pk3.

**Comment by x0rnn** [comment]
That's what I'm saying, ht_campaign05_2023 is after ht240114_legacy_2.81.1 but it doesn't override.

**Comment by jackeri** [comment]
Eh, just run `path` command to show the package order to figure out the issue.

**Comment by x0rnn** [comment]
Actual path of files matters, not symlink location?

realpath ht231231_legacy_2.81.1.pk3:
/download/legacy/ht231231_legacy_2.81.1.pk3

realpath ht_campaign05_2023.pk3:
/download/etmain/ht_campaign05_2023.pk3

**Comment by Aciz** [comment]
Doesn't `fs_game` always take priority over `etmain`?
