### ISSUE TITLE
Console font too small when using higher resolution

### ISSUE THREAD

**Issue by u1ps** [etlegacy/etlegacy#2460]
Console font scales together with resolution. Is it possible to make console font size static. For example 1080p resolution console would be good base point in terms of readability. This seems most compatible option imo? 

Extra feature could be option to change console font size for further customizability.

![32423](https://github.com/etlegacy/etlegacy/assets/99591943/e00e1862-492b-43f6-975e-6b17517a15b5)
![12](https://github.com/etlegacy/etlegacy/assets/99591943/04fea125-59a7-4f96-b459-52b9c147b7bd)
![ET Legacy 21 01 2024 16_21 57](https://github.com/etlegacy/etlegacy/assets/99591943/f7885dc4-c1a1-4600-aad3-827bf10ebb8c)

**Comment by Aciz** [comment]
#2124 should likely be reverted if this is implemented, other engines that implement `con_scale` cvar use that instead for non-native rendering. While it's nice that it auto-adjusts to default, from a quick look it looked pretty annoying to code around.
