### ISSUE TITLE
Omnibot fails to load on clean install

### ISSUE THREAD

**Issue by GeneralKenobi72** [etlegacy/etlegacy#2483]
Omni-bot fails to load.
## System used
Arch Linux x86_64
Kernel: 6.7.4-arch1-1

## Workaround
I thought that this issue was supposed to be fixed, but it doesn't run on current version(2.81.1-2).
Solution that worked for me is linked in following post:
```
https://github.com/flathub/com.etlegacy.ETLegacy/issues/2
```
I had to find installation directory of omni-bot mod, and type the command in game prompt from linked post, for me:
```
\omnibot_path "/home/user/.cache/yay/etlegacy/src/etlegacy-v2.81.1-x86_64/legacy/omni-bot"

**Comment by rafal1137** [comment]
@GeneralKenobi72 The issue you are describing refers to omnibots path not being correctly set/flatpak file system makes it hard to load them. I do remember correctly how/where flatpak stores all the files. Can you enlighten me ?

**Comment by GeneralKenobi72** [comment]
I do not use flatpak, I installed etlegacy using  yay. It's just that the linked solution helped me make omnibot work. I tried installing on 3 different systems(all using arch), and all 3 times omni-bit was not loading correctly. Setting path like I mentioned does work, but it took me a while to find the solution. It might take other first time useres aswell, that's why I posted the issue.

**Comment by rafal1137** [comment]
@GeneralKenobi72 What would happen if you lauch etl binary with `+set omnibot_enable 1 +set omnibot_path "./legacy/omni-bot"` and paste console output when you run a server using etl.

NOTE:
When running etlded you should specifically run it with `+exec etl_server.cfg`

**Comment by GeneralKenobi72** [comment]
Running binary with ``` +set omnibot_enable 1 +set omnibot_path "./legacy/omni-bot" ``` resulted with following output: 
```        0 ^2ET Legacy v2.81.1 linux-x86_64 Mar 12 2023
       0 Zone megs: 64
       0 INFO: fs_game now defaults to 'legacy' mod instead of 'etmain'
       0 ----- Initializing Filesystem --
       0 Current working directory:
       0     /home/kenobi/.cache/yay/etlegacy/src/etlegacy-v2.81.1-x86_64
       0 Current search path:
       0     D /home/kenobi/.etlegacy/legacy
       0     D ./legacy
       0     D /home/kenobi/.etlegacy/etmain
       0     D ./etmain
       0     P ./legacy/legacy_v2.81.1.pk3 (1407 files)
       0
       0 1407 files in pk3 files
       0 --------------------------------
       0 ----- Client Shutdown ----------
       0 --------------------------------
       0 WARNING FS_FileExists: empty fileName
       0 SQLite3 can't close database - not active.
FS_InitFilesystem: Original game data files not found.

Please copy pak0.pk3 from the 'etmain' path of your Wolfenstein: Enemy Territory installation to:

"./etmain"


tty]Warning: --icon-name is deprecated and will be removed in a future version of zenity; Treating as --icon.
```
I did as the output suggested, located pak0.pak3 file and copied it to etmain directory, after which game successfully launched, with omni-bot loaded. Looks like every time you wish to host a server with bots, you will have to start with those additional arguments(or set the path like mentioned in first comment of issue). However, it might be misleading to new players, since menu Referee -> Bots is available even without starting with additional attributes, and new players will probably think it should work out of the box.

**Comment by rafal1137** [comment]
@GeneralKenobi72 
We do not recommend/expect new players to play with hosting their servers without any knowledge of how to do it, any minimal knowledge about how to set it up properly is way to go here. Also there were people asking for those setup hints but those were deditaced servers requests.

**Comment by GeneralKenobi72** [comment]
@rafal1137 
Okay, that's fair. If this is excpected behavior, I have nothing more to add.
