### ISSUE TITLE
Zoomed in Menu

### ISSUE THREAD

**Issue by scupoli** [etlegacy/etlegacy#2498]
Windows 10 Pro 64bit 
Asus 2070 Super with latest NVidia drivers.

I just installed ET Legacy and my menu is zoomed in. 
Cannot access settings to change resolution.
I've already adjusted advanced DPI in windows with no success.

**Comment by rafal1137** [comment]
I suppose are you running 4k Display ?
Solutions:
1: Decresse Scaling.
2: Download Latest Snapshot
3: Wait for nexe release in few days

**Comment by scupoli** [comment]
Hi, I appreciate your response. 
I found a custom autoexec config that had the problem. 
It's been fixed.
