### ISSUE TITLE
Disable dropobj in competitive configs

### ISSUE THREAD

**Issue by ETLIssues** [etlegacy/etlegacy#2504]
ETPro never had the ability to drop objectives. It completely changes the dynamic of the game to have it enabled. I think it should be disabled, instead of making changes for change's sake.

**Comment by jackeri** [comment]
It's been part of legacy for quite a while. I see no reason to disable it for any game mode.

**Comment by ETLIssues** [comment]
Lots of issues have existed in Legacy for quite a while. They're not written off. It was not a part of ETPro for way longer than it's been part of Legacy. Just because the people who transitioned the competitive community from ETPro to ETL did a very poor job of maintaining consistency isn't a reason that we shouldn't strive to make it consistent. If we can move to regular supply after playing ETL Supply all this time, we can disable dropobj.

**Comment by ryzyk-krzysiek** [comment]
> It was not a part of ETPro for way longer than it's been part of Legacy.

Give it a few more years.

> Just because the people who transitioned the competitive community from ETPro to ETL did a very poor job of maintaining consistency isn't a reason that we shouldn't strive to make it consistent.

Noone forced them to transition, why should everyone who played Legacy mod for years before them now bow to them and do whatever they think is right? I was part of the group of people that enjoyed competitive matches on Legacy before they switched.

That said, if you don't like it so much, why don't you just disable it on your servers with a cvar? Just set `g_dropObjDelay 9999999` and you will not be able drop it for that many miliseconds. Unless you can't even find consensus on this topic in your competitive community so you want developers to do it for you.
