### ISSUE TITLE
Log health pickups

### ISSUE THREAD

**Issue by x0rnn** [etlegacy/etlegacy#2506]
Similar to #2394 (Ammo pickups), this got removed in Legacy for some reason.

Logging ammo pickups has since been re-added, but now I realized health pickups (Health_Pack in VET/ETPro) are missing too and should be re-added.

**Comment by rmarquis** [comment]
Oops. Looks like I removed these logs when I cleaned up the old unused OSP stats system back in the day: 650e9d8d7f3e909a199bb8e6c0248d669a254f71
