### ISSUE TITLE
Segfault in _et_gentity_set on Win x64

### ISSUE THREAD

**Issue by Aciz** [etlegacy/etlegacy#2527]
Reproducable with `!slap` command from WolfAdmin for example, but likely many others too as this is a rather generic function.

Doesn't seem to occur on Linux x64 or Win x86.

![image](https://github.com/etlegacy/etlegacy/assets/14221121/d93fbd34-0147-45e3-85de-c6251e893a7a)

**Comment by jackeri** [comment]
This is similar to the other Lua bug I fixed previously.

**Comment by Aranud** [comment]
Fixed in https://github.com/etlegacy/etlegacy/commit/1de8d85411ae930c31b2a50421276fa13e30e7d0
