### ISSUE TITLE
eventParm integer wraparound in EV_BULLET causes incorrect impacts for entities

### ISSUE THREAD

**Issue by Aciz** [etlegacy/etlegacy#2571]
When firing to an entity, the entity number is stored in `ent->s.eventParm`

https://github.com/etlegacy/etlegacy/blob/6935de0c07596db0fcbf9243999fb7ecc4e7a1b4/src/game/g_weapon.c#L3574-L3575

This is problematic because `eventParm` is transmitted as 8-bit integer over the net, so this causes integer wraparound in cgame when `EV_BULLET` is processed if the `entityNum` is > `255`

https://github.com/etlegacy/etlegacy/blob/6935de0c07596db0fcbf9243999fb7ecc4e7a1b4/src/qcommon/msg.c#L1156

This makes `CG_Bullet` potentially process impacts with incorrect entitynumber, if the entity number is > `255`, which can cause things like this to happen (`entityNum` wraps around to value < `MAX_CLIENTS`, so flesh impact is applied)

![2024-05-20-221636-etl_base](https://github.com/etlegacy/etlegacy/assets/14221121/4f352432-12f5-4731-932e-8625769ed3cf)
![image](https://github.com/etlegacy/etlegacy/assets/14221121/87194862-e55f-4bee-aebb-4648f4f16876)
![image](https://github.com/etlegacy/etlegacy/assets/14221121/9b31bc11-4977-42be-a1b2-3a053823c5dd)

**Comment by Aciz** [comment]
Caused by https://github.com/etlegacy/etlegacy/commit/d8bba8e5f43551612df3707f47115376bc1c905d

**Comment by Vorschreibung** [comment]
Rebased on `master` - ready for review now.
