### ISSUE TITLE
Mounted MG42 fires excess overheat events when unmounting and re-mounting

### ISSUE THREAD

**Issue by Aciz** [etlegacy/etlegacy#2572]
Mounted MG42s are handled mostly on server side, when a client mounts MG42, cgame never gets the correct heat value that the MG currently has (`pmext->weapHeat[WP_DUMMY_MG42]` is only updated on server side as there's no cgame code that handles mounting at all). This means that when a client fires mounted MG42 until it overheats, exits the gun and then re-enters it, the client/server side heat values get de-synced, server gets the updated value from the MG42 entity, but client never receives this.

https://streamable.com/ji2ai3

This, combined with moving the `weapHeat` to `pmext`, causes cgame to fire excess overheat events, as the client-side `Pmove` thinks the weapon is overheating since it's now de-synced from the server value. When `weapHeat` was stored in `ps`, the client side value never got updated as there's no mounted MG handling in cgame, so the weapon heat value effectively stayed at 0. This meant that server side `Pmove` called from `Clientthink_real` was responsible for triggering the overheating event. Now that weapon heat is stored in `pmext`, the client side value is also updated, but it gets de-synced in the scenario explained above, which causes client side `Pmove` to fire excess overheat events.

Since this client side `pmext->weapHeat[WP_DUMMY_MG42]` isn't actually used for anything, a potential fix is to simply keep it at 0 with an `#ifdef CGAMEDLL` in `Pmove`, which hands off the event firing to server side, which is correctly synced to the mounted MG heat when unmounting/re-mounting.

Another, probably cleaner way to fix this is setting `cg.pmext.weapHeat[WP_DUMMY_MG42]` to 0 in `CG_PredictPlayerState`, so the client value doesn't get updated like in vanilla implementation.

**Comment by ryzyk-krzysiek** [comment]
Since the comments on that merged commit don't load for me for whatever reason I will reply here because I can't be arsed waiting.

> Yeah I'm aware of the downsides of this, but I honestly doubt it's gonna come up much, and it's much less intrusive than the excess overheat events that were getting fired. I don't think it's possible to (at least easily) communicate the heat value properly from the mounted guns, iirc they aren't networked to begin with.

Yea I guess it's debatable, I don't have any strong opinion about it just sharing my thoughts.

I think the extra event happens everytime at least once regardless of ping and the higher the ping the more it will happen (you can shoot every 66ms so not more than that) on the other hand the other issue happens on re-entry which might happen less often although it is more noticeable.

When I was experimenting few months back I wanted to try sending it as server command and it works but it is susceptible to packet loss. Command itself is reliable so it is never lost, but the value sent becomes outdated and I couldn't think of a way around it at the time.

```diff
diff --git a/src/cgame/cg_local.h b/src/cgame/cg_local.h
index f893202fe..746fe1415 100644
--- a/src/cgame/cg_local.h
+++ b/src/cgame/cg_local.h
@@ -1581,6 +1581,8 @@ typedef struct
 	                                                  ///< instead of iterating through whole CMD_BACKUP array every frame
 
 	qboolean mapConfigLoaded; // qtrue if map-specific autoexec was loaded
+
+	float mg42Update;
 } cg_t;
 
 #define MAX_LOCKER_DEBRIS 5
diff --git a/src/cgame/cg_predict.c b/src/cgame/cg_predict.c
index 5a8b52e73..44f4d2880 100644
--- a/src/cgame/cg_predict.c
+++ b/src/cgame/cg_predict.c
@@ -1123,7 +1123,7 @@ void CG_PredictPlayerState(void)
 	// the heat values of each individual mounted gun in the map
 	// otherwise we fire excess overheat events when client exits and re-enters
 	// the gun, as the correct heat value is never assigned client side
-	cg.pmext.weapHeat[WP_DUMMY_MG42] = 0.0f;
+	//cg.pmext.weapHeat[WP_DUMMY_MG42] = 0.0f;
 
 	// fill in the current cmd with the latest prediction from
 	// cg.pmext (#166)
@@ -1393,6 +1393,13 @@ void CG_PredictPlayerState(void)
 		{
 			cg.oldestValidCmd       = cmdNum;
 			cg.updateOldestValidCmd = qfalse;
+
+			// copy the pmext value from server onto first valid pmext
+			// further ones will be re-predicted again from this state
+			if (cg.mg42Update)
+			{
+				pmext.weapHeat[WP_DUMMY_MG42] = cg.mg42Update;
+			}
 		}
 
 		if (cg_pmove.pmove_fixed)
@@ -1425,7 +1432,12 @@ void CG_PredictPlayerState(void)
 		// copy the pmext as it was just before we
 		// previously ran this cmd (or, this will be the
 		// current predicted data if this is the current cmd)  (#166)
-		Com_Memcpy(&pmext, &oldpmext[cmdNum & cg.cmdMask], sizeof(pmoveExt_t));
+		// don't copy if we received pmext value from server
+		// as we need to re-predict them just like playerstate
+		if (!cg.mg42Update)
+		{
+			Com_Memcpy(&pmext, &oldpmext[cmdNum & cg.cmdMask], sizeof(pmoveExt_t));
+		}
 
 		fflush(stdout);
 
@@ -1504,6 +1516,8 @@ void CG_PredictPlayerState(void)
 		CG_Printf("[%i : %i] ", cg_pmove.cmd.serverTime, cg.time);
 	}
 
+	cg.mg42Update = 0;
+
 	if (!moved)
 	{
 		if (cg_showmiss.integer)
diff --git a/src/cgame/cg_servercmds.c b/src/cgame/cg_servercmds.c
index 2de0ab6fa..2c9281787 100644
--- a/src/cgame/cg_servercmds.c
+++ b/src/cgame/cg_servercmds.c
@@ -3101,6 +3101,7 @@ void CG_AddToBannerPrint(const char *str)
 #define BP_HASH             25102
 #define XPGAIN_HASH         78572
 #define AUTH_SHOW_MSG_HASH  92849
+#define MG_HASH             25331
 // -----------
 
 /**
@@ -3697,6 +3698,9 @@ static void CG_ServerCommand(void)
 		break;
 	}
 #endif
+	case MG_HASH:
+		cg.mg42Update = Q_atof(CG_Argv(1));
+		break;
 	default:
 		CG_Printf("Unknown client game command: %s [%lu]\n", cmd, hash);
 		break;
diff --git a/src/game/g_active.c b/src/game/g_active.c
index 83f54ae4c..0cd84d099 100644
--- a/src/game/g_active.c
+++ b/src/game/g_active.c
@@ -2437,4 +2437,12 @@ void ClientEndFrame(gentity_t *ent)
 
 	// store the client's current position for antilag traces
 	G_StoreClientPosition(ent);
+
+	// this breaks if packet is lost
+	// the value the client receives is outdated
+	if (ent->client->mg42Update)
+	{
+		trap_SendServerCommand(ent - g_entities, va("mg %0.6f\n", ent->client->pmext.weapHeat[WP_DUMMY_MG42]));
+		ent->client->mg42Update = qfalse;
+	}
 }
diff --git a/src/game/g_cmds.c b/src/game/g_cmds.c
index 7dafaf0a8..f6c0115c9 100644
--- a/src/game/g_cmds.c
+++ b/src/game/g_cmds.c
@@ -4161,6 +4161,7 @@ qboolean Do_Activate_f(gentity_t *ent, gentity_t *traceEnt)
 		ent->backupWeaponTime                      = ent->client->ps.weaponTime;
 		ent->client->ps.weaponTime                 = traceEnt->backupWeaponTime;
 		ent->client->pmext.weapHeat[WP_DUMMY_MG42] = traceEnt->mg42weapHeat;
+		ent->client->mg42Update                    = qtrue;
 
 		G_UseTargets(traceEnt, ent);     // added for Mike so mounting an MG42 can be a trigger event (let me know if there's any issues with this)
 	}
diff --git a/src/game/g_local.h b/src/game/g_local.h
index fef4798af..3a453c169 100644
--- a/src/game/g_local.h
+++ b/src/game/g_local.h
@@ -1068,6 +1068,8 @@ struct gclient_s
 	char scores[MAX_SCORES_CMDS][MAX_STRING_CHARS];
 
 	damageReceivedStats_t dmgReceivedSts[MAX_CLIENTS];
+
+	qboolean mg42Update;
 };
 
 /**

```

The other idea I've had was to try using array `ps->holdable[16]` since it is networked but it is unused even in VET iirc, but never got around to trying it since it wasn't that interesting, although it probably would add less bandwidth than that server command I think.
