### ISSUE TITLE
Rifle fire animation bug. Tip of weapon does not shake like gun does

### ISSUE THREAD

**Issue by u1ps** [etlegacy/etlegacy#2603]
Allies and Axis rifle affected. Effect is stronger on Axis rifle

https://discord.com/channels/260750790203932672/346956915814957067/1257323902258905108

[Captures.zip](https://github.com/user-attachments/files/16053605/Captures.zip)

**Comment by Aciz** [comment]
https://github.com/etlegacy/etlegacy/assets/14221121/04d26240-61dd-4b1c-a957-369a9b4c9067


https://github.com/etlegacy/etlegacy/assets/14221121/8d6c1240-15de-406f-9c65-e9e19277d1df
