### ISSUE TITLE
internal image format for textures undefined/unknown unless texture bits is set

### ISSUE THREAD

**Issue by wwwchriswww** [etlegacy/etlegacy#2702]
i'm on windows 11, running 32 bit version of etlegacy. i just noticed that /imagelist command shows internal format as "????" for all listed images used in etlegacy. this should not be the case as tr_image.c is supposed to assign a default RGB format if all else fails however, this somehow doesnt work out. if you have compression turned on, then a few images will show up as DXT5 but majority is still "????". simply changing r_texturebits to 32 or 16 rather than default 0, now shows internal image formats as having been assigned, e.g. RGB8.

**Comment by Aciz** [comment]
The fault here is actually simply in the `imagelist` command, it does not correctly handle all the possible formats that are assigned to images, and just falls back to the default case of `????`. The format is set correctly, this just fails to parse it.

https://github.com/etlegacy/etlegacy/blob/609fdcad2e082a1b62817f55d043b928c3789931/src/renderer/tr_image.c#L205-L283

`r_textureBits 32` sets image format to `GL_RGBA8`, which is handled in the switch, but the default `0` is `GL_RGBA`, which is not handled.
