### ISSUE TITLE
Add permissions for Android app to view external demos

### ISSUE THREAD

**Issue by x0rnn** [etlegacy/etlegacy#2721]
You currently can't view demos recorded on another device from the Android app.

Possibly related issues from other software:

`Three new permission is introduced with Android 13: READ_MEDIA_IMAGES, READ_MEDIA_VIDEO, and READ_MEDIA_AUDIO. If you were using READ_EXTERNAL_STORAGE for accessing files, then you need to use one of these new permissions. If a user with Android 13 has previously granted this permission, then all is good. If not, then the permission request for READ_EXTERNAL_STORAGE will be ignored.
`

https://github.com/Baseflow/flutter-permission-handler/issues/1143

https://github.com/ankidroid/Anki-Android/pull/15825

@rafal1137

**Comment by x0rnn** [comment]
MANAGE_EXTERNAL_STORAGE permission is already included, but this doesn't work... 

Related:
https://github.com/apache/cordova-plugin-file/issues/568#issuecomment-1635875461

"Notes on API 33+
READ_EXTERNAL_STORAGE is now obsolete. It's still required to support API 32 and earlier, but on API 33, we have 3 new permissions:

READ_MEDIA_AUDIO
READ_MEDIA_IMAGES
READ_MEDIA_VIDEO
You'll notice we still don't have a permission for docs, so we cannot "discover" documentation. We can only open docs via a system file picker intent, like in previous android versions and only if the app that owns the document has a content provider implemented to grant third-party apps access to their document files."

**Comment by x0rnn** [comment]
I think the only way to make it work on modern Androids is to have a file picker method on the Demos menu, where you need to manually select a demo to play.

**Comment by mittermichal** [comment]
I would prefer to open demos from file browser using file type association rather than using game UI

**Comment by x0rnn** [comment]
Fixed in recent commits.
