### ISSUE TITLE
Make "VM_Create on cgame" error more informative for 64bit ETL

### ISSUE THREAD

**Issue by x0rnn** [etlegacy/etlegacy#2724]
Instead of `VM_Create on %s failed\n\nMake sure ^2%s ^*exists in the mod's folder you're trying to run and that the mod is compatible with your platform.`

Change it maybe to:
`VM_Create on %s failed\n\nMake sure ^2%s ^*exists in the mod's folder you're trying to run and that the mod supports your platform, or try the 32-bit client instead (for N!tmod, silEnT, Jaymod, NQ).`

**Comment by Exagone313** [comment]
It would be even better if we could enumerate the available mod binaries from the pk3 list received from the server and provide a list of the supported platforms.
