### ISSUE TITLE
Spontaneous Demo playback mode during gameplay in v2.82.1-269-gcf348cb

### ISSUE THREAD

**Issue by csmaxpower** [etlegacy/etlegacy#2797]
When pressing `SHIFT + W` AND/OR `SHIFT + S` repeatedly and with speed, you are magically removed from the team and put into what appears to be some type of demo playback mode.  You cannot swap teams or go spectator, the only fix is to disconnect and reconnect.

Here is a full demo file and a clip for quick review:

https://www.twitch.tv/mayaaaan/clip/InspiringSmokyToadSeemsGood-p9pSmCMdArz17Btw

[2024-09-19-demobug-etl_frostbite.zip](https://github.com/user-attachments/files/17066351/2024-09-19-demobug-etl_frostbite.zip)

**Comment by mittermichal** [comment]
it's multiview being activated
maybe he pressed bind for `mvactivate` on accident (M by default)

**Comment by mittermichal** [comment]
the issue is that multiview should only be allowed for spectator

**Comment by csmaxpower** [comment]
> the issue is that multiview should only be allowed for spectator

just as an FYI, the behavior currently in spectator when trying to use `mvactivate` is a message response of:  `INFO: Multiview is disabled by server`

**Comment by mittermichal** [comment]
I see, so maybe it's not that simple 😄

**Comment by Aciz** [comment]
This looks like an overflow happening somewhere, at the time MV is activated, the game thinks there's 3 multiview clients (`ps.powerups[PW_MVCLIENTLIST]`), and curiously `ps.ammo[0]` is 4025, which makes no sense since it's `WP_NONE`.

Edit: so what this means is that nobody activated multiview by accident/on purpose, but there's an invalid write to a memory address that sets the powerup field so that the client thinks it's in multiview.

![image](https://github.com/user-attachments/assets/cdd9dfa5-e92e-4181-8081-06a44bb10e81)

**Comment by Aciz** [comment]
@csmaxpower just to rule this out quickly: were there any LUAs running on the server?

**Comment by csmaxpower** [comment]
> @csmaxpower just to rule this out quickly: were there any LUAs running on the server?

yes, `team-lock` (keeps teams locked when in play), and `game-stats` (writes end round stats to file).  Can send both if you want to look them over.

**Comment by Aciz** [comment]
Looked over the LUAs in DMs, they are fine, no writes to playerstate are happening, only reads. So this is definitely an error in code somewhere that writes garbage value to `ps.powerups` and/or `ps.ammo`.

**Comment by ryzyk-krzysiek** [comment]
> > the issue is that multiview should only be allowed for spectator
> 
> just as an FYI, the behavior currently in spectator when trying to use `mvactivate` is a message response of: `INFO: Multiview is disabled by server`

You can do `mvadd` while in game though, I don't know why would anyone have it bound and use it by accident though. As to why it is even possible I don't know. Whole multiview is probably 20 year old VET code never touched by anyone and so bugged as hell.

**Comment by ryzyk-krzysiek** [comment]
And to clarify, it works and breaks the game similiar as in the clip but I doubt anyone used it.

**Comment by Aciz** [comment]
> And to clarify, it works and breaks the game similiar as in the clip but I doubt anyone used it.

Oof, yeah that should not be possible. Still, given the stacktrace and state of ps during the demo playback, I don't think that's what happened here.

**Comment by ryzyk-krzysiek** [comment]
> > And to clarify, it works and breaks the game similiar as in the clip but I doubt anyone used it.
> 
> Oof, yeah that should not be possible. Still, given the stacktrace and state of ps during the demo playback, I don't think that's what happened here.

Yea idk what triggered mv exactly, but I don't think it was some garbage values either, although I spent only a moment looking at this.

1. Number 35 in ps.powerups is to my understanding bits of bit shifted client ids, [0, 1, 5] -> 1 + 2 + 32 = 35
2. multiview reuses `ps.ammo` to store additional information. IIRC even etpro reuses it (either first or last index) for sprinttime, other mods like legacy send it in ~~powerups~~ stats.

**Comment by Aciz** [comment]
> > > And to clarify, it works and breaks the game similiar as in the clip but I doubt anyone used it.
> > 
> > 
> > Oof, yeah that should not be possible. Still, given the stacktrace and state of ps during the demo playback, I don't think that's what happened here.
> 
> Yea idk what triggered mv exactly, but I don't think it was some garbage values either, although I spent only a moment looking at this.
> 
>     1. Number 35 in ps.powerups is to my understanding bits of bit shifted client ids, [0, 1, 5] -> 1 + 2 + 32 = 35
> 
>     2. multiview reuses `ps.ammo` to store additional information. IIRC even etpro reuses it (either first or last index) for sprinttime, other mods like legacy send it in powerups.

Oh you're right, I completely missed that mv writes to playerstate like that, so it could just be a red herring.

It seems really weird though that this would just be activated via accidental `mvadd` command, and furthermore the demo actually crashes in `CG_mvTransitionPlayerState`, but recording a demo where you specifically do `mvadd` when you're not supposed to be able to use mv at all does not cause such crash, which makes me think this mv access was not done "properly" via the command, so some setup was missing and that caused a crash.

![image](https://github.com/user-attachments/assets/2d98cfa0-e233-478d-8253-72fee6546171)

**Comment by mittermichal** [comment]
are those multiview clients stored in ps.powerups referencing valid clients ids or is it garbage?

**Comment by Aciz** [comment]
> are those multiview clients stored in ps.powerups referencing valid clients ids or is it garbage?

AFAIS no, 0, 1 and 5 were not valid clientnums for players on the server.
