### ISSUE TITLE
crushing player gives 30 max lives

### ISSUE THREAD

**Issue by mittermichal** [etlegacy/etlegacy#2828]
[outlAw twitch clip](https://www.twitch.tv/outlawryy/clip/RepletePhilanthropicHerdYouDontSay-46pSwjM3yvtXRAb_)
[2024-09-29-213554-supply.zip](https://github.com/user-attachments/files/17181425/2024-09-29-213554-supply.zip) in this demo it happens at 8:23

dunno if it happened to other players at that moment, need to ask

**Comment by Vorschreibung** [comment]
Tried to reproduce on supply. Crushed a player via truck. Maxlives remained unchanged.

**Comment by mittermichal** [comment]
I checked demos from 2 allies players from that outlaw's twitch clip and none of them got this bug at that specific moment

**Comment by mittermichal** [comment]
idea to reproduce: make lua script that will crush some other players periodically and do it with many bots

**Comment by mittermichal** [comment]
btw MOD_CRUSH = 30

**Comment by Vorschreibung** [comment]
> btw MOD_CRUSH = 30

good find!

**Comment by mittermichal** [comment]
> idea to reproduce: make lua script that will crush some other players periodically and do it with many bots

managed to reproduce using following lua script:
```lua
function et_ClientCommand(clientNum, command)
        if command == "crush" then
                for i = 0,et.MAX_CLIENTS      
                do      
                        if i ~= clientNum then
                                et.G_Damage( i, 0, 89, 10, 0, et.MOD_CRUSH-1 ) -- supply truck is 89
                        end
                end
                return 1
        end
end
```
Max lives are then set to whatever MOD is ( et.MOD_CRUSH-1 == 29 )
To reproduce I used 1 client to host server and set `lua_modules` and join some team. Run another client and join some team too. Run `crush` command with second client when client1 doesn't have spawn shield anymore.

It happens on any damage (its 10 in lua). The damage attacker has to be 89.


![shot0003](https://github.com/user-attachments/assets/24d0b0f8-9135-47b0-9119-b5a8b977bef7)


```
\players 
[skipnotify]GUID      Status   : ID : Player                    Nudge  Rate  MaxPkts  Snaps  Specials
[skipnotify]-----------------------------------------------------------------------------------------
[skipnotify]48265E5B* NOTREADY :L 0 : client1(server)               0 45000      125     40  REF       ET Legacy v2.82.1-248-gabafe02 linux-x86_64 Sep 30 2024 DEBUG
[skipnotify]48265E5B* NOTREADY :L 1 : client2                       0 45000      125     40            ET Legacy v2.82.1-248-gabafe02 linux-x86_64 Sep 30 2024 DEBUG
```

**Comment by Vorschreibung** [comment]
Great! Can you do a git bisect? - Let's try to find out when this was introduced!
`d59dd6c45df82af43d27758a59ec1455f65c08af` is the latest revision that still builds out of the box on my Linux setup
