### ISSUE TITLE
Invalid pk3 files when building old snapshots

### ISSUE THREAD

**Issue by HeDo88TH** [etlegacy/etlegacy#2838]
Since the built snapshots are not stored beyond daily and weekly, I need to be able to build an arbitrary snapshot given its commit hash.
This is what I have right now:

`$1` is the commit hash (first parameter)

```bash
git clone --recurse-submodules https://github.com/etlegacy/etlegacy.git
git fetch --tags --force
git checkout "$1"

cd etlegacy

export CI_ETL_DESCRIBE=$(git describe --abbrev=7 2>/dev/null | awk '{$1=$1};1')
export CI_ETL_TAG=$(git describe --abbrev=0 2>/dev/null | awk '{$1=$1};1')

# Output version info
echo "Version info: $CI_ETL_DESCRIBE ?? $CI_ETL_TAG"

cd ..

docker run --rm -v ${PWD}/etlegacy:/code -e CI_ETL_DESCRIBE=${CI_ETL_DESCRIBE} -e CI_ETL_TAG=${CI_ETL_TAG} -e CI=true -it etlegacy/lnx-build:latest bash
```

Inside the build container I run:

```bash
./easybuild.sh build -64
cd build
cpack
```

And I get:

```
[...]
[100%] Generating legacy/legacy_v2.82.1-306-g7cf4f61.pk3
[100%] Built target mod_pk3
[...]
CPack: Create package
CPack: - package: /code/build/etlegacy-v2.82.1-306-g7cf4f61-x86_64.tar.gz generated.
[...]
```

Now if I compare it with the one built with the github workflow:

```
wget https://www.etlegacy.com/workflow-files/dl/7cf4f61cf1a9b79b75d1afe02d52afca991ec0bd/lnxx8664/etlegacy-v2.82.1-306-g7cf4f61-x86_64.tar.gz

sha1sum etlegacy-v2.82.1-306-g7cf4f61-x86_64.tar.gz
# 48bed90dd284243ca25bbb35f9f7dbf6d6fce018  etlegacy-v2.82.1-306-g7cf4f61-x86_64.tar.gz

sha1sum etlegacy/build/etlegacy-v2.82.1-306-g7cf4f61-x86_64.tar.gz
# 27cc4f3abfdf4c6c4e852d41f5692d7d2e0f1ec6  etlegacy/build/etlegacy-v2.82.1-306-g7cf4f61-x86_64.tar.gz
```
They are different! And they have different sizes: 85.009.353 (github) vs ls 69.706.814 (built) which is much smaller (?).

When I try to run a server using the freshly built archive I get invalid pk3 files. 

This is the server dockerfile I use:
```dockerfile

FROM debian:stable-slim AS builder

COPY etlegacy*.tar.gz /legacy/server/

RUN mkdir -p /legacy/homepath \
    && cd /legacy/server \
    && tar zxvf etlegacy*.tar.gz --strip-components=1 \
    && rm etlegacy*.tar.gz \
    && arch=$(arch) \
    && rm etl.$arch etl_bot.$arch.sh *.so \
    && mv etlded.$arch etlded \
    && mv etlded_bot.$arch.sh etlded_bot.sh

FROM debian:stable-slim

RUN useradd -Ms /bin/bash legacy \
    && mkdir -p /legacy/homepath \
    && chown -R legacy:legacy /legacy \
    && chmod -R 775 /legacy/homepath

COPY --from=builder --chown=legacy:legacy /legacy /legacy/

WORKDIR /legacy/server

VOLUME /legacy/homepath
VOLUME /legacy/server/etmain

EXPOSE 27960/UDP

USER legacy

ENTRYPOINT ["./etlded", "+set", "fs_homepath", "/legacy/homepath", "+set", "g_protect", "1", "+exec", "etl_server.cfg"]

```

It's a slighly edited official docker file.

Can anyone tell me why it is not possible to rebuild correctly the old snapshots?

**Comment by Exagone313** [comment]
The build you can download contains the mod built for each platform, but your build is only for the Linux x86-64 platform.

The checksum will always be different as ET Legacy doesn't make reproducible builds.

**Comment by HeDo88TH** [comment]
Ok clear but why doesn't it work? You cannot connect to the resulting server. It sends "Invalid PK3 files" to every client

> The build you can download contains the mod built for each platform, but your build is only for the Linux x86-64 platform.

That's the platform where the server is going to run

**Comment by HeDo88TH** [comment]
This is the culprit: I need to build the mod files for each and every platform and merge them together into a single archive

**Comment by Aranud** [comment]
Can we close this case ?

**Comment by HeDo88TH** [comment]
Yes!
