### ISSUE TITLE
Make all weapons recoil FPS independent and random

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#284]
Author: @rmarquis (Spyhawk)
Date: 2013-04-07
Redmine Issue: 284, https://dev.etlegacy.com/issues/284

---

Current recoil value is highly FPS dependent (specially the 71 FPS value).
Recoil should be made (slightly) random and FPS independent.

Note that some mode removed +lookup, -lookup, +lookdown, and -lookdown commands from the client mod to deal with anti-recoil cheats.

Forum discussion link: http://dev.etlegacy.com/boards/3/topics/326

**Comment by ETLegacyTeam** [comment]
From: @realkemon (keMoN)
Date: 2019-05-03T12:28:13Z

---

https://github.com/etlegacy/etlegacy/blob/f0bf85d7e1b1675b9e69ce6b47d3c12604406560/src/qcommon/common.c#L2923

What's going on here?

**Comment by ryzyk-krzysiek** [comment]
The mentioned issue with recoil in PR was just on my end as the servers using snapshot that has this change have no issues, so everything looks to be fine.
