### ISSUE TITLE
cg_drawgun 2 tank/mg inconsistency

### ISSUE THREAD

**Issue by x0rnn** [etlegacy/etlegacy#2907]
Reported by adr:

If you have cg_drawgun 2 and you use a MG nest or tank turret with your SMG, the gun is invisible (cg_drawgun 0), but if you use it with grenades or health pack for example, the gun is drawn (cg_drawgun 1)

**Comment by Vorschreibung** [comment]
Above PR fixes the tank mg rendering, however stationary MG42's are always rendered independent of `cg_drawGun`, as they are considered in world objects and not actually hand gun models AFAIS.
