### ISSUE TITLE
On Android 15, apply for permission to access external storage files

### ISSUE THREAD

**Issue by Junkmer** [etlegacy/etlegacy#2911]
Please kindly ask whether the latest version of permission_handler now supports application for external file access permission of Android 15. I see no relevant description in change log. I also cannot apply for "external file access permission" when running on the Android 15 emulator. Is there an estimated release time for support
![image](https://github.com/user-attachments/assets/21982984-5797-4e7a-9f03-57bba15c8f6e)

**Comment by x0rnn** [comment]
Related to https://github.com/etlegacy/etlegacy/issues/2721

**Comment by rafal1137** [comment]
This can be closed since latest changes in permissions has resolved access for files in external storage.
