### ISSUE TITLE
Prevent mid-air proning

### ISSUE THREAD

**Issue by Vorschreibung** [etlegacy/etlegacy#2916]
ET:L currently allows to prone mid-air in scenarios where ETPro prevents doing so.

e.g.: deploying MG42 mid-air

ETPRO

https://github.com/user-attachments/assets/013dccc8-3e98-4ff1-a349-4a98a8d31e3b

vs ETL

https://github.com/user-attachments/assets/4a462ea3-6c91-45e3-b258-462b3cffc555

**Comment by Vorschreibung** [comment]
There's supposedly issues with hitboxes while mid-air proning, some of that seems reflected in the following footage (notice the prone leg hitbox starting to show) - however the body hitbox seems to stay the correct size.

Should be further investigated.

https://github.com/user-attachments/assets/dbc14b21-d430-4c34-a680-62c4f502b2d2

**Comment by mittermichal** [comment]
in addition some unintended jumps are possible due to mid-air proning e.g. https://www.youtube.com/watch?v=FQIZ36OgFbA

**Comment by ryzyk-krzysiek** [comment]
> ET:L currently allows to prone mid-air in scenarios where ETPro prevents doing so.

Just use `g_pronedelay 2` then, ask server owners and their players why it's not enabled (spoiler: they like it)

**Comment by Aciz** [comment]
This was requested years back already, it's been in the game as an option since 2.81.0

https://github.com/etlegacy/etlegacy/commit/db430512b455679c1ea00b23e5b0c9910fc9c050

**Comment by mittermichal** [comment]
so just set g_pronedelay to 3 in competitive configs ( currently 1 is used https://github.com/Oksii/legacy-configs/blob/f4773c04c6cf6a455a14c22cd09999f775366a62/configs/legacy6.config#L128 )

I had no idea this cvar is bitmask with ability to remove mid-air jump

**Comment by ryzyk-krzysiek** [comment]
> in addition some unintended jumps are possible due to mid-air proning e.g. https://www.youtube.com/watch?v=FQIZ36OgFbA

ETL ships with legacy configs that use `g_pronedelay 3` https://github.com/etlegacy/etlegacy/blob/94a47fadb735e6adb740426caac8c7de9e889e7e/etmain/configs/legacy6.config#L128

**Comment by mittermichal** [comment]
> (spoiler: they like it)

who? competitive players?

**Comment by Vorschreibung** [comment]
Beautiful! Thanks everyone! :heart_hands:

**Comment by ryzyk-krzysiek** [comment]
> > (spoiler: they like it)
> 
> who? competitive players?

Teammuppet, they had a vote on it years ago, and it was voted to keep proning mid-air, maybe they don't anymore, I wouldn't know.
