### ISSUE TITLE
Location Data commands from ETpro* - dd locations editor

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#292]
Author: @harleking (Harlekin)
Date: 2013-04-15
Redmine Issue: 292, https://dev.etlegacy.com/issues/292

---

I miss the features to create/edit/modify location data files.

Commands: 
loc_add
loc_del (operates on closest)
loc_rename (closest)
loc_save [full]
loc_load
loc_show (closest)

Implement loc_add , loc_del (operates on closest), loc_rename (closest), loc_save [full], loc_load, loc_show (closest)

see also http://wolfwiki.anime.net/index.php/Target_location

---

Related issue(s): #590

**Comment by jackeri** [comment]
Added a "loc" command that has the relevant commands as arguments. Like "loc open", "loc save", "loc edit" etc.
