### ISSUE TITLE
Crosshair is blurry / transparent since 2.82.0

### ISSUE THREAD

**Issue by S1RIUS1** [etlegacy/etlegacy#2942]
Crosshair is blurry / transparent since 2.82.0

Tried r_scalesvg 1 or 2
Tried cg_useCvarCrosshair 1
Tried with a fresh profile.

Files included show the difference between 2.82.1 and 2.81.1. 
Crosshairsize is 38, game is running at 1080p on 1080p screen.

Rendering the game at 1440p then downscaling it to 1080p _fix_ the issue (with nvidia SuperRes)

![2811](https://github.com/user-attachments/assets/ab992cdc-b90c-4363-807e-8a2206c76fc0)
![2821](https://github.com/user-attachments/assets/b0525da0-d44f-4d19-ac72-9ee59087a19c)

**Comment by Vorschreibung** [comment]
Thanks for reporting! :heart: We'll look into it!

**Comment by Vorschreibung** [comment]
@Aranud AFAIS this can be closed since we now have `cg_crosshairSVG`.

**Comment by Aciz** [comment]
I wouldn't necessarily consider this fixed, the cvar is a duct tape solution to the underlying issue.

**Comment by Aranud** [comment]
The duct tape will stay until crosshair editor will be in. Would say, svg will be no longer a discussion for crosshair all

**Comment by Vorschreibung** [comment]
> The duct tape will stay until crosshair editor will be in. Would say, svg will be no longer a discussion for crosshair all

I agree.
