### ISSUE TITLE
New custom crosshairs not in build

### ISSUE THREAD

**Issue by wwwchriswww** [etlegacy/etlegacy#2978]
upon installing new version 2.83.1 for windows, dont see any cg_customcrosshair* cvars in base mod. new sharp vector based custom crosshairs are introduced in changelog, but looks like not present.

**Comment by mittermichal** [comment]
are you trying this on your local server or on some online server? This is a mod feature and if you are connected to a server that still has older mod version, you won't be able to use it there.

**Comment by wwwchriswww** [comment]
wasnt running any server yet. thought it would come up as a cvar. also tried whilst connected to jaymod server. guess it needs etlegacy mod with new version running on server. thanks, close.

**Comment by mittermichal** [comment]
for other mods you can try https://github.com/lacymorrow/crossover
