### ISSUE TITLE
Nerf scoped FG42

### ISSUE THREAD

**Issue by x0rnn** [etlegacy/etlegacy#2981]
In 2.83 the recoil for scoped weapons is closer to 71 FPS, so whereas in 2.82 there was a bug for lvl3 covert ops where the recoil for FG42 was very tiny, that is now fixed, but now with recoil being closer to 71 FPS, FG42 is already overpowered with lvl0.

Possible fixes are:
1) return firerate from 200 to 400 or possibly 300ms
2) return FG42 recoil closer to 100 FPS
3) reduced scoped damage (not a fan of this)

**Comment by Aranud** [comment]
The aim spread cool down decrease too fast in Legacy compared to vanilla.
Recoil will be adjusted as well.
