### ISSUE TITLE
Players name draw time instant fade out

### ISSUE THREAD

**Issue by x0rnn** [etlegacy/etlegacy#2982]
Reported by u!ps

https://github.com/user-attachments/assets/5d5ab7d0-f3f4-4d8d-8892-157c4684f4d8

**Comment by Aranud** [comment]
`cg_drawcrosshairFade` default value has been reduced from 1000 to 250. 
The behaviour observed is normal.

**Comment by x0rnn** [comment]
Oh, was there a reason for that? Do I close this then?

**Comment by Aranud** [comment]
The reason was it hide too much field of view (at least on default HUD). 
You can close it :)

**Comment by Aranud** [comment]
The fade effect work for all entities who may draw an health bar to crosshair .... but players.

This need to be fixed
