### ISSUE TITLE
Tweak default client config

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#300]
Author: @adanski (Dragonji)
Date: 2013-05-02
Redmine Issue: 300, https://dev.etlegacy.com/issues/300

---

This is a very important thing in my eyes. It would be great if the default cfg that is bundled with installer was "newbie friendly" as default config is terrible IMO, especially for newbies who dunno much about cvars and stuff (there aren't many new players unfortunately).

For me the biggest issues are:
1. It is too dark by default (even Oasis doesn't look like an Nothern African map in noon time)
2. The weap viewmodel take almost half of the screen, small FoV increase (let's say to 100) would be appreciated.
3. Blood HUD splash, bob things etc. are not any useful to play better.
4. ... more to add

---

Related commit(s):
b4d8f8c8412f8db1058cd08736e0f365c6e47a33 - cgame: enable hitsounds by default, refs 300
 0b193eed3b55b2e6279261b1dddac5261574ced7 - cgame: set default fov value to 106.27 for 16:9 sc..
 91e4bb66e395ce8cd668c0e9bc1517928f2f33e7 - Revert "cgame: set default fov value to 106.27 for..

**Comment by ETLegacyTeam** [comment]
From: @adanski (Dragonji)
Date: 2013-06-27T00:25:23Z

---

Here's my config for example, with screenshots (it is too bright on winter maps such as Rail Gun though).

> seta r_displayRefresh "75"
> seta r_smp "0"
> seta r_mode "7"
> seta r_depthbits "24"
> seta r_stencilbits "0"
> seta r_stereo "0"
> seta r_colorbits "0"
> seta r_texturebits "0"
> seta r_clampToEdge "1"
> seta r_ext_texture_env_add "1"
> seta r_nv_fogdist_mode "GL_EYE_RADIAL_NV"
> seta r_ext_NV_fog_dist "0"
> seta r_ext_texture_filter_anisotropic "0"
> seta r_ati_fsaa_samples "1"
> seta r_ati_truform_pointmode "GL_PN_TRIANGLES_POINT_MODE_LINEAR"
> seta r_ati_truform_normalmode "GL_PN_TRIANGLES_NORMAL_MODE_LINEAR"
> seta r_ati_truform_tess "1"
> seta r_ext_ATI_pntriangles "0"
> seta r_glIgnoreWicked3D "0"
> seta r_ext_compiled_vertex_array "1"
> seta r_ext_multitexture "1"
> seta r_ext_gamma_control "1"
> seta r_ext_compressed_textures "1"
> seta r_allowExtensions "1"
> seta r_glDriver "opengl32"
> seta joy_threshold "0.15"
> seta in_joyBallScale "0.02"
> seta in_joystick "0"
> seta in_mouse "1"
> seta in_mididevice "0"
> seta in_midichannel "1"
> seta in_midiport "1"
> seta cg_zoomstepsniper "2"
> seta cg_zoomDefaultSniper "20"
> seta cg_voiceSpriteTime "6000"
> seta cg_descriptiveText "1"
> seta snaps "20"
> seta sensitivity "2.4"
> seta scr_conspeed "6"
> seta rate "50000"
> seta pmove_msec "8"
> seta pmove_fixed "0"
> seta mv_sensitivity "20"
> seta cm_playerCurveClip "1"
> seta s_wavonly "0"
> seta s_volume "0.281250"
> seta s_separation "0.5"
> seta s_musicvolume "0.541667"
> seta s_mixPreStep "0.05"
> seta s_mixahead "0.2"
> seta s_khz "44"
> seta s_doppler "1"
> seta s_defaultsound "0"
> seta s_channels "2"
> seta s_bits "16"
> seta r_znear "3"
> seta r_zfar "0"
> seta r_wolffog "0"
> seta r_uifullscreen "0"
> seta r_trisColor "1.0 1.0 1.0 1.0"
> seta r_textureMode "GL_LINEAR_MIPMAP_NEAREST"
> seta r_textureAnisotropy "1.0"
> seta r_swapInterval "0"
> seta r_subdivisions "999"
> seta r_singleShader "0"
> seta r_simpleMipMaps "1"
> seta r_showtris "0"
> seta r_shownormals "0"
> seta r_showmodelbounds "0"
> seta r_roundImagesDown "1"
> seta r_railWidth "16"
> seta r_railSegmentLength "32"
> seta r_railCoreWidth "1"
> seta r_primitives "0"
> seta r_picmip "1"
> seta r_overBrightBits "1"
> seta r_oldMode ""
> seta r_normallength "0.5"
> seta r_nocurves "0"
> seta r_nocull "0"
> seta r_mapoverbrightbits "3"
> seta r_lodscale "5"
> seta r_lodCurveError "250"
> seta r_lodbias "2"
> seta r_lightmap "0"
> seta r_intensity "1.50"
> seta r_inGameVideo "1"
> seta r_ignorehwgamma "1"
> seta r_ignoreGLErrors "1"
> seta r_ignoreFastPath "0"
> seta r_highQualityVideo "0"
> seta r_gamma "1.48"
> seta r_fullscreen "1"
> seta r_flares "0"
> seta r_finish "0"
> seta r_fastsky "0"
> seta r_facePlaneCull "1"
> seta r_dynamiclight "0"
> seta r_drawworld "1"
> seta r_drawSun "0"
> seta r_drawfoliage "0"
> seta r_drawentities "1"
> seta r_dlightBacks "1"
> seta r_detailtextures "0"
> seta r_customaspect "1"
> seta r_colorMipLevels "0"
> seta r_clear "0"
> seta r_cacheShaders "1"
> seta r_ambientScale "0.5"
> seta m_pitch "0.0131"
> seta m_yaw "0.019"
> seta m_forward "0.25"
> seta m_side "0.19"
> seta m_filter "0"
> seta con_autoclear "1"
> seta com_maxfps "125"
> seta com_introplayed "0"
> seta cl_yawspeed "140"
> seta cl_wwwDownload "1"
> seta cl_timenudge "0"
> seta cl_run "1"
> seta cl_pitchspeed "0"
> seta cl_packetdup "1"
> seta cl_mouseAccel "0"
> seta cl_maxpackets "100"
> seta cl_language "0"
> seta cl_freelook "1"
> seta cl_doubletapdelay "350"
> seta cl_anonymous "0"
> seta cl_allowDownload "1"
> seta cg_wolfparticles "0"
> seta cg_weaponcycledelay "1"
> seta cg_viewsize "100"
> seta cg_useWeapsForZoom "1"
> seta cg_useScreenshotJPEG "1"
> seta cg_teamChatTime "8000"
> seta cg_teamChatsOnly "0"
> seta cg_teamChatHeight "5"
> seta cg_stereoSeparation "0.4"
> seta cg_specHelp "1"
> seta cg_showblood "1"
> seta cg_shadows "0"
> seta cg_runroll "0"
> seta cg_runpitch "0"
> seta cg_recoilPitch "0"
> seta cg_railTrailTime "400"
> seta cg_quickMessageAlt "1"
> seta cg_printObjectiveInfo "1"
> seta cg_predictItems "1"
> seta cg_popupLimboMenu "0"
> seta cg_noVoiceText "0"
> seta cg_noVoiceChats "0"
> seta cg_noTaunt "0"
> seta cg_noAmmoAutoSwitch "0"
> seta cg_marktime "0"
> seta cg_instanttapout "1"
> seta cg_hudalpha "2"
> seta cg_gun_frame "0"
> seta cg_gibs "1"
> seta cg_fov "108"
> seta cg_footsteps "1"
> seta cg_fastSolids "1"
> seta cg_errordecay "100"
> seta cg_drawWeaponIconFlash "0"
> seta cg_drawTeamOverlay "2"
> seta cg_drawStatus "1"
> seta cg_drawSpreadScale "1"
> seta cg_drawSnapshot "0"
> seta cg_drawSmallPopupIcons "1"
> seta cg_drawRoundTimer "1"
> seta cg_drawReinforcementTime "1"
> seta cg_drawNotifyText "1"
> seta cg_drawGun "1"
> seta cg_drawFPS "1"
> seta cg_drawFireteamOverlay "1"
> seta cg_drawCrosshairPickups "1"
> seta cg_drawCrosshairNames "1"
> seta cg_drawCrosshair "5"
> seta cg_drawCompass "1"
> seta cg_drawBuddies "1"
> seta cg_draw2D "1"
> seta cg_damageKick "1"
> seta cg_cycleAllWeaps "1"
> seta cg_cursorHints "1"
> seta cg_crosshairY "0"
> seta cg_crosshairX "0"
> seta cg_crosshairSize "36"
> seta cg_crosshairPulse "0"
> seta cg_crosshairHealth "0"
> seta cg_crosshairColorAlt "red"
> seta cg_crosshairColor "cyan"
> seta cg_crosshairAlphaAlt "1.0"
> seta cg_crosshairAlpha "1.0"
> seta cg_coronas "0"
> seta cg_coronafardist "0"
> seta cg_complaintPopUp "0"
> seta cg_cameraOrbitDelay "50"
> seta cg_brassTime "0"
> seta cg_bobyaw "0"
> seta cg_bobup "0.0"
> seta cg_bobroll "0"
> seta cg_bobpitch "0"
> seta cg_bloodTime "0"
> seta cg_bloodFlash "0"
> seta cg_bloodDamageBlend "0"
> seta cg_blinktime "0"
> seta cg_autoswitch "0"
> seta cg_autoReload "0"
> seta cg_autoactivate "1"
> seta cg_autoAction "0"
> seta cg_atmosphericEffects "0"
> seta cg_announcer "1"
> seta cg_console "0"
> seta cg_consoleShadowed "1"
> seta cg_zoomfov "22.5"
> seta cg_zoomDefaultBinoc "22.5"
> seta cg_zoomDefaultSnooper "40"
> seta cg_zoomDefaultFG "55"
> seta cg_zoomStepBinoc "3"
> seta cg_zoomStepSnooper "5"
> seta cg_zoomStepFG "10"
> seta cg_deferPlayers "1"
> seta cg_hitsounds "1"
> seta cg_obituaryLocation "0"
> seta cg_obituaryFilter "0"
> seta cg_drawDisconnectIcon "1"
> seta cg_popupTime "0"
> seta cg_popupFadeTime "2500"
> seta cg_popupWaitTime "5000"
> seta cg_numPopups "10"
> seta cg_drawClock "0"
> seta cg_muzzleFlash "1"
> seta cg_mapZoom "5"
> seta cg_locationMode "0"
> seta cg_locationMaxChars "25"
> seta cg_locationJustify "0"
> seta cg_drawSpeed "0"
> seta cg_speedRefresh "100"
>
> seta cg_optimizePrediction "1"
> seta cg_recording_statusline "9"
> seta cg_tracers "1"
> seta cg_drawTime "1"
> seta cg_drawTimeSeconds "0"
> seta cg_panzerhack "1"
> seta cg_speedinterval "100"
> seta cg_speedunit "0"
> seta cg_fireteamAlpha "0.6"
> seta cg_chatAlpha "0.33"
> seta cg_lagometerAlpha "0.6"
> seta cg_specAlpha "1.0"

**Comment by ETLegacyTeam** [comment]
From: @JanSimek (Radegast)
Date: 2013-06-28T07:55:41Z

---

Are you still using 2.60b? If not, I recommend you let ET:L recreate the config, because there are tons of obsolete cvars in that config. I removed some of them plus Silent mod cvars and changed a couple of things. The remaining unchecked cvars are marked with ">"


```
seta r_mode "-2" // default to desktop resolution
seta r_depthbits "24"
seta r_stencilbits "0"
seta r_stereoEnabled "0"
seta r_colorbits "0"
seta r_texturebits "0"
seta r_ext_texture_env_add "1"
seta r_ext_texture_filter_anisotropic "0" // Why 0?
seta r_ext_compiled_vertex_array "1"
seta r_ext_multitexture "1"
seta r_ext_compressed_textures "1"
seta r_allowExtensions "1"
seta joy_threshold "0.15"
seta in_joyBallScale "0.02"
seta in_joystick "0"
seta in_mouse "1"
seta cg_zoomstepsniper "2"
seta cg_zoomDefaultSniper "20"
seta cg_voiceSpriteTime "6000"
seta cg_descriptiveText "1"
seta snaps "20"
seta sensitivity "2.4"
seta scr_conspeed "6" // maybe too much
seta rate "50000"
seta pmove_msec "8"
seta pmove_fixed "0"
> seta mv_sensitivity "20"
> seta cm_playerCurveClip "1"
> seta s_volume "0.281250"
> seta s_separation "0.5"
> seta s_musicvolume "0.541667"
> seta s_mixPreStep "0.05"
> seta s_mixahead "0.2"
> seta s_khz "44"
> seta s_doppler "1"
> seta s_defaultsound "0"
> seta s_channels "2"
> seta s_bits "16"
> seta r_znear "3"
> seta r_zfar "0"
> seta r_wolffog "0"
> seta r_uifullscreen "0"
> seta r_trisColor "1.0 1.0 1.0 1.0"
seta r_textureMode "GL_LINEAR_MIPMAP_NEAREST"
> seta r_swapInterval "0"
> seta r_subdivisions "999"
> seta r_singleShader "0"
> seta r_simpleMipMaps "1"
> seta r_showtris "0"
> seta r_shownormals "0"
> seta r_showmodelbounds "0"
> seta r_roundImagesDown "1"
> seta r_railWidth "16"
> seta r_railSegmentLength "32"
> seta r_railCoreWidth "1"
> seta r_primitives "0"
> seta r_picmip "1"
> seta r_overBrightBits "1"
> seta r_oldMode ""
> seta r_normallength "0.5"
> seta r_nocurves "0"
> seta r_nocull "0"
> seta r_mapoverbrightbits "3"
> seta r_lodscale "5"
> seta r_lodCurveError "250"
> seta r_lodbias "2"
> seta r_lightmap "0"
> seta r_intensity "1.50"
seta r_inGameVideo "1"
> seta r_ignorehwgamma "1"
seta r_ignoreGLErrors "1"
> seta r_ignoreFastPath "0"
seta r_highQualityVideo "1" // changed to 1. BTW, this is a candidate for removal along with the dumb preset detection
> seta r_gamma "1.48"
seta r_fullscreen "1"
> seta r_flares "0"
> seta r_finish "0"
> seta r_fastsky "0"
> seta r_facePlaneCull "1"
> seta r_dynamiclight "0"
> seta r_drawworld "1"
> seta r_drawSun "0"
> seta r_drawfoliage "0"
> seta r_drawentities "1"
> seta r_dlightBacks "1"
> seta r_detailtextures "0"
> seta r_customaspect "1"
> seta r_colorMipLevels "0"
> seta r_clear "0"
> seta r_cacheShaders "1"
> seta r_ambientScale "0.5"
> seta m_pitch "0.0131"
> seta m_yaw "0.019"
> seta m_forward "0.25"
> seta m_side "0.19"
> seta m_filter "0"
> seta con_autoclear "1"
> seta com_maxfps "125"
> seta com_introplayed "0"
> seta cl_yawspeed "140"
seta cl_wwwDownload "1"
> seta cl_timenudge "0"
seta cl_run "1"
> seta cl_pitchspeed "0"
> seta cl_packetdup "1"
> seta cl_mouseAccel "0"
> seta cl_maxpackets "100"
seta cl_language "0"
seta cl_freelook "1"
> seta cl_doubletapdelay "350"
> seta cl_anonymous "0"
seta cl_allowDownload "1"
seta cg_wolfparticles "0"
> seta cg_weaponcycledelay "1"
> seta cg_useWeapsForZoom "1"
seta cg_useScreenshotJPEG "1"
> seta cg_teamChatTime "8000"
> seta cg_teamChatsOnly "0"
> seta cg_teamChatHeight "5"
> seta cg_stereoSeparation "0.4"
seta cg_specHelp "1"
> seta cg_showblood "1"
seta cg_shadows "0" // Why 0?
> seta cg_runroll "0"
> seta cg_runpitch "0"
> seta cg_recoilPitch "0"
> seta cg_railTrailTime "400"
> seta cg_quickMessageAlt "1"
> seta cg_printObjectiveInfo "1"
> seta cg_predictItems "1"
> seta cg_popupLimboMenu "0"
> seta cg_noVoiceText "0"
> seta cg_noVoiceChats "0"
> seta cg_noAmmoAutoSwitch "0"
> seta cg_marktime "0"
> seta cg_instanttapout "1"
> seta cg_hudalpha "2"
> seta cg_gun_frame "0"
> seta cg_gibs "1"
seta cg_fov "108" // Others should look this over. 
> seta cg_footsteps "1"
> seta cg_fastSolids "1"
> seta cg_errordecay "100"
> seta cg_drawWeaponIconFlash "0"
> seta cg_drawTeamOverlay "2"
> seta cg_drawStatus "1"
> seta cg_drawSpreadScale "1"
> seta cg_drawSnapshot "0"
seta cg_drawSmallPopupIcons "1"
> seta cg_drawRoundTimer "1"
> seta cg_drawReinforcementTime "1"
> seta cg_drawNotifyText "1"
seta cg_drawGun "1"
seta cg_drawFPS "0" // most players are not interested in this
> seta cg_drawFireteamOverlay "1"
> seta cg_drawCrosshairPickups "1"
> seta cg_drawCrosshairNames "1"
> seta cg_drawCrosshair "5"
> seta cg_drawCompass "1"
> seta cg_drawBuddies "1"
seta cg_draw2D "1"
> seta cg_cycleAllWeaps "1"
> seta cg_cursorHints "1"
> seta cg_crosshairY "0"
> seta cg_crosshairX "0"
> seta cg_crosshairSize "36"
> seta cg_crosshairPulse "0"
> seta cg_crosshairHealth "0"
> seta cg_crosshairColorAlt "red"
> seta cg_crosshairColor "cyan"
> seta cg_crosshairAlphaAlt "1.0"
> seta cg_crosshairAlpha "1.0"
> seta cg_coronas "0"
> seta cg_coronafardist "0"
> seta cg_complaintPopUp "0"
> seta cg_cameraOrbitDelay "50"
> seta cg_brassTime "0"
> seta cg_bobyaw "0"
> seta cg_bobup "0.0"
> seta cg_bobroll "0"
> seta cg_bobpitch "0"
> seta cg_bloodTime "0"
> seta cg_bloodFlash "0"
> seta cg_bloodDamageBlend "0"
> seta cg_blinktime "0"
> seta cg_autoswitch "0"
> seta cg_autoReload "0"
> seta cg_autoactivate "1"
> seta cg_autoAction "0"
> seta cg_atmosphericEffects "0"
> seta cg_consoleShadowed "1"
> seta cg_zoomfov "22.5"
> seta cg_zoomDefaultBinoc "22.5"
> seta cg_zoomDefaultSnooper "40"
> seta cg_zoomDefaultFG "55"
> seta cg_zoomStepBinoc "3"
> seta cg_zoomStepSnooper "5"
> seta cg_zoomStepFG "10"
> seta cg_deferPlayers "1"
seta cg_hitsounds "0" // I know a lot of people use this, but W:ET != Q3, so 0 by default
> seta cg_obituaryLocation "0"
> seta cg_obituaryFilter "0"
> seta cg_drawDisconnectIcon "1"
> seta cg_popupTime "0"
> seta cg_popupFadeTime "2500"
> seta cg_popupWaitTime "5000"
> seta cg_numPopups "10"
seta cg_muzzleFlash "1"
> seta cg_mapZoom "5"

seta cg_recording_statusline "9"
seta cg_tracers "1"
seta cg_drawTime "1"

```

**Comment by rmarquis** [comment]
Closing in favour of #1237.
