### ISSUE TITLE
Implement g_teamDamageRestriction

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#304]
Author: @IR4T4 (IR4T4)
Date: 2013-05-17
Redmine Issue: 304, https://dev.etlegacy.com/issues/304

---

Nice to have - an auto kick for excessive team bleeders ...

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2013-09-05T21:29:27Z

---

Lua can do!

**Comment by rmarquis** [comment]
If nobody implemented this is Lua these past 7 years, I guess there is no need for it. Closing.
