### ISSUE TITLE
Mouserate/FPS dependant turnspread

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#313]
Author: S3ti (S3ti)
Date: 2013-06-09
Redmine Issue: 313, https://dev.etlegacy.com/issues/313

---

If FPS are higher than mouse polling rate, turning spread reduces.
If you get twice the FPS than your mouse polling rate (e.g 250FPS/125Hz) you get 0 added spread by moving your mouse.
Overall turning spread seems to be somewhat FPS dependant.
Maybe it's fixable or made selectable through a server cvar?

http://dev.etlegacy.com/boards/3/topics/513

**Comment by Aciz** [comment]
Fixed in 5d3226a652359af64f04d8e0264cc6d8bf88f8a8
