### ISSUE TITLE
Guid Masterserver

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#36]
Author: Sol (Sol)
Date: 2012-04-25
Redmine Issue: 36, https://dev.etlegacy.com/issues/36

---

None

---

Related commit(s):
99758dc7cc829913c27914e6e42a0f2c7cba371c - Guid Masterserver Support fixes 36

**Comment by thunderpwn** [comment]
80% done says redmine, whats missing?

**Comment by rmarquis** [comment]
This feature has been deprecated in favor of #57 (client side GUID generation). Closing.
