### ISSUE TITLE
Scriptable fx and particle systems

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#366]
Author: @jackeri (Jacker)
Date: 2013-10-14
Redmine Issue: 366, https://dev.etlegacy.com/issues/366

---

At the moment all the particle systems and game fx are hard coded, lets free up that so people can create and modify effects more freely. (In the long run this will also make our lives easier when we want to add some effects to explosions and so on.)

There are many example implementations already so doing the switch will not be as large scale rework as it sounds.

**Comment by rmarquis** [comment]
Done as part of #1450. Closing now.
