### ISSUE TITLE
Create an addtional mod bin pk3 for 'non vanilla' operating systems

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#381]
Author: @IR4T4 (IR4T4)
Date: 2013-10-24
Redmine Issue: 381, https://dev.etlegacy.com/issues/381

---

As the title says ... to let all the other OS (Pandora, AROS etc) users play on servers we require the mod bins. 

These will be put into 'etl_binX_v2.71rc3.pk3' and will be also available to download.

{TODO}
- Pandora
- AROS
- OpenBSD?
- Linux 64b

---

Related issue(s): #157, #372

**Comment by ETLegacyTeam** [comment]
From: @BSzili (BSzili)
Date: 2013-10-26T20:09:59Z

---

In the case of AROS and MorphOS clients this wouldn't do much other than taking up some disk space, since they always reference the PK3s with the Windows DLLs.

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2013-11-18T05:14:20Z

---

etl_bin_v2.71rc3_os1.pk3 has been created and put on our server. It contains the binaries for Pandora/ARM.

**Comment by rmarquis** [comment]
Official support for AROS and MorphOS has been dropped a long time ago. Linux 64 is now a separate arch, and RPi might join the club soon - without the need to have a separate bin pk3. Closing now.
