### ISSUE TITLE
renderer2: Loading screen

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#382]
Author: @jackeri (Jacker)
Date: 2013-10-25
Redmine Issue: 382, https://dev.etlegacy.com/issues/382

---

So idea is simple, when we are first starting up ETL and the game window pops up the window goes gray/black for a while until the intro or UI is loaded and it start drawing elements to the screen. We should draw the legacy icon to the center of the screen so that people know that something is actually happening.

This comes even more important with the renderer2 implementation which takes a while to compile (or load) the shaders and the windows actually stays gray for a long time. In ren2 we will actually need to compile an über simple shader that only does this one thing before anything else (right after opengl context is created and setup is complete).

**Comment by ETLegacyTeam** [comment]
From: @jackeri (Jacker)
Date: 2013-10-25T15:17:14Z

---

Radegast this is not a splash screen (that was already done for windows) but a single texture that is shown in the main window while everything else is being initialized.

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2014-04-29T20:08:18Z

---

This is a must have for renderer2.

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2018-08-14T09:27:50Z

---

Note: creating cubemaps is messing up the loading screen.

**Comment by rmarquis** [comment]
This has been implemented as a static SDL splashscreen in 5fd47f3e5aba47a6e6b9dfd5a3e0b87bdfd3fd23.
