### ISSUE TITLE
Add server /uptime cmd

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#414]
Author: @IR4T4 (IR4T4)
Date: 2013-12-08
Redmine Issue: 414, https://dev.etlegacy.com/issues/414

---

Command should show the uptime of the server

- add the command
- print uptime (and level/map uptime) in server crashlog.txt

There are several known time issues in q3 and in future this command might help us to 'debug' productive servers. At least we've got the info when a crash occures.

---

Related issue(s): #541

---

Related commit(s):
35b16111113ec745f2d46c171642795942360642 - server: uptime cmd refs 414 - initial patch by An..
 6c4c89d24e28b7a031dc5e45fce2fb6ee72d0aed - misc: prevent headers from being included more tha..
 e8e96c13443906d62f55017becd4927438ad33c1 - server: formatted uptime output refs 414 - patch ..

**Comment by ETLegacyTeam** [comment]
From: Anna (Anna)
Date: 2014-06-06T21:19:17Z

---

Here is a trivial patch that just adds the uptime and uptimeReset commands to the server side (not tested)
Since I have not worked with the codebase it may not be a good implemetation

If still needed I will work on printing the level/map uptime too

**Comment by ETLegacyTeam** [comment]
From: Anna (Anna)
Date: 2014-06-07T16:07:43Z

---

Sorry, my git is broken for the moment so I can not generate new patches.
I firstly submit a example of code that prints the days, hours, minutes and seconds of the uptime.
Secondly I think to make it work with the map uptime we just need to add a static time_t mapUptimeSince, a void SV_MapUptimeReset(void){mapUptimeSince = time(NULL);} and call SV_MapUptimeReset from SV_InitGameProgs and SV_RestartGameProgs.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2015-12-30T20:39:21Z

---

What is missing to mark this feature as 'done'? Is map uptime really necessary?

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2015-12-31T09:08:57Z

---

Spyhawk wrote:

> What is missing to mark this feature as 'done'? ... 
crashlog doesn't print the uptime

> ... Is map uptime really necessary?
Do you know a way to find out the map uptime via rcon? I think that was the reason to add it.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2015-12-31T10:25:04Z

---

IR4T4 wrote:
> crashlog doesn’t print the uptime
Ok, thank. We'll find a way to add this.

> > ... Is map uptime really necessary?
> Do you know a way to find out the map uptime via rcon? I think that was the reason to add it.

I don't know what "map uptime" means here. The time the map has been currently played? Maps are on rotation, so the uptime would be reset at each game. In what way having the map uptime
would help?

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2016-01-12T16:39:50Z

---

I'm talking about rest of time for the current map.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2016-01-12T19:40:54Z

---

IR4T4 wrote:
> I'm talking about rest of time for the current map.

This still doesn't make sense to me... How rest of current map time is useful in any way? By definition, real map length is variable. I might totally be missing something here, but I don't get what map time/rest of map time brings in crashlog  information.

**Comment by rmarquis** [comment]
This has been implemented. 6. Years. Ago. Closing now.
