### ISSUE TITLE
When next map starts console would start from the bottom again

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#437]
Author: @saukko28 (Saukko)
Date: 2013-12-26
Redmine Issue: 437, https://dev.etlegacy.com/issues/437

---

So there is this when you have scrolled up in your console a bit and the next map starts, your console is all the way up and it doesn't show anything. You have to scroll down all the ay or press End to get back to the bottom. So make this work, when next map loads and you open console it would be straight in the bottom instead of all the way up.

-*S

**Comment by ryzyk-krzysiek** [comment]
This only works on local server. I think the solution would be to put `Con_ScrollBottom` here instead.

https://github.com/etlegacy/etlegacy/blob/d99da7d64a4d2e589184c5afe785cdb666809feb/src/client/cl_cgame.c#L565-L581
