### ISSUE TITLE
Implement all the death animations

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#457]
Author: @jackeri (Jacker)
Date: 2013-12-31
Redmine Issue: 457, https://dev.etlegacy.com/issues/457

---

Currently we only use the one death animation, but in reality there are multiple available which should be used based on the kill shot and from which direction it came from.

Also for the future this should be more generic as we might want to add these animations our selves.

---

Related commit(s):
9a127a5480de8ca6a491afbe95b348da7ba27377 - mod: script animation movement type 'dead' added, ..
 6427d4a59a7cbbcbe4187b3a517e3020736686c6 - game: additional anim conditions for the death ani..
 effa93dece345774a966df2726ae9c5758832a8e - mod: implement unused death animation, refs 457..

**Comment by rmarquis** [comment]
All death animations, at least from pak0.pk3, have been implemented.
