### ISSUE TITLE
Nightly builds

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#46]
Author: @JanSimek (Radegast)
Date: 2012-05-08
Redmine Issue: 46, https://dev.etlegacy.com/issues/46

---

### Set up buildbot for nightly builds

The objective is to make testing easier and have realtime build reports on our irc channel. This process should be completely automated and new builds added to the files section through "Redmine REST api":http://www.redmine.org/projects/redmine/wiki/Rest_api if possible or a dedicated wiki page and or http://mirror.etlegacy.com

Build bot: http://trac.buildbot.net

### Automatically replace test server with nightly builds

Test server running at etlegacy.com should be replaced every day at 2:00 CET or alternatively by manually executing a script for immediate replacement.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2014-11-30T19:18:53Z

---

Just FYI:

user:skybon hosts a git server at etl.vorotnikov.me:27960.
It features daily reset and updates directly from ET:L git repo. Linux and Win32 binaries provided!

No MacOS binaries for now. It's not trivial, most cross compiling solution are outdated or/and for masochist people. The best possible solution seems to be  https://github.com/tpoechtrager/osxcross.

**Comment by ETLegacyTeam** [comment]
From: neoyukito (neoyukito)
Date: 2015-12-24T15:43:11Z

---

Add information from #908

Description

This is a recommended to increase branch review of the current task.

The idea is using a script that automatically generate a test version on the main branch, every day or every week. This way you can go proactively testing the new features, corrected defects, involuntary defects (eg, to correct a defect, you can generate another defect).

This version of etlegacy may be a debug version, it could be supplemented by generating a memory dump and condump automatically upon entering the game or mod. This will complement the defect could attached the folder ".. \etlegacy\debug\Log_18DEC2015_001\files..".

Regards.

**Comment by rmarquis** [comment]
We have been having an "on-demand" autobuild setup for a while now, thanks to @zedar187. This isn't done for each commit, but that isn't required either, as all builds aren't all stable.

Closing now.
