### ISSUE TITLE
Upgrade GeoIP country database to GeoLite2

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#477]
Author: @JanSimek (Radegast)
Date: 2014-01-06
Redmine Issue: 477, https://dev.etlegacy.com/issues/477

---

More information: http://dev.maxmind.com/geoip/geoip2/geolite2

Suggested by user:Dragonji.

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2014-01-06T14:43:27Z

---

It's not the time to do now. Currently I don't see any advantages if we switch from 'GEOIP Legacy' to 'GEOIP2' ... it's more the opposite see http://dev.maxmind.com/geoip/geoip2/whats-new-in-geoip2/

 "Downloadable databases for GeoIP2 are not yet available." 

- We would have IP data requests at runtime which would burdens a game server additionally. 

Our current solution does it's job - so why we should switch? Is there any missing feature?

**Comment by ETLegacyTeam** [comment]
From: @JanSimek (Radegast)
Date: 2014-01-06T16:47:19Z

---

That's outdated news. GeoIPLite2 downloadable database has been made available since then and it has a stable API. You can find it at the link in the ticket.

We could use the city db to announce which part of the country a user has connected from. It would be particularly useful on servers where one nation has the majority of players. It's also actively updated while the old version receives updates from time to time, but it won't do indefinitely.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-01-01T15:56:46Z

---

GeoIP Legacy update has stopped being updated in March 2018, and will be removed from Maxmind website on January 2, 2019 (tomorrow).

> Updated versions of the GeoLite Legacy databases are now only available to redistribution license customers, although anyone can continue to download the March 2018 GeoLite Legacy builds. Starting January 2, 2019, the last build will be removed from our website. GeoLite Legacy database users will need to switch to the GeoLite2 or commercial GeoIP databases and update their integrations by January 2, 2019.

This is the version we're currently using. We have a copy of it on our own server, but we need to upgrade to GeoLite2 as data will increasingle become inaccurate with time.
The API code is quite different, as the format of GeoLite2 is radically different from GeoIP Legacy.

Resource:
* https://github.com/maxmind/libmaxminddb
* https://github.com/maxmind/geoipupdate
* https://github.com/maxmind/geoipupdate-legacy

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-12-29T14:12:52Z

---

Looks like using GeoIP2 freely isn't possible anymore, due to the upcoming California Consumer Privacy Act. See related blogpost: https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

It was fine to use under GDPR, but CCPA seems to make it legally ambiguous, and free access under a  Creative Common license is replaced by a required (free) account.

> The California Consumer Privacy Act (CCPA) mandates that businesses honor valid “Do Not Sell” requests from California residents. In this context, complying with a valid request involves MaxMind removing IP addresses from the GeoLite2 data and communicating to GeoLite2 users that the IP addresses in question should (immediately) not be utilized for uses covered under the CCPA. We have been advised that any download, including one without charge, constitutes a sale. Serving GeoLite2 database downloads on a public page simply does not allow us to communicate and honor valid “Do Not Sell” requests we receive from individuals.

> The solution we have chosen is to introduce a new end-user license agreement containing the relevant data processing provisions that both we, as the business providing data, and you, as the third party user of the data, need to comply with applicable data privacy regulations. Additionally, by requiring a MaxMind account and contact information from you, we will be able to communicate all valid “Do Not Sell” requests to you as we receive them.

> With this approach, we can continue to offer GeoLite2 databases, without charge, while remaining responsible stewards of data that improves the experience of countless users across the internet.

Do we really want the legal hassle here?

> Starting December 30, 2019, we will be requiring users of our GeoLite2 databases to register for a MaxMind account and obtain a license key in order to download GeoLite2 databases. We will continue to offer the GeoLite2 databases without charge, and with the ability to redistribute with proper attribution and in compliance with privacy regulations. In addition, we are introducing a new end-user license agreement to govern your use of the GeoLite2 databases. Previously, GeoLite2 databases were accessible for download to the public on our developer website and were licensed under the Creative Commons Attribution-ShareAlike 4.0 International License.

> Starting December 30, 2019, downloads will no longer be served from our public GeoLite2 page, from geolite.maxmind.com/download/geoip/database/*, or from any other public URL.

**Comment by ETLegacyTeam** [comment]
From: @jackeri (Jacker)
Date: 2019-12-29T14:49:42Z

---

Spyhawk wrote:
> Do we really want the legal hassle here?

We could possibly move the checkup to the master server's end. Servers would need to query the country information for the clients. The master server already has an geoip implementation that is used internally to check the server locations, but it could be easily made accessible with the udp protocol too.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-12-29T19:06:03Z

---

That would bypass the issue of being able to distribute the GeoIP data, but I'm afraid that won't cover us legally speaking since we'd still be in violation of CCPA, as I understand it.

I really don't see us turning off the option by default (almost nobody would opt in), and add some legal disclaimer when using the feature, nor we would be able to remove/filter out the data in case someone ask not to have their IP/country identified (legally speaking).

At this point, I'd very much would suggest to scrap the feature entirely.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-12-31T16:30:09Z

---

Note: beside the legal issue mentioned above, [this](https://github.com/sherpya/geolite2legacy can be used to convert GeoLite2 database to GeoLite1 Legacy format - so we could update the current data from March 2018 to December 2019. Pre-converted database can be found [here](https://mailfud.org/geoip-legacy/).

**Comment by rmarquis** [comment]
I am closing this issue. Moving to GeoLite2 isn't worth it. Without even getting into the legal aspects, the existence of a Legacy format conversion script makes it unneeded to ever implement GeoLite2 format.
