### ISSUE TITLE
Fix dead player hitbox direction and bb height

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#503]
Author: @IR4T4 (IR4T4)
Date: 2014-02-01
Redmine Issue: 503, https://dev.etlegacy.com/issues/503

---

Current hitbox:
http://bani.anime.net/etpro/corpsebb-old.jpg

Better:
http://bani.anime.net/etpro/corpsebb-rtcw.jpg

{FIXME}
The bb height is also wrong. 
Reproduce: throw a nade on dead player.

---

Related commit(s):
a711af4b4e488af467212dd660c2e96e7c5ce1ca - game: hitbox adjustments for proning & dead player..

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2014-12-21T22:32:22Z

---

Hitbox drection is adjusted (in 2.71). Nades still fly over hitboxes.

**Comment by ryzyk-krzysiek** [comment]
I encountered 2 issues with lower (0 height) BBox that I was unable to reproduce on etpro or height 12, there was another place where I got gibbed because of it but Im unable to reproduce it there so it might have been something else I guess.

https://streamable.com/qeiwn8
https://streamable.com/xoz4ep

**Comment by ryzyk-krzysiek** [comment]
Another 2 examples:

Mentioned above issue: https://streamable.com/9z8wyx
Getting stuck after revive: https://streamable.com/m9wmnq
[2021-10-31-204020-sw_goldrush_te stuck bug.zip](https://github.com/etlegacy/etlegacy/files/7452876/2021-10-31-204020-sw_goldrush_te.stuck.bug.zip)

**Comment by Helldembez** [comment]
https://streamable.com/pwhvh9

**Comment by Aciz** [comment]
This is as good as it gets now without breaking collision, closing.
