### ISSUE TITLE
Cointoss

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#505]
Author: @rmarquis (Spyhawk)
Date: 2014-02-12
Redmine Issue: 505, https://dev.etlegacy.com/issues/505

---

Missing little feature, mostly useful for competition: cointoss (virtual coin flipping).

Also add a button in the Referee menu.

---

Related commit(s):
2ac15e3247d876ce5f188b5d013c0bdd6d1bdbc1 - ladm: added cointoss and pm inbuilt commands

**Comment by ETLegacyTeam** [comment]
From: @JanSimek (Radegast)
Date: 2014-02-12T17:08:15Z

---

Could you describe this feature a bit more? What is it for?

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2014-02-12T17:47:10Z

---

It's really a simple referee command, that returns "Heads" or "Tails" to everybody.

It's useful to make small decision such as "Which team starts on the Axis side on the first SW round?".

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2014-02-12T17:58:26Z

---

Command makes sense :)

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2014-02-12T18:09:53Z

---

Now that I think about it, wouldn't it be better implemented in Lua in the core admin package (noq and/or ladm)?

**Comment by ETLegacyTeam** [comment]
From: @JanSimek (Radegast)
Date: 2014-02-12T18:14:12Z

---

I see. Definitely belongs to lua.

**Comment by ETLegacyTeam** [comment]
From: @JanSimek (Radegast)
Date: 2014-02-13T00:38:37Z

---

Added in commit commit:2ac15e3247d876ce5f188b5d013c0bdd6d1bdbc1

**Comment by rmarquis** [comment]
Reopening. Having cointoss in the base mod is actually important, as a full Lua suite shouldn't be needed to play comp.
