### ISSUE TITLE
Shooting dead body makes sparks

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#518]
Author: @saukko28 (Saukko)
Date: 2014-02-22
Redmine Issue: 518, https://dev.etlegacy.com/issues/518

---

Ok there are two things to mention here. When you shoot a dead body it makes sparks. When you shoot sand normally it doesn't make any sparks when you hit it with bullets. So when you keep shooting on the sand where the dead body was for a while, it still makes sparks. But after a while it doesn't make anymore sparks.

-*S

**Comment by ETLegacyTeam** [comment]
From: @saukko28 (Saukko)
Date: 2014-11-15T04:47:39Z

---

For now I haven't been able to reproduce this. But I will keep my ete on this still for a while. I will put it fixed myself after a while.

-*S

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2014-11-15T12:23:40Z

---

I can imagine this issue was caused by the decal changes we did. Let's close this now.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2014-12-11T15:34:08Z

---

Reopened. The bug still exists, according to Saukko.

**Comment by ETLegacyTeam** [comment]
From: @saukko28 (Saukko)
Date: 2014-12-11T18:51:02Z

---

The bug is still alive. See the demo I attached.

-*S

**Comment by Vorschreibung** [comment]
Redmine ticket gone, no demo attached anymore, can't reproduce by what I tried.
Suggest to close again, can be reopened once reproducible.
