### ISSUE TITLE
"FIGHT!" sound doesn't necessarily play when you spectate somebody

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#522]
Author: @saukko28 (Saukko)
Date: 2014-02-22
Redmine Issue: 522, https://dev.etlegacy.com/issues/522

---

There is this little addition to the specification to the actual bug.
When you start a map, you will have a starting location as a spectator. When you spectate somebody during the warmup and then the map starts and the player you spectated is far away from the spectators' starting location, the "FIGHT!" sound can't be heard. It all depends how far the spectated player is away from the spectators' starting location. The sound will gain more volume the closer it gets to the starting location.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2015-01-21T14:27:02Z

---

I cannot reproduce. Does this bug still exist?

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2015-01-21T14:59:32Z

---

Yes. I think the sound is played but origin of sound is outdated.

**Comment by ETLegacyTeam** [comment]
From: @saukko28 (Saukko)
Date: 2015-01-21T16:05:29Z

---

It does exist. Just try it out on Oasis. Spectate an Allied player during the warmup and you can't even here "FIGHT!".

-*S

**Comment by ETLegacyTeam** [comment]
From: @thunderpwn (thunder)
Date: 2017-06-10T17:31:04Z

---

this isnt much a bug I'd say

```<code class="c">// Announce game in progress if we are really playing
	if (old_gs != GS_PLAYING && cgs.gamestate == GS_PLAYING)
	{
		trap_S_StartLocalSound(cgs.media.countFight, CHAN_ANNOUNCER);

		Pri("^1FIGHT!\n");
		CPri(CG_TranslateString("^1FIGHT!\n"));
	}</code>
```

*Announce game in progress if we are really playing*
prob says it all

**Comment by Vorschreibung** [comment]
Can confirm, surely seems like a bug.

"Fight" voice line is written&voiced as spectator without spectating any particular player.

Once actually spectating a particular player, the "Prepare to fight" line is still written&voiced, yet the "Fight" line is only written, not voiced.

Code referenced in the previous comment is outdated.
