### ISSUE TITLE
MAX_GAMESTATE_CHARS exceeded

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#588]
Author: @rafal1137 (RaFaL)
Date: 2014-09-19
Redmine Issue: 588, https://dev.etlegacy.com/issues/588

---

It happens whenever I do devmap I assume listen server would do the same 
Setting maxbots to 18 on 20 slots

---

Related issue(s): #538

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2014-09-20T01:39:56Z

---

How many maps/pk3 files are in path? Which map causes this?

**Comment by ETLegacyTeam** [comment]
From: @rafal1137 (RaFaL)
Date: 2014-09-20T16:21:30Z

---

Given link from you http://dev.etlegacy.com/projects/etlegacy/wiki/Mapping_and_Textures#Configstrings-or-the-configstring
I read about this and its my fault I have over 150 maps in my etmain
so could you close this issue ?

**Comment by aviogit** [comment]
My server is plagued by this problem. In my opinion `MAX_GAMESTATE_CHARS` should be made configurable via server config and clients should dynamically allocate the memory of `cl.gameState.stringData` according to the value of `MAX_GAMESTATE_CHARS` communicated by the server. This is the only way to have servers with hundreds of maps that work reliably even with several dozen bots.

**Comment by ensiform** [comment]
It must be static and if you change it you won't be compatible with any other client.

And I'm not sure you could reliably have it as a configuration like that. This buffer contains the cvar strings of systeminfo (replicated cvars) and serverinfo (broadcast cvars for server browser), so either place you'd be storing it to send to clients, the size would already need to be known ahead of time.

The only way to have hundreds of maps is to turn off pure mode or enhance it to only register pk3s with maps in use but somehow still allow all of them to be referenced for vote lists.

**Comment by aviogit** [comment]
Ok, let's say that making it configurable is unnecessarily complicated. Why not set it to 48000 or 64000 from the next version of ETL and put an end to all this pain?

Older clients < 2.78 would no longer be compatible, but would that be so bad?

The other two options you propose are interesting but are just a workaround IMHO. The second one looks ok but it maybe even more complicated than the kind of one-shot negotiation I was talking about.

**Comment by ensiform** [comment]
Vanilla clients (ET.exe), ETe clients and other third party non etlegacy.exe would not be able to join these servers. Talking about application executable not the mod (cgame). Not ideal.

Changing the network protocol version is effectively required. Old demos no longer work even.

20,000 maps is already plausible in ETe as long as you aren't running pure. The menus probably wouldn't work as expected but you'll hit those limits anyway.

Also, making it configurable isn't just unnecessarily complicated, it is not feasible within the constraints of the way any string data information is sent to clients from the server. It's the chicken and egg problem.

**Comment by aviogit** [comment]
I see... maybe a pull request could be discussed with ETe devs to discuss the problem and move to larger `MAX_GAMESTATE_CHARS` values in a similar time frame? This consideration is based on the assumption that `ET.exe` users are close to zero at the moment, but I may be wrong.

**Comment by ensiform** [comment]
Pure servers are nearly pointless in this day and age though. You can also shrink your gamestate chars by avoiding extra cvars in your serverinfo which advertise mod or clan url etc.

Also, I am the ETe dev :P and have no intention to increase because my goals are more vanilla compatibility, not less.

I could be wrong about some of this but that's just from my recent memory looking over the gamestate code.
