### ISSUE TITLE
Test all Lua scripts with Lua 5.3 before next release

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#609]
Author: @IR4T4 (IR4T4)
Date: 2014-11-05
Redmine Issue: 609, https://dev.etlegacy.com/issues/609

---

I've noticed some scripts in our repository don't work properly with Lua 5.2 (see dynamite.lua f.e.) when tables are used.

---

Related commit(s):
7baf2e4d877998a30248e60955d9f13c0dcc58d9 - dynatimer: quick and dirty fix for lua 5.2.3, refs..
 3dcf3eb8a138bb373c8a7e8e116fb7136ec4c1d7 - fixed attempt to index a number value error

**Comment by ETLegacyTeam** [comment]
From: @rafal1137 (RaFaL)
Date: 2014-11-08T13:45:00Z

---

Legacyconst.lua loads corectly 

Dynamite.lua 
Lua API: et_InitGame error running lua script: [string "dyna.lua"]:100: bad argument #2 to 'insert' (position out of bounds)
Lua API: et_RunFrame error running lua script: [string "dyna.lua"]:139: attempt to call field 'foreach' (a nil value)

Xpsave.lua closing server without an error

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2014-11-08T14:10:22Z

---

See also changes done in issue #289.

**Comment by ETLegacyTeam** [comment]
From: @JanSimek (Radegast)
Date: 2014-11-08T15:47:37Z

---

RaFaL wrote:
> Dynamite.lua 
> Lua API: et_InitGame error running lua script: [string "dyna.lua"]:100: bad argument #2 to 'insert' (position out of bounds)
> Lua API: et_RunFrame error running lua script: [string "dyna.lua"]:139: attempt to call field 'foreach' (a nil value)
table.insert(client_msg, i, false)  - i starts at 0 which is out of bounds since lua 5.2.2. We just have to adapt the code to count sv_maxclients at 1. Easy fix.

> Xpsave.lua closing server without an error
Strange. You most likely don't have sqlite module installed.

**Comment by ETLegacyTeam** [comment]
From: @rafal1137 (RaFaL)
Date: 2014-11-08T19:18:39Z

---

I got sqlite module installed just downloaded a new one and this 

Lua API: G_LuaStartVM error running lua script: error loading module 'luasql.sqlite3' from file 'E:\etlegacy\legacy\lualibs\luasql\sqlite3.dll':
	Nie można odnaleźć określonej procedury.

**Comment by ETLegacyTeam** [comment]
From: @JanSimek (Radegast)
Date: 2014-12-05T21:36:40Z

---

dynatimer now works with the bundled lua

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2016-09-03T16:59:39Z

---

xpsave.lua gives this error at server shotdown:

    Lua API: et_ShutdownGame error running lua script: [string "xpsave.lua"]:159: attempt to index a number value (upvalue 'cur')

and

    Lua API: et_ShutdownGame error running lua script: [string "xpsave.lua"]:160: LuaSQL: there are open cursors

**Comment by rmarquis** [comment]
The relevant scripts are either obsoletes or now working with Lua 5.3. Closing.
