### ISSUE TITLE
Fix OpenGL ES renderer

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#612]
Author: @JanSimek (Radegast)
Date: 2014-11-08
Redmine Issue: 612, https://dev.etlegacy.com/issues/612

---

Compilation of OpenGL ES renderer is broken and it needs to be ported either to SDL 2 or native functions.

---

Related issue(s): #336

---

Related commit(s):
6f9cfb6a218c53ee435ff55b6827f778afe4af0c - renderer: ported OpenGL ES renderer to SDL 2, ref..

**Comment by ETLegacyTeam** [comment]
From: @JanSimek (Radegast)
Date: 2014-11-09T10:18:55Z

---

OpenGL ES renderer now compiles and links again, however it, uhm, won't render properly ingame. See attached screenshot.

**Comment by rmarquis** [comment]
Done as part of #885.
