### ISSUE TITLE
Landmine and dynamite hitbox

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#630]
Author: @saukko28 (Saukko)
Date: 2014-11-17
Redmine Issue: 630, https://dev.etlegacy.com/issues/630

---

These two bad boys are humongous. See the screenshots, those basically tell what's going on.

-*S

**Comment by ETLegacyTeam** [comment]
From: @Aranud (Aranud)
Date: 2018-05-10T23:16:27Z

---

The correct value to get homogeneous hit boxes are the following (change should be done in fire_grenade function):
Landmine :
{ -4, -4, 0 }
{ 4, 4, 10}

Dynamite :
{ -10, -10, 0 }
{ 10, 10, 11 }

Satchel :
{ -11, -11, 0 }
{ -11, -11, 8 }

But there is a little think we have to keep in mind. By changing the hitboxes, we have to be more precise when arming/disarming them.
So, it mean, the gameplay change a little bit.

Do we really want this ? (The feelling don't seem too different)

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2018-05-11T09:57:27Z

---

Now you can't move a lot while planting/defusing. This is a big difference in game play (in my eyes) since the engineer can't do defending moves as we know it. 
I think radius damage is affected too. Landmines are triggered on smaller distance?

**Comment by ETLegacyTeam** [comment]
From: @Aranud (Aranud)
Date: 2018-05-13T22:12:31Z

---

IR4T4 wrote:

bq. I think radius damage is affected too. Landmines are triggered on smaller distance?

Nah, radius damage and trigger distance still the same, it depend of the current origin, which don't change (from g_missile.c): 

```<code class="c">G_RadiusDamage(origin, ent, ent->parent, ent->splashDamage, ent->splashRadius, ent, ent->splashMethodOfDeath)</code>
```

```<code class="c">		 vec3_t dist;

		VectorSubtract(mine->r.currentOrigin, ent->r.currentOrigin, dist);
		// have to be within the trigger distance AND on the ground -- if we jump over a mine, we don't set it off
		//      (or if we fly by after setting one off)
		if ((VectorLengthSquared(dist) <= Square(LANDMINE_TRIGGER_DIST)) && (Q_fabs(dist[2]) < 45))
		{
			return qtrue;
		}</code>
```

**Comment by rmarquis** [comment]
For dynamite arming/disarming, we can use a bigger specific hitbox that works only with pliers. See #1174: the syringe uses a bigger hitbox than any other weapons to make it easier to revive.

**Comment by ryzyk-krzysiek** [comment]
https://github.com/etlegacy/etlegacy/commit/da2ee309c9664820cfd9dbd52734fe6af00fd9b3
