### ISSUE TITLE
Explosion splash radius is sometimes bugged

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#631]
Author: @saukko28 (Saukko)
Date: 2014-11-19
Redmine Issue: 631, https://dev.etlegacy.com/issues/631

---

It's hard to explain what's going on in this one but here are something what I tried out. The demo I took shows pretty much what's happening.
There are two enemies hugging each other. Put a satchel/grenade on top of one of them. Only the other dies and the other one doesn't take any damage. Sometimes both die but don't know precisely when. But when you throw a grenade or a satchel charge on the ground, for example behind the other guy while the other enemy is behind the other one, then they both will die no matter what.

But watch the demo, it shows the problem.

-*S

**Comment by rmarquis** [comment]
Handled as part of #1470. Closing.
