### ISSUE TITLE
An item set on top of another won't go lower when the one below it disappears

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#651]
Author: @saukko28 (Saukko)
Date: 2014-11-20
Redmine Issue: 651, https://dev.etlegacy.com/issues/651

---

The next demo which I will show you is a very good example how this bug occurs. There are several other cases like this. Maybe one of the best is when you put a satchel charge on top of a corpse, the corpse disappears and the satchel charge keeps floating.

-*S

---

Related issue(s): #406

**Comment by ETLegacyTeam** [comment]
From: Mateos (Mateos)
Date: 2014-11-21T15:31:02Z

---

Only NQ does this atm afaik?

**Comment by ETLegacyTeam** [comment]
From: @saukko28 (Saukko)
Date: 2014-11-21T15:34:37Z

---

No, this was tested in etl mod.

-*S

**Comment by ETLegacyTeam** [comment]
From: Mateos (Mateos)
Date: 2014-11-21T16:05:01Z

---

I meant this behavior is only in NQ afaik, the fact the game checks for dynamic items locations, to not be floating like in Minecraft :P

**Comment by Aciz** [comment]
Fixed in 7de013e1d120fe8f55af1202dc5c0f2674edc82f
