### ISSUE TITLE
Add on option to disable adrenaline

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#686]
Author: @IR4T4 (IR4T4)
Date: 2014-11-30
Redmine Issue: 686, https://dev.etlegacy.com/issues/686

---

Add on option to disable adrenaline on a server.
Revive without teamkill  see #586 should replace 'Adrenaline Self' skill in that case.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-01-20T19:54:13Z

---

This is already possible by setting _skill_medic "20 50 90 -1"_. In fact, any skill level can be disabled, but this is badly documented.

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2019-01-21T09:00:00Z

---

{FIXME}

- replace adrenaline skill with "Revive without teamkill" skill/ability when g_misc 2 bitflag  is set and adrenaline is disabled

**Comment by rmarquis** [comment]
This has been superseded by #1238. Closing.
