### ISSUE TITLE
Fix referee window and function issues

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#701]
Author: @saukko28 (Saukko)
Date: 2014-12-09
Redmine Issue: 701, https://dev.etlegacy.com/issues/701

---

Alright I took a look into the referee stuff; all the function. Messages are unclear or even wrong. And then the player list in the referee window shows white names in grey.
Muting spectators doesn't work as a function. So it would be great to take a look into these as a whole.

-*S

---

Related issue(s): #732

---

Related commit(s):
8dad8dd66d5b545c92097dcdbe8e8833f2766a8f - ui: fixed ingame public/comp settings ref button, ..

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2015-01-07T17:15:47Z

---

Saukko> Please make a list of all "broken" stuff, so we can double check we won't forget anything.
Also, I think the grey name list cannot be fixed (at least not easily).

**Comment by ETLegacyTeam** [comment]
From: @saukko28 (Saukko)
Date: 2015-01-07T20:23:12Z

---

{TODO}
1. Referee menu

MISC:
* Fix team (un)locking
- Teams don't get (un)locked at all when under 3 players
- Disable team switching while teams are locked
- Fix messages sent to referee and other clients (choose where the message is sent [echo/cpm/console?] for each)
+ Add possibility (un)lock only one team
* Fix spectators (un)locking
- Fix the problem when spectator lock disappears (but is still active) when the only client alive changes team
- Fix the problem while spectator lock being active and other team has no players and someone joins in it. The one in spectator can spectate the player who joined to the opposite team leaving that team to be able to be spectated
- Fix the messages sent to referee and other clients 
* Fix timelimit setting
- Disable the possibility to set the same timilimit more than once in a row
- Fix the number shown when setting a new timelimit (it will show the timelimit set with many decimals)
- Fix messages sent to referee and other clients
- Disable timelimit setting during the warmup
- Add possibility to set unlimited time instead of changing the timelimit to 100000 to make it unlimited
* Fix spectator muting, currently not functioning at all (because of localhost?)
* Fix 'Next map' function
- Fix the problem when using this function, it will start the map all over again if playing only one map
- Fix the problem that the warmup ends when using this function
* Fix the message "Competition Settings Loaded!"
- This message doesn't come when it is first time loaded but on the second time if you load it or even the public settings, the message will appear
* Fix 'Swap teams' and 'XP shuffle restarting the match when it is still going
* Add messages for 'Swap teams', 'XP shuffle', 'Reset match' and 'Restart map' to both referee and other clients

PLAYERS:
* Fix kicking
- Fix the problem when you kick someone who has the same name as the referee
- Fix messages sent to referee and other clients
* Fix (un)muting
- Fix the problem when you can't (un)mute someone who's having the same name as referee
- Fix messages sent to referee and other clients
* Fix 'Make referee'
- Fix the problem when you can't make someone referee who has the same name as referee
- Fix the problem when you are not getting unmuted when a referee grants you referee access
- Fix messages sent to referee and other clients
* Fix 'Make Axis/Allies'
- Fix the problem when trying to put someone with same name will put you into a team instead
- Add message to inform client(s) that they have been put into a team
* Fix 'Make Spectator'
- Fix the problem which restricts referee to put someone to spectators with the same name as referee
- Fix messages sent to referee and other client(s)
* Fix warning
- Fix the problem which restricts the referee to warn player with the same name
- Fix the message sent to referee when trying to warn ownself
- Fix the messages sent to referee and other clients

To be continued....

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2017-04-12T15:12:36Z

---

{FIXME}
- make menu & referee commands to use slots instead of player names

**Comment by rmarquis** [comment]
Handled as part of #1276.
