### ISSUE TITLE
In-game mouse cursor shows when opening certain popup menus

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#724]
Author: @saukko28 (Saukko)
Date: 2014-12-14
Redmine Issue: 724, https://dev.etlegacy.com/issues/724

---

See the screenshot attached, you see a tiny bit of the cursor. When you check by pressing ESC, the cursor starts from the very same place.

-*S

**Comment by ETLegacyTeam** [comment]
From: @saukko28 (Saukko)
Date: 2019-06-27T09:48:47Z

---

Alright I gathered more info on this one. The only popup menu that actually works as intended is fireteam voicecommand menu. I haven't found yet what could make it different from the others.

-*S

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-06-27T10:05:42Z

---

> I haven’t found yet what could make it different from the others.

The fireteam command menu is hardcoded (in cgame), while the other menus use the script system (.menu files).

**Comment by ETLegacyTeam** [comment]
From: @saukko28 (Saukko)
Date: 2019-06-27T10:19:51Z

---

Actually now I came to notice that there is this event handler in cg_newDraw. So yeah, you are absolutely correct. So at this point the only question is that to which direction this case should be heading? Should eveyrhting be hardcoded or rather not?

-*S

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-06-27T10:36:49Z

---

Hardcoding provides greater flexibility (which the fireteam menu make use of), but doing so is indeed lot of work. Using menu file is much simpler and faster, but we can't exactly do everything we want. Is it worth hardcoding all the menu to fix that little cursor issue? Absolutely not.

**Comment by ETLegacyTeam** [comment]
From: @saukko28 (Saukko)
Date: 2019-06-27T11:36:41Z

---

That is a valid point. This is such a minor issue so it might not be worth it. But still in the end of the day, a fixable bug is always fixable. ;)

But we can let this be as it is... for now.

-*S

**Comment by Vorschreibung** [comment]
Redmine ticket is gone, what popup menus are affected here? - Can't make sense of this issue / reproduce.
