### ISSUE TITLE
Update update-installer cmake script for cross-compilation

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#727]
Author: @rmarquis (Spyhawk)
Date: 2014-12-15
Redmine Issue: 727, https://dev.etlegacy.com/issues/727

---

We should think of building the update-installer as part of the main code, with a submodule link to the "Update-Installer":https://github.com/etlegacy/Update-Installer repo and a new optional BUILD_UPDATEINSTALLER cmake flag.

I had to install an entire 32 bits chroot to build the updater for Linux 32, which is quite inconvenient to say the least (dirty, but quick).

Alternatively, improve the Mendeley CMake scripts for 32 bits cross compilation and send the improvement upstream (probably preferable solution).

**Comment by ETLegacyTeam** [comment]
From: @jackeri (Jacker)
Date: 2014-12-15T18:08:03Z

---

I think we should keep it as a separate thing, it should only be built when we need it updated and its a completely separate project anyway.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2014-12-15T18:19:23Z

---

You are right. I actually edited the description after creating the ticket: making the included CMake script work for cross-compilation (and pushing it upstream if possible) would probably be a better idea.

**Comment by rmarquis** [comment]
Closing. We don't actually use the update installer, and the Linux only issue described above should be taken care by distro packagers.
