### ISSUE TITLE
Explosives and bullets can move your teammate

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#736]
Author: @saukko28 (Saukko)
Date: 2014-12-18
Redmine Issue: 736, https://dev.etlegacy.com/issues/736

---

Alright. Title and then this attached demo will also show the current problem. Probably add a CVAR for it?
Tried also g_shove "0" without succession.

-*S

---

Related commit(s):
5885eadf61d72ed7cafc853b84f4c0aabf5eb18b - added a misc flag to disable knockback on team mem..
 95e1b47a78382c4d9216bfbbf663be3090ba0a79 - Revert "added a misc flag to disable knockback on ..

**Comment by ETLegacyTeam** [comment]
From: @jackeri (Jacker)
Date: 2014-12-18T10:31:21Z

---

Added this now, but please no more "public only" modifications like this. These things really hurt the credibility of the mod for the clan scene.

**Comment by ETLegacyTeam** [comment]
From: @saukko28 (Saukko)
Date: 2014-12-18T10:38:45Z

---

Works.

-*S

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2014-12-19T00:42:24Z

---

Following our discussion on IRC, I'm reverting this commit.
I'm not against improving no-FF features, but using a cvar just for that is a bit... too much? Maybe we should implement it by default or improve g_shove instead, or done in Lua(?).

Anyway, reverted for now and delayed to the next version. This is also a feature request.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2014-12-19T01:05:36Z

---

Applied in changeset commit:95e1b47a78382c4d9216bfbbf663be3090ba0a79.

**Comment by ETLegacyTeam** [comment]
From: @adanski (Dragonji)
Date: 2014-12-19T13:13:20Z

---

Spyhawk wrote:
> I'm not against improving no-FF features, but using a cvar just for that is a bit... too much? Maybe we should implement it by default or improve g_shove instead, or done in Lua(?)
This should be cvar controlled IMO.

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2014-12-19T14:25:12Z

---

Of course explosives and bullets can move your teammate. I don't see a problem here. Or is this about friendly fire off?

**Comment by ETLegacyTeam** [comment]
From: @saukko28 (Saukko)
Date: 2014-12-19T18:03:16Z

---

Yeah FF off. When I made this ticket, I had my FF off and I could fly all over the place when nades under my feet. Could be easily abused. That's why I thought about adding a possible CVAR for it to control it. But seems like so many are against the idea.

-*S

**Comment by rmarquis** [comment]
Let's close this in favor of #742. FF is about damage, not ability to move entities, and I'd argue this should be managed by admins in case of abuse on public servers.
