### ISSUE TITLE
Rework the vote system

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#764]
Author: @jackeri (Jacker)
Date: 2015-01-09
Redmine Issue: 764, https://dev.etlegacy.com/issues/764

---

The vote system is very rigid, lets change that by adding proper structures and data transfers.

Also the way the vote is shows should be reworked, maybe something similar to csgo where there's a box for the vote with its progress and so on.

**Comment by rmarquis** [comment]
Handled as part of #1424. Closing now.
