### ISSUE TITLE
Full screen console being opened while console is part-open

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#770]
Author: Anonymous (Anonymous)
Date: 2015-01-11
Redmine Issue: 770, https://dev.etlegacy.com/issues/770

---

Normally in ET if you have the console open you can press ALT and tilde together two times to close the console then open it full screen. In ET:L when you do this, it only closes the console then opens it the normal way again. The console can still be opened in full screen if you use the "alt+~" combination with the console fully closed.

**Comment by rmarquis** [comment]
The issue has been introduced by 8bf43ae65ab828bec36277d9c97909b3b3bc1739. Fixed in f7b94c65e123c4115e20f9d3974ba6afb60ab5f4.
