### ISSUE TITLE
Merge translation templates

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#778]
Author: @JanSimek (Radegast)
Date: 2015-01-12
Redmine Issue: 778, https://dev.etlegacy.com/issues/778

---

Translations have to be kept separate for each mod and map. etlegacy_mod.pot and etlegacy_client.pot will be merged into legacy.pot

New locale structure will look like this:

* locale/[fs_game]/en.po
* maps/[mapname]/locale/en.po

**Comment by rmarquis** [comment]
We're not going to translate maps, only the client and the mod - which is already handled. Closing now.
