### ISSUE TITLE
Automate Coverity scan

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#779]
Author: @rmarquis (Spyhawk)
Date: 2015-01-12
Redmine Issue: 779, https://dev.etlegacy.com/issues/779

---

We actually use [coverity](https://scan.coverity.com/projects/1160) as static analysis tool to improve quality of our codebase, and monitor the introduction of new bugs. According to the size of our current codebase, we're allowed to submit 2 scans/day max and 8 scans/week max.

Scans are actually triggered manually by myself about every 1-2 days with [this script](https://github.com/etlegacy/etlegacy-tools/blob/master/coverity/coverity.sh), but it might be wise to completely automate this task with a cron job on our server.

A scan requires pull the last code from git, run the script which will compile the code, create some files and send them to coverity for analysis.

**Comment by rmarquis** [comment]
Done in b92cbfe0915327dddd7fc7db692c9bb85bd827dc, 82f3a9e7385003f2b938ff4701362df1c44646ef, 2978901ff0f93813b5d90e85e2bbd963192d94f0, 39a63953a802dec6ac18ba45a1765f2a458db75e.
