### ISSUE TITLE
ET:L starts windowed

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#788]
Author: Lammert (Lammert)
Date: 2015-01-17
Redmine Issue: 788, https://dev.etlegacy.com/issues/788

---

I have this problem that ET:L starts windowed.
I can't use ALT+ENTER to get it to full screen.
After the first map, the screen restarts and goes to full screen.
Then I can use ALT+ENTER again to switch between windowed and full screen.

**Comment by ETLegacyTeam** [comment]
From: @saukko28 (Saukko)
Date: 2015-01-18T12:30:00Z

---

It works fine for me. I'm talking about the latest build on my Windows 8.1.

-*S

**Comment by ETLegacyTeam** [comment]
From: @rafal1137 (RaFaL)
Date: 2015-01-18T14:33:01Z

---

Can you give us your cfg ?
For me it works fine

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2015-01-18T17:06:07Z

---

Start your ETL with param '+seta r_fullscreen 1' and it should be fixed.

**Comment by ETLegacyTeam** [comment]
From: Lammert (Lammert)
Date: 2015-01-18T20:23:23Z

---

Config:

cl_allowDownload 1
seta cl_maxpackets "100"

seta pb_cl_enable 1

seta com_hunkmegs "192"
seta com_maxfps "125"

seta cg_drawCrosshairNames 7
seta cg_drawPing 1
seta cg_drawTime 1
seta cg_hitSounds 1
seta cg_HUDAlpha 2
seta cg_drawFPS 1

seta cg_limbo_secondary 2
seta cg_AutoSwitch 0
seta cg_autoReload 0

seta cg_bobroll 0
seta cg_fov "120"
seta cg_bloodFlash 0
seta cg_showblood 0
seta cg_bloodDamageBlend 0
seta cg_bobpitch 0
seta cg_bobup 0
seta cg_bobroll 0
seta cg_bobyaw 0

seta cg_drawCrosshair 2
seta cg_crosshairColor white
seta cg_crosshairColorAlt red
seta cg_complaintPopUp 0

seta r_mode "-1" 
seta r_customwidth "1920"
seta r_customheight "1080"
seta sensitivity "2.2"

seta logfile 1

***
seta r_fullscreen 1 - worked. Although I think it is a weird problem

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2015-01-18T21:44:00Z

---

Possible explanation: "Fullscreen not allowed with in_nograb 1" (sdl_glimp.c).

**Comment by ETLegacyTeam** [comment]
From: @rafal1137 (RaFaL)
Date: 2015-01-18T22:30:31Z

---

Better when you will use r_mode -2 sets automaticly to your desktop resolution

**Comment by ETLegacyTeam** [comment]
From: @saukko28 (Saukko)
Date: 2015-01-19T02:02:42Z

---

Is that your nq config? Because I remember having an issue with vanilla ET that all by sudden my etconfig.cfg in etmain has got polluted by my etconfig.cfg in nq folder making that it starts in windowed mode. Also my resolution has been affected.

-*S

**Comment by ETLegacyTeam** [comment]
From: Lammert (Lammert)
Date: 2015-01-20T19:55:38Z

---

Saukko wrote:
> Is that your nq config? Because I remember having an issue with vanilla ET that all by sudden my etconfig.cfg in etmain has got polluted by my etconfig.cfg in nq folder making that it starts in windowed mode. Also my resolution has been affected.
> 
> -*S

Got no problem on my pc (or at least I don't notice anything :P )

**Comment by rmarquis** [comment]
Not enough info for reproducing this issue. Nobody else seemed to have it the past few years, so might have been some customized config issue. Closing now.
