### ISSUE TITLE
Fix weapon restrictions

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#804]
Author: @IR4T4 (IR4T4)
Date: 2015-01-31
Redmine Issue: 804, https://dev.etlegacy.com/issues/804

---

case WP_KAR98 in line 1613 is never reached - IS_HEAVY_WEAPON weapon check at top of function denies that
coverity CID: 1152803

---

Related commit(s):
eb92ad27d7216939df3f9774b0963d7ae53e42b5 - game: G_IsWeaponDisabled adjusted to consider riff..
 5f1158cdabf41c3e47635b203206e61172447c00 - mod: take alt weapons into account of restriction ..
 59abe8ae442716b636b70327b76d24033f3fcf36 - mod: fix weapon restriction condition refs 804
 3a0f9b22dea15e5e315b169b297cb1af5ef50e84 - mod: missing weapons for restrictions refs 804

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2015-02-04T19:04:25Z

---

I've had a c&p virus in the commit message related to the issue index:
http://dev.etlegacy.com/projects/etlegacy/repository/revisions/eb92ad27d7216939df3f9774b0963d7ae53e42b5

{TODO}
-CG_LimboPanel_RealWeaponIsDisabled in cg_limbopanel.c-

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2015-03-23T16:04:26Z

---

CG_LimboPanel_RealWeaponIsDisabled

and 

G_IsWeaponDisabled

should be adjusted to take alt weapons into account.

{TODO}
- check if we have to count picked up opposite team weapons as well

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2015-11-25T15:24:16Z

---

We should test this deeply.

**Comment by rmarquis** [comment]
Should be covered by #1403, #1273, #1254, #1151. Closing.
