### ISSUE TITLE
allow Mac OS  compiling with jpeg-turbo

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#835]
Author: @rmarquis (Spyhawk)
Date: 2015-03-29
Redmine Issue: 835, https://dev.etlegacy.com/issues/835

---

Currently, the Mac OS X version doesn't build with jpeg-turbo, but only jpeg when using dynamic linking (the full static might still work).
Tried to fix this issue in 239d57bf3e493d30e266962c041d68dd2ceaf284, but it seems it still doesn't work.

---

Related commit(s):
239d57bf3e493d30e266962c041d68dd2ceaf284 - misc: fixed JPEGTURBO detection on Mac OS X
 0a1498ce4992dc34beadeac57ca16f08bc2a3e0f - misc: updated Mac OS X compile instructions

**Comment by rmarquis** [comment]
This has been fixed for the newer jpeg-turbo with https://github.com/etlegacy/etlegacy-libs/commit/d077f3e9360f241a682db3a9ea83fd8d52e7a996, https://github.com/etlegacy/etlegacy-libs/commit/04a084073d0a467e5084887ac7ddf14426457620 and https://github.com/etlegacy/etlegacy-libs/commit/ee9e1b7c3d4c70e206507bb402a32e677aacb14a.
