### ISSUE TITLE
Add dynamite counter for spectators/shoutcaster

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#838]
Author: @rmarquis (Spyhawk)
Date: 2015-04-27
Redmine Issue: 838, https://dev.etlegacy.com/issues/838

---

Similarly to the name above players head, spectators (or shoutcasters) should be able to see to remaining time floating above planted dynamite.
This is implemented in etpro, but for shoutcasters only.

---

Related issue(s): #1292

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2016-09-14T21:15:17Z

---

For this we have to implement shoutcaster? Or do you want to see this as spectator with cvar?

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2016-09-15T07:58:18Z

---

We don't have a working ettv (or do we?), but having that option as spec would be great.

Not sure if a new cvar would be needed, or if it could be merged with an existing one (g_misc again?). Also, display owner of dynamite/landmine should also work for spec if enabled.

**Comment by rmarquis** [comment]
Closing as duplicated of #1292.
