### ISSUE TITLE
SRV records support

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#847]
Author: XelA (XelA)
Date: 2015-07-22
Redmine Issue: 847, https://dev.etlegacy.com/issues/847

---

An SRV (Service) record points one domain to another domain name using a specific destination port.  It can also designate some hosts as primary servers  and others as backups (MX like). 

It's already implemented in several services/game: https://en.wikipedia.org/wiki/SRV_record#Usage

With SRV records, no need to specify the port anymore when connecting to a "non-default port" server with a domain name.

**Comment by ETLegacyTeam** [comment]
From: @jackeri (Jacker)
Date: 2015-07-24T09:21:05Z

---

I am not really sure how this applies to ET:L since you do not need to use the port if the port is the standard one, but in the case the it isn't usually means that there are multiple server running in the target computer in which case you need to define the port either way..

**Comment by rmarquis** [comment]
Not applying to ET:L. Closing.
