### ISSUE TITLE
Implement translation/unicode support for non legacy mods

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#859]
Author: @IR4T4 (IR4T4)
Date: 2015-08-16
Redmine Issue: 859, https://dev.etlegacy.com/issues/859

---

Language and unicode support are currently supported for legacy mod only. Find a way (whitelist?, cvar?, files in path?) so other mods can use these features too.

See 'doTranslateMod' (language) and 'IS_LEGACY_MOD (unicode)' 

---

Related issue(s): #591, #831

**Comment by rmarquis** [comment]
This has been done as part of #1365, specifically in a6c09688c397057e4af24241f08d5fe4fd9f0933:

> Any mod can issue unstripped commands, engine will intelligently
handle these on both client and server sides, stripping chars from
commands when necessary.

Closing now.
