### ISSUE TITLE
Fix/Inspect Sniper aim

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#863]
Author: @IR4T4 (IR4T4)
Date: 2015-08-17
Redmine Issue: 863, https://dev.etlegacy.com/issues/863

---

"sniper shot is sometimes inaccurate (related to pmove_fixed 1, see 
http://bani.anime.net/banimod/forums/viewtopic.php?p=40394&sid=d65b880747a0487bf5102914d449606b)
"

**Comment by Vorschreibung** [comment]
Obsoleted via `b_fixedphysics` - can be closed
