### ISSUE TITLE
Rebalance the game to make soldiers with SMG more useful

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#865]
Author: @rmarquis (Spyhawk)
Date: 2015-08-20
Redmine Issue: 865, https://dev.etlegacy.com/issues/865

---

Soldiers with SMG are usually never seen in game as they are utterly useless. They have minimal combat capacity and not strict advantage over any other class.

Idea: reinforce the Soldier role in game similarly to what Splash Damage did in ETQW:

* Give the extra health bonus to soldier instead of giving it to medics (current: max health of medic is 156, other class is 140).
* The more soldier in a team, the more health every players in a team has (current: the more medic, the more health for everybody)
* Medics keep the health generation and ability to pick up their own medpack

By shifting the "combat" bonus from medic to regular soldiers, we might actually decrease the "Rambo medic" effect and introduce a whole new tactical aspect to the game.

Questions that arise:
* Would this still be ET? Can this be part of the "Legacy" mod?
* If yes, should this be introduced with an optional cvar? Should this cvar turned on by default?

---

Related commit(s):
5c22608cbbc2bf7e0e48e1491f89b49011eab0f7 - game: allow medics to max out health from cabinet

**Comment by ETLegacyTeam** [comment]
From: @realkemon (keMoN)
Date: 2015-08-20T16:15:47Z

---

I really like this idea! The only fear I have is an increasing amount of panzernoobs, but they are way less frequent and annoying as rambomedics.
If it is done with a cvar, then I would set it as default, but I honestly think we can be a little bolder here and there and just push it in. People will adapt quickly.


//OFFTOPIC: I've seen a mod somewhere where the soldier carries around a MG that he can drop and then be repaired by a friendly engi. This is also a neat idea to empower the soldier. Obviously this is a major game changer though.

**Comment by ETLegacyTeam** [comment]
From: @jackeri (Jacker)
Date: 2015-08-21T08:20:02Z

---

keMoN wrote:
> I really like this idea! The only fear I have is an increasing amount of panzernoobs, but they are way less frequent and annoying as rambomedics.
> If it is done with a cvar, then I would set it as default, but I honestly think we can be a little bolder here and there and just push it in. People will adapt quickly.
> 
> 
> //OFFTOPIC: I've seen a mod somewhere where the soldier carries around a MG that he can drop and then be repaired by a friendly engi. This is also a neat idea to empower the soldier. Obviously this is a major game changer though.

The plan was not to add health to all soldiers, only if the Soldier has Thompson/MP40 as the main weapon will he get the health boost. The heavy weapon soldiers already server their purpose and as such don't need a boost, but the normal soldier class with a normal gun could use tweaking to make it a viable option to play with.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2015-08-21T08:59:13Z

---

Jacker wrote:
> The plan was not to add health to all soldiers, only if the Soldier has Thompson/MP40 as the main weapon will he get the health boost. The heavy weapon soldiers already server their purpose and as such don't need a boost, but the normal soldier class with a normal gun could use tweaking to make it a viable option to play with.

I'll check how this is implemented in ETQW, but I'm not convinced restricting the health boost to the weapon carried is necessary, not mentioning this does add issues when the player change weapon on field. Adding the extra health boost to the entire soldier class won't make any difference anyway, or only a marginal difference.

The extra 16hp won't help a panzernoob to launch panzer any better, or a MG/flamer to move faster in a fight. This is truly about 1vs1 SMG fight where medic have actually always the upper hand, because they accumulate all the "bonus" available in the game (extra HP + health regeneration + medpack).

**Comment by ETLegacyTeam** [comment]
From: @adanski (Dragonji)
Date: 2015-08-21T10:41:19Z

---

Boost for soldiers is not necessary. At most give them more ammo for SMG. Really needed thing is to nerf medics. They have most HP, they can heal themselves, their HP automatically regenerates. They are incredibly OP.

**Comment by ETLegacyTeam** [comment]
From: @realkemon (keMoN)
Date: 2015-08-21T11:47:28Z

---

Spyhawk wrote:
> I'll check how this is implemented in ETQW, but I'm not convinced restricting the health boost to the weapon carried is necessary, not mentioning this does add issues when the player change weapon on field. Adding the extra health boost to the entire soldier class won't make any difference anyway, or only a marginal difference.
> 
> The extra 16hp won't help a panzernoob to launch panzer any better, or a MG/flamer to move faster in a fight. This is truly about 1vs1 SMG fight where medic have actually always the upper hand, because they accumulate all the "bonus" available in the game (extra HP + health regeneration + medpack).

I'm completely on your side here. When carrying heavy weapons a soldier is already increadibly slow, so I think the extra health is actually a pretty fair thing. Also the soldier can have a Thompson/MP40 as secondary weapon, so what makes him different from a soldier that chose to carry only Thompson/MP40?


Dragonji wrote:
> Boost for soldiers is not necessary. At most give them more ammo for SMG. Really needed thing is to nerf medics.
However I also agree with Dragonji. The most important thing is nerfing the medics! 

But I still don't see how giving the soldier extra health could go completely wrong. I mean it just makes more sense actually to boost your heavy weapons support. In real life that is done with increased armor etc, simply because they are a slower target. Medics on the other hand quite often only had sidearms, because they were rather behind their team mates. (No real knowledge!)

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2015-08-21T13:32:16Z

---

Let's be straight here:

The actual question I'd like to answer is not "How do we rebalance the gameplay?", because lots of mods tried that already, and to be honest they all failed in some way because balancing a game is very difficult/time taking. This is road to hell if you don't take care of careful statistical analysis.

The question I'd like to answer here is "How does the medic/soldier rebalancing as done by Splash Damage in ETQW translates when applied to original ET?". In other words, they recognized something had to be changed in the balance and they changed it, with extensive testing and experimentation. Why not building up upon this knowledge? Although yes, both game have a similar gameplay (on the GDF side at least), yet they are still different game.

**Comment by ETLegacyTeam** [comment]
From: @jackeri (Jacker)
Date: 2015-08-21T14:23:59Z

---

balancing is not something that is done once, most popular games nerf or boost different aspects of the game with every path. We can test things and fix issues as they arise.

**Comment by ETLegacyTeam** [comment]
From: @yfcz (yfcz)
Date: 2015-08-21T15:17:28Z

---

Spyhawk wrote:
> The extra 16hp won't help a panzernoob to launch panzer any better, or a MG/flamer to move faster in a fight. This is truly about 1vs1 SMG fight where medic have actually always the upper hand, because they accumulate all the "bonus" available in the game (extra HP + health regeneration + medpack).
Extra 16 HP could help to survive one more shot from SMG. It gives extra time to Soldier to launch panzer.
Soldier with panzer is powerful enough, there is no need to buff it. Lets be conservative here.

Based on my long-term experience as very addicted ETPro public player I see Panzerfauts, MG and mortar very capable.
Very different story is with flamer and SMG. Flamer is very weak in most situations and you will do much better with other weapons/classes. In my opinion it makes sense to buff SMG/flamer soldier only. 

Buffing panzer/mg/mortar could hurt gameplay. Let's be conservative here pls.

But there is already one known case where could be SMG soldier pretty handy. It's when you restrict use all other classes to low numbers of use and leave numbers of soldier unrestricted. But in past 10 years nobody really used this feature.

Spyhawk wrote:
> Let's be straight here:
> 
> The actual question I'd like to answer is not "How do we rebalance the gameplay?", because lots of mods tried that already, and to be honest they all failed in some way because balancing a game is very difficult/time taking. This is road to hell if you don't take care of careful statistical analysis.
The problem with other mods (exept etpro/etmain) is that they provided too powerful settings for unaware game admins. These setting can change gameplay radically. And they do!  The mod developers really don't have game balance or gameplay under their control anymore. Game admins do.

Jacker wrote:
> balancing is not something that is done once, most popular games nerf or boost different aspects of the game with every path. We can test things and fix issues as they arise.
But developers of such games have under control their game servers and can remove outdated stuff from servers. You can't. Remember 2.55 vs 2.60b fight?

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2015-08-22T06:38:35Z

---

Whatever you add for rebalancing please add a CVAR and don't set it as default.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2015-08-22T06:43:50Z

---

IR4T4 wrote:
> Whatever you add for rebalancing please add a CVAR and don't set it as default.

I guess it is clear by now that a cvar is needed...

{FIXME}
* -allow the buffed class to increase health with medpack taken from cabinet. This works with medpack, and since medics have regeneration that issue has never been noticed.- done

**Comment by ETLegacyTeam** [comment]
From: @jackeri (Jacker)
Date: 2015-08-22T08:06:40Z

---

Spyhawk wrote:
> IR4T4 wrote:
> > Whatever you add for rebalancing please add a CVAR and don't set it as default.
> 
> I guess it is clear by now that a cvar is needed.

In my opinion making everything cvar: able is a bad thing, trying to balance classes with cvar flags will result in every server having different settings, and no one will actually ever test the new setting.

Just make it a C Macro.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2015-09-02T19:03:53Z

---

Had a closer look at ETQW, here how it is implemented for GDF team (just to give some rough idea):
* Everyone starts with 100 HP (like ET)
* +5HP bonus per medic in team (ET is 10HP, maxed to 25 HP)
* (ET Battle Sense level 3 gives +15HP)
* +20HP bonus for soldier (ET gives +12% more to medics)
* autoregeneration for all class that have Battle sense level 4 (ET medics heal 3 HP/sec to MAXHEALTH, then 2 HP/sec to fill the 12% bonus)
* medpacks give 25 HP, medic level 1 have better Medpack (30HP?) (ET medpacks give 20 HP)
* medics can give 4 medpack before their power bar is depleted (same as ET)

**Comment by ETLegacyTeam** [comment]
From: Mateos (Mateos)
Date: 2015-09-11T11:58:38Z

---

And the "dynamite" was given to the Soldier, so Engis just repair stuff, and the Soldier has a real role :P

I'd limit the amount of med kits a medic can grab in a given amount of time, so they can't just run away healing themselves... Would just affect dropped kits, not the ones on cabs

Most games give the Medics faster movements, but I don't think that's a good idea for ET

All in all, even though the Medic has more health, if you're a good shooter, you can down them. It's harder if they started to shoot, but heh, that's a challenge :P

Flamer is fine imo: it does damage over the time, can reach large groups, can harden the sight and shooting of the target...

A cvar is a good solution, for the people wanting to have at least the choice, may they like or not that new feature

Oh, and also: you're willing to nerf the Medic because of the players using him as an attacking class, while I'm sure he was supposed to get in the middle reviving people...
What about a resistance boost when the syringe is equipped?

**Comment by ETLegacyTeam** [comment]
From: @realkemon (keMoN)
Date: 2015-09-11T18:13:55Z

---

I also would avoid adding another cvar. Either implement it as default (which I would appreciate) or don't do it at all!

>What about a resistance boost when the syringe is equipped?
Then medics would equip the syringe to run away from a gunfight.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2015-09-11T18:39:03Z

---

Yep, syringe would somewhat acts as adrenaline. I do believe medic taking their own medpack is fine actually (healing others but not themselves is kinda weird to be honest..), but we can nerf other parameters. As I see it, the issue is that medics, in a 1 vs 1 fight, have *always* the edge.

As a first step, looking at the ETQW implementation, I'd try to
* move the extra 12% bonus from medics to soldiers
* disable auto-regeneration for medics

I also did try to change the medic bonus team to a soldier bonus team instead, and the result is quite interesting: having too many medics in a team has a negative impact on the whole team (in current ET it always has a positive impact), so there is an additional tactic element here.

**Comment by ETLegacyTeam** [comment]
From: @adanski (Dragonji)
Date: 2015-09-11T18:42:25Z

---

Spyhawk wrote:
> * disable auto-regeneration for medics

Or add regeneration for all classes and make it globally slower.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2015-09-11T19:33:35Z

---

Two more ideas discussed on IRC:

Don't remove autoregeration, but:
* use a "cooldown" feature so medic don't have regeneration in fights. This is already implemented in the code to calculate battlefield points (see COMBATSTATE).
* lower regeneration rate, from 3HP/sec to 1HP/sec or even less.

**Comment by ETLegacyTeam** [comment]
From: Mateos (Mateos)
Date: 2015-09-14T08:27:40Z

---

keMoN wrote:
> I also would avoid adding another cvar. Either implement it as default (which I would appreciate) or don't do it at all!
> 
> >What about a resistance boost when the syringe is equipped?
> Then medics would equip the syringe to run away from a gunfight.

No, they would rather heal themselves, because when they run away, their health is low enough to be killed :)

So you want to implement it as a default and non-deactivated feature? So people are forced to cope with it?

Even though I think this feature is a good thing, and even a progress, I don't like "forcing" people. But that's my pov :D

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2015-09-14T10:47:48Z

---

Mateos wrote:
> So you want to implement it as a default and non-deactivated feature? So people are forced to cope with it?
> 
> Even though I think this feature is a good thing, and even a progress, I don't like "forcing" people. But that's my pov :D

The general consensus is that medics are overpowered in the base game. If that is a feature, then we should remove it, and if that is a bug then we should fix it. Beside, check the changelog. We already "force" lot of small gameplay change. The only difference I see here is that rambo medic won't be pleased. They'll actually have to be better and play more as a team to succeed.

If we can find *minimal* changes that improve the gameplay balance, then I personally don't see any reason not to make it a default without a possible option (which would have its set of drawback). Whatever you do, you can't please everyone, so let's please ourselves first - players that also like Legacy will play it.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2015-09-15T17:43:57Z

---

Implemented the following locally (currently with a macro):

* moved the extra 12% bonus from medics to soldiers (soldiers still spawn with 100% health only, not 112%, similarly as it is currently done in vanilla for medics, but can increase it with additional medpack)
* medic don't have regeneration for 5 seconds after receiving damages
* regeneration rate lowered from 3HP/sec to 1HP/sec

Also tried with moving the team bonus from medics count to soldier count (as previously mentioned), but at the moment I'll keep it on the medic since this is not implemented anywhere else afaik (etqw).

It's not worth pushing into master until we've got a test server to collect feedback, to see what works better and what's worst:
* Obviously, if rambo medics might be harder to play now, they might have a more difficult time to actually revive their teammate on the field.
* Soldiers with a Thomson/MP40 will have the edge in a 1vs1 fight if, and only if, they have taken an additional medpack after spawn.

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2015-11-27T18:21:52Z

---

... just to mention: SMG is still optional and everybody knows it's not the best choice as soldier

**Comment by ETLegacyTeam** [comment]
From: @harleking (Harlekin)
Date: 2015-12-13T20:01:16Z

---

Why don't let the soldier reload MG 42 within the Clip. I would love to reload on eg 30 bullets left and throw them away to get a new clip loaded.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2015-12-13T20:15:52Z

---

Harlekin wrote:
> Why don't let the soldier reload MG 42 within the Clip. I would love to reload on eg 30 bullets left and throw them away to get a new clip loaded.

Already implemented, unless I don't understand what you mean here.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2016-04-03T20:59:21Z

---

Related discussion: https://dev.etlegacy.com/boards/3/topics/2558

The perfect solution for solving the rambo medic issue could be to remove the "best fragger" award. >:)

**Comment by ETLegacyTeam** [comment]
From: yks (yks)
Date: 2018-03-18T09:43:28Z

---

But what about increasing the damage or accuracy of SMG when fired by soldier? Logic behind is that soldiers only purpose is that he can fight/shoot really well. That's his specialty.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2018-03-18T19:44:14Z

---

This might be a possibility too.

**Comment by rmarquis** [comment]
Any rebalancing is hard to do. The best way to make soldier more relevant is to give them an active role. ETQW and Brink basically gave soldiers the task of arming dynamite - while engineers could defuse it.

This is however out of the scope of Legacy mod, and better left to a third party mod. Closing now.
