### ISSUE TITLE
chat-alert when including player name

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#870]
Author: @realkemon (keMoN)
Date: 2015-08-23
Redmine Issue: 870, https://dev.etlegacy.com/issues/870

---

Besides having private messages I think it is useful to also have a chat-alert when the player name is included in the public chat-message. 
This would work like in IRC and a certain key (in IRC - TAB) would complete the started player name.

Should be able to turn of in the options menu (and maybe also specify the key)

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2015-08-23T09:58:00Z

---

Wouldn't this better done in Lua? I think there is a script around that does exactly that.. 
Edit: no, it's actually an advanced private message thing. This public chat alert makes sense.

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2015-08-23T10:54:51Z

---

Currently we don't support shortcuts ... but it might interfere with chat binds from players if we implement that.

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2015-09-30T17:08:14Z

---

Should be done with Lua.

**Comment by ETLegacyTeam** [comment]
From: Ray (Ray)
Date: 2017-01-10T12:28:53Z

---

IR4T4 wrote:
> Should be done with Lua.

Zelly made a LUA script for silEnT some year ago, that inludes ingame @mentions and ingame email. Unfortunatly all features does not work as they should on my server. This LUA is pretty awesome. To bad Zelly has taken a longer break from developing it some more. ;)  http://mygamingtalk.com/wiki/LESM
Maybe a smiliar system for Legacy?

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2017-01-13T11:50:31Z

---

Active development and our approach of managing games: https://github.com/timosmit/wolfadmin

**Comment by rmarquis** [comment]
This has been implemented in f4ef73a52e2ce186a7952dcad628c1bc501b7204.
