### ISSUE TITLE
Client app hang

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#873]
Author: @yfcz (yfcz)
Date: 2015-08-24
Redmine Issue: 873, https://dev.etlegacy.com/issues/873

---

When I few times click using left mouse button during loading of map (no matter what map) — it causes non-recoverable application hang.

I found this issue when my client app hanged during loading of map Library Beta 3 which has loading time very long (40 seconds; Fuel Dump loads in 10 seconds).
Library b3 download: http://mirror.netteam.cz/enemy/etmain/library_b3.pk3

How test it: start clicking like insane during loading of map.

------------------

settings used: default except some cg_*blood* cvars
OS: Windows 8.1 x64
RAM: 3 GB (2.2 GB available for apps)
Procesor: Pentium Dual-Core E2180
MB: ASRock > 4CoreDual-SATA2
VIDEO: ATI x1650 128 MB

**Comment by rmarquis** [comment]
Old issue we can't do anything about without additional input. It might have been solved already.
Simple workaround in case it still exists: don't "click like insane during loading of map". Closing now.
