### ISSUE TITLE
Create ET:L on/for Raspberry Pi

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#885]
Author: @IR4T4 (IR4T4)
Date: 2015-11-06
Redmine Issue: 885, https://dev.etlegacy.com/issues/885

---

Adjust the scripts & code for Raspbian + -rendererGLES- openGL.

---

Related commit(s):
96d8b88985bee87527668de4db4823315c7840e4 - misc: easybuild.sh update for RPI refs 885
 8236b583019a53e5e93d08140336911a4766d10f - misc/rendererGLES: cmake FindGLES added refs 885
 125ee59888daee748771742096244b65b7eaa915 - RPI: update easybuild - let RPI builds no longer u..
 5d703bfde86294ca3e2f5e1f7ae849c9fcfc9473 - RPI: let etl compile with RPI system sdl2 lib refs..

**Comment by ETLegacyTeam** [comment]
From: @morsik (morsik)
Date: 2015-11-07T09:41:49Z

---

Actually, even etlded worked really slow on RPi

**Comment by ETLegacyTeam** [comment]
From: @rafal1137 (RaFaL)
Date: 2015-11-07T21:11:41Z

---

morsik which version of rpi were you trying etl on ?

**Comment by ETLegacyTeam** [comment]
From: @adanski (Dragonji)
Date: 2015-11-08T10:29:00Z

---

As far as ET:L is single threaded I guess it will heavily lag on any ARM. RPi2's got a quad-core Cortex-A7 CPU and single core speed is only 900MHz. I guess it would run fine if it could use the whole power of RPi.

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2015-12-30T19:00:39Z

---

About performance we'll figure it out. Afaik genuine sytem requirements of vanilla ET are Pentium III 600 MHz, 128 MB RAM. It also depends on used instruction sets and GLES but RPI2 should deal with that. Time will tell.

Current status for raspbian:
```
./easybuild.sh -RPI -j4

```
Should build the current master on RPI. Some libs/features are disabled.

{FIXME}
-sound system isn't found- 
- client doesn't start (fix GLES linking)
- fix bundled libs not compiling (see  easybuild.sh)
- optimize SDL2 build for RPI (our SDL lib/sdl/cmakeList.txt isn't prepared for arm - see architecture in script)
- use armv8, armv7 or armv6 in file names

Interesting links:
https://www.raspberrypi.org/forums/viewtopic.php?t=56756&p=430647
https://solarianprogrammer.com/2015/01/22/raspberry-pi-raspbian-getting-started-sdl-2/

Required libs (under construction):
- nasm autoconf git cmake zip gcc g++ libtool
- libudev-dev libdbus-1-dev
- libraspberrypi0 libraspberrypi-bin libraspberrypi-dev libx11-dev libglew-dev libegl1-mesa-dev
- libopenal-dev libasound2-dev
- libgles2-mesa-dev mesa-utils-extra ?!

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2018-10-05T14:04:29Z

---

Our libtheora 1.1.1 doesn't support ARM. This has been introduced in theora v1.2.0alpha1.

{FIXME}

Adjust this for ARM:
```
	if(32BITS)
		add_definitions("-DOC_X86_ASM")
		if(MSVC)
			FILE(GLOB THEORA_ASM_SRC
				"${CMAKE_CURRENT_LIST_DIR}/theora/lib/x86_vc/*.c"
				"${CMAKE_CURRENT_LIST_DIR}/theora/lib/x86_vc/*.h"
			)
		else()
			FILE(GLOB THEORA_ASM_SRC
				"${CMAKE_CURRENT_LIST_DIR}/theora/lib/x86/*.c"
				"${CMAKE_CURRENT_LIST_DIR}/theora/lib/x86/*.h"
			)
		endif()

		LIST(APPEND THEORA_SRC ${THEORA_ASM_SRC})
	endif()

```

**Comment by rmarquis** [comment]
Done as part of #1421.
