### ISSUE TITLE
Enabling Anti-Aliasing on NVIDIA Cards gives OpenGL Error (Linux)

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#886]
Author: sadsfae (sadsfae)
Date: 2015-11-10
Redmine Issue: 886, https://dev.etlegacy.com/issues/886

---

Enabling Anti-Aliasing on Nvidia cards (and possibly other models) causes the following error:

GLW_StartOpenGL() - could not load OpenGL subsystem: Missing GL version
See "/home/liam/.etlegacy/legacy/crashlog.txt" for details.

There is a dev forum post about this here:
http://dev.etlegacy.com/boards/1/topics/2011?r=2205#message-2205

I was unable to find an option within etconfig.cfg to toggle this back off so the workaround was to simply rename my etconfig.cfg and let the game re-create it, then NOT toggle AA.
Other games (Urban Terror, GoG games don't seem to have this issue).

---

Related commit(s):
fdc1bafaadc770e745dda8f88bc7f80965969155 - sdl: print SDL errors for users in GLimp_SetMode (..

**Comment by ETLegacyTeam** [comment]
From: Mateos (Mateos)
Date: 2015-11-10T17:31:03Z

---

Windows 8.1, NVidia GT640, fine; May be Linux-related?

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2015-11-10T17:49:22Z

---

Are we talking about r_ext_multisample cvar enabled? What's your setting of AA when you run nvidia-settings (see 'X screen 0")?

Edit: I can reproduce, 32 bit is affected too

**Comment by ETLegacyTeam** [comment]
From: sadsfae (sadsfae)
Date: 2015-11-10T18:06:57Z

---

IR4T4 wrote:
> Are we talking about r_ext_multisample cvar enabled? What's your setting of AA when you run nvidia-settings (see 'X screen 0")?
> 
> Edit: I can reproduce, 32 bit is affected too

Anti-aliasing settings: Use application settings 
(available options are application, override application settings, enhance application settings)
Enable FXAA unchecked

Attached are screenshots.

I'm happy to test toggling this on, backing up my etconfig.cfg and retrying - will that help?

Here's my r_ext_multisample settings:

-- snip --
seta r_ext_multitexture "1" unsafe
seta r_ext_multisample "0"
-- snip --

For what it's worth here's the only thing I load with xorg/X11:

-=>>cat /etc/X11/xorg.conf.d/30-nvidia.conf 
Section "Device"
        Identifier "Nvidia Card"
        Driver      "nvidia"
        Option     "RenderAccel"         "True"
        Option     "TwinView"              "True"
        Option     "DynamicTwinView"  "True"
        Option     "AddARGBGLXVisuals" "true" 
        ### edit adding this
        Option      "NvAGP" "1"
        Option "backingstore" "false"
EndSection

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2015-11-10T18:24:28Z

---

r_ext_multitexture values 1,2 and 4 fail with NVIDIA. As Mateos reported it seems no issue on Windows. At this point we know it's SDL2 or driver related and we should test r_ext_multitexture  with ATI/intel and Linux to exclude SDL2.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2015-11-12T10:13:17Z

---

No issue to report with r_ext_multitexture 1,2 and 4 with Intel under Linux. Seems related to nVidia to me.

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2015-11-12T19:49:59Z

---

I'm getting the impression it's a driver issue of nvida. SDL doesn't get a valid visual.

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2015-11-14T09:28:26Z

---

I've changed some debug prints to be visible for all:
```
----- R_Init -----
SDL initialized driver "x11"
Initializing OpenGL display
Estimated display aspect: 1.600
...setting mode -2: 1680x1050
SDL_CreateWindow failed: Couldn't find matching GLX visual
SDL_CreateWindow failed: Couldn't find matching GLX visual
SDL_CreateWindow failed: Couldn't find matching GLX visual
SDL_CreateWindow failed: Couldn't find matching GLX visual
SDL_CreateWindow failed: Couldn't find matching GLX visual
SDL_CreateWindow failed: Couldn't find matching GLX visual
SDL_CreateWindow failed: Couldn't find matching GLX visual
SDL_CreateWindow failed: Couldn't find matching GLX visual
SDL_CreateWindow failed: Couldn't find matching GLX visual
SDL_CreateWindow failed: Couldn't find matching GLX visual
SDL_CreateWindow failed: Couldn't find matching GLX visual
SDL_CreateWindow failed: Couldn't find matching GLX visual
SDL_CreateWindow failed: Couldn't find matching GLX visual
SDL_CreateWindow failed: Couldn't find matching GLX visual
SDL_CreateWindow failed: Couldn't find matching GLX visual
SDL_CreateWindow failed: Couldn't find matching GLX visual
Available modes [14]: '1280x800 1440x900 1680x1050 1280x720 1366x768 1680x945 640x480 800x600 1024x768 1152x864 1280x960 1280x1024 1280x480 2048x768'
Couldn't get a visual


```

**Comment by rmarquis** [comment]
Closing in favour of #1732..
