### ISSUE TITLE
Add new awards

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#894]
Author: @rmarquis (Spyhawk)
Date: 2015-12-05
Redmine Issue: 894, https://dev.etlegacy.com/issues/894

---

Now that stats have been improved (see #478), we can think about adding new awards. Awards should be carefully chosen in order not to incite the player to behave in a certain way (ie, "Jack the ripper" award in NQ makes players killing with knife instead of using the best weapon at hand in some situation). Instead, they should be simply informative.

Here are the existing awards:

```
    "Highest Fragger",
    "Highest Experience Points",
    "Highest Ranking Officer",
    "Most Highly Decorated",
    "Highest Battle Sense",     // min lvl 1
    "Best Engineer",
    "Best Medic",
    "Best Field Ops",
    "Highest Light Weapons",
    "Best Soldier",
    "Best Covert Ops",
    "Highest Accuracy",
    "I Ain&rsquo;t Got No Friends Award", // min 5 tks
    "Welcome Newbie! Award",    // dont get this if any other award given or > 100 xp (this map)

```

Here are a few possibilities:
- most death
- best accuracy
- most damage given
- most time survived (time alive)
- most gibs
- ...

---

Related issue(s): #860, #892

---

Related commit(s):
af5186d890593834b2c068505a68d12a133f09b8 - game: stats functions cleanup, refs 894
 7f1586c9f6d993b8dc0176c234b2a75272ba8252 - mod: display awards value, refs 894
 6fb0d606274d6f76a9305ad67edd8e71ed9acd0a - game: don't show numerical value for higher rankin..
 2833cc54c4cad249dd5874f53ba0006e8680ca3a - game: always show integer value for skill awards, ..
 ffe7aef38e006229af887b7d6b4b9df1e61e8032 - cgame: make room for additional awards, refs 894
 73b8bc39dae6dbbae76431b971614fab0e60da42 - cgame: fixed unitialized variable, refs 894
 ed3650f0ff94188bebc2751b1a9b166550fc24a5 - game: capped accuracy award value to 100%, refs 8..
 69ceaa9f65d8527983f1e4129390afbc5f4b5326 - cgame: fixed awards list scroll, refs 894
 f35d3dbc3629df1a07fa1698500c8f2b7fbe4794 - mod: added some additional awards, refs 894
 d444f6e1fd8062944cf7222accba652ca11e7c7b - cgame: awards screen fixes and clean up, refs 894
 63cac6a7014697b41b9cdae00947b7aedff73a4d - cgame: fixed awards scroll index, refs 894
 70200ff4174541b26beb7bd0e6c5e8ecd779819f - mod: added HS percentage award, refs 894
 179e058b12898c82010967fda6a2a394b02d742f - game: highest XP award checks map XP only, refs 8..
 9d193942b83204c9adb47ab2a6e6cf1d9223a979 - mod: use highest ranking as first award, refs 403..
 4a6029acad37a2e62ec4cbb4d32e0d838139b3fb - mod: added highest rated player award, refs 403 ..
 0b9bab5bf86c06d427088f920b8928d4d2daabcc - mod: display endgame stats float values with two d..
 1eb2ab85b8f4c71244585b5b1ae0a2b671495536 - game: do not display rating award if not positive,..

**Comment by ETLegacyTeam** [comment]
From: gwrrr (gwrrr)
Date: 2015-12-05T15:06:44Z

---

A few suggestions:

Highlander award = 0 deaths during the match
I hate myself award = most suicides during the match
Sniper award = most kills with scoped rifle
Junkie award = most adrenalines used
Mass exterminator award = most multiple kills
Serial killer award = highest number of killing sprees
Party pooper award = most airstrikes blocked/reverted
Veteran award = most time played or survived
Infiltrator award = most time spent in disguise
BBQ award = most kills with the flamethrower
"It's raining men" award = most kills with mortar
The great reaper award = most kills with machinegun (including stationary and tank mounted ones)
Butcher award = most gibs

**Comment by ETLegacyTeam** [comment]
From: Mateos (Mateos)
Date: 2015-12-05T15:30:08Z

---

I believe objective-oriented awards may fit well (most damage given for defense for instance), some others are really player-centered ^^'

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2015-12-05T16:13:49Z

---

Mateos wrote:
> I believe objective-oriented awards may fit well (most damage given for defense for instance), some others are really player-centered ^^'

True, we should emphasis objective team play where possible ("War Hero" award for objective players?)

> Sniper award = most kills with scoped rifle
> Junkie award = most adrenalines used
> Mass exterminator award = most multiple kills
> Serial killer award = highest number of killing sprees
> Party pooper award = most airstrikes blocked/reverted
> "It’s raining men" award = most kills with mortar
> The great reaper award = most kills with machinegun (including stationary and tank mounted ones)
> Infiltrator award = most time spent in disguise
> BBQ award = most kills with the flamethrower

We don't track spree (and never will I hope), and I'd prefer to use the global stats already available instead of tracking new stats. Also, see my comment about NQ above.

> Highlander award = 0 deaths during the match
> I hate myself award = most suicides during the match
> Veteran award = most time played or survived
> Butcher award = most gibs

We can add these. I'm just not sue about the award name... sounds too "fun" and not self explanatory enough . Legacy doesn't aim to be another NQ.

**Comment by ETLegacyTeam** [comment]
From: @harleking (Harlekin)
Date: 2015-12-07T19:51:04Z

---

Mister Dynamite - most dynamites planted @ objective
Mister FixIt - Most constructibles build/repaired or dynamites defused

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2015-12-09T17:49:39Z

---

{FIXME}:
-Fix scroll in awards screen. For some reason the indexes used are those of PlayerList...-

**Comment by ETLegacyTeam** [comment]
From: @harleking (Harlekin)
Date: 2015-12-09T19:14:35Z

---

Maybe "Best Engi" award could be calculated without XP earned by using rifle?
The award is most of the times given to rifle players and not to the one that does build/destry objectives most of the time.

**Comment by ETLegacyTeam** [comment]
From: Mateos (Mateos)
Date: 2015-12-09T19:30:27Z

---

The rifle is also a strategic weapon, and mastering it do help to lead to the victory :)

In a hard game, if an engi can clear an area so an other can plant, they're both important.

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2015-12-09T19:56:45Z

---

Some suggestions are exactly NQ style with other names:
```
	"Highest Ranking Officer",		// highest rank
	"Highest Experience Points",	// most xp
	"Highest Fragger",				// most kills
	"Most Headshots",				// most headshots
	"Highest Overall Accuracy",		// best total accuracy
	"Best Killing Spree",			// most kills in a killing spree (minimum spree of 5)
	"Bounty Hunter",				// most bounty collected
	"Map XP Collector",				// most XP gain on this map
	"War Hero - Best Objective Play",// best mission/objective play
	"Best Engineer",				// best engineer
	"Best Medic",					// best medic
	"Life Saver ^2Award^7",			// most rescusetations
	"Jack the Ripper ^2Award^7",	// most knife kills
	"Dr. Overdose ^2Award^7",		// most poison kills
	"The Executioner ^2Award^7",	// killed from behind
	"Kick Ass ^2Award^7",			// most kick kills
	"Super Mario ^2Award^7",		// minimum of 1 goomba
	"Purple Heart ^3Award^7",		// most deaths (not including darwin/newton/panzernoob)
	"Best Grenadier ^2Award^7",		// most (throwing) grenade kills
	"Riflenade Master ^2Award^7",	// most kills with riflenade
	"Panzernoob ^1Award^7",			// most self/teamkills with panzer !! Darwin does no longer include self-panzer-kills
	"Darwin ^1Award^7",				// Most deaths from non-players (falling, crushed) and accidental self-kills
	"Isaac Newton ^1Award^7",		// most falling deaths
	"I Ain't Got No Friends ^1Award^7",	// most team kills (minimum of 5 tks)
	"Artillery Spammer ^1Award^7",	//
	"Soul Collector ^2Award^7",		// dog tags

```

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2015-12-09T20:03:57Z

---

Harlekin wrote:
> The award is most of the times given to rifle players and not to the one that does build/destry objectives most of the time.

You can build/destroy obj and use rifles... these are not mutually exclusive.

For now, I just added a few simple awards to check behavior in the UI (and I do find bugs), but keep the suggestion coming! I'd personally like to see more team/objective play awards, like the "War Hero" award.

**Comment by ETLegacyTeam** [comment]
From: @saukko28 (Saukko)
Date: 2015-12-09T20:54:15Z

---

I must say that this one should be kept as simple as possible. There shouldn't be added too many of these 'fun' awards. I think something headshots are at least ones I'd like to see added. But dividing kills into many categories isn't a good option in my opinion. Think about the competitive gameplay point of view.

-*S

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2015-12-09T21:23:13Z

---

Saukko wrote:
> I think something headshots are at least ones I'd like to see added.

We can add "HS percentage" since we already track that info. Might actually be more interesting that the raw number of HS. Also fixed that annoying scroll issue, yeah!

{FIXME}
* Check newbie award

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2015-12-09T22:20:13Z

---

I'll add the war hero soon.

**Comment by ETLegacyTeam** [comment]
From: Mateos (Mateos)
Date: 2015-12-10T07:59:37Z

---

Saukko wrote:
> Think about the competitive gameplay point of view.
> 
> -*S

I don't think players are aiming to these awards in competitions anyway :P

Raw HS data may be interesting with time played

**Comment by rmarquis** [comment]
We've been adding awards when they accompanied a relevant feature implementation. As such, this general ticket doesn't have much purpose anymore - we'll continue to add/modify awards when it make sense. Closing now.
