### ISSUE TITLE
Providing Debian packages for ET: Legacy

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#901]
Author: apo (apo)
Date: 2015-12-07
Redmine Issue: 901, https://dev.etlegacy.com/issues/901

---

I am attaching my preliminary work to provide official Debian packages of ET: Legacy. Unfortunately the etmain source folder is covered by the original EULA and it is therefore non-distributable for Debian. The game can't even be packaged for non-free. Perhaps someone else might find those files useful though.

---

Related issue(s): #161

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2015-12-06T23:06:39Z

---

Some packaging work has been attached to #901, closing here as duplicate.

**Comment by rmarquis** [comment]
We should ensure our Packaging info is up-to-date on the wiki, but we should let distro packagers do their work. We officially support only the released static binaries.
