### ISSUE TITLE
Rework engine tmp ban system

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#909]
Author: @IR4T4 (IR4T4)
Date: 2015-12-20
Redmine Issue: 909, https://dev.etlegacy.com/issues/909

---

Currently engine server side tmp bans are quite limited (management & size).

- Make the engine side ban system use of sqlite3
- Add commands to show and manage bans
- Enable bans for:
-- GUIDs
-- IP/IP range
--  etc ... countries?

**Comment by rmarquis** [comment]
This is handled on the Lua side. Closing now.
