### ISSUE TITLE
Add throwing knives

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#912]
Author: @IR4T4 (IR4T4)
Date: 2015-12-29
Redmine Issue: 912, https://dev.etlegacy.com/issues/912

---

Add throwing knives and make this feature as option.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-02-17T16:59:16Z

---

Can we agree to never implement this feature in Legacy mod? That'd be more for a "fun" fork.

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2019-02-18T17:07:14Z

---

Actually I don't see extending the weapons & options we have without adding new 'real' weapons (also see #911) as targets of 'fun' mods.
These are additional ways to attack and probably not of everyones taste thinking of the pro purists. But it's something 'new' and it is making the game a bit more real.

It shouldn't be enabled by default.

**Comment by rmarquis** [comment]
After discussion: this is better handled in a separate "fun" mod. Closing now.
