### ISSUE TITLE
Fix timescale div 0 issues

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#922]
Author: @IR4T4 (IR4T4)
Date: 2016-03-14
Redmine Issue: 922, https://dev.etlegacy.com/issues/922

---

timescale/com_timescale 0 value results in undefined behaviour.

---

Related issue(s): #1018

---

Related commit(s):
3911ebc028176cd5fa633a9a0129325a5bd8e9ca - server: fix div/0 in SV_RateMsec when com_timescal..
 df26b89340f7c61be23d8273aac257a4a104b4a6 - general: fixed div/0 with com_timescale, refs 922

**Comment by ETLegacyTeam** [comment]
From: @realkemon (keMoN)
Date: 2016-05-31T21:14:35Z

---

Talked with Backsnipe about the 2.75 release/ open issues and he mentioned this regarding this ticket:
backsnip3 [10:35 PM] 
lol com_timescale 0 value results in undefined behaviour
I'd like to try that
seems pretty easy to fix to me
just force it > 0
nobody uses this command anyway
except for replay thing
to have 3000 fps

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2016-08-21T14:29:09Z

---

Isn't this fixed already with https://github.com/etlegacy/etlegacy/commit/3911ebc028176cd5fa633a9a0129325a5bd8e9ca ?

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2016-08-22T14:09:53Z

---

Indeed fixed already.

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2016-08-22T14:23:17Z

---

Do a search for timescale and you'll notice more locations in the code where x/timescale is done.

This issue is actually not fully fixed.

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2016-08-24T15:15:05Z

---

Note: We might change the factor from 1 to 0.05 for case timescale 0.

I'll move this to 2.76. Let's get some feedback.

**Comment by rmarquis** [comment]
This has been fixed. Closing.
