### ISSUE TITLE
ETL crashes on OSX with other mods (NQ1.2.9)

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#936]
Author: Odal (Odal)
Date: 2016-09-13
Redmine Issue: 936, https://dev.etlegacy.com/issues/936

---

Everything works until entering the game. Then complete exiting with following console message (I don't know which message are related to this problem):
```
13/09/16 09:20:16,442 launchservicesd[95]: SecTaskLoadEntitlements failed error=22
13/09/16 09:20:16,478 com.apple.xpc.launchd[1]: (com.etlegacy.etl.908192[41186]) Service exited with abnormal code: 2
13/09/16 09:20:16,478 WindowServer[186]: CGXGetConnectionProperty: Invalid connection 148235
13/09/16 09:20:16,479 WindowServer[186]: CGXGetConnectionProperty: Invalid connection 148235
13/09/16 09:20:16,479 WindowServer[186]: CGXGetConnectionProperty: Invalid connection 148235
13/09/16 09:20:16,479 WindowServer[186]: CGXGetConnectionProperty: Invalid connection 148235
13/09/16 09:20:16,479 WindowServer[186]: CGXGetConnectionProperty: Invalid connection 148235
13/09/16 09:20:16,507 WindowServer[186]: MPAccessSurfaceForDisplayDevice: Set up page flip mode on display 0x0b40caf2 device: 0x7fa77040a8c0  isBackBuffered: 1 numComp: 3 numDisp: 3
13/09/16 09:20:16,549 identityservicesd[503]: <IMMacNotificationCenterManager: 0x7f876c93fea0>: notification observer: com.apple.iChat   notification: __CFNotification 0x7f876ca4dcd0 {name = _NSDoNotDisturbDisabledNotification}
13/09/16 09:20:16,567 identityservicesd[503]: <IMMacNotificationCenterManager: 0x7f876c93fea0>:    NC Disabled: NO
13/09/16 09:20:16,575 identityservicesd[503]: <IMMacNotificationCenterManager: 0x7f876c93fea0>:   DND Enabled: NO
13/09/16 09:20:16,575 identityservicesd[503]: <IMMacNotificationCenterManager: 0x7f876c93fea0>: Updating enabled: YES   (Topics: (
    "com.apple.private.alloy.icloudpairing",
    "com.apple.private.alloy.continuity.encryption",
    "com.apple.private.alloy.continuity.activity",
    "com.apple.private.ids",
    "com.apple.private.alloy.phonecontinuity",
    "com.apple.private.alloy.phone.auth",
    "com.apple.private.alloy.keychainsync",
    "com.apple.private.alloy.fmf",
    "com.apple.private.alloy.screensharing",
    "com.apple.private.alloy.maps",
    "com.apple.private.alloy.thumper.keys",
    "com.apple.private.alloy.continuity.tethering"
))
```
I tried on a MacMini (late 2012) and a MacBookPro (13", mid 2012) both updated to ElCapitan (10.11.6)

---

Related issue(s): #825

**Comment by ETLegacyTeam** [comment]
From: Odal (Odal)
Date: 2016-09-13T07:38:43Z

---

It crashes with the downloaded version (2.75 "official") and also with the git/compiled version.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2016-09-13T07:44:15Z

---

See https://dev.etlegacy.com/projects/etlegacy/wiki/Compatible_Mods.

Support of third party mods on Mac OS X is somewhat erratic.

**Comment by ETLegacyTeam** [comment]
From: Odal (Odal)
Date: 2016-09-13T07:47:50Z

---

I tried to connect to a server with MOD "etlegacy" and it worked!

So, for now *it does NOT work with NQ 1.2.9 mod*

**Comment by ETLegacyTeam** [comment]
From: Odal (Odal)
Date: 2016-09-13T07:48:16Z

---

I am sorry.
Now I understand.
Thanks for your work.

v55

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2016-09-13T12:32:36Z

---

Alright. I did expect issues with OSX see #825 #848 #883 (there are more - do a ticket search for 'osx') But this is the first time we are loading the mod libs for real. 

"SecTaskLoadEntitlements failed error=22" is an apple specific error we should examine.

**Comment by ETLegacyTeam** [comment]
From: Odal (Odal)
Date: 2016-09-26T12:02:48Z

---

Today, after compiling, I re-tried and ... it works!

I usually connect to [UJE] Clan - Teamplay server (37.120.174.14) with etlegacy server 2.71rc1 1  and NQ 1.29.
So, NQ 1.29  works with EtLegacy on OSX.

OSX 10.12 Sierra.

**Comment by ETLegacyTeam** [comment]
From: Odal (Odal)
Date: 2016-09-26T12:13:19Z

---

Also with ElCapitan works (10.11.6) :-)

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2016-09-26T13:26:11Z

---

Well, I really don't get that Mac OS X stuff..

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2016-09-26T16:21:50Z

---

I've heard the NQ guys did pay you for this post :) ... Great news!

**Comment by ETLegacyTeam** [comment]
From: @adanski (Dragonji)
Date: 2016-09-27T20:37:04Z

---

Could you also try some silEnT mod server?

http://www.gametracker.com/search/et/?search_by=server_variable&search_by2=mod_url&query=http%3A%2F%2Fmygamingtalk.com%2F&searchipp=25#search

**Comment by ETLegacyTeam** [comment]
From: Mateos (Mateos)
Date: 2017-01-12T16:12:35Z

---

Is there any related commit(s)?

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2017-01-12T19:29:58Z

---

No. This is why this mac issue is so fun to debug! :P

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2017-01-13T10:53:16Z

---

There are related commits ... see #825. We no longer load the default mod and some fixes were done in the zip code ...

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2018-01-18T10:49:40Z

---

From the forums https://dev.etlegacy.com/boards/2/topics/3276

fs_basepath
```
Sys_LoadGameDll > FS_CL_ExtractFromPakFile(/Users/Loic/Library/Application Support/etlegacy, silent, ui_mac)
Sys_LoadDll → Sys_TryLibraryLoad(/Users/Loic/Library/Application Support/etlegacy, silent, ui_mac)...
- Trying zipped .bundle... failed. (Not a valid zip).
– Trying extension-less dylib... failed: "Failed loading /Users/Loic/Library/Application Support/etlegacy/silent/ui_mac: dlopen(/Users/Loic/Library/Application Support/etlegacy/silent/ui_mac, 6): image not found"
– Trying dylib with extension... failed: "Failed loading /Users/Loic/Library/Application Support/etlegacy/silent/ui_mac.dylib: dlopen(/Users/Loic/Library/Application Support/etlegacy/silent/ui_mac.dylib, 6): image not found"
Sys_LoadDll > Sys_TryLibraryLoad(/Applications/ET Legacy, silent, ui_mac)...

```

fs_homepath
```
- Trying zipped .bundle... failed. (Not a valid zip).
– Trying extension-less dylib... failed: "Failed loading /Applications/ET Legacy/silent/ui_mac: dlopen(/Applications/ET Legacy/silent/ui_mac, 6): image not found"
– Trying dylib with extension... failed: "Failed loading /Users/Loic/Library/Application Support/etlegacy/silent/ui_mac.dylib: dlopen(/Users/Loic/Library/Application Support/etlegacy/silent/ui_mac.dylib, 6): image not found"
Sys_LoadDll(silent/ui) failed to load library

```

{FIXME}
It looks like there is something terrible wrong with the search paths at least for the fs_homepath search. The extension-less dylib is missing the real path prefix? See https://github.com/etlegacy/etlegacy/blob/master/src/sys/sys_main.c#L593
Sys_TryLibraryLoad is called twice (for fs_basepath and fs_homepath)

Clarify (from our wiki): fs_basepath and fs_homepath are same path on OS X?! I do assume this won't work because of apple priviledges?

**Comment by jackeri** [comment]
I will just close this, as ETL (now requiring x86_64 or m1 bundles) does work in OSX just fine with mods that have the valid binaries. As far as I know only nitmod has proper support currently, but this is not the fault of legacy but just the lack of support from the mod makers.
