### ISSUE TITLE
more ammo and healthcabinets

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#955]
Author: @thunderpwn (thunder)
Date: 2016-10-22
Redmine Issue: 955, https://dev.etlegacy.com/issues/955

---

I wnat to add 4 more models here
1 ammocrate with tags and one healthcrate with tags
1 ammocupboard and one healthcupboard

paths will be the same as old ones and will be named healtlocker.md3 , ammolocker.md3, helathcrate.md3 and ammocrate.md3
just to have some variatons for mappers and ofc we will keep the old ones

**Comment by rmarquis** [comment]
Out of scope. New assets might be useful for #218, where the effort should be redirected. Closing.
