### ISSUE TITLE
Add WolfAdmin to installers

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#975]
Author: @IR4T4 (IR4T4)
Date: 2017-01-15
Redmine Issue: 975, https://dev.etlegacy.com/issues/975

---

Let's add our prefered game manager to the installs.

---

Related issue(s): #1010

---

Related commit(s):
9811244e657fa866715da31bfd60091452566661 - cmake: add WolfAdmin to installers, refs 975
 dda0db65a6f4d80f01567f72e80faadd599516ef - misc: fix cmake scripts for geoip, ob  & wa
 c0e1d80940996731b3f5207497a1bfa37fdc2e85 - misc: fixed WolfAdmin install path, refs 975
 67e89ae5773e99e9caa9a584e892e1a2148a1f84 - misc: updated WolfAdmin md5sum, refs 975

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2017-01-19T10:13:53Z

---

From #217:

IR4T4 wrote:
> We should ask the OB team to change their code and read the OB config file from fs_homepath first. If there is no file in fs_homepath the fs_basepath file is failback case.

There is a similar issue with WolfAdmin. We should ensure it takes fs_basepath as fallback (for config files, maybe database too).

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2017-03-24T21:41:36Z

---

{TODO}
* Fix "chmod: cannot access './legacy/omni-bot/': No such file or directory" error
* -Fix wIn installaler Polish translation-
* -Fix WA default config + DB creation- (done)

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2017-05-21T13:35:19Z

---

{FIXME}
-The WA achive shouldn't be entirely extracted in the mod folder, but correctly installed.- (done)

**Comment by ETLegacyTeam** [comment]
From: @illwieckz (illwieckz)
Date: 2018-10-23T23:32:20Z

---

I tried to compile ET: Legacy using @easybuild.sh@ but it fails on WolfAdmin extraction step:

```<code>-- Installing WolfAdmin
-- Downloading WolfAdmin archive to /home/illwieckz/dev/etlegacy/build/legacy/wolfadmin.tar.gz
-- [download 1% complete]…
-- [download 100% complete]
-- Extracting WolfAdmin archive to /home/illwieckz/dev/etlegacy/build/legacy/wolfadmin
CMake Error at cmake/ETLInstallWolfAdmin.cmake:19 (file):
  file COPY cannot find
  "/home/illwieckz/dev/etlegacy/build/legacy/wolfadmin/luamods".
Call Stack (most recent call first):
  CMakeLists.txt:168 (include)


CMake Error at cmake/ETLInstallWolfAdmin.cmake:22 (file):
  file COPY cannot find
  "/home/illwieckz/dev/etlegacy/build/legacy/wolfadmin/lualibs".
Call Stack (most recent call first):
  CMakeLists.txt:168 (include)


-- Adding WolfAdmin to installer scripts
-- ***********************************************************
-- Genuine ET files are not copied - ET: Legacy won't start !!!
-- In order to start the game copy
-- pak0.pk3, pak1.pk3 and pak2.pk3
-- to ./etmain
-- ***********************************************************
-- Configuring incomplete, errors occurred!
See also "/home/illwieckz/dev/etlegacy/build/CMakeFiles/CMakeOutput.log".
Exiting!</code>
```

The CMakeOutput.log seems to have nothing related to WolfAdmin:

```<code>$ grep -ir wolfadmin /home/illwieckz/dev/etlegacy/build/CMakeFiles/CMakeOutput.log
Ø</code>
```

The @wolfadmin.tar.gz@ file is correctly downloaded, stored with the right name and expected path, and listable.

**Comment by ETLegacyTeam** [comment]
From: @illwieckz (illwieckz)
Date: 2018-10-23T23:35:36Z

---

Wait, I just did that in @cmake/ETLFunctions.cmake@ and it now works, that makes no sense:

```<code class="diff">- 		COMMAND ${CMAKE_COMMAND} -E tar -xzf ${_PATH}
+ 		COMMAND ${CMAKE_COMMAND} -E tar -xvzf ${_PATH}</code>
```

**Comment by rmarquis** [comment]
This has been done. Closing.
