### ISSUE TITLE
Inspect/add prediction code...

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#98]
Author: @IR4T4 (IR4T4)
Date: 2012-11-03
Redmine Issue: 98, https://dev.etlegacy.com/issues/98

---

Extend pmove for prediction.

---

Related commit(s):
53d3cbe5b08829a7a09869bf45f96f9f47d881f8 - cgame: commented a condition in CG_PredictionOk wh..
 2d2ef4f1d56a1d38c7266457cbb6033223e79d1b - cgame: cg_optimizePrediction feature by forty
 de041647e89449d25446e37b59e73ad7919cefce - cgame: missing prediction code
 8f2446a066862ebf12254c0efb45fb9e5ff81f3b - mod: fix stats[STAT_AIRLEFT] prediction when not i..

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2015-08-09T10:31:59Z

---

* CG_PredictionOk() in cg_predict.c is actually unused in Vanilla/Legacy mod.
* ETPub and NQ make use of it with the cg_optimizePrediction cvar.
* Check also coverity CID 1315760. There is an early return in the middle of the existing CG_PredictionOk function.

**Comment by ETLegacyTeam** [comment]
From: @adanski (Dragonji)
Date: 2015-08-09T19:38:52Z

---

Prediction code in ETPub is bugged. They fixed it in silEnT mod but changes are not public as silEnT is closed.

http://mygamingtalk.com/forums/tracker/issue-200-jump-problems/

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2015-08-10T10:19:02Z

---

Dragonji wrote:
> Prediction code in ETPub is bugged. They fixed it in silEnT mod but changes are not public as silEnT is closed.
> 
> http://mygamingtalk.com/forums/tracker/issue-200-jump-problems/

Thx Dragon. If I understand correctly, this mostly affects doublejump that isn't (and might never be) implemented in legacy). Also, according to that "forum link":http://mygamingtalk.com/forums/topic/1078-doublejump-problem, the open sourced "ETrun":https://github.com/ETrun/ETrun mod also fixed it, probably in this "commit":https://github.com/ETrun/ETrun/commit/97e6c276c30e3ca3e5ee51a3a511dd7ddcec26e1.

**Comment by ETLegacyTeam** [comment]
From: @adanski (Dragonji)
Date: 2015-08-10T13:48:55Z

---

Not exactly. Don't know about ETrun but in ETPub/old silEnT jumping is bugged in general, not only DJ. My movie attached to the ticket nicely showed it but as I can see it's no more available. Unfortunately I can't reupload it atm.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2015-08-23T12:03:01Z

---

{FIXME}
* Check leaning code. Afaik, it's implemented client side only. Sync it server side might solve a few issues related to the anti-wallhack. Edit: This might be done already in 8f074a9c473692305d459f6cc04bd10bedee20d7.

**Comment by rmarquis** [comment]
Some commits above related to #1408. Worth handle this task at the same time.

**Comment by rmarquis** [comment]
Closing, tracking in #1408 instead.
