### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#987]
Author: @rmarquis (Spyhawk)
Date: 2017-02-01
Redmine Issue: 987, https://dev.etlegacy.com/issues/987

---

Server randomly crashes after being left alone for a few days (etlegacy.com). This happened a couple of time already.

```
Userinfo: \name\^o[BOT]^7Royen\rate\25000\snaps\20\ip\localhost\cl_guid\OMNIBOT1200000000000000000000000
ClientUserinfoChanged: 12 n\^o[BOT]^7Royen\t\2\c\3\lc\3\r\0\m\0000000\s\0000000\dn\\dr\0\w\8\lw\8\sw\7\mu\0\ref\0\u\0
Userinfo: \name\^o[BOT]^7Merki\rate\25000\snaps\20\ip\localhost\cl_guid\OMNIBOT1400000000000000000000000
ClientUserinfoChanged: 14 n\^o[BOT]^7Merki\t\2\c\1\lc\1\r\0\m\0000000\s\0000000\dn\\dr\0\w\8\lw\8\sw\7\mu\0\ref\0\u\0
voice: ^o[BOT]^7Beelz Medic
Kill: 6 5 8: ^o[BOT]^7Halfwit killed ^o[BOT]^7Beelz by MOD_MP40
----- Server Shutdown -----
Sending heartbeat to etmaster.idsoftware.com
Sending heartbeat to master.etlegacy.com
==== ShutdownGame (0 - venice) ====
^2<EndGame>
^2-- Script System Info --
^2Current Memory Usage 3.6894 MB
^2Soft Memory Usage 4.80334 MB
^2Hard Memory Limit 5.33704 MB
^2System Memory Usage 2.90606 MB
^2Full Collects 3
^2Inc Collects 1
^2GC Warnings 0
^2Threads: 4, 3 Running, 0 Blocked, 1 Sleeping
^2ShutdownOmniBot
ShutdownGame:
------------------------------------------------------------
---------------------------
Z_Malloc: failed on allocation of 33912 bytes from the main zone: /media/sf_legacy/lnxetlegacy64/src/server/sv_net_chan.c, line: 265 (sizeof(netchan_buffer_t))

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2017-02-01T10:55:49Z

---

Note this might be related to the MSG_WriteBits issue that has been fixed in master already.

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2017-02-01T14:40:52Z

---

Spyhawk wrote:
> Note this might be related to the MSG_WriteBits issue that has been fixed in master already.

Not sure about this. Basically the given error message tells us we are out of memory in Z - allocating memory fails. We did fix tons of leaks and I think we should update our server to master. Let's use latest code ...

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2017-02-06T10:54:35Z

---

Sever had been updated. Let's see if it crashes again.

**Comment by ETLegacyTeam** [comment]
From: @Ododo (Ododo)
Date: 2019-10-23T04:57:19Z

---

A file descriptor for etl.db  seems to be created on each map load, without closing the previous. (see attachment)
So maybe the system has reached a limit as the errno 24 on mapvoteinfo.txt suggest.


EDIT: sorry wanted to answer to #1243

**Comment by ETLegacyTeam** [comment]
From: hellreturn (hellreturn)
Date: 2019-11-25T19:53:38Z

---

Had similar crash today. 

Players: 40 appx
ETL Server: Current release
Mod: silent mod
Map: ET Beach 

Error before crash - 
Z_Malloc: failed on allocation of 33856 bytes from the main zone.

**Comment by ETLegacyTeam** [comment]
From: @isRyven (ryven)
Date: 2019-11-25T20:00:08Z

---

Are you using official 2.76 build, or making one yourself from the master?
But thanks for the report, these issues being slowly investigated.

**Comment by ETLegacyTeam** [comment]
From: hellreturn (hellreturn)
Date: 2019-11-25T23:35:31Z

---

ryven wrote:
> Are you using official 2.76 build, or making one yourself from the master?
> But thanks for the report, these issues being slowly investigated.

2.76 build. All our ETL servers (Windows + Linux) are on official 2.76 build as of now.

**Comment by jackeri** [comment]
This issue should have been fixed on master, closing for now.
